const $=s=>document.querySelector(s);const names={m:'The open studio',n:'The project album',o:'The project desk'};
const defaults={m:['milestone','actions','approvals'],n:['milestone','actions'],o:['actions','updates']};
const titles={updates:'Visual updates',brief:'AI project brief',milestone:'Next milestone',actions:'Next actions',budget:'Landscape budget',fee:'Design fee',journey:'Project journey',approvals:'Pending approvals',week:'This week',activity:'Latest activity',savings:'Closing the budget gap',bids:'Contractor bids'};
const state={layout:['m','n','o'].includes(location.hash.slice(1))?location.hash.slice(1):'m',selected:Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,[...v]])),tab:'today',days:4,alerts:true,timing:'weekly',dismissed:false,done:new Set(),approved:new Set(),fast:false};
const nav=[['Project home','M3 3h12v12H3z M3 7h12 M7 7v8'],['Brief & site','M4 2h8l3 3v11H4z M7 7h5 M7 10h5'],['Project files','M2 5h5l2 2h7v8H2z'],['Design','M2 4l4-2 6 2 4-2v12l-4 2-6-2-4 2z M6 2v12 M12 4v12'],['Costs & savings','M4 2h10v14H4z M7 5h4 M7 9h1 M10 9h1 M7 12h1 M10 12h1'],['Client Center','M2 3h14v10H7l-4 3v-3H2z M5 6h8 M5 9h5'],['Financials','M3 15V8h3v7 M8 15V3h3v12 M13 15V6h3v9'],['Deliver','M2 4l1 1 2-3 M7 4h9 M2 10l1 1 2-3 M7 10h9 M7 15h9']];
$('#nav').innerHTML=nav.map(([name,path],i)=>`<button class="${i?'':'active'}" data-info="${name}"><svg class="nav-icon" viewBox="0 0 18 18" aria-hidden="true"><path d="${path}"/></svg>${name}</button>`).join('');
const scene=(copy=false)=>`<div class="hero ${copy?'large':''}"><svg class="scene" viewBox="386 514 380 507" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Sample garden design reference with a pool, planted terraces and outdoor living spaces"><image href="../../assets/asian-scenes.png" width="1536" height="1024"/></svg>${copy?'<div class="hero-copy"><small>YOUR PROJECT, TAKING SHAPE</small><h2>Quiet geometry.<br>Warm materials.</h2></div>':''}<span class="image-label">Concept direction · sample imagery</span></div>`;
const head=(title,action,label)=>`<div class="card-head"><h2>${title}</h2>${action?`<button data-info="${action}">${label||'View detail'}</button>`:''}</div>`;
const bottom=(label,info)=>`<div class="bottom"><button data-info="${info||label}">${label}</button></div>`;
const pager=(id,n)=>`<div class="pager"><div class="dots">${Array.from({length:n},(_,i)=>`<button data-slide="${id}" data-index="${i}" aria-label="${id} view ${i+1}" aria-current="${i===0}"></button>`).join('')}</div><div class="arrows"><button data-step="-1" data-carousel="${id}" aria-label="Previous ${id} view">‹</button><button data-step="1" data-carousel="${id}" aria-label="Next ${id} view">›</button></div></div>`;
function brief(dark=false){return `<article class="card brief ${dark?'dark':''}" data-card="brief">${head('AI project brief','Brief sources','Sources')}<div class="slides" id="brief" tabindex="0" aria-label="Project brief slides"><section class="slide"><span class="eyebrow">MONDAY, SEPTEMBER 28</span><h3>A clear direction.<br>A few decisions ahead.</h3><p>The design is moving forward. ${state.approved.size===2?'Both sample approvals are recorded.':'Confirm the material palette before finalizing the review set.'} The estimate is <strong>12% over budget</strong>; design fees project a <strong>29% margin.</strong></p></section><section class="slide"><div class="slide-title"><b>Where the budget stands</b><small>12% over</small></div><svg class="diagram" viewBox="0 0 380 110" role="img" aria-label="Budget 450 thousand dollars. Current estimate 504 thousand dollars, 54 thousand above budget."><text x="0" y="15">Landscape budget</text><rect x="0" y="25" width="286" height="17" rx="4" fill="#b8c9af"/><text x="302" y="38">$450k</text><text x="0" y="66">Current estimate</text><rect x="0" y="76" width="320" height="17" rx="4" fill="#d9b6c0"/><text x="335" y="89">$504k</text></svg><p>Review specification options before increasing the budget.</p></section><section class="slide"><div class="slide-title"><b>Work before delivery</b><small>Example allocation</small></div><svg class="diagram" viewBox="0 0 380 110" role="img" aria-label="15 hours of planned work and 12 hours available, a three hour gap"><text x="0" y="15">Planned effort · 15 hours</text><rect x="0" y="28" width="360" height="20" rx="4" fill="#b9cedc"/><text x="0" y="72">Available across projects · 12 hours</text><rect x="0" y="83" width="288" height="20" rx="4" fill="#b8c9af"/><rect x="294" y="83" width="66" height="20" rx="4" fill="#dec2c9"/></svg><p>Three hours need reassignment or a change to the plan.</p></section></div>${pager('brief',3)}</article>`}
const tasks=[['palette','Confirm material palette','Alex · client decision','0.5 h'],['plant','Finish planting plan','Maya · design development','4 h'],['light','Coordinate lighting','Maya · design development','3 h']];
const taskRows=()=>tasks.map(([id,t,sub,h])=>`<label class="task"><input type="checkbox" data-task="${id}" ${state.done.has(id)?'checked':''} aria-label="Complete ${t}"><span>${t}<small>${sub}</small></span><small>${h}</small></label>`).join('');
function milestone(){return `<article class="card milestone ${state.layout==='l'?'pink':'blue'}" data-card="milestone">${head('Next milestone','Milestone settings','Edit')}<div class="slides" id="milestone" tabindex="0" aria-label="Milestone slides"><section class="slide"><div class="countdown ${state.days<=2?'urgent':state.days<=7?'soon':'calm'}"><b class="big">${state.days}</b><span>${state.days===1?'day':'days'} to go</span></div><h3>Design development delivery</h3><small class="date">${new Date(Date.UTC(2026,8,28+state.days)).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'})} · Fixed deadline · Alex</small><div class="small-line"><span>${3-state.done.size} priority tasks remaining</span><button class="plain" data-slide="milestone" data-index="1">View tasks →</button></div><div class="track"><span style="width:${state.done.size/3*100}%"></span></div></section><section class="slide">${taskRows()}</section></div>${pager('milestone',2)}</article>`}
function budget(){return `<article class="card" data-card="budget">${head('Landscape budget','Estimate','Open estimate')}<small>Current estimate</small><div class="metric-top"><strong>$504,000</strong><span class="delta">12% over budget</span></div><svg class="budget-svg" viewBox="0 0 400 79" role="img" aria-label="504 thousand dollar estimate exceeds the 450 thousand dollar budget by 54 thousand dollars"><rect x="0" y="25" width="398" height="19" rx="5" fill="#edf1e9"/><rect x="0" y="25" width="354" height="19" rx="5" fill="#b6c6ad"/><path d="M354 25h39q5 0 5 5v9q0 5-5 5h-39z" fill="#dbb8c2"/><path d="M354 15v39" stroke="#6b7866"/><text x="0" y="70">$0</text><text x="310" y="9">Budget $450k</text><text x="350" y="70">$504k</text></svg><div class="budget-caption"><span>Above budget</span><b>$54,000</b></div>${bottom('View potential savings')}</article>`}
function fee(){return `<article class="card" data-card="fee">${head('Design fee','Financials','Financials')}<small>Projected profit</small><div class="fee-total"><b>$10,400</b><span class="phase">28.9% margin</span></div><div class="budget-caption"><span>Agreed fee</span><b>$36,000</b></div><div class="fee-bar" role="img" aria-label="36 thousand dollar fee: 18,400 costs to date, 7,200 forecast remaining costs, 10,400 projected profit"><span></span><span></span><span></span></div><div class="fee-legend"><div><small>Cost to date</small><b>$18,400</b></div><div><small>To complete</small><b>$7,200</b></div><div><small>Projected profit</small><b>$10,400</b></div></div></article>`}
function actions(){return `<article class="card tasks" data-card="actions">${head('Next actions','Task roadmap','Task roadmap')}${taskRows()}${bottom('View all tasks','Task roadmap')}</article>`}
function approvals(){return `<article class="card" data-card="approvals">${head('Pending approvals','Approval record','View record')}${[['material','Material palette','Needed before final specifications'],['coping','Pool coping selection','Client review · requested Sep 26']].map(([id,t,sub])=>`<label class="approval"><input type="checkbox" data-approval="${id}" ${state.approved.has(id)?'checked':''} aria-label="Record approval for ${t}"><span>${t}<small>${state.approved.has(id)?'Approval recorded by you · Undo by unchecking':sub}</small></span></label>`).join('')}<p>Already received a decision? Check it here.</p></article>`}
function journey(){return `<article class="card journey" data-card="journey">${head('Project journey','Task roadmap','View roadmap')}${[['✓','Discovery',9,9,'completed'],['!','Concept',11,13,'open'],['3','Design development',8,14,'current'],['4','Documentation',0,11,''],['5','Bidding',0,6,'']].map(([n,t,a,b,c])=>`<div class="journey-item ${c}"><span>${n}</span><span>${t}</span><i><b style="width:${a/b*100}%"></b></i><small>${a}/${b}</small></div>`).join('')}</article>`}
function week(){let work=state.fast?['Confirm palette; planting plan','Lighting & estimate','Assemble review set','Internal review','Client delivery']:['Confirm material palette','Planting & lighting','Update the estimate','Assemble review set','Client delivery'];return `<article class="card week-card" data-card="week"><div class="week-head"><h2>This week</h2><div class="segment"><button data-mode="spread" aria-pressed="${!state.fast}">Spread out</button><button data-mode="fast" aria-pressed="${state.fast}">Finish ASAP</button></div></div><div class="week">${['Mon','Tue','Wed','Thu','Fri'].map((d,i)=>`<div class="day ${i===0?'today':''}"><div><b>${d}</b><small>${[28,29,30,1,2][i]}</small></div><p>${work[i]}</p><small>${i===4?'Fixed date · Oct 2':['Alex','Maya','Alex','Maya'][i]}</small></div>`).join('')}</div></article>`}
function activity(){return `<article class="card" data-card="activity">${head('Latest activity','Activity history','View history')}<div class="activity-line"><span class="initial">M</span><div>Maya updated the planting plan.<small>Today · 10:42 am</small></div></div><div class="activity-line"><span class="initial">A</span><div>Alex revised the estimate.<small>Today · 9:15 am</small></div></div><div class="activity-line"><span class="initial">C</span><div>Last client email received.<small>Sep 25 · example connection</small></div></div></article>`}
function savings(){return `<article class="card" data-card="savings">${head('Closing the budget gap','View potential savings','Explore')}${[['Specification swaps','$9,400'],['Adjust selected finishes','$6,300'],['Consider a later phase','$6,400']].map(([t,n])=>`<div class="list-row"><span>${t}</span><b>${n}</b></div>`).join('')}<small>Example opportunities · not verified or additive.</small></article>`}
function bids(){return `<article class="card" data-card="bids">${head('Contractor bids','Bid comparison','Compare')}<p>Three bids ready to review.</p>${[['Contractor A','$498,000'],['Contractor B','$476,000'],['Contractor C','$521,000']].map(([t,n])=>`<div class="list-row"><span>${t}</span><b>${n}</b></div>`).join('')}</article>`}
const cards={updates,brief,milestone,actions,budget,fee,journey,approvals,week,activity,savings,bids};
const photo=(kind='garden')=>kind==='garden'?`<svg viewBox="386 514 380 507" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Garden concept reference"><image href="../../assets/asian-scenes.png" width="1536" height="1024"/></svg>`:`<img src="../../assets/${kind==='materials'?'med-materials.png':'lounge-chair.png'}" alt="${kind==='materials'?'Material palette reference':'Lounge chair selection reference'}">`;
function visualRecap(){return `<article class="visual-recap"><div class="recap-heading"><span class="eyebrow">AI RECAP · EXAMPLE</span><button class="plain" data-info="Brief sources">Sources</button></div><div class="slides" id="recap" tabindex="0" aria-label="Visual recap"><section class="slide"><h2>The details are<br>coming together.</h2><p>The palette and outdoor living selections are taking shape. ${state.approved.size===2?'Both sample decisions are recorded.':'Two decisions need a response before the next issue.'}</p><div class="recap-evidence"><button data-update="materials" aria-label="View palette update">${photo('materials')}</button><button data-update="chair" aria-label="View furniture update">${photo('chair')}</button><div><b>Follow the changes.</b><small>Palette & furniture<br>Example project references</small></div></div></section><section class="slide"><h2>A little room<br>to rebalance.</h2><p>The estimate is 12% above budget. Review specification options while keeping the design intent.</p><svg class="diagram" viewBox="0 0 380 110" role="img" aria-label="Budget 450 thousand; estimate 504 thousand"><text x="0" y="15">Budget · $450k</text><rect x="0" y="26" width="286" height="18" rx="4" fill="#b8c9af"/><text x="0" y="72">Estimate · $504k</text><rect x="0" y="84" width="320" height="18" rx="4" fill="#dbb7c2"/></svg></section><section class="slide"><h2>Protect the time<br>for the final details.</h2><p>The sample plan needs 15 hours before delivery, with 12 hours available. Review the remaining tasks and staffing.</p><div class="recap-stat"><strong>3 h</strong><span>capacity gap<small>Example workload forecast</small></span></div><button data-info="Task roadmap">Review the plan</button></section></div>${pager('recap',3)}</article>`}
const updateData=[['materials','Material palette refined','Maya · Today, 10:42 am','Review the palette before finalizing specifications.'],['chair','Outdoor lounge selection added','Alex · Yesterday, 3:10 pm','A new furniture reference is ready for review.'],['garden','Concept reference updated','Maya · Friday, 11:20 am','Review the outdoor living direction alongside the latest work.']];
function updates(){return `<article class="card update-card" data-card="updates">${head('Latest updates','Activity history','View all')}<div class="slides" id="updates" tabindex="0" aria-label="Visual project updates">${updateData.map(([id,t,by,desc])=>`<section class="slide"><button class="update-photo" data-update="${id}" aria-label="Open ${t}">${photo(id)}</button><div class="update-copy"><span class="eyebrow">EXAMPLE ACTIVITY</span><h3>${t}</h3><small>${by}</small><p>${desc}</p><button class="plain" data-update="${id}">View update ↗</button></div></section>`).join('')}</div>${pager('updates',3)}</article>`}
function updateStrip(){return `<div class="update-strip"><span class="eyebrow">LATEST UPDATES</span><div>${updateData.map(([id,t,by])=>`<button data-update="${id}"><span class="mini-photo">${photo(id)}</span><span><b>${t}</b><small>${by} · Example</small></span></button>`).join('')}</div></div>`}
function tabNav(){return `<div class="focus-nav"><div class="tabs" role="tablist" aria-label="Project focus">${[['today','Today'],['numbers','The numbers'],['progress','Progress']].map(([id,t])=>`<button role="tab" data-tab="${id}" aria-selected="${state.tab===id}">${t}</button>`).join('')}</div><span>${state.tab==='today'?'A few things to move forward.':state.tab==='numbers'?'Budget & design-fee health.':'The journey and what changed.'}</span></div>`}
function album(){return `<div class="album-top"><div class="album-main">${photo('garden')}<div><span class="eyebrow">CONCEPT DIRECTION</span><h2>The spaces.<br>The materials.<br>The feeling.</h2></div></div><div class="album-detail"><div class="slides" id="album" tabindex="0" aria-label="Project reference images"><section class="slide"><button data-update="materials">${photo('materials')}</button><div><span class="eyebrow">01 / THE PALETTE</span><h3>Texture, warmth & contrast.</h3><p>Material direction · example reference</p></div></section><section class="slide"><button data-update="chair">${photo('chair')}</button><div><span class="eyebrow">02 / OUTDOOR LIVING</span><h3>A place to settle in.</h3><p>Furniture selection · example reference</p></div></section></div>${pager('album',2)}</div></div>`}
function render(){const s=state;document.body.dataset.design=s.layout;document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.layout===s.layout));const active=s.tab==='today'?s.selected[s.layout]:s.tab==='numbers'?['budget','fee']:['journey','updates'];const draw=ids=>ids.map(id=>cards[id]()).join('')||'<div class="empty">Choose a card in Customize home.</div>';let top='';if(s.layout==='m')top=`<div class="open-studio"><div class="open-image">${photo('garden')}<div><span class="eyebrow">DESIGN DEVELOPMENT</span><h2>Room for the next chapter.</h2><small>Sample concept reference</small></div></div>${visualRecap()}</div>`;
if(s.layout==='n')top=album()+`<div class="album-brief"><div><span class="eyebrow">AI RECAP</span><h2>A strong direction. A few decisions to make.</h2><p>Confirm the palette and finish the review set. The estimate is 12% above budget; design fees project a 29% margin.</p></div><button data-info="Visual project brief">Explore recap ↗</button></div>`;
if(s.layout==='o')top=`<div class="project-desk"><div class="desk-story">${visualRecap()}</div><div class="desk-visual"><div class="desk-photo">${photo('garden')}<span>Sample concept reference</span></div><div class="desk-date"><div><b>${s.days}</b><span>days until delivery<small>Design development · fixed deadline</small></span></div><button data-info="Milestone settings">Details ↗</button></div></div></div>`;
$('#canvas').innerHTML=top+tabNav()+`<div class="board focus-board" role="tabpanel">${draw(active)}</div>`;$('#caption').innerHTML=`${names[s.layout]} · Example figures & activity. <a href="../project-home-r4/?revision=1#k">Previous designs K / L ↗</a>`;renderAlert();wireSlides();}
function renderAlert(){const visible=state.alerts&&state.timing==='now'&&!state.dismissed;$('#alert').innerHTML=visible?`<div class="notice" role="status"><p><b>Delivery needs a little attention.</b><small>Example forecast: 15 hours of work, 12 hours available.</small></p><button data-action="alerts">Preferences</button><button class="x" data-action="dismiss" aria-label="Dismiss delivery alert">×</button></div>`:''}
function wireSlides(){document.querySelectorAll('.slides').forEach(el=>{el.addEventListener('scroll',()=>{const i=Math.round(el.scrollLeft/el.clientWidth);document.querySelectorAll(`[data-slide="${el.id}"]`).forEach(b=>b.setAttribute('aria-current',+b.dataset.index===i))},{passive:true});el.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();el.scrollBy({left:el.clientWidth*(e.key==='ArrowRight'?1:-1),behavior:'smooth'})}})})}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').hidden=true,2300)}
function modal(title,content){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=content;if(!$('dialog').open)$('dialog').showModal()}
function preferences(){modal('Your alerts, your timing',`<p>Choose whether Home shows delivery-risk alerts and when you want to review them.</p><label><input id="alerts-enabled" type="checkbox" ${state.alerts?'checked':''}>Show delivery-risk alerts on Home</label><label class="field">When to show alerts<select id="alert-timing"><option value="now">When a new risk is detected</option><option value="daily">Daily summary · 9 am</option><option value="weekly">Weekly planning · Monday 9 am</option></select></label><label><input type="checkbox" checked disabled>Keep milestone dates visible</label><small>Preview only. Daily and weekly notifications need the future scheduler. “When a new risk is detected” shows an example you can dismiss.</small><br><button class="primary" data-action="save-alerts">Save preferences</button>`);$('#alert-timing').value=state.timing}
function customization(){modal('Make this home yours',`<p>Choose the cards in Today. The numbers and Progress remain available in their own tabs.</p>${Object.entries(titles).map(([id,t])=>`<label><input type="checkbox" data-card-toggle="${id}" ${state.selected[state.layout].includes(id)?'checked':''}>${t}</label>`).join('')}<button class="primary" data-action="close">Done</button><button data-action="reset-cards">Restore this layout</button>`)}
const info={
'About this study':'Three additional standalone Project Home directions. All previous mockups, including K and L, remain unchanged. The project name, address and $450,000 budget follow the built-in sample. Images are design references. Other figures, tasks, staff, dates, activity and AI wording are illustrative. Nothing here changes your project or sends notifications. Preferences reset when you reload.',
'Brief sources':'In the finished app, the brief would link to the latest estimate, agreed fee, remaining effort, approval records and committed milestones. These slides use example figures. The diagrams show the underlying amounts, rather than an unexplained AI score.',
'Task roadmap':'This will open the project’s phase-by-phase tasks, owners, dependencies and completion evidence. Checking a priority task here updates this preview only; it does not stand in for a recorded client approval.',
'Approval record':'A check records that the designer received approval. The finished app should store who recorded it, when, the exact selection or revision, and optional email or document evidence. It is not an automatic client signature. You can uncheck an item in this study to undo it.',
'Financials':'The example agreed design fee is $36,000. Costs to date are $18,400, with $7,200 forecast to finish. Projected profit is $10,400, or 28.9%. This is an example forecast, not invoiced or collected cash.',
'Estimate':'Example estimate: $504,000 against a $450,000 landscape budget. The difference is $54,000, or 12%. The approved Home card will use the project’s calculated estimate.',
'View potential savings':'This opens cost-saving options tied to real quantities and specifications. This preview’s opportunities are illustrative and must not be added together as guaranteed savings.',
'Bid comparison':'This would open the three bids with scope, quantities, allowances and exclusions compared. The preview figures are examples.',
'Plans & files':'Open the existing project file library: current plans, prior revisions, photos and issued deliverables. This is a shortcut, not a second file store.',
'Ask Studio H':'The project assistant will answer in a lightbox using authorized project information. No AI service is connected to this standalone study.',
'Switch project':'In the app, this switches the entire Home page to the selected project. This design study has one sample project.'};
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.update){const u=updateData.find(x=>x[0]===b.dataset.update);modal(u[1],`<div class="update-detail-photo">${photo(u[0])}</div><p>${u[2]} · Example activity</p><p>${u[3]}</p><small>In the app this would show the actual saved revision, who changed it, and a link to its project record. These are sample references.</small><br><button class="primary" data-action="close">Done</button>`);return}if(b.dataset.layout){state.layout=b.dataset.layout;location.hash=state.layout;render();return}if(b.dataset.tab){state.tab=b.dataset.tab;render();return}if(b.dataset.slide){let el=document.getElementById(b.dataset.slide);el.scrollTo({left:el.clientWidth*Number(b.dataset.index),behavior:'smooth'});return}if(b.dataset.carousel){const el=document.getElementById(b.dataset.carousel),n=el.children.length,i=Math.round(el.scrollLeft/el.clientWidth);el.scrollTo({left:el.clientWidth*((i+Number(b.dataset.step)+n)%n),behavior:'smooth'});return}if(b.dataset.mode){state.fast=b.dataset.mode==='fast';render();return}const action=b.dataset.action;if(action==='close')$('dialog').close();if(action==='cards')customization();if(action==='alerts')preferences();if(action==='dismiss'){state.dismissed=true;renderAlert()}if(action==='save-alerts'){state.alerts=$('#alerts-enabled').checked;state.timing=$('#alert-timing').value;state.dismissed=false;$('dialog').close();renderAlert();toast('Alert preference saved for this preview.')}if(action==='reset-cards'){state.selected[state.layout]=[...defaults[state.layout]];render();customization()}if(action==='save-milestone'){const d=Number($('#remaining-days').value);if(!Number.isInteger(d)||d<1||d>90){toast('Choose 1–90 days.');return}state.days=d;$('dialog').close();render()}if(b.dataset.info){const key=b.dataset.info;if(key==='Milestone settings'){modal('Milestone timing',`<p>Try the countdown colors: 1–2 days is muted rose, 3–7 powder blue, and more than a week soft green. The words and number stay visible.</p><label class="field">Days until delivery<input id="remaining-days" type="number" min="1" max="90" value="${state.days}"></label><button class="primary" data-action="save-milestone">Update preview</button>`)}else if(key==='Visual project brief'){modal('A visual project brief',brief(true).replaceAll('id="brief"','id="brief-modal"').replaceAll('data-slide="brief"','data-slide="brief-modal"').replaceAll('data-carousel="brief"','data-carousel="brief-modal"'));wireSlides()}else modal(key,`<p>${info[key]||`This would open ${key.toLowerCase()} for the current project. This standalone mockup keeps you on the preview.`}</p><button class="primary" data-action="close">Done</button>`)}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.task){t.checked?state.done.add(t.dataset.task):state.done.delete(t.dataset.task);const indexes={};document.querySelectorAll('.slides').forEach(s=>indexes[s.id]=Math.round(s.scrollLeft/s.clientWidth));render();Object.entries(indexes).forEach(([id,n])=>{const el=document.getElementById(id);if(el)el.scrollLeft=el.clientWidth*n});toast('Task updated in this preview.')}if(t.dataset.approval){t.checked?state.approved.add(t.dataset.approval):state.approved.delete(t.dataset.approval);render();toast(t.checked?'Approval recorded in preview. Uncheck to undo.':'Preview approval removed.')}if(t.dataset.cardToggle){let a=state.selected[state.layout];state.selected[state.layout]=t.checked?[...a,t.dataset.cardToggle]:a.filter(id=>id!==t.dataset.cardToggle);render()}});
window.addEventListener('hashchange',()=>{if(names[location.hash.slice(1)]){state.layout=location.hash.slice(1);render()}});render();
