const $=s=>document.querySelector(s);
const presets=[{id:'grid',name:'01 · Calm grid',desc:'Balanced, square images',dims:[[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2]]},{id:'feature',name:'02 · Feature & details',desc:'One big idea, smaller pieces',dims:[[3,3],[3,1],[1,2],[2,2],[3,1],[3,1],[2,2],[2,2],[2,2]]},{id:'smart',name:'03 · AI Smart Layout',desc:'A rendering leads; details support',dims:[[6,6],[6,3],[3,3],[3,3],[3,3],[3,3],[2,2],[2,2],[2,2]]},{id:'plan',name:'04 · Around the plan',desc:'Concept plan at the center',dims:[[4,4],[4,2],[4,2],[2,2],[2,2],[2,2],[2,2],[4,2],[4,2]]}];
const sizes=[[2,2],[3,2],[2,3],[3,3],[4,2],[4,4]];let state,history=[],dragged=null,timer;
const seed=()=>({preset:'smart',selected:1,surface:'card',labels:true,dense:true,gap:14,radius:16,edge:"straight",cardInset:0.125,collection:[],includePlan:false,showScale:true,showNorth:true,northAngle:0,showGrid:false,project:{company:"Studio H",title:"Concept landscape plan",address:"1205 Patton Way, San Marino, CA 91108"},sheetView:true,sheetColor:"#f0f0eb",planScale:0,extentW:80,extentH:60,paper:"24,36",orientation:"landscape",pw:36,ph:24,margin:0.5,titleOn:true,titlePct:100/6,next:10,tiles:presets[2].dims.map(([w,h],i)=>({id:i===0?2:i===1?1:i+1,w,h}))});state=seed();
function checkpoint(){history.push(structuredClone(state));if(history.length>40)history.shift()}
function change(fn){checkpoint();fn();draw()}
function notify(s){$('#status').textContent=s;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',2500)}
const names={1:'Conceptual design plan',2:'3D rendering',3:'Lounge furniture',4:'Dining furniture',5:'Paving material',6:'Feature tree',7:'Shrub selection',8:'Groundcover',9:'Color & texture'};
const name=id=>state.tiles.find(t=>t.id===id)?.title||names[id]||'Image '+String(id).padStart(2,'0');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const positions=[[3,3],[1,1],[5,1],[1,3],[7,3],[1,5],[7,5],[1,7],[5,7]];
function placement(t,i){if(state.preset!=='plan')return '';const [c,r]=positions[i]||[1,9+(i-9)*2];return `grid-column:${c}/span ${t.w};grid-row:${r}/span ${t.h};`}

const icon='<svg viewBox="0 0 32 32" aria-hidden="true"><rect x="4" y="4" width="24" height="24" rx="3"/><circle cx="12" cy="12" r="2"/><path d="m6 25 8-8 5 4 4-6 4 10"/></svg>';
function draw(){const selected=state.tiles.find(t=>t.id===state.selected);$('.presets').innerHTML=presets.map(p=>`<button class="preset" data-preset="${p.id}" aria-pressed="${p.id===state.preset}"><span class="mini" aria-hidden="true">${p.dims.slice(0,6).map(([w,h])=>`<i style="grid-column:span ${w};grid-row:span ${h}"></i>`).join('')}</span><span><strong>${p.name}</strong><small>${p.desc}</small></span></button>`).join('');$('#layout-name').textContent=(presets.find(p=>p.id===state.preset)?.name.split(' · ')[1]||'Your arrangement')+(state.preset==='custom'?'':'');const board=$('#board');board.dataset.layout=state.preset;board.style.setProperty('--radius',state.radius+'px');$('#radius').value=state.radius;$('#radius-value').textContent=state.radius+' px';$('#layout-note').textContent=state.preset==='plan'?'Concept plan stays central, with renderings and selections arranged around it.':state.preset==='smart'?'Suggested hierarchy: a dominant 3D rendering, medium furniture and material images, and smaller planting details.':'Choose a tile to adjust its size and position.';board.style.setProperty('--gap',state.gap+'px');board.style.gridAutoFlow=state.dense?'row dense':'row';board.classList.toggle('no-labels',!state.labels);board.innerHTML=state.tiles.map((t,i)=>`<button type="button" draggable="true" class="tile ${state.surface}" data-id="${t.id}" style="--w:${t.w};--mobile-w:${Math.min(t.w,4)};grid-column:span ${t.w};grid-row:span ${t.h};${placement(t,i)}" aria-label="${esc(name(t.id))}, ${t.w} by ${t.h}. Select to resize or move." aria-pressed="${t.id===state.selected}"><span class="placeholder">${icon}</span><small>${t.w} × ${t.h}</small><span class="caption">${esc(name(t.id))}</span></button>`).join('');$('#selected-name').textContent=selected?name(selected.id):'Choose an image';$('#shapes').innerHTML=sizes.map(([w,h])=>`<button data-size="${w},${h}" aria-label="${w} by ${h}" aria-pressed="${selected?.w===w&&selected?.h===h}" ${!selected?'disabled':''}><span class="shape" style="width:${w/h>1?30:Math.max(10,24*w/h)}px;height:${h/w>1?30:Math.max(10,24*h/w)}px"></span>${w} × ${h}</button>`).join('');document.querySelectorAll('[data-surface]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.surface===state.surface));$('#gap').value=state.gap;$('#gap-value').textContent=state.gap+' px';$('#labels').checked=state.labels;$('#dense').checked=state.dense;$('#undo').disabled=!history.length;const index=state.tiles.findIndex(t=>t.id===state.selected);$('#earlier').disabled=index<=0;$('#later').disabled=index<0||index===state.tiles.length-1;$('#remove').disabled=state.tiles.length<=1;document.querySelectorAll('[data-edge]').forEach(b=>b.setAttribute('aria-pressed',state.edge===b.dataset.edge));$('#ratio-w').value=selected?.rw||selected?.w||1;$('#ratio-h').value=selected?.rh||selected?.h||1;syncSheetControls();bind();requestAnimationFrame(()=>arrange())}
function reorder(from,to){if(from===to)return;change(()=>{const a=state.tiles.findIndex(t=>t.id===from),b=state.tiles.findIndex(t=>t.id===to);if(a<0||b<0)return;const [tile]=state.tiles.splice(a,1);state.tiles.splice(b,0,tile);state.selected=from;state.preset='custom'});notify(name(from)+' moved')}
function bind(){document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>change(()=>{const p=presets.find(p=>p.id===b.dataset.preset);state.preset=p.id;state.tiles.forEach(t=>{delete t.pin;delete t.size;delete t.gridHeight;delete t.rw;delete t.rh});state.includePlan=p.id==='plan';state.sheetView=true;if(p.id==='smart'||p.id==='plan'){const hero=p.id==='smart'?2:1;state.tiles.sort((a,b)=>(a.id===hero?-1:b.id===hero?1:a.id-b.id))}state.tiles.forEach((t,i)=>{[t.w,t.h]=p.dims[i%p.dims.length]})}));document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>change(()=>{const t=state.tiles.find(t=>t.id===state.selected);if(t)[t.w,t.h]=b.dataset.size.split(',').map(Number);state.preset='custom'}));document.querySelectorAll('[data-id]').forEach(b=>{b.onclick=()=>{state.selected=+b.dataset.id;draw();selectImage(state.selected)};b.ondragstart=e=>{dragged=+b.dataset.id;e.dataTransfer.setData('text/plain',String(dragged));e.dataTransfer.effectAllowed='move';b.classList.add('dragging')};b.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';b.classList.add('over')};b.ondragleave=()=>b.classList.remove('over');b.ondrop=e=>{e.preventDefault();b.classList.remove('over');if(dragged!==null)reorder(dragged,+b.dataset.id);dragged=null};b.ondragend=()=>{dragged=null;document.querySelectorAll('.over,.dragging').forEach(x=>x.classList.remove('over','dragging'))}})}
document.querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>change(()=>state.edge=b.dataset.edge));$('#apply-ratio').onclick=()=>{const w=+$('#ratio-w').value,h=+$('#ratio-h').value;if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0||w>100||h>100){notify('Enter width and height between 0.1 and 100.');return}change(()=>{const t=state.tiles.find(t=>t.id===state.selected);if(t){t.rw=w;t.rh=h}})};document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>change(()=>{const t=state.tiles.find(t=>t.id===state.selected);if(t)[t.rw,t.rh]=b.dataset.ratio.split(':').map(Number)}));document.querySelectorAll('[data-surface]').forEach(b=>b.onclick=()=>change(()=>state.surface=b.dataset.surface));$('#theme').onchange=e=>document.body.dataset.theme=e.target.value;$('#labels').onchange=e=>change(()=>state.labels=e.target.checked);$('#dense').onchange=e=>change(()=>state.dense=e.target.checked);$('#gap').oninput=e=>{$('#board').style.setProperty('--gap',e.target.value+'px');$('#gap-value').textContent=e.target.value+' px';arrange(+e.target.value)};$('#gap').onchange=e=>change(()=>state.gap=+e.target.value);$('#radius').oninput=e=>{$('#board').style.setProperty('--radius',e.target.value+'px');$('#radius-value').textContent=e.target.value+' px'};$('#radius').onchange=e=>change(()=>state.radius=+e.target.value);$('#undo').onclick=()=>{if(history.length){state=history.pop();draw()}};$('#reset').onclick=()=>change(()=>state=seed());$('#add').onclick=()=>{if(state.tiles.length>=24){notify('This study supports up to 24 tiles.');return}change(()=>{const id=state.next++;state.tiles.push({id,w:2,h:2});state.selected=id;state.preset='custom'})};$('#remove').onclick=()=>change(()=>{if(state.tiles.length<=1)return;state.tiles=state.tiles.filter(t=>t.id!==state.selected);state.selected=state.tiles[0].id;state.preset='custom'});$('#earlier').onclick=()=>{const i=state.tiles.findIndex(t=>t.id===state.selected);if(i>0)reorder(state.selected,state.tiles[i-1].id)};$('#later').onclick=()=>{const i=state.tiles.findIndex(t=>t.id===state.selected);if(i>=0&&i<state.tiles.length-1)reorder(state.selected,state.tiles[i+1].id)};

// Equal gutters within and between columns. Straight mode fits frames to a shared height;
// staggered mode preserves chosen proportions and lets column ends differ.
function arrange(gap=state.gap){
 setupSheet();if(state.sheetView){arrangeSheet(gap);return}const board=$('#board'),width=board.clientWidth,mobile=width<500;board.classList.remove('snap-layout');
 const nodes=new Map([...board.querySelectorAll('.tile')].map(e=>[+e.dataset.id,e]));
 const visibleTiles=state.planScale?state.tiles.filter(t=>t.id!==1):state.tiles;const count=mobile?2:3,cols=Array.from({length:count},()=>[]);
 const hero=state.preset==='plan'?1:state.preset==='smart'?2:null;
 const focal=visibleTiles.find(t=>t.id===hero),center=state.preset==='plan'&&!mobile?1:0;
 if(focal)cols[center].push(focal);
 const load=cols.map((c,i)=>c.reduce((sum,t)=>sum+(focal&&i===center?1.65:1)/((t.rw||t.w)/(t.rh||t.h)),0));
 for(const t of visibleTiles){if(t===focal)continue;const c=load.indexOf(Math.min(...load));cols[c].push(t);load[c]+=(focal&&c===center?1.65:1)/((t.rw||t.w)/(t.rh||t.h))+.06}

 const weights=cols.map((c,i)=>focal&&i===center?1.65:1),unit=(width-gap*(count-1))/weights.reduce((a,b)=>a+b,0);
 const heights=cols.map((col,i)=>col.map(t=>unit*weights[i]/((t.rw||t.w)/(t.rh||t.h))));
 const total=heights.map(h=>h.reduce((a,b)=>a+b,0)+Math.max(0,h.length-1)*gap),target=Math.max(...total);
 board.replaceChildren();board.classList.add('free-layout');board.dataset.edge=state.edge;board.style.gap=gap+'px';
 cols.forEach((col,i)=>{const wrap=document.createElement('div');wrap.className='layout-column';wrap.style.flex=weights[i];wrap.style.gap=gap+'px';col.forEach((t,j)=>{const e=nodes.get(t.id);if(!e)return;const natural=heights[i][j],scale=(target-gap*Math.max(0,col.length-1))/(total[i]-gap*Math.max(0,col.length-1)||1);e.style.height=(state.edge==='straight'?natural*scale:natural)+'px';e.querySelector('small').textContent=(t.rw||t.w)+':'+(t.rh||t.h);wrap.append(e)});board.append(wrap)});
 fitBoard();$('#edge-note').textContent=state.edge==='straight'?'Frames align to one outer rectangle. Image proportions may need cropping; plans should fit fully inside their frames.':'Frames keep their chosen proportions. Equal gutters stay in place while the outer edge steps in and out.';
}
new ResizeObserver(()=>setupSheet()).observe($('#sheet-stage'));

function sheetSize(){if(state.paper==='custom')return [state.pw,state.ph];const [a,b]=state.paper.split(',').map(Number);return state.orientation==='portrait'?[a,b]:[b,a]}
function syncSheetControls(){$('#card-inset').value=state.cardInset;$('#inset-value').textContent=state.cardInset+' in';syncProjectControls();$('#sheet-color').value=state.sheetColor;$('#quick-captions').checked=state.labels;$('#board-view').setAttribute('aria-pressed',!state.sheetView);$('#sheet-view').setAttribute('aria-pressed',state.sheetView);for(const [id,v] of Object.entries({paper:state.paper,orientation:state.orientation,margin:state.margin,'title-height':state.titlePct,'paper-w':state.pw,'paper-h':state.ph}))$('#'+id).value=v;$('#plan-scale').value=state.planScale;$('#extent-w').value=state.extentW;$('#extent-h').value=state.extentH;$('#title-on').checked=state.titleOn;$('#custom-paper').hidden=state.paper!=='custom';$('#orientation').disabled=state.paper==='custom';$('#title-height').disabled=!state.titleOn}
function setupSheet(){if(typeof updateTitle!=='function')return;$('#sheet').style.setProperty('--card-inset',state.cardInset*960/sheetSize()[0]+'px');$('#sheet').style.setProperty('--sheet-color',state.sheetColor);document.body.classList.toggle('board-preview',!state.sheetView);if(!state.sheetView){$('#sheet').style.left='0px';$('#sheet').style.height='auto';$('#sheet').style.transform='none';$('#sheet-stage').style.height='auto';return}const [w,h]=sheetSize(),sh=960*h/w,m=960*state.margin/w,t=state.titleOn?sh*state.titlePct/100:0;const sheet=$('#sheet');sheet.style.height=sh+'px';const available=$('#sheet-stage').clientWidth;const scale=Math.min(available/960*Math.min(w/36,1),Math.max(180,innerHeight-180)/sh);sheet.style.left=((available-960*scale)/2)+'px';sheet.style.transform=`scale(${scale})`;$('#sheet-stage').style.height=sh*scale+'px';const area=$('#image-area');Object.assign(area.style,{left:m+'px',top:m+'px',width:(960-2*m)+'px',height:(sh-2*m-t-(t?14:0))+'px'});Object.assign($('#titleblock').style,{left:m+'px',bottom:m+'px',width:(960-2*m)+'px',height:t+'px',display:state.titleOn?'flex':'none'});updateTitle();$('#sheet-summary').textContent=`${w} × ${h} in · ${state.margin} in border · ${state.titleOn?(h*state.titlePct/100).toFixed(2)+' in title block':'No title block'}`;$('#margin-value').textContent=state.margin+' in';$('#title-value').textContent=state.titlePct.toFixed(1)+'%';$('#titleblock').setAttribute('aria-label','Title block reserved area, '+(h*state.titlePct/100).toFixed(2)+' inches high');let style=$('#print-size');if(!style){style=document.createElement('style');style.id='print-size';document.head.append(style)}style.textContent=`@page{size:${w}in ${h}in;margin:0}@media print{#sheet-stage{width:${w}in!important;height:${h}in!important}#sheet{transform:scale(${w/10})!important}}`}
function fitBoard(){if(!state.sheetView){$('#export-pdf').disabled=false;$('#scale-status').textContent=state.planScale?'Open Sheet preview to inspect the locked plan scale.':'Plan is fitted visually. No measured scale is claimed.';$('#scaled-plan').hidden=true;$('#board').style.transform='none';$('#board').style.left='0px';$('#board').style.top='0px';return}const reserved=placePlan();const b=$('#board'),a=$('#image-area');b.style.transform='none';b.style.width='960px';const scale=Math.min(a.clientWidth/960,Math.max(1,a.clientHeight-reserved)/b.scrollHeight);b.style.transform=`scale(${scale})`;b.style.left=((a.clientWidth-960*scale)/2)+'px';b.style.top=reserved+'px'}
$('#paper').onchange=e=>change(()=>{state.paper=e.target.value;state.sheetView=true});$('#orientation').onchange=e=>change(()=>{state.orientation=e.target.value;state.sheetView=true});$('#apply-paper').onclick=()=>{const w=+$('#paper-w').value,h=+$('#paper-h').value;if(w<4||h<4||w>60||h>60){notify('Choose a sheet between 4 and 60 inches.');return}change(()=>{state.pw=w;state.ph=h;state.sheetView=true})};$('#margin').oninput=e=>change(()=>{state.margin=+e.target.value;state.sheetView=true});$('#title-on').onchange=e=>change(()=>{state.titleOn=e.target.checked;state.sheetView=true});$('#title-height').oninput=e=>change(()=>{state.titlePct=+e.target.value;state.sheetView=true});$('#export-pdf').onclick=()=>{state.sheetView=true;draw();requestAnimationFrame(()=>{arrange();if(!$('#export-pdf').disabled)window.print()})};

function placePlan(){const frame=$('#scaled-plan'),scale=state.planScale;frame.hidden=!scale;$('#export-pdf').disabled=false;if(!scale){$('#scale-status').textContent='Plan is fitted visually. No measured scale is claimed.';return 0}const [sheetW]=sheetSize(),px=960/sheetW,w=state.extentW*scale*px,h=state.extentH*scale*px,area=$('#image-area');const fits=w<=area.clientWidth&&h+100<=area.clientHeight;Object.assign(frame.style,{width:w+'px',height:h+'px',left:Math.max(0,(area.clientWidth-w)/2)+'px',top:'0px'});$('#plan-scale-label').textContent=`${scale===.125?'1/8':scale===.25?'1/4':'1/16'} inch = 1 foot · print at 100% · illustrative`;
 $('#scale-status').textContent=`Plan frame: ${(state.extentW*scale).toFixed(2)} × ${(state.extentH*scale).toFixed(2)} in. `+(fits?'Scale is locked; other images fit around the reserved space.':'Not enough room for the plan and supporting images. Choose a larger sheet, smaller scale, or smaller title block.');$('#export-pdf').disabled=!fits;frame.classList.toggle('no-fit',!fits);return h+36}
$('#plan-scale').onchange=e=>change(()=>{state.planScale=+e.target.value;state.includePlan=true;state.sheetView=true});$('#apply-extent').onclick=()=>{const w=+$('#extent-w').value,h=+$('#extent-h').value;if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0){notify('Enter verified positive plan dimensions.');return}change(()=>{state.extentW=w;state.extentH=h})};
let detailTrigger;
function openDetails(id){detailTrigger=id;const isPlan=id===1;$('#detail-title').textContent=name(id);$('#detail-caption').textContent=isPlan?'Concept plan used to demonstrate the full-image viewer and measured sheet frame.':'Full-size preview placeholder. A connected project image will appear here uncropped, with its caption and library record.';$('#detail-img').hidden=!isPlan;$('#detail-blank').hidden=isPlan;if(isPlan){$('#detail-img').src='sample-plan.svg';$('#detail-img').alt='Full illustrative conceptual plan'}else{$('#detail-blank').innerHTML=icon;$('#detail-blank').setAttribute('aria-label','No project image attached in this mockup')}$('#detail-source').textContent=isPlan?'Layout study · illustrative SVG':'Library source not connected in this study';$('#detail-size-note').textContent=isPlan&&state.planScale?'Measured scale is locked. Change Drawing scale to resize the plan.':'Size changes keep the image on the alignment grid.';$('#detail-info').textContent=isPlan?'1200 × 900 · SVG · example dimensions only':'No original image metadata available';$('#source-link').hidden=!isPlan;$('#source-link').href='sample-plan.svg';const added=state.tiles.find(t=>t.id===id);if(added?.src){$('#detail-img').hidden=false;$('#detail-blank').hidden=true;$('#detail-img').src=added.src;$('#detail-img').alt=name(id);$('#detail-caption').textContent=added.title;$('#detail-source').textContent=added.source;$('#detail-info').textContent=added.iw+' × '+added.ih+' pixels';$('#source-link').hidden=false;$('#source-link').href=added.src}$('#image-dialog').showModal()}
function closeDetails(){$('#image-dialog').close();requestAnimationFrame(()=>document.querySelector(`[data-id="${detailTrigger}"]`)?.focus({preventScroll:true}))}
$('#close-detail').onclick=closeDetails;$('#edit-detail').onclick=()=>{closeDetails();$('#selected-name').scrollIntoView({behavior:'smooth',block:'center'})};$('#image-dialog').onclick=e=>{if(e.target===$('#image-dialog'))closeDetails()};$('#scaled-plan').onclick=()=>selectImage(1);$('#scaled-plan').tabIndex=0;$('#scaled-plan').setAttribute('role','button');$('#scaled-plan').setAttribute('aria-label','Open conceptual plan image details');$('#scaled-plan').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectImage(1)}};

$('#board-view').onclick=()=>change(()=>{state.sheetView=false;$('#export-pdf').disabled=false});$('#sheet-view').onclick=()=>change(()=>state.sheetView=true);$('#quick-captions').onchange=e=>change(()=>state.labels=e.target.checked);

$('#sheet-color').onchange=e=>change(()=>{state.sheetColor=e.target.value;state.sheetView=true});

$('#card-inset').oninput=e=>change(()=>state.cardInset=+e.target.value);
