const librarySamples={chair:{src:'../../assets/lounge-chair.png',title:'Lounge chair',source:'Furniture library · sample'},materials:{src:'../../assets/med-materials.png',title:'Warm material palette',source:'Materials library · sample'},inspiration:{src:'../../assets/med-scenes.png',title:'Garden inspiration',source:'Inspiration library · sample'}};
function renderAddedImages(){document.querySelectorAll('#board [data-id]').forEach(el=>{const t=state.tiles.find(t=>t.id===+el.dataset.id);if(!t?.src)return;const ph=el.querySelector('.placeholder');if(!ph)return;if(ph.querySelector('img'))return;ph.replaceChildren();const img=document.createElement('img');img.src=t.src;img.alt=t.title;img.draggable=false;ph.append(img)})}
function openAdd(){$('#add-status').textContent='';$('#add-dialog').showModal()}
$('#add').onclick=openAdd;$('#close-add').onclick=()=>$('#add-dialog').close();
$('#remove-presentation').onclick=()=>{const id=state.selected;change(()=>{state.tiles=state.tiles.filter(t=>t.id!==id);if(id===1)state.includePlan=false;state.selected=state.tiles[0]?.id||0});$('#close-tools').click();notify('Removed from this presentation only. Undo restores it.')};
async function addSource(src,title,source){const img=new Image();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Image could not be loaded. Try uploading it instead.')),12000);img.onload=()=>{clearTimeout(timer);resolve()};img.onerror=()=>{clearTimeout(timer);reject(new Error('This URL is not an accessible image. Try a direct image URL or upload.'))};img.src=src});const old=structuredClone(state);checkpoint();const id=state.next++;state.tiles.push({id,w:3,h:3,rw:Math.round(img.naturalWidth/Math.max(img.naturalWidth,img.naturalHeight)*16*10)/10,rh:Math.round(img.naturalHeight/Math.max(img.naturalWidth,img.naturalHeight)*16*10)/10,size:3,title,source,src,iw:img.naturalWidth,ih:img.naturalHeight});state.sheetView=true;state.selected=id;draw();arrange();if(sheetGeometry?.missing.length){state=old;history.pop();draw();arrange();throw new Error('No room for another image. Remove or reduce an image first.')}state.collection.push(structuredClone(state.tiles.find(t=>t.id===id)));$('#add-dialog').close();selectImage(id);notify('Image added to the presentation preview');}
async function withStatus(fn){$('#add-status').textContent='Loading image…';try{await fn();$('#add-status').textContent=''}catch(e){$('#add-status').textContent=e.message;notify(e.message)}}
document.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>withStatus(()=>{const x=librarySamples[b.dataset.library];return addSource(x.src,x.title,x.source)}));
async function addFiles(files){for(const file of files){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Choose a JPG, PNG, WebP or GIF image.');if(file.size>20*1024*1024)throw new Error('For this preview, choose images below 20 MB.');const url=URL.createObjectURL(file);try{await addSource(url,file.name,'Uploaded image · preview only')}catch(e){URL.revokeObjectURL(url);throw e}}}
$('#image-upload').onchange=e=>withStatus(()=>addFiles([...e.target.files]));
$('#add-url').onclick=()=>withStatus(async()=>{let url;try{url=new URL($('#image-url').value)}catch{throw new Error('Enter a complete HTTPS image URL.')}if(url.protocol!=='https:')throw new Error('Use an HTTPS image URL.');await addSource(url.href,'Linked image',url.hostname)});
for(const zone of [$('#upload-drop'),$('#sheet-stage')]){zone.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();zone.classList.add('file-over')}});zone.addEventListener('dragleave',()=>zone.classList.remove('file-over'));zone.addEventListener('drop',e=>{zone.classList.remove('file-over');if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();withStatus(()=>addFiles([...e.dataTransfer.files]))}},true)}
$('#upload-drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#image-upload').click()}};

Object.assign(librarySamples,{sage:{src:'sample-sage.svg',title:'Cleveland sage',source:'Plants · sample Plant Book illustration'},olive:{src:'sample-olive.svg',title:'Fruitless olive',source:'Plants · sample Plant Book illustration'},palette:{src:'sample-palette.svg',title:'Warm neutrals · soft greens',source:'Color palettes · sample'},insight:{src:'sample-insight.svg',title:'A lower-water garden',source:'Insights · illustrative sample'}});
for(const [key,category] of [['sage','Plants'],['olive','Plants'],['palette','Color palettes'],['insight','Insights']]){const x=librarySamples[key],b=document.createElement('button');b.dataset.library=key;b.dataset.category=category;const img=document.createElement('img');img.src=x.src;img.alt=x.title;b.append(img,document.createTextNode(category+' · '+x.title));b.onclick=()=>withStatus(()=>addSource(x.src,x.title,x.source));$('.library-choices').append(b)}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.library-choices button').forEach(x=>x.hidden=b.dataset.cat!=='all'&&x.dataset.category!==b.dataset.cat);document.querySelectorAll('[data-cat]').forEach(x=>x.setAttribute('aria-pressed',x===b))});
function collectionCategory(item){return item.source.startsWith('Plants')?'Plants':item.source.startsWith('Insights')?'Insights':item.source.startsWith('Color palettes')?'Color palettes':item.source.startsWith('Furniture')?'Furniture':item.source.startsWith('Materials')?'Materials':'Inspiration & uploads'}
function showSections(){const root=$('#section-items');root.replaceChildren();if(!state.collection.length){root.textContent='Add an item from the libraries to create its section here.'}const groups={};state.collection.forEach(item=>(groups[collectionCategory(item)]??=[]).push(item));for(const [category,items] of Object.entries(groups)){const section=document.createElement('section'),h=document.createElement('h3');h.textContent=category;section.append(h);const list=document.createElement('div');list.className='section-cards';for(const item of items){const card=document.createElement('div'),img=document.createElement('img'),label=document.createElement('p');img.src=item.src;img.alt=item.title;label.textContent=item.title;card.append(img,label);if(!state.tiles.some(t=>t.id===item.id)){const btn=document.createElement('button');btn.textContent='Add back to presentation';btn.onclick=()=>{editPresentation(()=>state.tiles.push(structuredClone(item)));showSectionContents()};card.append(btn)}list.append(card)}section.append(list);root.append(section)}if(!$('#sections-dialog').open)$('#sections-dialog').showModal()}
function showSectionContents(){showSections()}
$('#section-view').onclick=showSections;$('#close-sections').onclick=()=>$('#sections-dialog').close();$('#section-add').onclick=()=>{$('#sections-dialog').close();openAdd()};
draw();
