const railIcons={undo:'<path d="M9 5 4 10l5 5M4 10h10a5 5 0 0 1 0 10"/>',layout:'<rect x="3" y="3" width="8" height="18" rx="2"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="13" width="7" height="8" rx="1"/>',sheet:'<path d="M5 3h10l4 4v14H5zM14 3v5h5M8 12h8M8 16h6"/>',plan:'<path d="M3 5 9 3l6 3 6-2v16l-6 2-6-3-6 2zM9 3v16M15 6v16"/>',image:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="2"/><path d="m4 18 6-6 4 3 4-5 3 7"/>',style:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>',add:'<path d="M12 4v16M4 12h16"/>',sections:'<path d="m3 7 9-4 9 4-9 4zM3 12l9 4 9-4M3 17l9 4 9-4"/>',export:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>'};
const rail=document.createElement('nav');rail.id='tracer-rail';rail.setAttribute('aria-label','Presentation tools');
const topActions=[['undo','Undo'],['layout','Layout'],['sheet','Sheet'],['plan','Plan'],['image','Image'],['style','Style'],['add','Add'],['sections','Sections']];
for(const [id,label] of topActions){const b=document.createElement('button');b.dataset.rail=id;b.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${railIcons[id]}</svg><span>${label}</span>`;b.title=label;b.onclick=()=>railAction(id);rail.append(b)}
const bottom=document.createElement('div');bottom.className='rail-bottom';for(const [id,label] of [['export','Export'],['close','Close']]){const b=document.createElement('button');b.dataset.rail=id;b.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${railIcons[id]}</svg><span>${label}</span>`;b.onclick=()=>railAction(id);bottom.append(b)}rail.append(bottom);document.body.append(rail);
const panel=document.createElement('section');panel.id='tracer-panel';panel.innerHTML='<div class="shell-panel-head"><strong id="shell-panel-title"></strong><button id="collapse-panel" aria-label="Collapse tool panel">‹</button></div><div id="shell-panel-body"></div>';document.body.append(panel);
const panels=[...document.querySelectorAll('aside>.panel')];const groups={layout:document.querySelector('.presets'),sheet:panels[0],plan:panels[1],style:panels[2],image:$('#image-tools')};
const staging=document.createElement('div');staging.hidden=true;staging.id='tool-storage';document.body.append(staging);Object.values(groups).forEach(el=>staging.append(el));
const intro=document.createElement('p');intro.className='shell-intro';intro.textContent='Choose the starting arrangement. Select images on the sheet to customize.';groups.layout.prepend(intro);
const quick=document.createElement('label');quick.className='shell-check';quick.append($('#quick-captions'),document.createTextNode(' Show image captions'));groups.style.append(quick);
const gridLabel=document.createElement('label');gridLabel.className='shell-check';gridLabel.append($('#show-grid'),document.createTextNode(' Show alignment grid'));groups.style.append(gridLabel);
let currentGroup=null;
function setTool(id){if(currentGroup&&groups[currentGroup])staging.append(groups[currentGroup]);currentGroup=id;document.body.classList.toggle('tool-expanded',!!id);document.querySelectorAll('[data-rail]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.rail===id));if(id){$('#shell-panel-title').textContent={layout:'Layout',sheet:'Sheet & title',plan:'Plan & scale',image:'Selected image',style:'Appearance'}[id];$('#shell-panel-body').replaceChildren(groups[id]);if(id==='image'){groups.image.hidden=false;syncImageTools()}}requestAnimationFrame(()=>arrange())}
function railAction(id){if(groups[id]){setTool(currentGroup===id?null:id);return}if(id==='undo'){$('#undo').click();return}if(id==='add'){openAdd();return}if(id==='sections'){showSections();return}if(id==='export'){$('#export-pdf').click();return}if(id==='close'){location.href='../moodboard-layouts/?revision=11'}}
$('#collapse-panel').onclick=()=>setTool(null);
const previousSelectImage=selectImage;selectImage=function(id){previousSelectImage(id);setTool('image');document.body.classList.remove('editing-image')};
$('#close-tools').onclick=()=>setTool(null);
const header=document.createElement('header');header.id='shell-top';header.innerHTML='<div><strong>Moodboard presentation</strong><small>Tracer-style workspace · interactive study</small></div><div class="shell-top-actions"><a href="../moodboard-layouts/?revision=11">Compare previous layout ↗</a></div>';header.querySelector('.shell-top-actions').append($('#theme'));document.body.append(header);
const footer=document.createElement('div');footer.id='shell-foot';footer.textContent='Select an image to edit · Hold and drag to move · Sections and presentation share this preview’s selections';document.body.append(footer);
state.sheetView=true;draw();setTool('layout');
