const $=s=>document.querySelector(s);
const presets=[{id:'grid',name:'01 · Calm grid',desc:'Balanced, square images',dims:[[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2],[2,2]]},{id:'feature',name:'02 · Feature & details',desc:'One big idea, smaller pieces',dims:[[3,3],[3,1],[1,2],[2,2],[3,1],[3,1],[2,2],[2,2],[2,2]]},{id:'mosaic',name:'03 · Fitted mosaic',desc:'Mixed shapes that fill together',dims:[[2,2],[3,1],[1,3],[3,1],[1,2],[2,2],[2,1],[2,1],[1,1]]},{id:'strips',name:'04 · Long & lean',desc:'Panoramas and tall accents',dims:[[3,1],[3,1],[1,3],[2,2],[3,1],[3,1],[2,2],[3,1],[3,1]]}];
const sizes=[[1,1],[2,2],[3,1],[1,3],[3,2],[3,3]];let state,history=[],dragged=null,timer;
const seed=()=>({preset:'mosaic',selected:1,surface:'card',labels:true,dense:true,gap:14,next:10,tiles:presets[2].dims.map(([w,h],i)=>({id:i+1,w,h}))});state=seed();
function checkpoint(){history.push(structuredClone(state));if(history.length>40)history.shift()}
function change(fn){checkpoint();fn();draw()}
function notify(s){$('#status').textContent=s;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',2500)}
const name=id=>'Image '+String(id).padStart(2,'0');
const icon='<svg viewBox="0 0 32 32" aria-hidden="true"><rect x="4" y="4" width="24" height="24" rx="3"/><circle cx="12" cy="12" r="2"/><path d="m6 25 8-8 5 4 4-6 4 10"/></svg>';
function draw(){const selected=state.tiles.find(t=>t.id===state.selected);$('.presets').innerHTML=presets.map(p=>`<button class="preset" data-preset="${p.id}" aria-pressed="${p.id===state.preset}"><span class="mini" aria-hidden="true">${p.dims.slice(0,6).map(([w,h])=>`<i style="grid-column:span ${w};grid-row:span ${h}"></i>`).join('')}</span><span><strong>${p.name}</strong><small>${p.desc}</small></span></button>`).join('');$('#layout-name').textContent=(presets.find(p=>p.id===state.preset)?.name.split(' · ')[1]||'Your arrangement')+(state.preset==='custom'?'':'');const board=$('#board');board.style.setProperty('--gap',state.gap+'px');board.style.gridAutoFlow=state.dense?'row dense':'row';board.classList.toggle('no-labels',!state.labels);board.innerHTML=state.tiles.map(t=>`<button type="button" draggable="true" class="tile ${state.surface}" data-id="${t.id}" style="--w:${t.w};grid-column:span ${t.w};grid-row:span ${t.h}" aria-label="${name(t.id)}, ${t.w} by ${t.h}. Select to resize or move." aria-pressed="${t.id===state.selected}"><span class="placeholder">${icon}</span><small>${t.w} × ${t.h}</small><span class="caption">${name(t.id)}</span></button>`).join('');$('#selected-name').textContent=selected?name(selected.id):'Choose an image';$('#shapes').innerHTML=sizes.map(([w,h])=>`<button data-size="${w},${h}" aria-label="${w} by ${h}" aria-pressed="${selected?.w===w&&selected?.h===h}" ${!selected?'disabled':''}><span class="shape" style="width:${w/h>1?30:Math.max(10,24*w/h)}px;height:${h/w>1?30:Math.max(10,24*h/w)}px"></span>${w} × ${h}</button>`).join('');document.querySelectorAll('[data-surface]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.surface===state.surface));$('#gap').value=state.gap;$('#gap-value').textContent=state.gap+' px';$('#labels').checked=state.labels;$('#dense').checked=state.dense;$('#undo').disabled=!history.length;const index=state.tiles.findIndex(t=>t.id===state.selected);$('#earlier').disabled=index<=0;$('#later').disabled=index<0||index===state.tiles.length-1;$('#remove').disabled=state.tiles.length<=1;bind()}
function reorder(from,to){if(from===to)return;change(()=>{const a=state.tiles.findIndex(t=>t.id===from),b=state.tiles.findIndex(t=>t.id===to);if(a<0||b<0)return;const [tile]=state.tiles.splice(a,1);state.tiles.splice(b,0,tile);state.selected=from;state.preset='custom'});notify(name(from)+' moved')}
function bind(){document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>change(()=>{const p=presets.find(p=>p.id===b.dataset.preset);state.preset=p.id;state.tiles.forEach((t,i)=>{[t.w,t.h]=p.dims[i%p.dims.length]})}));document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>change(()=>{const t=state.tiles.find(t=>t.id===state.selected);if(t)[t.w,t.h]=b.dataset.size.split(',').map(Number);state.preset='custom'}));document.querySelectorAll('[data-id]').forEach(b=>{b.onclick=()=>{state.selected=+b.dataset.id;draw();document.querySelector('[data-id="'+state.selected+'"]').focus({preventScroll:true})};b.ondragstart=e=>{dragged=+b.dataset.id;e.dataTransfer.setData('text/plain',String(dragged));e.dataTransfer.effectAllowed='move';b.classList.add('dragging')};b.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';b.classList.add('over')};b.ondragleave=()=>b.classList.remove('over');b.ondrop=e=>{e.preventDefault();b.classList.remove('over');if(dragged!==null)reorder(dragged,+b.dataset.id);dragged=null};b.ondragend=()=>{dragged=null;document.querySelectorAll('.over,.dragging').forEach(x=>x.classList.remove('over','dragging'))}})}
document.querySelectorAll('[data-surface]').forEach(b=>b.onclick=()=>change(()=>state.surface=b.dataset.surface));$('#theme').onchange=e=>document.body.dataset.theme=e.target.value;$('#labels').onchange=e=>change(()=>state.labels=e.target.checked);$('#dense').onchange=e=>change(()=>state.dense=e.target.checked);$('#gap').oninput=e=>{$('#board').style.setProperty('--gap',e.target.value+'px');$('#gap-value').textContent=e.target.value+' px'};$('#gap').onchange=e=>change(()=>state.gap=+e.target.value);$('#undo').onclick=()=>{if(history.length){state=history.pop();draw()}};$('#reset').onclick=()=>change(()=>state=seed());$('#add').onclick=()=>{if(state.tiles.length>=24){notify('This study supports up to 24 tiles.');return}change(()=>{const id=state.next++;state.tiles.push({id,w:2,h:2});state.selected=id;state.preset='custom'})};$('#remove').onclick=()=>change(()=>{if(state.tiles.length<=1)return;state.tiles=state.tiles.filter(t=>t.id!==state.selected);state.selected=state.tiles[0].id;state.preset='custom'});$('#earlier').onclick=()=>{const i=state.tiles.findIndex(t=>t.id===state.selected);if(i>0)reorder(state.selected,state.tiles[i-1].id)};$('#later').onclick=()=>{const i=state.tiles.findIndex(t=>t.id===state.selected);if(i>=0&&i<state.tiles.length-1)reorder(state.selected,state.tiles[i+1].id)};draw();
