const librarySamples={chair:{src:'../../assets/lounge-chair.png',title:'Lounge chair',source:'Furniture library · sample'},materials:{src:'../../assets/med-materials.png',title:'Warm material palette',source:'Materials library · sample'},inspiration:{src:'../../assets/med-scenes.png',title:'Garden inspiration',source:'Inspiration library · sample'}};
function renderAddedImages(){document.querySelectorAll('#board [data-id]').forEach(el=>{const t=state.tiles.find(t=>t.id===+el.dataset.id);if(!t?.src)return;const ph=el.querySelector('.placeholder');if(!ph)return;if(ph.querySelector('img'))return;ph.replaceChildren();const img=document.createElement('img');img.src=t.src;img.alt=t.title;img.draggable=false;ph.append(img)})}
function openAdd(){$('#add-status').textContent='';$('#add-dialog').showModal()}
$('#add').onclick=openAdd;$('#close-add').onclick=()=>$('#add-dialog').close();
$('#remove-presentation').onclick=()=>{const id=state.selected;change(()=>{state.tiles=state.tiles.filter(t=>t.id!==id);if(id===1)state.includePlan=false;state.selected=state.tiles[0]?.id||0});$('#close-tools').click();notify('Removed from this presentation only. Undo restores it.')};
async function addSource(src,title,source){const img=new Image();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Image could not be loaded. Try uploading it instead.')),12000);img.onload=()=>{clearTimeout(timer);resolve()};img.onerror=()=>{clearTimeout(timer);reject(new Error('This URL is not an accessible image. Try a direct image URL or upload.'))};img.src=src});const old=structuredClone(state);checkpoint();const id=state.next++;state.tiles.push({id,w:3,h:3,rw:Math.round(img.naturalWidth/Math.max(img.naturalWidth,img.naturalHeight)*16*10)/10,rh:Math.round(img.naturalHeight/Math.max(img.naturalWidth,img.naturalHeight)*16*10)/10,size:3,title,source,src,iw:img.naturalWidth,ih:img.naturalHeight});state.sheetView=true;state.selected=id;draw();arrange();if(sheetGeometry?.missing.length){state=old;history.pop();draw();arrange();throw new Error('No room for another image. Remove or reduce an image first.')}$('#add-dialog').close();selectImage(id);notify('Image added to the presentation preview');}
async function withStatus(fn){$('#add-status').textContent='Loading image…';try{await fn();$('#add-status').textContent=''}catch(e){$('#add-status').textContent=e.message;notify(e.message)}}
document.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>withStatus(()=>{const x=librarySamples[b.dataset.library];return addSource(x.src,x.title,x.source)}));
async function addFiles(files){for(const file of files){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw new Error('Choose a JPG, PNG, WebP or GIF image.');if(file.size>20*1024*1024)throw new Error('For this preview, choose images below 20 MB.');const url=URL.createObjectURL(file);try{await addSource(url,file.name,'Uploaded image · preview only')}catch(e){URL.revokeObjectURL(url);throw e}}}
$('#image-upload').onchange=e=>withStatus(()=>addFiles([...e.target.files]));
$('#add-url').onclick=()=>withStatus(async()=>{let url;try{url=new URL($('#image-url').value)}catch{throw new Error('Enter a complete HTTPS image URL.')}if(url.protocol!=='https:')throw new Error('Use an HTTPS image URL.');await addSource(url.href,'Linked image',url.hostname)});
for(const zone of [$('#upload-drop'),$('#sheet-stage')]){zone.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();zone.classList.add('file-over')}});zone.addEventListener('dragleave',()=>zone.classList.remove('file-over'));zone.addEventListener('drop',e=>{zone.classList.remove('file-over');if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();withStatus(()=>addFiles([...e.dataTransfer.files]))}},true)}
$('#upload-drop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#image-upload').click()}};
draw();
