import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import worker,{hash} from '../../worker-v2/src/index.js';import {environment} from '../../worker-v2/tests/fixture.mjs';
const require=createRequire(import.meta.url),{chromium,firefox}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),env=environment(),token='b'.repeat(64),id='startup-test';
await env.PROJECTS.put('sessions/'+await hash(token),JSON.stringify({owner:'test-studio',user:'admin',role:'admin',expires:Date.now()+3600000}));
const bytes=gzipSync(JSON.stringify(Array.from({length:5000},(_,i)=>({id:i,label:'Private library detail '+i})))),digest=createHash('sha256').update(bytes).digest('hex'),ref={__v2asset:digest,project:id,mime:'application/gzip',json:true,encoding:'gzip'};
await env.PROJECTS.put(`accounts/test-studio/projects/${id}/assets/${digest}`,bytes);
await env.PROJECTS.put(`accounts/test-studio/projects/${id}/state.json`,JSON.stringify({schema:1,projectId:id,name:'Startup project',bid:{S:{pi:{project:'Startup project'},testData:ref,secondCopy:ref}},engine:{},workspace:{notes:{marker:'server workspace'}}}));
await env.PROJECTS.put('accounts/test-studio/users/admin/preferences.json',JSON.stringify({studioh_v2_last_project:{text:id}}));
const b=await(process.env.BROWSER==='firefox'?firefox.launch():chromium.launch({channel:'chrome'}));try{const p=await b.newPage();let release;const blocked=new Promise(r=>release=r);let assetReads=0,writes=0,failed=0;const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(t=>{if(window===top){sessionStorage.setItem('studioh_v2_session_tab',t);indexedDB.databases=()=>{throw Error('Returning startup must not scan browser backups')}}},token);
await p.route('https://studioh-v2-storage.warwick-cca.workers.dev/**',async route=>{const q=route.request();if(q.method()==='PUT')writes++;if(q.url().includes('/assets/')&&q.method()==='GET'){assetReads++;await blocked}const r=await worker.fetch(new Request(q.url(),{method:q.method(),headers:{...q.headers(),origin:'https://designingla27.github.io'},...(['GET','HEAD'].includes(q.method())?{}:{body:q.postDataBuffer()})}),env);if(r.status>=400&&r.status!==404)failed++;await route.fulfill({status:r.status,headers:{...Object.fromEntries(r.headers),'Access-Control-Allow-Origin':'http://127.0.0.1:51843'},body:Buffer.from(await r.arrayBuffer())})});
await p.goto('http://127.0.0.1:51843/v2/');await p.waitForFunction(()=>window.v2Workspace&&document.documentElement.getAttribute('data-cloud-opening')===null);assert.equal(await p.locator('#v2-cloud-gate').count(),0);assert(await p.locator('#v2-rail [data-page]').count()>10);assert.equal(await p.evaluate(()=>v2Workspace.demo.notes.marker),'server workspace');assert.equal(await p.evaluate(()=>v2Preview.ready),false);assert.equal(writes,0);assert.equal(assetReads,1);await p.evaluate(()=>localStorage.setItem('studioh_v2_theme_v1','Morning'));assert.equal(writes,0);release();await p.waitForFunction(()=>v2Preview.ready);const f=p.frames()[1];assert.equal(await f.evaluate(()=>S.testData.length),5000);assert.equal(await f.evaluate(()=>S.secondCopy.length),5000);await p.evaluate(()=>v2Cloud.flush());assert.equal(failed,0);assert.deepEqual(errors,[]);console.log('PASS workspace visible before delayed assets; no premature saves; duplicate asset read once; no backup scans or sign-in flash; complete data restored');
await p.reload();await p.waitForFunction(()=>window.v2Preview?.ready);assert.equal(await p.locator('#v2-cloud-gate').count(),0);console.log('PASS refresh reconnects without a login prompt');
await env.PROJECTS.put('accounts/test-studio/projects/broken-test/state.json',JSON.stringify({schema:1,projectId:'broken-test',name:'Broken test',bid:{S:{pi:{project:'Broken test'},missing:{...ref,project:'broken-test'}}},engine:{},workspace:{notes:{marker:'wrong workspace'}}}));
const before=await p.evaluate(()=>v2Cloud.projectId);await p.evaluate(()=>v2Cloud.openProject('broken-test').catch(()=>{}));assert.equal(await p.evaluate(()=>v2Cloud.projectId),before);assert.equal(await p.evaluate(()=>v2Workspace.demo.notes.marker),'server workspace');await p.evaluate(()=>v2Cloud.flush());console.log('PASS failed project download leaves the existing workspace and save target intact');

}finally{await b.close()}
