import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');import assert from 'node:assert/strict';import worker,{hash} from '../../worker-v2/src/index.js';import {environment} from '../../worker-v2/tests/storage.test.mjs';
const env=environment(),token='a'.repeat(64);await env.PROJECTS.put('sessions/'+await hash(token),JSON.stringify({owner:'test-studio',user:'admin',expires:Date.now()+3600000}));
const b=await chromium.launch({channel:'chrome'});const errors=[];
async function page(legacy, incomplete=false){const ctx=await b.newContext({viewport:{width:1280,height:960}});const p=await ctx.newPage();if(legacy)await p.addInitScript(({bid,incomplete})=>{if(window!==top)return;localStorage.setItem('studioh_v2_workspace_v2',JSON.stringify({notes:{recovery:'keep this'}}));window.__seedDone=new Promise((resolve,reject)=>{const r=indexedDB.open('studioh-v2-projects',1);r.onupgradeneeded=()=>r.result.createObjectStore('projects');r.onsuccess=()=>{const db=r.result,t=db.transaction('projects','readwrite');t.objectStore('projects').put({v2_project:JSON.stringify(bid)},'current');if(incomplete)t.objectStore('projects').put({studioh_theme:'Night'},'before-cloud-open');t.oncomplete=()=>{db.close();resolve()};t.onerror=reject}})},{bid:legacy,incomplete});p.on('pageerror',e=>errors.push(e.message));await p.route('https://studioh-v2-storage.warwick-cca.workers.dev/**',async route=>{const q=route.request();const r=await worker.fetch(new Request(q.url(),{method:q.method(),headers:{...q.headers(),origin:'https://designingla27.github.io'},...(['GET','HEAD'].includes(q.method())?{}:{body:q.postDataBuffer()})}),env);await route.fulfill({status:r.status,headers:{...Object.fromEntries(r.headers),"Access-Control-Allow-Origin":"http://127.0.0.1:51843"},body:Buffer.from(await r.arrayBuffer())})});await p.goto('http://127.0.0.1:51843/v2/?view=mood');await p.evaluate(()=>window.__seedDone);await p.evaluate(t=>v2Cloud.start(t),token);await p.waitForFunction(()=>v2Preview.ready);return {p,ctx,f:p.frames()[1]}}
try{
 const a=await page();await a.f.waitForSelector('.vmb-views');await a.f.evaluate(()=>{mbWizardClose();S.pi.project='Server persistence test';S.designBrief.photos=[{id:'photo-test',url:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jM1sAAAAASUVORK5CYII=',name:'Test photo',tags:['entry'],favorite:true}];S.v2ProjectFiles=[{id:'doc-test',name:'rules.txt',size:14,data:'data:text/plain;base64,cHJvamVjdCBydWxlcw=='}];S.moodboard.sections=['plants','palette'];_bidSchedule()});await a.p.waitForFunction(()=>v2Cloud.dirty);await a.p.waitForTimeout(2000);await a.p.evaluate(()=>v2Cloud.flush());console.log('first save',await a.p.locator('#v2-state').innerText());
 const savedKeys=[...env.PROJECTS.data.keys()];assert(savedKeys.some(k=>k.includes('/assets/')));const stateKey=savedKeys.find(k=>k.endsWith('/state.json'));const saved=await (await env.PROJECTS.get(stateKey)).json();assert.equal(saved.bid.S.pi.project,'Server persistence test');assert(saved.bid.S.designBrief.photos[0].url.__v2asset);assert(saved.bid.S.v2ProjectFiles[0].data.__v2asset);assert.equal(await a.p.evaluate(()=>localStorage.length>0),true);assert.equal(await a.p.evaluate(async()=>{const d=await indexedDB.databases();return d.length}),0);
 const c=await page();await c.f.waitForFunction(()=>S.pi.project==='Server persistence test');assert.equal(await c.f.evaluate(()=>S.designBrief.photos[0].favorite),true);assert.equal(await c.f.evaluate(()=>S.v2ProjectFiles[0].data),'data:text/plain;base64,cHJvamVjdCBydWxlcw==');assert.match(await c.f.evaluate(()=>S.designBrief.photos[0].url),/^data:image/);console.log('PASS fresh browser loaded project, moodboard, photos, tags, files from server');
 await c.f.evaluate(()=>{S.pi.notes='Changed on second browser';_bidSchedule()});await c.p.waitForTimeout(2500);await c.p.evaluate(()=>v2Cloud.flush());await a.f.evaluate(()=>{S.pi.project='Conflicting change';_bidSchedule()});await a.p.waitForFunction(()=>document.getElementById('v2-state').textContent.includes('conflict'),{},{timeout:15000});console.log('PASS stale revision prevented overwrite');
 const legacy=await c.f.evaluate(()=>{const b=_bidPayload();b.S.pi.project='Local recovery';return b});const recovered=await page(legacy);assert.equal(await recovered.f.evaluate(()=>S.pi.project),'Local recovery · recovered current');assert.equal(await recovered.p.evaluate(async()=>(await indexedDB.databases()).length),0);assert.equal(await recovered.p.evaluate(()=>v2Workspace.demo.notes.recovery),'keep this');console.log('PASS automatic recovery verified before clearing local copies');
 await recovered.p.waitForTimeout(1500);await recovered.p.evaluate(()=>v2Cloud.flush());const offline=route=>route.abort();await recovered.p.route('https://studioh-v2-storage.warwick-cca.workers.dev/**',offline);await recovered.f.evaluate(()=>{S.pi.notes='Pending connection';_bidSchedule()});await recovered.p.waitForFunction(()=>document.getElementById('v2-state').textContent.includes('Not saved'));assert.equal(await recovered.p.evaluate(()=>v2Cloud.dirty),true);await recovered.p.unroute('https://studioh-v2-storage.warwick-cca.workers.dev/**',offline);await recovered.p.evaluate(()=>v2Cloud.flush());assert.equal(await recovered.p.locator('#v2-state').innerText(),'Saved to Cloudflare');console.log('PASS interrupted save remains unsaved until successful retry');
 const partial=await page(legacy,true);assert.equal(await partial.f.evaluate(()=>S.pi.project),'Local recovery · recovered current');assert.equal(await partial.p.locator('#v2-cloud-gate').count(),0);assert.match(await partial.p.locator('#v2-recovery-warning').innerText(),/preserved/);assert((await partial.p.evaluate(()=>indexedDB.databases())).some(d=>d.name==='studioh-v2-projects'));console.log('PASS incomplete historical record preserves local backup without blocking workspace');
 await recovered.p.screenshot({path:'/tmp/studioh-cloud-test.png'});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS no browser database, no JS errors');
}finally{await b.close()}
