import {readFileSync} from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('./../src/settings-engine.js',import.meta.url),'utf8');
function setup(){const c={PREFS:{profile:{company:'Studio H',keep:'safe'},defaults:{ql:0,keep:'safe'}},GSET:{margin:20,marketAdj:0},PHASES_ALL:[{id:'a',nm:'Concept'},{id:'b',nm:'Build'}],CONF_DEFAULT:{scope:{}},QL:[{label:'Entry'}],SHVIZ_CFG:{keep:'safe'},SHVIZ_LIGHT_PRESET:{day:{nm:'Day'}},spacingPct:()=>80,_confDisplayVal:()=>10,prefsSave(){},gsetSave(){},_applyProfileText(){},rebuildPhases(){},applyPriceBook(){},renderPhaseBar(){},shvizCfgSave(){}};c.v2PlantRequest=m=>m.action==='studio-settings'?{profile:c.PREFS.profile,defaults:c.PREFS.defaults}:m.action;vm.createContext(c);vm.runInContext(source,c);return c}
const valid={ql:0,markup:25,margin:20,marketAdj:0,spacingPct:80,goodsModel:'resale',location:'Test',phases:[{id:'a',on:true,lo:5,hi:10},{id:'b',on:false,lo:10,hi:20}]};
test('existing bridge actions preserved',()=>assert.equal(setup().v2PlantRequest({action:'project-data'}),'project-data'));
test('pricing persists fields and preserves unrelated defaults',()=>{const c=setup();c.v2PlantRequest({action:'settings-workspace-save',group:'defaults',values:valid});assert.equal(c.PREFS.defaults.markup,25);assert.equal(c.PREFS.defaults.keep,'safe');assert.equal(c.PREFS.phasesOff.b,1);assert.equal(c.PREFS.defaults.confidence.scope.b.hi,20)});
test('invalid values and all phases disabled do not mutate settings',()=>{for(const changes of [{markup:NaN},{spacingPct:39},{phases:valid.phases.map(p=>({...p,on:false}))}]){const c=setup(),before=JSON.stringify(c.PREFS);assert.throws(()=>c.v2PlantRequest({action:'settings-workspace-save',group:'defaults',values:{...valid,...changes}}));assert.equal(JSON.stringify(c.PREFS),before)}});
test('studio save preserves unrelated fields and rejects SVG payloads',()=>{const c=setup(),values=Object.fromEntries(['company','contact','addr','phone','email','web','license'].map(k=>[k,'Updated']));c.v2PlantRequest({action:'settings-workspace-save',group:'studio',values});assert.equal(c.PREFS.profile.keep,'safe');assert.throws(()=>c.v2PlantRequest({action:'settings-workspace-save',group:'studio',values:{...values,logo:'data:image/svg+xml;base64,AAA='}}))});
test('render save whitelists fields and validates before mutation',()=>{const c=setup(),render={bgWord:'white',bgHex:'#ffffff',padPct:10,heroUp:20,heroRound:25,keyDeg:45,maxPx:1200,lightPreset:'day',shadow:'soft',untrusted:'x'};c.v2PlantRequest({action:'settings-workspace-save',group:'libraries',values:{render}});assert.equal(c.SHVIZ_CFG.maxPx,1200);assert.equal(c.SHVIZ_CFG.untrusted,undefined);assert.equal(c.SHVIZ_CFG.keep,'safe');assert.throws(()=>c.v2PlantRequest({action:'settings-workspace-save',group:'libraries',values:{render:{...render,maxPx:10000}}}));assert.equal(c.SHVIZ_CFG.maxPx,1200)});
