import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');const core=source.slice(source.indexOf('function bcState(){'),source.indexOf('// ── The view ─',source.indexOf('function bcState(){')));
const adapter=fs.readFileSync(new URL('../src/bid-engine.js',import.meta.url),'utf8');
function engine(name='Sample — San Marino'){
 const ctx=vm.createContext({console,AbortSignal,crypto:globalThis.crypto,localStorage:{getItem:()=>null,setItem(){}},setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>({content:[{type:'text',text:JSON.stringify({overall:{headline:'Compared',body:'Evidence reviewed'},bids:['bs_alta','bs_verde','bs_coast'].map(id=>({id,headline:'Bid summary',body:'Source based'}))})}]})})});
 vm.runInContext(`var S={pi:{project:${JSON.stringify(name)}},cats:{keep:{on:true,lumpSum:333}},budget:999};var PB=['genconds','drainage','firepit','paving','woodMetal','pool','irrigation','lighting','planting','sitework','electrical','walls','furnish'].map(id=>({id,name:id}));var AI_PROXY_URL='https://fixture.invalid';var saved=0;function _bidSchedule(){saved++}function v2PlantRequest(){return 'original'}function catSubtotal(){return 333}function fmtN(x){return '$'+x}function secArea(){return 1000}function escAttr(x){return x}`,ctx);
 vm.runInContext(core,ctx);vm.runInContext(adapter,ctx);return {ctx,run:s=>vm.runInContext(s,ctx),req:(action,args={})=>ctx.v2PlantRequest({action,...args})};
}
test('real V1 sample loads once without replacing current estimate or project',()=>{const e=engine(),before=e.run('JSON.stringify(S.cats)');const r=e.req('bid-v2-seed');assert.equal(r.seeded,true);assert.equal(r.bids.length,3);assert.equal(r.estimate,126590);assert.equal(e.run('S.budget'),999);assert.equal(e.run('JSON.stringify(S.cats)'),before);assert.equal(e.req('bid-v2-seed').seeded,false);assert.deepEqual(Array.from(r.bids,b=>b.lines.length),[23,4,12]);assert.deepEqual(Array.from(r.bids,b=>b.price.actual),[151044,167031,177892]);});
test('never seeds other projects or overwrites existing bids',()=>{const e=engine('Private project');assert.equal(e.req('bid-v2-seed').seeded,false);const s=engine();s.run('S.bidcmp={bids:[{id:"existing",total:100,lines:[]}],cons:{}}');assert.equal(s.req('bid-v2-seed').seeded,false);assert.equal(s.req('bid-v2-read').bids[0].id,'existing');});
test('grades and confidence data cover all bids and unavailable historical checks stay unavailable',()=>{const e=engine();const r=e.req('bid-v2-seed');assert.deepEqual(Array.from(r.bids,b=>b.score.grade),['B','F','B+']);assert.ok(r.bids.every(b=>b.score.rows.length===6&&b.score.checks===5));assert.equal(e.run('bcGrade(71)'),'C−');assert.equal(e.run('bcGrade(95)'),'A');assert.equal(e.run('bcGrade(41)'),'F');});
test('allowance dollars are not entire pool totals; overlapping adjustments counted once',()=>{const e=engine();const r=e.req('bid-v2-seed');assert.equal(r.bids[0].allowanceTotal,13930);assert.equal(r.bids[0].price.added,5844);assert.equal(r.bids[2].price.added,1050);assert.ok(r.bids[1].allowances.some(x=>x.qty===0));});
test('section corrections persist; invalid categories rejected',()=>{const e=engine();e.req('bid-v2-seed');e.req('bid-v2-line',{id:'bs_alta',index:0,category:'genconds'});assert.equal(e.run('S.bidcmp.bids[0].lines[0].cat'),'genconds');assert.throws(()=>e.req('bid-v2-line',{id:'bs_alta',index:0,category:'bad'}));});
test('AI summary validation and staleness cover all bids',()=>{const e=engine();e.req('bid-v2-seed');const input=e.req('bid-v2-ai-brief');assert.equal(e.req('bid-v2-read').ai.overall,undefined);const result={overall:{headline:'Overall',body:'Compared'},bids:['bs_alta','bs_verde','bs_coast'].map(id=>({id,headline:'Bid summary',body:'Reviewed'}))};e.req('bid-v2-ai-save',{signature:input.signature,result});assert.equal(e.req('bid-v2-read').ai.bids.length,3);assert.equal(e.req('bid-v2-read').ai.stale,false);e.run('S.bidcmp.bids[0].note+=" changed"');assert.equal(e.req('bid-v2-read').ai.stale,true);assert.throws(()=>e.req('bid-v2-ai-save',{signature:input.signature,result:{...result,bids:result.bids.slice(0,2)}}));});
test('clarification notes persist and do not change bid price',()=>{const e=engine();e.req('bid-v2-seed');e.req('bid-v2-question',{id:'bs_alta',question:'Who pays permits?',note:'Await revised offer',status:'Awaiting reply'});assert.equal(e.req('bid-v2-reply',{id:'bs_alta',question:'Who pays permits?'}).status,'Awaiting reply');assert.equal(e.req('bid-v2-read').bids[0].price.stated,145200);});
test('manual bids can be entered on real projects with validated lines',()=>{const e=engine('Current project');e.req('bid-v2-add',{bid:{name:'Contractor',total:500,lines:[{desc:'Pool',amount:500,cat:'pool'}]}});assert.equal(e.req('bid-v2-read').bids.length,1);assert.throws(()=>e.req('bid-v2-add',{bid:{name:'X',total:-1,lines:[]}}));});
const routeText=fs.readFileSync(new URL('../../worker-v2/tests/recovered-bid-route.mjs',import.meta.url),'utf8');
async function route({access='owner',role='admin',replyText}={}){const c=vm.createContext({URL,AbortSignal,TextDecoder});vm.runInContext(routeText,c);let calls=0;const brief={bids:[{id:'x',contractor:'Contractor',bidAsWritten:100,likeForLike:120}],project:{estimate:120}};const req=new Request('https://app.warwick.design/bidcompare/p/recommendation',{method:'POST',body:JSON.stringify({brief})});const r=await c.bidCompareRoute(req,{LEGACY:{fetch:async()=>{calls++;return {ok:true,json:async()=>({content:[{type:'text',text:JSON.stringify(replyText||{overall:{headline:'Review',body:'Comparison $120.'},bids:[{id:'x',headline:'Confirm scope',body:'Submitted $100.'}]})}]})}}}},{role},{reply:(status,data)=>({status,data}),body:async req=>new Uint8Array(await req.arrayBuffer()),permission:async()=>access,hash:()=>{}});return {...r,calls}}
test('AI endpoint rejects missing/viewer project access without upstream calls',async()=>{for(const access of [null,'viewer']){const r=await route({access});assert.equal(r.status,403);assert.equal(r.calls,0)}});
test('AI endpoint accepts complete evidence-based summaries and rejects invented dollar values',async()=>{assert.equal((await route()).status,200);const bad={overall:{headline:'Review',body:'Save $999.'},bids:[{id:'x',headline:'Confirm',body:'Check scope.'}]};assert.equal((await route({replyText:bad})).status,502)});
