import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const engine=fs.readFileSync(new URL('../src/process-engine.js',import.meta.url),'utf8');
function fixture(){let S={phase:'concept',pi:{project:'Test project'},checklist:{done:{a:true},meta:{a:{note:'Keep this note',who:'Existing person'}}}};let evidence=false;const ctx={S,PHASES:[{id:'pre',nm:'Pre-concept'},{id:'concept',nm:'Concept'}],PHASES_ALL:[{id:'pre'},{id:'concept'},{id:'cd'}],CHK_APPLY_ITEMS:{},chkApplies:()=>false,chkState:()=>S.checklist,chkItems:ph=>ph==='concept'?[{id:'a',ph,t:'Manual task',done:!!S.checklist.done.a},{id:'k_plan',ph,t:'Concept plan',grp:'Deliverables',done:false},{id:'auto',ph,t:'Automatic source',v:'addr',auto:{ok:evidence},hard:true,done:evidence}]:[],v2PlantRequest:()=>null,_bidSchedule:()=>{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../src/process-foundation.js',import.meta.url),'utf8'),ctx);vm.runInContext(engine,ctx);return{ctx,S,read:()=>ctx.v2PlantRequest({action:'process-v2-read'}),save:(data,revision)=>ctx.v2PlantRequest({action:'process-v2-save',process:data,revision}),evidence:v=>evidence=v}}
test('migration preserves prior completion, assignment, note, phase and source identity without writing Process on read',()=>{let f=fixture(),d=f.read();assert.equal(d.steps[0].done,true);assert.equal(d.steps[0].owner,'Existing person');assert.equal(d.steps[0].note,'Keep this note');assert.equal(d.steps[1].kind,'deliverable');assert.equal(d.steps[1].sub[0].sourceId,'k_plan');assert.equal(d.steps[1].sub[0].owner,'');assert.equal(f.S.v2Process,undefined);assert.equal(f.S.phase,'concept')});
test('save/reload preserves moved hierarchy, hours, owners, manual completion and timestamps',()=>{let f=fixture(),d=f.read();let group=d.steps.find(x=>x.id==='k_plan');group.ph='pre';group.sub[0].done=true;group.sub[0].plannedHours=1.5;group.sub[0].owner='Maya';f.save(d,0);let n=f.read().steps.find(x=>x.id==='k_plan').sub[0];assert.equal(n.ph,'pre');assert.equal(n.plannedHours,1.5);assert.equal(n.owner,'Maya');assert.ok(n.completedAt);assert.equal(f.S.checklist.done.k_plan,true);assert.equal(f.S.checklist.meta.k_plan.who,'Maya')});
test('automatic evidence cannot be forged; source checks cannot gain manual children',()=>{let f=fixture(),d=f.read();d.steps.find(x=>x.id==='auto').done=true;assert.equal(f.save(d,0).steps.find(x=>x.id==='auto').done,false);f.evidence(true);assert.equal(f.read().steps.find(x=>x.id==='auto').done,true);let latest=f.read();latest.steps.find(x=>x.id==='auto').sub=[{id:'fake',kind:'task',t:'Fake',ph:'concept'}];assert.throws(()=>f.save(latest,1),/automatic check/)});
test('reject stale revisions, duplicate IDs, invalid phases, negative effort and nested deliverables',()=>{let f=fixture(),d=f.read();assert.throws(()=>f.save(d,9),/another view/);let duplicate=structuredClone(d);duplicate.steps.push(duplicate.steps[0]);assert.throws(()=>f.save(duplicate,0),/unique ID/);for(let bad of [{ph:'unknown'},{plannedHours:-2}]){let v=structuredClone(d);Object.assign(v.steps[0],bad);assert.throws(()=>f.save(v,0))}let v=structuredClone(d);v.steps[1].sub[0].kind='deliverable';assert.throws(()=>f.save(v,0),/directly/)});
test('removed ordinary source work stays removed and hard blockers cannot be deleted',()=>{let f=fixture(),d=f.read();d.steps=d.steps.filter(n=>n.id!=='a');f.save(d,0);assert.ok(!f.read().steps.some(n=>n.id==='a'));let v=f.read();v.steps=v.steps.filter(n=>n.id!=='auto');assert.ok(f.save(v,1).steps.some(n=>n.id==='auto'))});
test('new work defaults unassigned; project stores remain isolated',()=>{let f=fixture(),b=fixture(),d=f.read();d.steps.push({id:'custom',kind:'task',t:'New task',ph:'pre',plannedHours:2});f.save(d,0);assert.equal(f.read().steps.at(-1).owner,'');assert.ok(!b.read().steps.some(x=>x.id==='custom'))});
test('subtask rollups update the original manual source check without double-counted parent hours',()=>{let f=fixture(),d=f.read(),a=d.steps[0];a.sub=[{id:'sub1',kind:'task',t:'First',ph:'concept',done:true,plannedHours:1},{id:'sub2',kind:'task',t:'Second',ph:'concept',done:false,plannedHours:2}];a.plannedHours=20;let r=f.save(d,0);assert.equal(f.S.checklist.done.a,false);assert.equal(r.steps[0].plannedHours,null);r.steps[0].sub[1].done=true;f.save(r,1);assert.equal(f.S.checklist.done.a,true)});
