const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome'});try{const p=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.V2_TEST_URL||'http://127.0.0.1:51843/v2/?view=mood');await p.waitForFunction(()=>window.v2Preview?.ready);let f=p.frames()[1];await f.waitForSelector('.vmb-views');
await f.evaluate(()=>{const mb=_mbEnsure();mb.sections=['plants'];mb._seeded=true;mb.supportCards={};mb.view='grid';S.designBrief.photos=[{id:'builder-reference',name:'Builder reference',kind:'Inspiration',url:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jM1sAAAAASUVORK5CYII='}];renderMoodBoard()});
const plantCount=await f.evaluate(()=>_mbGather().plants.length);await f.locator('[data-vmb-builder-toggle]').click();await f.locator('.vmb-builder [data-vmb-section="plants"]').click();assert.equal(await f.evaluate(()=>_mbGather().plants.length),plantCount);assert.equal(await f.evaluate(()=>_mbEnsure().sections.includes('plants')),false);
await f.locator('#vmb-add-sections [data-vmb-section="materials"]').click();await f.locator('.vmb-builder [data-vmb-section="v2_inspiration"]').click();assert.equal(await f.locator('[data-vmb-item="references:builder-reference"]').count(),1);
await f.locator('.vmb-builder [data-vmb-move="v2_inspiration"][data-delta="-1"]').click();assert.equal(await f.evaluate(()=>_mbEnsure().sections[0]),'v2_inspiration');
await f.locator('[data-vmb-support="connection"]').uncheck();await f.locator('[data-vmb-support="brief"]').uncheck();
const state=await f.evaluate(()=>JSON.stringify({sections:S.moodboard.sections,cards:S.moodboard.supportCards}));
for(const theme of ['Morning','Day','Afternoon','Dusk','Night']){await p.evaluate(t=>v2Preview.command({v2cmd:'theme',theme:t}),theme);for(const view of ['grid','editorial','wall']){await f.locator('[data-vmb-view="'+view+'"]').click();assert.equal(await f.evaluate(()=>JSON.stringify({sections:S.moodboard.sections,cards:S.moodboard.supportCards})),state);assert.equal(await f.locator('[data-support="connection"]').isVisible(),false);assert.equal(await f.locator('[data-support="palette"]').isVisible(),true);assert.equal(await f.locator('[data-vmb-item="references:builder-reference"]').count(),1);assert(await f.evaluate(()=>document.getElementById('view-moodboard').scrollWidth<=innerWidth+2),'desktop overflow '+view);}}
await f.locator('[data-vmb-view="grid"]').click();await p.screenshot({path:'/tmp/moodboard-shared-builder.png'});
for(const width of [834,390]){await p.setViewportSize({width,height:1000});for(const view of ['grid','editorial','wall']){await f.locator('[data-vmb-view="'+view+'"]').click();assert(await f.evaluate(()=>document.getElementById('view-moodboard').scrollWidth<=innerWidth+2),'overflow '+width+view)}}
await f.locator('[data-vmb-present]').click();assert.equal(await f.locator('.vmb-builder').isVisible(),false);await f.locator('[data-vmb-present]').click();
// Adding an already specified plant brings its section back without duplicate quantities.
await f.evaluate(()=>{const plant=_mbGather().plants[0];mbAddExistingPlant(plant.kind,plant.p.id)});assert.equal(await f.evaluate(()=>_mbGather().plants.length),plantCount);assert(await f.evaluate(()=>_mbEnsure().sections.includes('plants')));
await p.evaluate(()=>v2Preview.command({v2cmd:'save'}));await p.waitForTimeout(1500);await p.reload();await p.waitForFunction(()=>window.v2Preview?.ready);f=p.frames()[1];await f.waitForSelector('.vmb-views');assert.equal(await f.evaluate(()=>S.moodboard.supportCards.connection),false);assert.equal(await f.evaluate(()=>S.moodboard.sections[0]),'v2_inspiration');assert.equal(await f.evaluate(()=>S.moodboard.view),'wall');assert.equal(await f.locator('[data-vmb-item="references:builder-reference"]').count(),1);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS shared builder sections/order/cards, inline add, project reference images, 15 theme/views, responsive, presentation, automatic section restore, reload persistence');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
