import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../engine.html',import.meta.url),'utf8');const arrays=['PHASES_ALL','CHK_MASTER','CHK_APPLY_ITEMS'].map(k=>{const at=html.indexOf('const '+k+'=');const tail=html.slice(at);return tail.slice(0,tail.indexOf('\n];')>=0&&k!=='CHK_APPLY_ITEMS'?tail.indexOf('\n];')+3:tail.indexOf('\n};')+3)}).join('\n');
function setup(saved){const c={S:{phase:'concept',checklist:{done:{},meta:{}},v2Process:saved},v2PlantRequest:()=>null,_bidSchedule(){},chkApplies:k=>k==='hoa',chkState(){return c.S.checklist}};vm.createContext(c);vm.runInContext(arrays+`;const PHASES=PHASES_ALL.filter(p=>!p.optional);function chkItems(ph){return CHK_MASTER.filter(n=>n.ph===ph).map(n=>({...n,done:!!S.checklist.done[n.id],auto:n.v?{ok:false}:null}))};`,c);vm.runInContext(fs.readFileSync(new URL('../src/process-engine.js',import.meta.url),'utf8'),c);return{c,read:()=>c.v2PlantRequest({action:'process-v2-read'}),save:(m,r)=>c.v2PlantRequest({action:'process-v2-save',process:m,revision:r})}}
test('canonical phase names, standard fee metadata and new source check counts',()=>{const f=setup(),m=f.read();assert.equal(m.phases.length,8);assert.equal(m.phases[1].t,'Programming & Site Analysis');assert.equal(m.phases[5].t,'Bidding / Negotiation');assert.equal(m.phases[7].id,'close');for(const [ph,n] of [['consult',9],['pre',7],['dd',9],['co',10],['close',5]])assert.equal(m.steps.filter(x=>x.ph===ph).length,n);assert.equal(m.phases.filter(p=>p.feeShare).reduce((a,p)=>a+p.feeShare,0),100);assert.equal(m.steps.filter(n=>n.ph==='pre'&&n.grp==='Client').length,2);assert.equal(m.steps.filter(n=>n.ph==='pre'&&n.grp==='Site information').length,5)});
test('optional scope excludes rather than deletes work, and survives save/reload',()=>{const f=setup(),m=f.read();assert.equal(m.phases.find(p=>p.id==='dd').applicable,false);assert.ok(m.steps.filter(n=>n.ph==='dd').every(n=>!n.applicable));m.phaseScope={dd:true,co:false};let result=f.save(m,0);assert.ok(result.steps.filter(n=>n.ph==='dd').every(n=>n.applicable));assert.equal(result.phases.find(p=>p.id==='co').applicable,false);m.phaseScope.dd=false;result=f.save(m,1);assert.equal(result.steps.filter(n=>n.ph==='dd').length,9);assert.ok(result.steps.filter(n=>n.ph==='dd').every(n=>!n.applicable))});
test('permit migration preserves original identity and saved work; independent status does not mark checks done',()=>{const saved={schema:1,revision:4,steps:[{id:'b_permit',sourceId:'b_permit',kind:'task',ph:'bid',t:'Permit set issued',owner:'Pat',due:'2026-11-01',plannedHours:3,done:true,completedAt:'2026-10-01T00:00:00Z',mode:'person'}],removedSourceIds:[]};const f=setup(saved);f.c.S.checklist.done.b_permit=true;const m=f.read(),p=m.steps.find(n=>n.id==='b_permit');assert.equal(p.track,'permitting');assert.equal(p.ph,'cd');assert.equal(p.owner,'Pat');assert.equal(p.plannedHours,3);assert.equal(p.completedAt,saved.steps[0].completedAt);assert.equal(m.steps.filter(n=>n.ph==='bid'&&!n.track).length,5);m.tracks.permitting.status='awaiting-review';const after=f.save(m,4);assert.equal(after.tracks.permitting.status,'awaiting-review');assert.equal(after.steps.find(n=>n.id==='b_permit').due,'2026-11-01');assert.equal(after.steps.find(n=>n.id==='b_permit').plannedHours,3);assert.equal(after.steps.find(n=>n.id==='b_hoa').done,false);assert.equal(saved.steps[0].ph,'bid')});
test('recurring estimate source hooks exist for concept, DD, CD and bid reconciliation',()=>{const f=setup(),m=f.read();const checks=[];const walk=a=>a.forEach(n=>{if(n.sourceId&&n.recurring==='cost-estimating')checks.push(n);walk(n.sub||[])});walk(m.steps);assert.deepEqual(checks.map(n=>n.sourceId).sort(),['b_est','d_est','dd_est','k_est']);assert.ok(checks.every(n=>n.mode==='app'));});
export {setup};
test('deployed snapshot adapter is idempotent and excludes optional and permit work from phase statistics',()=>{const c={S:{v2Process:{phaseScope:{}}},rebuildPhases(){},chkPhaseStats(){}};vm.createContext(c);vm.runInContext(arrays+`;let PHASES=PHASES_ALL.filter(p=>!p.optional);function chkItems(ph){return CHK_MASTER.filter(n=>n.ph===ph)};`,c);const patch=fs.readFileSync(new URL('../src/phase-model.js',import.meta.url),'utf8');vm.runInContext(patch,c);vm.runInContext(patch,c);assert.equal(vm.runInContext('CHK_MASTER.length',c),72);assert.equal(c.chkPhaseStats('dd').n,0);assert.equal(c.chkPhaseStats('bid').n,5);assert.equal(c.chkPhaseStats('cd').n,11);c.S.v2Process.phaseScope.dd=true;assert.equal(c.chkPhaseStats('dd').n,9)});
