const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/warwick/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1100}});const base=process.env.PREVIEW_URL||'http://127.0.0.1:8769/deployment/studioh-estimator-gpt/v2/';let errors=[],apiRequests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/workers\.dev/.test(r.url())&&!['image','script','stylesheet'].includes(r.resourceType()))apiRequests.push(r.url())});await p.goto(base);await p.waitForFunction(()=>window.v2Preview?.ready);await p.evaluate(()=>localStorage.setItem('studioh_v1_isolation_probe','unchanged'));const f=p.frames()[1];
assert.equal(await f.evaluate(()=>localStorage.getItem('studioh_v1_isolation_probe')),null);await f.evaluate(()=>localStorage.setItem('studioh_v1_isolation_probe','v2-only'));await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>localStorage.getItem('studioh_v1_isolation_probe')),'unchanged');assert(await f.evaluate(()=>{try{return parent.localStorage.length<0}catch{return true}}));
for(const route of ['projectinfo','estimate','insights','ve','bidcompare','plantbook','pricebook','materials','furnishings','products','colorlibrary','hoa','nurseries','algos','clientbrief','designerbrief','checklist','reports','trace']){await p.evaluate(r=>v2Preview.show(r,r,true),route);await p.waitForTimeout(220);if(route==='clientbrief'){console.log('Q DEBUG',await p.evaluate(()=>({url:location.href,notice:document.getElementById('v2-notice')?.textContent,frames:document.querySelectorAll('iframe').length})),await f.evaluate(()=>({view:S.view,q:!!document.getElementById('questionnaire-frame')})));await f.waitForSelector('#questionnaire-frame',{timeout:4000});await f.frameLocator('#questionnaire-frame').locator('.p7').waitFor({timeout:15000})}console.log('Opened',route)}
await p.evaluate(()=>v2Preview.show('projectinfo','Project info'));await f.evaluate(()=>{S.pi.project='V2 isolation test';});await p.click('#v2-tool-save');await p.waitForTimeout(300);let store=await p.evaluate(()=>v2DeviceGet('current'));assert.equal(JSON.parse(store.v2_project).S.pi.project,'V2 isolation test');
const denied=await f.evaluate(async()=>{try{await fetch('https://studioh-ai.warwick-cca.workers.dev',{method:'POST',body:'{}'});return false}catch{return true}});assert(denied);assert.equal(apiRequests.length,0);
await p.reload();await p.waitForFunction(()=>window.v2Preview?.ready);assert.equal(await p.frames()[1].evaluate(()=>S.pi.project),'V2 isolation test');assert.equal(await p.evaluate(()=>localStorage.getItem('studioh_v1_isolation_probe')),'unchanged');
await p.evaluate(()=>v2Preview.show('plantbook','Plant Book',true));await p.waitForTimeout(300);await p.screenshot({path:'/tmp/v2-preview-library.png',fullPage:true});for(let width of [1024,834,390]){await p.setViewportSize({width,height:1100});await p.evaluate(()=>v2Preview.workspace());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'shell overflow '+width)}
console.log('PAGE ERRORS',JSON.stringify(errors));assert.equal(errors.length,0);console.log('PASS: existing tool routes, questionnaire, local save/reopen, V1 storage isolation, production API isolation, shell widths');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
