import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
const raw=fs.readFileSync(new URL('../src/process-workspace.js',import.meta.url),'utf8');const page=JSON.parse(raw.match(/^const PROCESS_PAGE = (.*);\n/)[1]);
function fixture(reduced=false){let pending=[],seen=[],el={classList:{add(){},remove(){}},offsetWidth:1,set textContent(n){seen.push(n)}};const c={matchMedia:()=>({matches:reduced}),document:{hidden:false,getElementById:()=>el},setTimeout:fn=>(pending.push(fn),pending.length)};vm.createContext(c);vm.runInContext('let motionTimer=null,motionShown=null,motionTarget=0;'+page.slice(page.indexOf('function motionCount('),page.indexOf('\nfunction motionRoots(')),c);return{c,seen,count:n=>c.motionCount(n),flush:()=>{let guard=0;while(pending.length){assert.ok(guard++<5000);pending.shift()()}}}}
test('arrival counts every integer from one through completed total, including both digits',()=>{for(const target of [1,13,42,108]){let f=fixture();f.count(target);f.flush();assert.deepEqual(f.seen,Array.from({length:target},(_,i)=>i+1))}});
test('zero and reduced motion show truthful final values immediately',()=>{let f=fixture();f.count(0);f.flush();assert.deepEqual(f.seen,[0]);f=fixture(true);f.count(42);assert.deepEqual(f.seen,[42])});
test('saving and rerendering do not restart the count, and completion can retarget it',()=>{let f=fixture();f.count(13);f.count(14);f.flush();assert.deepEqual(f.seen,Array.from({length:14},(_,i)=>i+1));f.count(13);f.flush();assert.equal(f.seen.at(-1),13)});
test('phase numerals persist and completion respects read-only, app evidence and gates',()=>{assert.ok(page.includes('${n.number}</span>'));assert.ok(page.includes("readOnly||n.mode==='app'||n.blocked||n.kind==='inbound'"));assert.ok(page.includes('prefers-reduced-motion:reduce'));assert.ok(page.includes('motion-progress'));});
function journeyFixture(reduced=false){let queue=new Map(),id=0,now=0;const nodes=Array.from({length:8},()=>({classes:new Set(),classList:{add(k){this.owner.classes.add(k)},toggle(k,on){on?this.owner.classes.add(k):this.owner.classes.delete(k)}}}));nodes.forEach(n=>n.classList.owner=n);let d=[];const line={style:{},isConnected:true,setAttribute(k,v){d=v},getTotalLength(){return Math.max(0,d.length-1)*100}};const counter={dataset:{value:'36'},textContent:''};const c={view:'phases',projectPhase:'cd',data:{phase:'cd'},document:{querySelectorAll:selector=>selector==='.firework-overlay'?[]:nodes,getElementById:()=>counter},motionFireworks:n=>n.classes.add('fireworks'),matchMedia:()=>({matches:reduced}),performance:{now:()=>now},requestAnimationFrame:fn=>(queue.set(++id,fn),id),cancelAnimationFrame:id=>queue.delete(id)};vm.createContext(c);vm.runInContext(page.slice(page.indexOf('let motionJourneyKey='),page.indexOf('const metricState=')),c);const list=nodes.map((_,i)=>({id:String(i),current:i===4}));return{c,nodes,line,counter,render:()=>c.motionJourney({querySelector:()=>line},list,list,p=>p),tick:t=>{now=t;const q=[...queue.values()];queue.clear();q.forEach(fn=>fn(t))}}}
test('line draws from start, fills markers in sequence, then pulses current marker',()=>{let f=journeyFixture();f.render();assert.equal(f.line.style.strokeDashoffset,'1000');f.tick(0);f.tick(840);assert.equal(f.line.style.strokeDashoffset,'500');assert.equal(f.nodes.filter(n=>n.classes.has('reached')).length,3);assert.ok(!f.nodes[4].classes.has('active-pulse'));f.tick(1680);assert.equal(f.line.style.strokeDashoffset,'0');assert.ok(f.nodes[4].classes.has('active-pulse'));f.c.motionReplay();f.c.view='deliverables';f.render();assert.equal(f.line.style.strokeDashoffset,'1000');assert.ok(!f.nodes[4].classes.has('active-pulse'))});
test('rerender preserves animation progress; reduced motion shows final state',()=>{let f=journeyFixture();f.render();f.tick(0);f.tick(840);f.render();assert.equal(f.line.style.strokeDashoffset,'500');f=journeyFixture(true);f.render();assert.equal(f.line.style.strokeDashoffset,'0');assert.equal(f.nodes.filter(n=>n.classes.has('reached')).length,5)});
test('task editor has one heading control and optional phases retain full opacity',()=>{assert.equal(page.split('Edit tasks, time & assignments').length-1,1);assert.ok(page.includes('class="motion-detail-tools"'));assert.ok(page.includes('.motion-node.excluded{opacity:1}'))});
test('scroll metrics stay pending offscreen, advance on entry, finish at card bottom and never rewind',()=>{let now=0,queue=new Map(),id=0,top=900;const card={getBoundingClientRect:()=>({top,height:300})},el={dataset:{metric:'test',value:'190'},style:{},isConnected:true,hasAttribute:()=>false,closest:()=>card,getBoundingClientRect:()=>({top:top+40,bottom:top+80,left:0,right:100})};const c={document:{querySelectorAll:()=>[el]},window:{innerHeight:700,innerWidth:1200,addEventListener(){}},matchMedia:()=>({matches:false}),IntersectionObserver:class{observe(){}disconnect(){}},requestAnimationFrame:fn=>(queue.set(++id,fn),id),cancelAnimationFrame:i=>queue.delete(i)};vm.createContext(c);vm.runInContext(page.slice(page.indexOf('const metricState='),page.indexOf('function motionAfterRender()')),c);const tick=t=>{now=t;let q=[...queue.values()];queue.clear();q.forEach(f=>f(t))};c.animateMetrics();tick(0);assert.equal(el.textContent,'0');top=600;vm.runInContext('metricWake()',c);tick(100);assert.equal(el.textContent,'0');top=500;vm.runInContext('metricWake()',c);tick(200);assert.ok(Number(el.textContent)>0&&Number(el.textContent)<190);top=400;vm.runInContext('metricWake()',c);tick(300);assert.equal(el.textContent,'190');top=600;vm.runInContext('metricWake()',c);tick(400);assert.equal(el.textContent,'190')});
test('fireworks fire only at reached markers and reduced motion suppresses it',()=>{let f=journeyFixture();f.render();f.tick(0);assert.ok(f.nodes[0].classes.has('fireworks'));assert.ok(!f.nodes[1].classes.has('fireworks'));f.tick(840);assert.ok(f.nodes[2].classes.has('fireworks'));assert.ok(!f.nodes[3].classes.has('fireworks'));f=journeyFixture(true);f.render();assert.ok(f.nodes.every(n=>!n.classes.has('fireworks')))});

test('top-right total finishes on the same frame as the line and resets on replay',()=>{let f=journeyFixture();f.render();assert.equal(f.counter.textContent,'1');f.tick(0);f.tick(840);assert.equal(f.counter.textContent,'18');f.tick(1679);assert.equal(f.counter.textContent,'35');f.tick(1680);assert.equal(f.counter.textContent,'36');assert.equal(f.line.style.strokeDashoffset,'0');f.c.motionReplay();f.c.view='deliverables';f.render();assert.equal(f.counter.textContent,'1');f=journeyFixture(true);f.render();assert.equal(f.counter.textContent,'36')});
