import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
const raw=fs.readFileSync(new URL('../src/process-workspace.js',import.meta.url),'utf8');const page=JSON.parse(raw.match(/^const PROCESS_PAGE = (.*);\n/)[1]);
function fixture(reduced=false){let pending=[],seen=[],el={classList:{add(){},remove(){}},offsetWidth:1,set textContent(n){seen.push(n)}};const c={matchMedia:()=>({matches:reduced}),document:{hidden:false,getElementById:()=>el},setTimeout:fn=>(pending.push(fn),pending.length)};vm.createContext(c);vm.runInContext('let motionTimer=null,motionShown=null,motionTarget=0;'+page.slice(page.indexOf('function motionCount('),page.indexOf('\nfunction motionRoots(')),c);return{c,seen,count:n=>c.motionCount(n),flush:()=>{let guard=0;while(pending.length){assert.ok(guard++<5000);pending.shift()()}}}}
test('arrival counts every integer from one through completed total, including both digits',()=>{for(const target of [1,13,42,108]){let f=fixture();f.count(target);f.flush();assert.deepEqual(f.seen,Array.from({length:target},(_,i)=>i+1))}});
test('zero and reduced motion show truthful final values immediately',()=>{let f=fixture();f.count(0);f.flush();assert.deepEqual(f.seen,[0]);f=fixture(true);f.count(42);assert.deepEqual(f.seen,[42])});
test('saving and rerendering do not restart the count, and completion can retarget it',()=>{let f=fixture();f.count(13);f.count(14);f.flush();assert.deepEqual(f.seen,Array.from({length:14},(_,i)=>i+1));f.count(13);f.flush();assert.equal(f.seen.at(-1),13)});
test('phase numerals persist and completion respects read-only, app evidence and gates',()=>{assert.ok(page.includes('${n.number}</span>'));assert.ok(page.includes("readOnly||n.mode==='app'||n.blocked||n.kind==='inbound'"));assert.ok(page.includes('prefers-reduced-motion:reduce'));assert.ok(page.includes('motion-progress'));});
function journeyFixture(reduced=false){let queue=new Map(),id=0,now=0;const nodes=Array.from({length:8},()=>({classes:new Set(),classList:{toggle(k,on){on?this.owner.classes.add(k):this.owner.classes.delete(k)}}}));nodes.forEach(n=>n.classList.owner=n);let d=[];const line={style:{},isConnected:true,setAttribute(k,v){d=v},getTotalLength(){return Math.max(0,d.length-1)*100}};const c={view:'phases',projectPhase:'cd',data:{phase:'cd'},document:{querySelectorAll:()=>nodes},matchMedia:()=>({matches:reduced}),performance:{now:()=>now},requestAnimationFrame:fn=>(queue.set(++id,fn),id),cancelAnimationFrame:id=>queue.delete(id)};vm.createContext(c);vm.runInContext(page.slice(page.indexOf('let motionJourneyKey='),page.indexOf('function motionAfterRender()')),c);const list=nodes.map((_,i)=>({id:String(i),current:i===4}));return{c,nodes,line,render:()=>c.motionJourney({querySelector:()=>line},list,list,p=>p),tick:t=>{now=t;const q=[...queue.values()];queue.clear();q.forEach(fn=>fn(t))}}}
test('line draws from start, fills markers in sequence, then pulses current marker',()=>{let f=journeyFixture();f.render();assert.equal(f.line.style.strokeDashoffset,'1000');f.tick(0);f.tick(840);assert.equal(f.line.style.strokeDashoffset,'500');assert.equal(f.nodes.filter(n=>n.classes.has('reached')).length,3);assert.ok(!f.nodes[4].classes.has('active-pulse'));f.tick(1680);assert.equal(f.line.style.strokeDashoffset,'0');assert.ok(f.nodes[4].classes.has('active-pulse'));f.c.motionReplay();f.c.view='deliverables';f.render();assert.equal(f.line.style.strokeDashoffset,'1000');assert.ok(!f.nodes[4].classes.has('active-pulse'))});
test('rerender preserves animation progress; reduced motion shows final state',()=>{let f=journeyFixture();f.render();f.tick(0);f.tick(840);f.render();assert.equal(f.line.style.strokeDashoffset,'500');f=journeyFixture(true);f.render();assert.equal(f.line.style.strokeDashoffset,'0');assert.equal(f.nodes.filter(n=>n.classes.has('reached')).length,5)});
test('task editor has one heading control and optional phases retain full opacity',()=>{assert.equal(page.split('Edit tasks, time & assignments').length-1,1);assert.ok(page.includes('class="motion-detail-tools"'));assert.ok(page.includes('.motion-node.excluded{opacity:1}'))});
