const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/warwick/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const p=await browser.newPage({viewport:{width:1280,height:960}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.PREVIEW_URL||'http://127.0.0.1:8769/deployment/studioh-estimator-gpt/v2/');await p.waitForFunction(()=>v2Preview.ready);const open=id=>p.evaluate(id=>v2Workspace.open(id),id);
await p.screenshot({path:'/tmp/v2-expanded-dashboard.png'});
for(const id of ['home','brief','design','mood','insights','savings','client','financials','deliver','cities','cad','watch','resources','community','business','studies','settings','roadmap']){await open(id);assert(await p.locator('#sh-content h1').isVisible(),id);console.log('Workspace',id)}
await open('home');const width=await p.locator('#v2-rail').evaluate(x=>x.getBoundingClientRect().width);assert.equal(width,228);await p.click('#v2-pin');await p.mouse.move(800,100);assert.equal(await p.locator('#v2-rail').evaluate(x=>x.getBoundingClientRect().width),52);await p.hover('#rail-logo');assert.equal(await p.locator('#v2-rail').evaluate(x=>x.getBoundingClientRect().width),228);await p.click('#v2-pin');await p.mouse.move(800,100);
for(const theme of ['Morning','Day','Afternoon','Dusk','Night']){await p.locator('.top [data-theme="'+theme+'"]').click();assert.equal(await p.locator('#sh-content h1').textContent(),'A clear view of your project.');assert.equal(await p.locator('#sh-v2').getAttribute('data-theme'),theme)}await p.locator('.top [data-theme="Afternoon"]').click();
await open('client');await p.click('[data-tab="Chat"]');await p.fill('#chat-text','Test message stays local');await p.click('.chat-compose button');assert.equal(await p.locator('.chat-bubble.mine').textContent(),'You · Local draftTest message stays local');await p.click('[data-tab="Decisions"]');await p.click('[data-decision="Material palette"][data-value="Approved"]');assert.equal(await p.evaluate(()=>v2Workspace.demo.decisions['Material palette']),'Approved');await p.click('[data-tab="Portal preview"]');assert(!/margin|Cost \/ hour|Projected profit/.test(await p.locator('#sh-content').innerText()));
await open('savings');await p.click('[data-saving="0"]');assert(await p.locator('#sh-content').innerText().then(t=>t.includes('$8,200')&&t.includes('$10,300')));
await open('business');await p.click('[data-tab="Time entry"]');await p.fill('[name="hours"]','2.5');await p.fill('[name="note"]','Concept test');await p.click('#time-form button');assert.equal(await p.evaluate(()=>v2Workspace.demo.time[0].hours),2.5);
await open('resources');await p.fill('#resource-form [name="name"]','Example resource');await p.fill('#resource-form [name="url"]','https://example.com/');await p.click('#resource-form button');assert.equal(await p.locator('.resource-link').getAttribute('href'),'https://example.com/');
await p.locator('#v2-rail-resize').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#v2-rail').evaluate(x=>x.getBoundingClientRect().width),236);await p.keyboard.press('ArrowLeft');
await open('client');if(await p.locator('[data-tab="Portal preview"]').count())await p.click('[data-tab="Portal preview"]');await p.click('[data-client-proposal]');assert(await p.locator('#sh-content').innerText().then(t=>t.includes('Scope of design services')&&!t.includes('Designer tools:')));
await open('mood');let first=await p.locator('.board-grid h3').first().textContent();await p.click('[data-move="0"][data-dir="1"]');assert.equal(await p.locator('.board-grid h3').nth(1).textContent(),first);
await open('watch');await p.click('[data-watch="0"][data-value="Accepted"]');assert.equal(await p.evaluate(()=>v2Workspace.demo.watch[0]),'Accepted');
await open('deliver');await p.click('[data-tab="Plan Check"]');await p.click('[data-check-plan]');assert(await p.locator('#plan-findings').innerText().then(t=>t.includes('Drawing A-102')));
await open('roadmap');await p.waitForFunction(()=>document.querySelectorAll('.roadmap-list details').length>100);await p.fill('[data-roadmap-search]','Sun & shade');assert(await p.locator('.roadmap-list summary').count()>0);
await p.reload();await p.waitForFunction(()=>v2Preview.ready);assert.equal(await p.evaluate(()=>v2Workspace.demo.messages.client[0]),'Test message stays local');assert.equal(await p.evaluate(()=>v2Workspace.demo.time[0].hours),2.5);
for(const route of ['projectinfo','clientbrief','estimate','plantbook','hoa']){await p.evaluate(r=>v2Preview.show(r,r),route);await p.waitForTimeout(300);assert(await p.locator('#v2-engine-pane').isVisible());await p.click('#v2-back');assert(await p.locator('#sh-content h1').isVisible())}
await open('client');await p.screenshot({path:'/tmp/v2-expanded-client.png'});await open('financials');await p.screenshot({path:'/tmp/v2-expanded-financials.png'});
for(const width of [1440,1280,1024,834,768,390]){await p.setViewportSize({width,height:width===390?844:960});await open('home');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);assert(await p.locator('#v2-rail').isVisible());if(width===834)await p.screenshot({path:'/tmp/v2-expanded-ipad.png'});if(width===390){await p.click('#v2-menu');assert(await p.locator('#sh-v2').getAttribute('class').then(x=>x.includes('mobile-open')));await p.locator('#v2-rail [data-page="brief"]').click();assert(await p.locator('#sh-content h1').innerText().then(t=>t==='Brief & site'));await p.screenshot({path:'/tmp/v2-expanded-phone.png'})}}
assert.deepEqual(errors,[]);console.log('PASS rail, themes, workspaces, local demo interactions, persistence, engine return, responsive widths; no script errors');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
