'use strict';
const D=window.LIBRARY, $=id=>document.getElementById(id), esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project='',type='Measurements & facts',page=0,filtered=[];const size=30;
const cats=['Measurements & facts','Plants','Plant preferences','Materials','Costs','Contractor price book','Design relationships','Revisions','Open questions','Review coverage','Area takeoff','Area ratios','Lighting density','Plant schedule density','Yard comparisons','Building connections','Building openings','Quantity and cost checks','Source files','Source text','Field catalog'];
const pmap=Object.fromEntries(D.projects.map(p=>[p.id,p]));
function value(r){let f=r.fields||{};if(r.type==='Contractor price book')return f.quoted_unit_rate==null?`$${Number(f.quoted_line_total).toLocaleString()} package`:`$${Number(f.quoted_unit_rate).toLocaleString()} / ${f.source_unit||'unit'}`;if(r.type==='Yard comparisons')return `${Number(f.sf_per_1000).toFixed(1)} SF / 1,000 SF`;if(r.type==='Area ratios'||r.type==='Lighting density'||r.type==='Plant schedule density')return `${Number(f.computed_value).toFixed(1)} ${String(f.output_unit).replaceAll('_',' ')}`;if(r.type==='Area takeoff')return `${Number(f.value).toLocaleString(undefined,{maximumFractionDigits:1})} ${f.unit==='sq_ft'?'SF':f.unit}`;if(r.type==='Building openings')return f.width_ft==null?'Width unknown':`${Number(f.width_ft).toFixed(2)} ft drawn span`;if(r.type==='Building connections')return `${Number(f.measurement_value).toFixed(1)} ${f.measurement_unit}`;if(r.type==='Costs')return f.line_total==null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:f.currency||'USD'}).format(f.line_total);if(r.type==='Plants')return `${f.quantity??(f.quantity_min!=null?`Approximately ${f.quantity_min}–${f.quantity_max}`:'Unknown')} ${f.unit||''} · ${f.size||''}`;if(r.type==='Plant preferences')return f.response||'No response recorded';if(r.type==='Materials')return f.product||'';if(r.type==='Measurements & facts')return `${f.value_number??f.value_text??'Not extracted'} ${f.unit||''}`;return r.review_status||''}
function records(){if(type==='Contractor price book')return (D.price_book?.rows||[]).map(f=>{const original=D.records.find(r=>r.id===f.cost_id);return {...original,type,title:f.contractor+' · '+f.description,fields:f,review_status:f.arithmetic_review?.arithmetic_status==='display_rounding_explained'?'Rounding explained by workbook':f.flags.includes('printed_rate_times_quantity_differs_from_total')?'Arithmetic review needed':'Historical quote · scope review required',search_text:JSON.stringify(f).toLowerCase()}});if(type==='Source files')return D.sources.map(s=>({id:s.id,project_id:s.project_id,type,title:s.relative_path,review_status:s.review_status,fields:s,search_text:JSON.stringify(s).toLowerCase()}));if(type==='Field catalog')return D.field_catalog.map(s=>({id:s.field_key,type,title:s.field_key,fields:s,search_text:JSON.stringify(s).toLowerCase(),review_status:'Target field, not extraction coverage'}));return D.records.filter(r=>r.type===type)}
function drawReady(){
 $('heading').textContent=project?pmap[project].name:'Project library';$('subtitle').textContent=project?pmap[project].coverage:'A searchable record of dimensions, planting, materials, costs and design decisions.';
 $('projects').innerHTML=[['','All projects'],...D.projects.map(p=>[p.id,p.name])].map(([id,name])=>`<button data-project="${esc(id)}" class="${id===project?'active':''}">${esc(name)}<small>${id?pmap[id].status_label:`${D.projects.length} projects · growing library`}</small></button>`).join('');
 const rs=D.records.filter(r=>!project||r.project_id===project),ss=D.sources.filter(s=>!project||s.project_id===project);
 $('stats').innerHTML=[[D.summary_counts[project].records,'Library records & open questions'],[D.summary_counts[project].costs,'Historical cost rows'],[ss.filter(s=>s.asset).length,'Included source files'],[ss.length,'Files indexed']].map(([n,l])=>`<div class="stat"><strong>${n.toLocaleString()}</strong><span>${l}</span></div>`).join('');
 $('overview').innerHTML=D.projects.filter(p=>!project||p.id===project).map(p=>`<article class="project-card">${p.preview?`<img src="${esc(p.preview)}" alt="${esc(p.name)} reference plan">`:""}<div><h2>${esc(p.name)}</h2><span class="badge">${esc(p.id)}</span><p>${esc(p.coverage)}</p><p>${(p.review_links||[]).map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)} ↗</a>`).join(' · ')}</p></div></article>`).join('');
 $('tabs').innerHTML=cats.map(t=>`<button data-type="${esc(t)}" class="${type===t?'active':''}">${esc(t)}</button>`).join('');
 const old=$('status').value,opts=[...new Set(records().filter(r=>!project||!r.project_id||r.project_id===project).map(r=>r.review_status))].filter(Boolean).sort();$('status').innerHTML='<option value="">All statuses</option>'+opts.map(s=>`<option value="${esc(s)}">${esc(s.replaceAll('_',' '))}</option>`).join('');$('status').value=opts.includes(old)?old:'';results();
}
function detail(r){let f=r.fields||{},e=r.evidence;let fields=Object.entries(f).filter(([k])=>!['id','project_id','evidence_id','version_id','asset','geometry_json','geometry_reference','route_geometry_json','arithmetic_review'].includes(k)).map(([k,v])=>`<dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(v===null?'Unknown':typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('');let source=e?.source||(type==='Source files'?f:null);return `<div class="detail"><dl>${fields}</dl>${f.arithmetic_review?.source_asset?`<p>${esc(f.arithmetic_review.review_note)}</p><p><a href="${esc(f.arithmetic_review.source_asset.url)}" target="_blank" rel="noopener">Open supporting bid workbook ↗</a> · ${esc(f.arithmetic_review.source_locator)}</p>`:''}${source?`<div class="evidence"><strong>Source evidence</strong><p>${esc(source.relative_path)}${e?.page?' · Page '+esc(e.page):''}${e?.locator?' · '+esc(e.locator):''}</p>${e?`<blockquote>${esc(e.excerpt)}</blockquote><p>Method: ${esc(e.method)}</p>`:''}${source.asset?`<a href="${esc(source.asset.url)}" target="_blank" rel="noopener">Open included source ↗</a>`:'Indexed only — source file not included in this release.'}</div>`:'<p class="meta">No source evidence attached to this open issue or schema field.</p>'}</div>`}
function results(){let q=$('search').value.toLowerCase(),status=$('status').value;filtered=records().filter(r=>(!project||!r.project_id||r.project_id===project)&&(!q||r.search_text.includes(q))&&(!status||r.review_status===status));page=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1));$('count').textContent=filtered.length+(filtered.length===1?' record':' records')+(q?' matching your search':'');$('results').innerHTML=filtered.slice(page*size,(page+1)*size).map(r=>`<details><summary><div><strong>${esc(r.title.replaceAll('_',' '))}</strong><small>${esc(pmap[r.project_id]?.name||'Library schema')}</small></div><div class="value">${esc(value(r))}</div><div class="meta">${esc(r.version?.label||r.review_status||'')}<small>${esc((r.review_status||'').replaceAll('_',' '))}</small></div></summary>${detail(r)}</details>`).join('')||'<div class="empty">No records match. Try another category or a broader search.</div>';$('page').textContent=`${filtered.length?page+1:0} / ${Math.ceil(filtered.length/size)}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*size>=filtered.length;}
$('projects').onclick=e=>{let b=e.target.closest('[data-project]');if(b){project=b.dataset.project;page=0;draw()}};$('tabs').onclick=e=>{let b=e.target.closest('[data-type]');if(b){type=b.dataset.type;page=0;draw()}};$('search').oninput=()=>{page=0;results()};$('status').onchange=()=>{page=0;results()};$('prev').onclick=()=>{page--;results()};$('next').onclick=()=>{page++;results()};
$('export').onclick=()=>{const keys=[...new Set(filtered.flatMap(r=>Object.keys(r.fields||{})))].filter(k=>!['asset','id','project_id','version_id','evidence_id'].includes(k));const fields=['project','category','record id',...keys,'version','source file','source page','source locator','source excerpt'];const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const lines=filtered.map(r=>[pmap[r.project_id]?.name||'',r.type,r.id,...keys.map(k=>{let v=r.fields[k];return v!==null&&typeof v==='object'?JSON.stringify(v):v}),r.version?.label||'',r.evidence?.source.relative_path||'',r.evidence?.page||'',r.evidence?.locator||'',r.evidence?.excerpt||'']);const blob=new Blob(['\ufeff'+[fields,...lines].map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`studio-h-${project||'all'}-${type.toLowerCase().replaceAll(' ','-')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};queueMicrotask(()=>draw());

const loaded=new Map();let revision=0;
async function draw(){const mine=++revision,kind=type==='Contractor price book'?'Costs':type;try{if(!loaded.has(kind)){ $('count').textContent='Loading this category…';const rows=await Promise.all((D.record_chunks[kind]||[]).map(async file=>{const r=await fetch(file);if(!r.ok)throw Error('This category could not load. Select it again to retry.');return r.json()}));loaded.set(kind,rows.flat())}if(mine!==revision)return;D.records=loaded.get(kind);drawReady()}catch(e){$('count').textContent=e.message}}
