/* Physical sheet decoration: persisted with the presentation and included in PDF. */
(()=>{
const box=document.createElement('section');box.className='board-finish-controls';box.innerHTML=`<h2>Board border & fill</h2><label class="check"><input id="board-border-on" type="checkbox"> Show board border</label><label for="board-border-offset">Offset from sheet edge <output id="board-border-offset-value"></output></label><input id="board-border-offset" type="range" min="0" max="2" step="0.125"><label for="board-border-radius">Corner radius <output id="board-border-radius-value"></output></label><input id="board-border-radius" type="range" min="0" max="2" step="0.125"><label for="board-border-width">Line thickness <output id="board-border-width-value"></output></label><input id="board-border-width" type="range" min="0.25" max="8" step="0.25"><label for="board-border-color">Line color</label><input id="board-border-color" type="color"><label class="check"><input id="board-fill-on" type="checkbox"> Background fill</label><label for="board-fill-color">Fill color</label><input id="board-fill-color" type="color"><label for="board-fill-opacity">Fill opacity <output id="board-fill-opacity-value"></output></label><input id="board-fill-opacity" type="range" min="0" max="100" step="5"><p class="hint">Border measurements use the printed sheet size. Fill sits behind the images and title block.</p>`;groups.sheet.append(box);
const edge=document.createElement('div');edge.id='board-border';edge.setAttribute('aria-hidden','true');$('#sheet').prepend(edge);
const defaults={borderOn:false,borderOffset:.25,borderRadius:0,borderWidth:1,borderColor:'#50793e',fillOn:true,fillOpacity:100};
const value=k=>state.boardFinish?.[k]??defaults[k];
const bindings={'board-border-on':'borderOn','board-border-offset':'borderOffset','board-border-radius':'borderRadius','board-border-width':'borderWidth','board-border-color':'borderColor','board-fill-on':'fillOn','board-fill-opacity':'fillOpacity'};
for(const [id,key] of Object.entries(bindings)){const el=$('#'+id);el.addEventListener('input',()=>change(()=>{state.boardFinish={...defaults,...state.boardFinish,[key]:el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value}}))}
$('#board-fill-color').oninput=e=>change(()=>state.sheetColor=e.target.value);
for(const input of box.querySelectorAll('input[type=range]')){const ticks=document.createElement('div');ticks.className='range-ticks';ticks.setAttribute('aria-hidden','true');for(let i=0;i<11;i++)ticks.append(document.createElement('i'));input.after(ticks)}
const setup=setupSheet;setupSheet=function(){setup();const px=960/sheetSize()[0],sheet=$('#sheet'),color=/^#[\da-f]{6}$/i.test(state.sheetColor)?state.sheetColor:'#f0f0eb',alpha=value('fillOn')?Math.max(0,Math.min(100,value('fillOpacity')))/100:0;const rgb=[1,3,5].map(i=>Math.round(255+(parseInt(color.slice(i,i+2),16)-255)*alpha));sheet.style.setProperty('--sheet-color',`rgb(${rgb.join(',')})`);sheet.style.setProperty('--presentation-card',rgb.every(x=>x>245)?'#eeeeea':'#ffffff');edge.hidden=!value('borderOn');const width=value('borderWidth')/72*px,offset=value('borderOffset')*px;Object.assign(edge.style,{inset:offset+'px',border:width+'px solid '+value('borderColor'),borderRadius:value('borderRadius')*px+'px'});for(const [id,key] of Object.entries(bindings)){const el=$('#'+id);if(el.type==='checkbox')el.checked=value(key);else el.value=value(key);const out=$('#'+id+'-value');if(out)out.textContent=value(key)+(key==='fillOpacity'?'%':key==='borderWidth'?' pt':' in')}$('#board-fill-color').value=color;};
})();
