/* Only the owning engine can supply project content or receive edits. */
(()=>{
const send=(type,data={})=>parent.postMessage({channel:'studioh-board',type,...data},'*');let ready=false,allItems=[],projectPlan=null,savedKeys=new Set(),pending=new Map();
$('.library-choices').replaceChildren();$('#catalog-types').hidden=true;$('#add-dialog h3').textContent='From this moodboard';$('#add-dialog>p').textContent='Use an existing dashboard selection, upload an image or paste a direct image link.';
$('#add-dialog').querySelectorAll('.hint').forEach(e=>e.remove());const library=document.createElement('button');library.textContent='Browse libraries on the moodboard ↗';library.onclick=()=>returnToDashboard('library');$('.library-choices').before(library);
$('#shell-foot').textContent='Presentation layout · Your moodboard sections and selections remain intact';$('.footnote').textContent='';$('#shell-top small').textContent='Presentation editor · Current V2 working copy';
$('#board-save').onclick=()=>save(false);$('#board-return').onclick=()=>save(true);window.boardReturn=()=>save(true);
function save(close){if(!ready)return;const value=structuredClone(state);value.knownKeys=[...new Set([...savedKeys,...allItems.map(x=>x.key)])];value.excludedKeys=allItems.filter(x=>!state.tiles.some(t=>t.sourceKey===x.key)).map(x=>x.key);send('save',{state:value,close})}
function returnToDashboard(action){save(false);send('dashboard',{action})}
const originalRail=railAction;railAction=function(id){if(id==='sections'){returnToDashboard('sections');return}originalRail(id)};
$('#section-view').onclick=()=>returnToDashboard('sections');
// Studio-wide settings are intentionally not represented as per-project logo uploads.
$('[data-rail=settings]').hidden=true;$('#open-logo-settings').textContent='Studio logo settings are awaiting account integration';$('#open-logo-settings').disabled=true;$('#show-company-logo').disabled=true;$('#show-company-logo').closest('label').append(document.createTextNode(' · No studio logo configured'));
$('#scaled-plan img').removeAttribute('src');$('.builder-link').remove();document.querySelectorAll('.board-head .tag').forEach(x=>x.remove());$('#scaled-plan img').alt='Project plan';$('#include-plan').checked=false;
function applyItem(x,id){return {id,sourceKey:x.key,title:x.title,src:x.src,source:x.source,caption:x.caption||'',w:3,h:3,rw:1,rh:1}}
function catalog(){const root=$('.library-choices');root.replaceChildren();for(const x of allItems){const b=document.createElement('button'),img=document.createElement('img');img.src=x.src;img.alt=x.title;b.append(img,document.createTextNode(x.title));b.disabled=state.tiles.some(t=>t.sourceKey===x.key);b.onclick=()=>{const id=state.next++;editPresentation(()=>state.tiles.push(applyItem(x,id)));if(state.tiles.some(t=>t.id===id)){$('#add-dialog').close();selectImage(id);catalog()}};root.append(b)}if(!allItems.length)root.textContent='Add images and cards to the moodboard dashboard to populate your presentation.'}
const prevOpen=openAdd;openAdd=function(){catalog();prevOpen()};
function safePlan(item){return item.key==='project:trace'||allItems.some(x=>x.key===item.key)}
function accept(data){allItems=data.items||[];const rank=x=>/render|3d|concept/i.test(x.title)?0:x.group==='furnishings'?1:x.group==='materials'?2:/groundcover|shrub/i.test(x.title)?5:3;allItems.sort((a,b)=>rank(a)-rank(b));projectPlan=data.plan||null;const prior=data.presentation&&Array.isArray(data.presentation.tiles)?data.presentation:null;state={...seed(),project:data.project,titleStyle:'band',titleColor:'#34472f',titleRadius:16,titleAlign:'left',subtitleAlign:'left',showLogo:false,studioLogo:'',...prior};state.project=prior?.project||data.project;state.tiles=(prior?.tiles||[]).filter(t=>allItems.some(x=>x.key===t.sourceKey));state.tiles.forEach(t=>{const fresh=allItems.find(x=>x.key===t.sourceKey);Object.assign(t,{src:fresh.src,title:fresh.title,source:fresh.source})});savedKeys=new Set(Array.isArray(prior?.knownKeys)?prior.knownKeys:[]);state.next=Math.max(2,...state.tiles.map(t=>t.id+1));for(const x of allItems){if(state.tiles.some(t=>t.sourceKey===x.key)||prior?.excludedKeys?.includes(x.key))continue;state.tiles.push(applyItem(x,state.next++))}state.collection=allItems.map((x,i)=>applyItem(x,i+1000));state.planImage=state.planImage||projectPlan;if(state.planImage&&!safePlan(state.planImage))state.planImage=null;state.includePlan=!!state.planImage&&!!prior?.includePlan;if(state.planImage)$('#scaled-plan img').src=state.planImage.src;state.selected=state.tiles[0]?.id||0;ready=true;draw();arrange();catalog();setTool('layout');document.body.dataset.theme=['Morning','Day','Afternoon','Dusk','Night'].includes(data.theme)?data.theme:'Morning';$('#theme').value=document.body.dataset.theme;$('#shell-foot').textContent=allItems.length?`${allItems.length} moodboard items · Current V2 working copy · Cloud sync pending`:'Your moodboard has no images yet. Use Add to return to the libraries or upload an image.';}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!=='studioh-project')return;const m=e.data;if(m.type==='load'){try{accept(m);send('loaded')}catch(err){send('error',{message:err.message})}}if(m.type==='plan'){projectPlan=m.plan;if(!state.planImage)state.planImage=projectPlan;}if(m.type==='close')save(true);if(m.type==='saved')notify(m.message);if(m.type==='added'){const resolve=pending.get(m.requestId);pending.delete(m.requestId);allItems.push(m.item);resolve?.(m.item)}});
// Uploads join the shared dashboard collection before becoming presentation tiles.
addSource=async function(src,title,source){const img=new Image();img.src=src;await img.decode();if(src.startsWith('blob:')){const c=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(img.width,img.height));c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);src=c.toDataURL('image/jpeg',.85)}const requestId=crypto.randomUUID(),item=await new Promise((resolve,reject)=>{pending.set(requestId,resolve);send('add',{requestId,item:{src,title}});setTimeout(()=>{if(pending.delete(requestId))reject(Error('The project did not respond. Please reopen the board.'))},10000)});const id=state.next++;editPresentation(()=>state.tiles.push(applyItem(item,id)));$('#add-dialog').close();catalog();save(false);notify(state.tiles.some(t=>t.id===id)?'Added to the moodboard dashboard and presentation.':'Added to the dashboard. Free space on this sheet, then add it from the board collection.');};
// No fabricated sample plan: a real plan must be selected before this can be enabled.
const originalBind=bind;bind=function(){originalBind();document.querySelectorAll('[data-preset]').forEach(b=>{const click=b.onclick;b.onclick=()=>{click();if(!state.planImage){state.includePlan=false;$('#include-plan').checked=false;if(b.dataset.preset==='plan')notify('Add a conceptual plan from your project images using Plan.');draw()}}})};
const planSelect=document.createElement('select');planSelect.id='project-plan-image';planSelect.setAttribute('aria-label','Conceptual plan image');const label=document.createElement('label');label.textContent='Choose a project image as the plan';label.append(planSelect);groups.plan.prepend(label);
const oldSetTool=setTool;setTool=function(id){oldSetTool(id);if(id==='plan'){planSelect.replaceChildren(new Option('Choose a plan image…',''),...[...(projectPlan?[projectPlan]:[]),...allItems].map(x=>new Option(x.title,x.key)));planSelect.value=state.planImage?.key||''}};
planSelect.onchange=()=>{const item=[...(projectPlan?[projectPlan]:[]),...allItems].find(x=>x.key===planSelect.value);change(()=>{state.planImage=item||null;state.includePlan=!!item;state.planScale=0});if(item){$('#scaled-plan img').src=item.src;notify('Plan selected. Enter verified image dimensions before using a drawing scale.')}};
$('#include-plan').onchange=e=>{if(e.target.checked&&!state.planImage){e.target.checked=false;notify('Choose a project image as the plan first.');return}change(()=>state.includePlan=e.target.checked)};
$('#plan-scale').onchange=e=>{if(!state.planImage){e.target.value='0';notify('Choose a plan image first.');return}change(()=>{state.planScale=+e.target.value;state.includePlan=true})};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]'))save(true)});
if(parent===window){$('#shell-foot').textContent='Open this editor from Moodboard → Build board.';$('#board-return').onclick=()=>location.href='../?view=mood';$('#board-save').disabled=true}else send('ready');
})();
