import test from 'node:test';import assert from 'node:assert/strict';
import {defaultBook,validateBook,syncBookItems,autoPhaseFees,discounts,priceFromBook,pricingMethod,suggestedAllowance,labourAverage} from '../../v2/assets/proposals/fee-book.mjs';
import {blank,total,clientDocument,validate} from '../../v2/assets/proposals/model.mjs';import {nextBand} from '../../v2/assets/proposals/rules.mjs';
function setup(){const d=blank(),a=d.agreement;a.feeBook=defaultBook();a.feeMethod='Fee by construction budget band';a.autoPhaseFees=true;d.budget=a.budget=214000;syncBookItems(a,d.budget,{replace:true});return d;}
test('book validates, caps include upper boundary, unknown allowances remain blank',()=>{const b=defaultBook();validateBook(b);assert.equal(priceFromBook(b,b.services[0].id,50000).fee,b.services[0].bands[0].fee);assert.equal(priceFromBook(b,b.services[0].id,50001).fee,b.services[0].bands[1].fee);assert.equal(priceFromBook(b,b.services[0].id,900000),null);assert.equal(b.services[0].fixed.fee,'');b.caps[1]=100;assert.throws(()=>validateBook(b));});
test('full package net totals match phase and deliverable billing; removing member removes discount',()=>{const d=setup(),a=d.agreement,ids=a.feeBook.services.slice(0,2).map(s=>s.id);a.feeBook.packages=[{name:'Concept pair',ids,discount:10}];ids.forEach(id=>a.items.find(i=>i.id===id).on=true);autoPhaseFees(a);const gross=ids.reduce((n,id)=>n+a.items.find(i=>i.id===id).fee,0);assert.equal(total(d),Math.round(gross*90)/100);a.basis='Fees by deliverable';assert.equal(total(d),Math.round(gross*90)/100);a.items.find(i=>i.id===ids[1]).on=false;autoPhaseFees(a);assert.equal(discounts(a).length,0);assert.equal(total(d),a.items.find(i=>i.id===ids[0]).fee)});
test('manual overrides survive budget changes and explicit reapply restores book prices',()=>{const d=setup(),a=d.agreement,i=a.items[0];i.fee=777;i.fromFeeBook=false;syncBookItems(a,60000);assert.equal(i.fee,777);syncBookItems(a,60000,{replace:true});assert.equal(i.fee,a.feeBook.services[0].bands[1].fee)});
test('next band uses custom studio table with package reduction; internal matrix is absent from client payload',()=>{const d=setup(),a=d.agreement,ids=a.feeBook.services.slice(0,2).map(s=>s.id);a.feeBook.packages=[{name:'Pair',ids,discount:10}];ids.forEach(id=>a.items.find(i=>i.id===id).on=true);const quote=nextBand(d);assert.equal(quote.fee,Math.round(quote.rows.reduce((n,r)=>n+r.fee,0)*90)/100);const client=JSON.stringify(clientDocument(d));assert(!client.includes('feeBook'));assert(!client.includes('"hours"'));assert(!client.includes('"cost"'));validate(d)});
test('optional service defaults, phase removal and hourly pricing keep appropriate behavior',()=>{const d=setup(),a=d.agreement;assert.equal(a.items.find(i=>/3D Rendering/.test(i.name)).optional,true);a.phases.splice(0,1);a.items.forEach(i=>i.phase--);syncBookItems(a,d.budget,{replace:true});assert.equal(a.items.find(i=>i.name==='Conceptual Plan').phase,-1);pricingMethod(a,'Hourly');assert(a.phases.every(p=>p.method==='Hourly'));assert.equal(total(d),0);assert.equal(d.capRequired,false)});
test('overlapping or incomplete packages cannot be saved',()=>{const b=defaultBook();b.packages=[{name:'Bad',ids:[b.services[0].id],discount:10}];assert.throws(()=>validateBook(b));b.packages=[{name:'A',ids:b.services.slice(0,2).map(s=>s.id),discount:10},{name:'B',ids:b.services.slice(1,3).map(s=>s.id),discount:10}];assert.throws(()=>validateBook(b))});
test('calendar phase timing uses explicit commencement and clamps month ends',async()=>{const {phaseFinish}=await import('../../v2/assets/proposals/rules.mjs');assert.equal(phaseFinish({duration:4,unit:'weeks'},null),null);assert.deepEqual(phaseFinish({duration:1,unit:'months',range:true,end:2},'2026-01-31T12:00:00Z'),{from:'2026-02-28',to:'2026-03-31'});assert.deepEqual(phaseFinish({duration:2,unit:'weeks'},'2026-10-04T12:00:00Z'),{from:'2026-10-18',to:null})});
test('standalone services contribute once alongside automatic phase totals',()=>{const d=setup(),a=d.agreement;a.items[0].on=true;a.items[0].phase=-1;autoPhaseFees(a);assert.equal(total(d),a.items[0].fee);const i=a.items[1];i.fee=2000;i.on=true;autoPhaseFees(a);assert.equal(total(d),a.items[0].fee+i.fee)});

test('multiplier budgets use internal average costs, preserve missing values and fixed pricing groups',()=>{const b=defaultBook();b.multiplier=3;b.labourRates=[{name:'Designer',cost:70},{name:'Lead',cost:90}];assert.deepEqual(suggestedAllowance(b,3000),{cost:1000,hours:12.5,average:80});b.labourRates[1].cost='';assert.equal(labourAverage(b),null);assert.equal(suggestedAllowance(b,3000).hours,'');assert.equal(suggestedAllowance(b,'').cost,'');const service=b.services[0];service.groupPrices={small:{fee:1500,hours:'',cost:''}};assert.equal(priceFromBook(b,service.id,0,false,'small').fee,1500);validateBook(b);assert(!b.services.some(s=>/Enhanced|Full CD|Softscape|DD Set|Detailed Cost|Lumion/.test(s.name)));});
