import test from 'node:test';import assert from 'node:assert/strict';import {financialRoute,validateFinancialState} from '../src/project-financials.js';import {calculate} from '../../v2/assets/financials/model.mjs';import {environment} from './fixture.mjs';
const state=()=>({schema:1,agreement:{phases:[],items:[]},invoices:[],outsideCosts:[],changes:[],remainingLabor:100,earnedFee:800,overhead:50,signed:{fee:1000}});
const ctx={reply:(s,d)=>Response.json(d,{status:s}),body:r=>r.arrayBuffer(),permission:async()=> 'owner',hash:async x=>x};
const session={owner:'test',user:'admin',role:'admin'};
const call=(env,method,data,s=session,path='p')=>financialRoute(new Request('https://local/financials/'+path,{method,...(data?{body:JSON.stringify(data)}:{})}),env,s,ctx);
test('unrated hours suppress costs and profitability',()=>{let m=calculate(state(),[{hours:2,user:'u'}]);assert.equal(m.actual,null);assert.equal(m.margin,null);assert.equal(m.missing,2)});
test('earned rate and approved additions counted once; optional proposals excluded',()=>{let s=state();s.changes=[{state:'Approved',fee:200},{state:'Approved',includedInSigned:true,fee:400},{state:'Proposed',fee:500}];s.outsideCosts=[{amount:100}];let m=calculate(s,[{hours:2,costRate:100}]);assert.equal(m.fee,1200);assert.equal(m.actual,300);assert.equal(m.forecast,400);assert.equal(m.grossHour,250);assert.equal(m.netHour,225);assert.equal(m.effectiveRate,400)});
test('unknown remaining effort and overhead are not zero',()=>{let s=state();s.remainingLabor=null;s.overhead=null;let m=calculate(s,[{hours:2,costRate:100}]);assert.equal(m.forecast,null);assert.equal(m.netHour,null)});
test('private route rejects non-admin and demo',async()=>{for(const s of [{...session,role:'viewer'},{...session,demo:true}])assert.equal((await call(environment(),'GET',null,s)).status,403)});
test('CAS save, stale conflict and server-owned signed snapshots',async()=>{let env=environment();let r=await call(env,'POST',{state:state(),revision:null});assert.equal(r.status,200);let d=await r.json();assert.equal(d.state.signed,null);assert.equal((await call(env,'POST',{state:state(),revision:null})).status,409);r=await call(env,'POST',{state:state(),revision:d.revision,reference:'Signed v3',signedFee:2000},session,'p/sign');d=await r.json();assert.equal(d.state.signed.fee,2000);let tamper=state();tamper.signed={fee:1};r=await call(env,'POST',{state:tamper,revision:d.revision});assert.equal((await r.json()).state.signed.fee,2000);assert.equal([...env.PROJECTS.data.keys()].some(k=>k.includes('/projects/')),false)});
test('overpayment and negative financial values fail',()=>{let s=state();s.invoices=[{id:'1',amount:100,paid:101}];assert.throws(()=>validateFinancialState(s));s.invoices=[];s.overhead=-1;assert.throws(()=>validateFinancialState(s))});
test('cross-project access and missing signed references fail closed',async()=>{let env=environment();let r=await financialRoute(new Request('https://local/financials/other'),env,session,{...ctx,permission:async()=>null});assert.equal(r.status,403);r=await call(env,'POST',{state:state(),revision:null,reference:'',signedFee:1000},session,'p/sign');assert.equal(r.status,400)});
test('proposal files remain private and checksum verified',async()=>{let env=environment();const c={...ctx,hash:async()=> 'a'.repeat(64)},url='https://local/financials/p/documents/'+'a'.repeat(64);let r=await financialRoute(new Request(url,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:'example'}),env,session,c);assert.equal(r.status,200);r=await financialRoute(new Request(url),env,{...session,role:'viewer'},c);assert.equal(r.status,403);r=await financialRoute(new Request(url),env,session,c);assert.equal(await r.text(),'example')});
test('proposal extraction returns evidence, never saves agreement implicitly',async()=>{let env=environment();await env.PROJECTS.put('accounts/test/financials/documents/p/'+'b'.repeat(64),'document',{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}});env.LEGACY={async fetch(u,o){const d=JSON.parse(o.body);assert.match(d.messages[0].content[1].text,/untrusted/);return Response.json({content:[{type:'text',text:JSON.stringify({phases:[{name:'Concept',method:'Fixed fee',fee:1000,source:'Paragraph 2'}],deliverables:[]})}],stop_reason:'end_turn'})}};let r=await call(env,'POST',{documentId:'b'.repeat(64),text:'Concept fee 1000'},session,'p/extract');assert.equal(r.status,200);assert.equal((await r.json()).extracted.phases[0].source,'Paragraph 2');assert.equal(await env.PROJECTS.get('accounts/test/financials/p.json'),null)});

test('approved sample reconciles across costs, fee, payments and forecast without replacing real data',async()=>{
 const {completeSample}=await import('../../v2/assets/financials/sample.mjs');
 const real=state(),before=JSON.stringify(real);completeSample(real);assert.equal(JSON.stringify(real),before);
 const sample={...state(),sample:true,signed:null,agreement:{phases:[{}],items:[{}]}};completeSample(sample);
 const m=calculate(sample,sample.sampleEntries);assert.equal(m.fee,36000);assert.equal(m.actual,9800);assert.equal(m.forecast,18000);assert.equal(m.margin,.5);assert.equal(m.outstanding,6000);assert.equal(m.headroom,1800);
 assert.equal(sample.agreement.items.filter(x=>x.on).reduce((n,x)=>n+x.fee,0),36000);
 sample.invoices[0].paid=100;completeSample(sample);assert.equal(sample.invoices[0].paid,100,'repeat load retains edits');
});
