import test from 'node:test';import assert from 'node:assert/strict';import {proposalRoute} from '../src/proposals.js';import {example,blank,clientDocument,total,validate,checks} from '../../v2/assets/proposals/model.mjs';import {environment} from './fixture.mjs';import {hash} from '../src/index.js';
const s={owner:'test',role:'admin',user:'owner'},ctx={reply:(status,data)=>Response.json(data,{status}),body:r=>r.arrayBuffer(),hash};
const call=(env,path='',data,session=s)=>proposalRoute(new Request('https://local/proposals'+path,{method:data===undefined?'GET':'POST',...(data===undefined?{}:{body:JSON.stringify(data)})}),env,session,ctx);
async function created(env,d=example()){const r=await call(env,'/one',{draft:d,revision:null});assert.equal(r.status,200);return r.json()}
test('real rate sheet sample has two fixed phases, optional excluded and no internal client costs',()=>{const d=example();assert.equal(total(d),13985);d.agreement.items[0].cost=9999;d.agreement.items[0].hours=200;d.agreement.rates[0].costRate=99;const out=JSON.stringify(clientDocument(d));assert(!out.includes('costRate'));assert(!out.includes('9999'));assert(!out.includes('"hours"'));const i=d.agreement.items[1];i.on=true;i.optional=true;i.fee=500;d.agreement.basis='Fees by deliverable';assert.equal(total(d),13985)});
test('missing cap, client and legal review block readiness',()=>{const d=blank();assert.equal(d.capRequired,false);d.capRequired=true;assert(checks(d).filter(x=>!x.ok).length>=5);d.cap=NaN;assert.throws(()=>validate(d));});
test('private admin policy, no cross-studio read and CAS conflicts',async()=>{const env=environment();for(const bad of [{...s,demo:true},{...s,role:'member'}])assert.equal((await call(env,'',undefined,bad)).status,403);const first=await created(env);assert.equal((await call(env,'/one',undefined,{...s,owner:'other'})).status,404);assert.equal((await call(env,'/one',{draft:example(),revision:null})).status,409);const d=example();d.name='Updated';assert.equal((await call(env,'/one',{draft:d,revision:first.revision})).status,200);const result=await (await call(env)).json();assert.equal(result.records[0].name,'Updated')});
test('signed state cannot be injected through draft save; project requires executed agreement',async()=>{const env=environment(),d=example();d.signed={fee:1};let r=await call(env,'/one',{draft:d,revision:null,status:'Signed',signed:{document:{fee:1}}});const x=await r.json();assert.equal(x.record.status,'Draft');assert.equal(x.record.signed,undefined);assert.equal((await call(env,'/one/project',{revision:x.revision})).status,400)});
test('record executed PDF locks drafts and conversion is idempotent, carries client and billing fields',async()=>{const env=environment(),d=example();d.email='client@example.com';d.legalText='Reviewed complete terms';d.legalReviewed=true;d.agreement.reviewed=true;let x=await created(env,d);const bytes=new TextEncoder().encode('%PDF-1.7\nfixture'),id=await hash(bytes);let r=await proposalRoute(new Request('https://local/proposals/one/document/'+id,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:bytes}),env,s,ctx);assert.equal(r.status,200);r=await call(env,'/one/signed',{revision:x.revision,documentId:id,clientSigner:'Client',studioSigner:'Designer',signedDate:'2026-10-02',confirmed:true});assert.equal(r.status,200);x=await r.json();assert.equal(x.record.status,'Signed');assert.equal((await call(env,'/one',{draft:example(),revision:x.revision})).status,409);r=await call(env,'/one/project',{revision:x.revision});assert.equal(r.status,200);x=await r.json();const a=await (await call(env,'/one/project',{revision:x.revision})).json();assert.equal(a.projectId,x.projectId);assert.equal([...env.PROJECTS.data.keys()].filter(k=>k.endsWith('/state.json')).length,1);const ledger=await (await env.PROJECTS.get('accounts/test/financials/'+x.projectId+'.json')).json();assert.equal(ledger.signed.fee,13985);assert.equal(ledger.agreement.rates[0].rate,295)});
test('AI extraction has evidence and does not mutate proposal; unknown cap stays unknown',async()=>{const env=environment(),x=await created(env);await env.PROJECTS.put('accounts/test/proposals/documents/one/'+'b'.repeat(64),'word',{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}});env.LEGACY={async fetch(url,opt){const p=JSON.parse(opt.body);assert.match(p.messages[0].content[1].text,/untrusted/);return Response.json({content:[{type:'text',text:JSON.stringify({constructionCap:null,phases:[],deliverables:[],sections:[{title:'Scope',text:'Source text',source:'Paragraph 2'}]})}],stop_reason:'end_turn'})}};const r=await call(env,'/one/extract',{documentId:'b'.repeat(64),text:'source'});assert.equal(r.status,200);assert.equal((await r.json()).extracted.constructionCap,null);assert.equal((await (await call(env,'/one')).json()).revision,x.revision)});
test('cap is conditional and unresolved tokens cannot bypass readiness',()=>{const d=example();d.cap='';d.capRequired=false;assert(checks(d).find(c=>c.title==='Construction cap not required by this agreement').ok);assert(checks(d).find(c=>c.title==='Estimate within construction cap').ok);d.legalText='Hello {{client.firstName}} in {{property.city}}';d.contact={firstName:'Alex'};d.property={city:'San Marino',internalSecret:'private'};assert(checks(d).find(c=>c.title==='No unresolved document fields').ok);assert.equal(clientDocument(d).legalText,'Hello Alex in San Marino');assert(!JSON.stringify(clientDocument(d)).includes('internalSecret'));d.legalText+=' {{unknown}}';assert(!checks(d).find(c=>c.title==='No unresolved document fields').ok);d.capRequired=true;assert(!checks(d).find(c=>c.title==='Construction cap entered').ok)});
import {nextBand,cancellation} from '../../v2/assets/proposals/rules.mjs';
test('next band excludes options, flags custom services and stops at highest band',()=>{const d=example(),q=nextBand(d);assert.equal(q.fee,17985);d.agreement.items[1].on=true;d.agreement.items[1].optional=true;assert.equal(nextBand(d).fee,17985);d.agreement.items.push({id:'custom',name:'Custom',on:true,optional:false,phase:0});assert.match(nextBand(d).error,/Custom/);d.agreement.threshold=750000;assert.match(nextBand(d).error,/No higher/)});
test('cancellation caps combined labor and penalty and reconciles credits',()=>{assert.deepEqual(cancellation({baseFee:36000,hoursValue:20000,paid:12000}),{total:30800,balance:18800,credit:0});assert.deepEqual(cancellation({baseFee:36000,hoursValue:40000,paid:40000}),{total:36000,balance:0,credit:4000});assert.throws(()=>cancellation({baseFee:NaN,hoursValue:0}))});
test('private media verifies type and hash and remains isolated by studio',async()=>{const env=environment();await created(env);const bytes=new Uint8Array([137,80,78,71,13,10,26,10]),id=await hash(bytes);const put=(type,session=s)=>proposalRoute(new Request('https://local/proposals/one/media/'+id,{method:'PUT',headers:{'Content-Type':type},body:bytes}),env,session,ctx);assert.equal((await put('image/png')).status,200);assert.equal((await put('image/jpeg')).status,400);assert.equal((await put('image/png',{...s,owner:'other'})).status,404);const r=await proposalRoute(new Request('https://local/proposals/one/media/'+id),env,s,ctx);assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'image/png')});
