import test from 'node:test';import assert from 'node:assert/strict';import {proposalRoute} from '../src/proposals.js';import {example,blank,clientDocument,total,validate,checks} from '../../v2/assets/proposals/model.mjs';import {environment} from './fixture.mjs';import {hash} from '../src/index.js';
const s={owner:'test',role:'admin',user:'owner'},ctx={reply:(status,data)=>Response.json(data,{status}),body:r=>r.arrayBuffer(),hash};
const call=(env,path='',data,session=s)=>proposalRoute(new Request('https://local/proposals'+path,{method:data===undefined?'GET':'POST',...(data===undefined?{}:{body:JSON.stringify(data)})}),env,session,ctx);
async function created(env,d=example()){const r=await call(env,'/one',{draft:d,revision:null});assert.equal(r.status,200);return r.json()}
test('real rate sheet sample has two fixed phases, optional excluded and no internal client costs',()=>{const d=example();assert.equal(total(d),13985);d.agreement.items[0].cost=9999;d.agreement.items[0].hours=200;d.agreement.rates[0].costRate=99;const out=JSON.stringify(clientDocument(d));assert(!out.includes('costRate'));assert(!out.includes('9999'));assert(!out.includes('"hours"'));const i=d.agreement.items[1];i.on=true;i.optional=true;i.fee=500;d.agreement.basis='Fees by deliverable';assert.equal(total(d),13985)});
test('missing cap, client and legal review block readiness',()=>{const d=blank();assert(checks(d).filter(x=>!x.ok).length>=5);d.cap=NaN;assert.throws(()=>validate(d));});
test('private admin policy, no cross-studio read and CAS conflicts',async()=>{const env=environment();for(const bad of [{...s,demo:true},{...s,role:'member'}])assert.equal((await call(env,'',undefined,bad)).status,403);const first=await created(env);assert.equal((await call(env,'/one',undefined,{...s,owner:'other'})).status,404);assert.equal((await call(env,'/one',{draft:example(),revision:null})).status,409);const d=example();d.name='Updated';assert.equal((await call(env,'/one',{draft:d,revision:first.revision})).status,200);const result=await (await call(env)).json();assert.equal(result.records[0].name,'Updated')});
test('signed state cannot be injected through draft save; project requires executed agreement',async()=>{const env=environment(),d=example();d.signed={fee:1};let r=await call(env,'/one',{draft:d,revision:null,status:'Signed',signed:{document:{fee:1}}});const x=await r.json();assert.equal(x.record.status,'Draft');assert.equal(x.record.signed,undefined);assert.equal((await call(env,'/one/project',{revision:x.revision})).status,400)});
test('record executed PDF locks drafts and conversion is idempotent, carries client and billing fields',async()=>{const env=environment(),d=example();d.email='client@example.com';d.legalText='Reviewed complete terms';d.legalReviewed=true;d.agreement.reviewed=true;let x=await created(env,d);const bytes=new TextEncoder().encode('%PDF-1.7\nfixture'),id=await hash(bytes);let r=await proposalRoute(new Request('https://local/proposals/one/document/'+id,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:bytes}),env,s,ctx);assert.equal(r.status,200);r=await call(env,'/one/signed',{revision:x.revision,documentId:id,clientSigner:'Client',studioSigner:'Designer',signedDate:'2026-10-02',confirmed:true});assert.equal(r.status,200);x=await r.json();assert.equal(x.record.status,'Signed');assert.equal((await call(env,'/one',{draft:example(),revision:x.revision})).status,409);r=await call(env,'/one/project',{revision:x.revision});assert.equal(r.status,200);x=await r.json();const a=await (await call(env,'/one/project',{revision:x.revision})).json();assert.equal(a.projectId,x.projectId);assert.equal([...env.PROJECTS.data.keys()].filter(k=>k.endsWith('/state.json')).length,1);const ledger=await (await env.PROJECTS.get('accounts/test/financials/'+x.projectId+'.json')).json();assert.equal(ledger.signed.fee,13985);assert.equal(ledger.agreement.rates[0].rate,295)});
test('AI extraction has evidence and does not mutate proposal; unknown cap stays unknown',async()=>{const env=environment(),x=await created(env);await env.PROJECTS.put('accounts/test/proposals/documents/one/'+'b'.repeat(64),'word',{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}});env.LEGACY={async fetch(url,opt){const p=JSON.parse(opt.body);assert.match(p.messages[0].content[1].text,/untrusted/);return Response.json({content:[{type:'text',text:JSON.stringify({constructionCap:null,phases:[],deliverables:[],sections:[{title:'Scope',text:'Source text',source:'Paragraph 2'}]})}],stop_reason:'end_turn'})}};const r=await call(env,'/one/extract',{documentId:'b'.repeat(64),text:'source'});assert.equal(r.status,200);assert.equal((await r.json()).extracted.constructionCap,null);assert.equal((await (await call(env,'/one')).json()).revision,x.revision)});
