import {test} from 'node:test';import assert from 'node:assert/strict';import worker,{hash} from '../src/index.js';
export class Bucket {constructor(){this.data=new Map()}async get(k){const d=this.data.get(k);if(!d)return null;return {...d,body:new Blob([d.bytes]).stream(),text:async()=>new TextDecoder().decode(d.bytes),json:async()=>JSON.parse(new TextDecoder().decode(d.bytes))}}async head(k){return this.get(k)}async put(k,v,opt={}){const old=this.data.get(k),c=opt.onlyIf;if(c?.etagDoesNotMatch==='*'&&old||c?.etagMatches&&old?.etag!==c.etagMatches)return null;const bytes=new Uint8Array(await new Response(v).arrayBuffer()),etag=await hash(bytes);const d={bytes,etag,httpEtag:'"'+etag+'"',httpMetadata:opt.httpMetadata,customMetadata:opt.customMetadata,uploaded:new Date()};this.data.set(k,d);return d}async delete(k){this.data.delete(k)}async list({prefix,delimiter}){return {objects:[...this.data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),delimitedPrefixes:[...new Set([...this.data.keys()].filter(k=>k.startsWith(prefix)).map(k=>prefix+k.slice(prefix.length).split(delimiter)[0]+delimiter))],truncated:false}}}
export function environment(){return {PROJECTS:new Bucket(),LEGACY:{async fetch(u,o){const d=JSON.parse(o.body);assert.deepEqual(Object.keys(d).sort(),['key','type']);assert.equal(d.type,'savepdf');return Response.json({error:d.key==='correct-key'?'No id':'Not authorized'},{status:d.key==='correct-key'?400:403})}}}}
const req=(path,method='GET',data,token,extra={})=>new Request('http://127.0.0.1:8788'+path,{method,headers:{Origin:'http://127.0.0.1:51844',...(token?{Authorization:'Bearer '+token}:{}),...extra},...(data!==undefined?{body:typeof data==='string'?data:JSON.stringify(data)}:{})});
test('private session, account isolation, raw media, revisions, history and logout',async()=>{const env=environment();assert.equal((await worker.fetch(req('/projects'),env)).status,401);assert.equal((await worker.fetch(req('/session','POST',{key:'bad'}),env)).status,401);const login=await worker.fetch(req('/session','POST',{key:'correct-key'}),env);assert.match(login.headers.get('Set-Cookie'),/HttpOnly/);const {token}=await login.json();const doc={schema:1,projectId:'test',name:'Test',bid:{S:{pi:{project:'Test'},moodboard:{sections:['plants']}}}};
let r=await worker.fetch(req('/projects/test','PUT',doc,token,{'If-None-Match':'*'}),env);assert.equal(r.status,200);const tag=r.headers.get('ETag');assert.equal((await worker.fetch(req('/projects/test','PUT',doc,token,{'If-None-Match':'*'}),env)).status,409);assert.equal((await worker.fetch(req('/projects/test','PUT',doc,token),env)).status,428);
r=await worker.fetch(req('/projects/test','PUT',{...doc,name:'Updated'},token,{'If-Match':tag}),env);assert.equal(r.status,200);assert.equal((await worker.fetch(req('/projects/test','PUT',doc,token,{'If-Match':tag}),env)).status,409);
const data='raw private document',digest=await hash(data);assert.equal((await worker.fetch(req('/projects/test/assets/'+digest,'PUT',data,token,{'Content-Type':'text/plain'}),env)).status,200);assert.equal(await (await worker.fetch(req('/projects/test/assets/'+digest,'GET',undefined,token),env)).text(),data);assert.equal((await worker.fetch(req('/projects/test/assets/'+digest),env)).status,401);
const other='b'.repeat(64);await env.PROJECTS.put('sessions/'+await hash(other),JSON.stringify({owner:'another-studio',user:'test',expires:Date.now()+10000}));assert.equal((await worker.fetch(req('/projects/test','GET',undefined,other),env)).status,404);assert.equal((await worker.fetch(req('/projects/test/assets/'+digest,'GET',undefined,other),env)).status,404);assert([...env.PROJECTS.data.keys()].some(k=>k.includes('/history/')));
assert.equal((await worker.fetch(req('/projects/test','GET',undefined,token,{Origin:'https://evil.example'}),env)).status,403);await worker.fetch(req('/logout','POST',undefined,token),env);assert.equal((await worker.fetch(req('/projects','GET',undefined,token),env)).status,401);
});

test('two users in one studio keep separate preferences; no production identity binding',async()=>{
 const env=environment();const alice='c'.repeat(64),bob='d'.repeat(64);
 for(const [token,user] of [[alice,'alice'],[bob,'bob']])await env.PROJECTS.put('sessions/'+await hash(token),JSON.stringify({owner:'same-studio',user,expires:Date.now()+10000}));
 assert.equal((await worker.fetch(req('/preferences','PUT',{theme:'Night'},alice,{'If-None-Match':'*'}),env)).status,200);
 assert.equal((await worker.fetch(req('/preferences','GET',undefined,bob),env)).status,404);
 assert.equal((await worker.fetch(req('/preferences','PUT',{theme:'Morning'},bob,{'If-None-Match':'*'}),env)).status,200);
 assert.deepEqual(await (await worker.fetch(req('/preferences','GET',undefined,alice),env)).json(),{theme:'Night'});
 assert.deepEqual(await (await worker.fetch(req('/preferences','GET',undefined,bob),env)).json(),{theme:'Morning'});
 delete env.LEGACY;
 assert.equal((await worker.fetch(req('/session','POST',{key:'correct-key'}),env)).status,503);
});
