import {test} from 'node:test';import assert from 'node:assert/strict';import {sessionAction,settle,elapsed} from '../src/time-session.js';
const input={projectId:'p',date:'2026-10-01',workType:'task',workId:'t1',workTitle:'Planting',offsetMinutes:0,mode:'countdown'};
const make=()=>({entries:[],drafts:[],weeks:{},timer:null,preferences:{smart:true}});
const ctx=now=>({now,clean:async d=>{if(!Number.isFinite(d.hours)||d.hours<=0||d.hours>24)throw Error('Invalid hours');return d},editWeek:()=>true,budgets:{p:{'task:t1':1,'deliverable:d1':2}}});
test('switch stops prior work into a draft, counts remaining allowance, and pauses at zero',async()=>{const l=make();await sessionAction('start',input,l,ctx('2026-10-01T10:00:00Z'));const id=l.timer.id;await sessionAction('pulse',{timerId:id},l,ctx('2026-10-01T10:01:00Z'));await sessionAction('switch',{...input,workType:'deliverable',workId:'d1'},l,ctx('2026-10-01T10:02:00Z'));assert.equal(l.drafts.length,1);assert.equal(l.drafts[0].workId,'t1');assert.equal(l.drafts[0].hours,2/60);assert.equal(l.entries.length,0);assert.equal(l.timer.workId,'d1');await sessionAction('switch',input,l,ctx('2026-10-01T10:02:10Z'));assert.equal(l.timer.limitSeconds,3480);l.timer.limitSeconds=10;settle(l.timer,Date.parse('2026-10-01T10:02:30Z'));assert.equal(l.timer.elapsedSeconds,10);assert.equal(l.timer.paused,true);assert.equal(l.timer.reason,'Budget reached');});
test('pause excludes a call, resume is explicit, and lease bounds disconnects',async()=>{const l=make();await sessionAction('start',input,l,ctx('2026-10-01T10:00:00Z'));const id=l.timer.id;await sessionAction('pause',{timerId:id},l,ctx('2026-10-01T10:00:30Z'));await assert.rejects(sessionAction('switch',{...input,workId:'t2'},l,ctx('2026-10-01T10:01:00Z')),/Resume/);assert.equal(elapsed(l.timer,Date.parse('2026-10-01T10:15:00Z')),30);await sessionAction('resume',{timerId:id},l,ctx('2026-10-01T10:15:00Z'));await sessionAction('finish',{timerId:id},l,ctx('2026-10-01T10:20:00Z'));assert.equal(l.timer,null);assert.equal(l.drafts[0].hours,120/3600);});
test('midnight splits dates; review respects locks, limits, discard and replay',async()=>{const l=make();await sessionAction('start',{...input,mode:'stopwatch'},l,ctx('2026-10-01T23:59:30Z'));await sessionAction('finish',{timerId:l.timer.id},l,ctx('2026-10-02T00:00:30Z'));assert.deepEqual(l.drafts.map(d=>d.date),['2026-10-01','2026-10-02']);assert.deepEqual(l.drafts.map(d=>d.hours),[30/3600,30/3600]);const items=l.drafts.map(d=>({id:d.id,hours:1}));await assert.rejects(sessionAction('review',{items},structuredClone(l),{...ctx('2026-10-02T00:01:00Z'),editWeek:()=>false}),/locked/);const over=structuredClone(l);over.entries.push({date:'2026-10-01',hours:24});await assert.rejects(sessionAction('review',{items},over,ctx('2026-10-02T00:01:00Z')),/24/);items[1].discard=true;await sessionAction('review',{items},l,ctx('2026-10-02T00:01:00Z'));assert.equal(l.entries.length,1);assert.equal(l.entries[0].hours,1);assert.equal(l.drafts.length,0);await assert.rejects(sessionAction('review',{items},l,ctx('2026-10-02T00:01:00Z')),/already/);});
test('a second tab cannot silently pulse, pause or switch the active clock',async()=>{const l=make();await sessionAction('start',{...input,controller:'one'},l,ctx('2026-10-01T10:00:00Z'));const timerId=l.timer.id;for(const action of ['pulse','pause'])await assert.rejects(sessionAction(action,{timerId,controller:'two'},l,ctx('2026-10-01T10:00:10Z')),/another tab/);await assert.rejects(sessionAction('switch',{...input,workId:'t2',controller:'two'},l,ctx('2026-10-01T10:00:10Z')),/another tab/);await sessionAction('resume',{timerId,controller:'two'},l,ctx('2026-10-01T10:00:10Z'));assert.equal(l.timer.controller,'two');await assert.rejects(sessionAction('pulse',{timerId,controller:'one'},l,ctx('2026-10-01T10:00:20Z')),/another tab/);});
test('switching to an exhausted allowance stops the old task instead of silently charging it',async()=>{const l=make();l.entries.push({...input,workType:'deliverable',workId:'d1',hours:2});await sessionAction('start',input,l,ctx('2026-10-01T10:00:00Z'));const result=await sessionAction('switch',{...input,workType:'deliverable',workId:'d1'},l,ctx('2026-10-01T10:01:00Z'));assert.equal(l.timer,null);assert.equal(l.drafts.length,1);assert.match(result.warning,/Previous work has stopped/);});
