const $=s=>document.querySelector(s);const names={g:'The gallery',h:'The studio journal',i:'The quiet workspace'};
const defaults={g:['brief','milestone','actions','budget'],h:['milestone','actions','fee','week'],i:['actions','approvals']};
const titles={brief:'AI project brief',milestone:'Next milestone',actions:'Next actions',budget:'Landscape budget',fee:'Design fee',journey:'Project journey',approvals:'Pending approvals',week:'This week',activity:'Latest activity',savings:'Closing the budget gap',bids:'Contractor bids'};
const state={layout:['g','h','i'].includes(location.hash.slice(1))?location.hash.slice(1):'g',selected:Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,[...v]])),tab:'today',days:4,alerts:true,timing:'weekly',dismissed:false,done:new Set(),approved:new Set(),fast:false};
const nav=[['Project home','M3 3h12v12H3z M3 7h12 M7 7v8'],['Brief & site','M4 2h8l3 3v11H4z M7 7h5 M7 10h5'],['Project files','M2 5h5l2 2h7v8H2z'],['Design','M2 4l4-2 6 2 4-2v12l-4 2-6-2-4 2z M6 2v12 M12 4v12'],['Costs & savings','M4 2h10v14H4z M7 5h4 M7 9h1 M10 9h1 M7 12h1 M10 12h1'],['Client Center','M2 3h14v10H7l-4 3v-3H2z M5 6h8 M5 9h5'],['Financials','M3 15V8h3v7 M8 15V3h3v12 M13 15V6h3v9'],['Deliver','M2 4l1 1 2-3 M7 4h9 M2 10l1 1 2-3 M7 10h9 M7 15h9']];
$('#nav').innerHTML=nav.map(([name,path],i)=>`<button class="${i?'':'active'}" data-info="${name}"><svg class="nav-icon" viewBox="0 0 18 18" aria-hidden="true"><path d="${path}"/></svg>${name}</button>`).join('');
const scene=(copy=false)=>`<div class="hero ${copy?'large':''}"><svg class="scene" viewBox="386 514 380 507" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Sample garden design reference with a pool, planted terraces and outdoor living spaces"><image href="../../assets/asian-scenes.png" width="1536" height="1024"/></svg>${copy?'<div class="hero-copy"><small>YOUR PROJECT, TAKING SHAPE</small><h2>Quiet geometry.<br>Warm materials.</h2></div>':''}<span class="image-label">Concept direction · sample imagery</span></div>`;
const head=(title,action,label)=>`<div class="card-head"><h2>${title}</h2>${action?`<button data-info="${action}">${label||'View detail'}</button>`:''}</div>`;
const bottom=(label,info)=>`<div class="bottom"><button data-info="${info||label}">${label}</button></div>`;
const pager=(id,n)=>`<div class="pager"><div class="dots">${Array.from({length:n},(_,i)=>`<button data-slide="${id}" data-index="${i}" aria-label="${id==='brief'?'Brief':'Milestone'} view ${i+1}" aria-current="${i===0}"></button>`).join('')}</div><div class="arrows"><button data-step="-1" data-carousel="${id}" aria-label="Previous ${id} view">‹</button><button data-step="1" data-carousel="${id}" aria-label="Next ${id} view">›</button></div></div>`;
function brief(dark=false){return `<article class="card brief ${dark?'dark':''}" data-card="brief">${head('AI project brief','Brief sources','Sources')}<div class="slides" id="brief" tabindex="0" aria-label="Project brief slides"><section class="slide"><span class="eyebrow">MONDAY, SEPTEMBER 28</span><h3>A clear direction.<br>A few decisions ahead.</h3><p>The design is moving forward. ${state.approved.size===2?'Both sample approvals are recorded.':'Confirm the material palette before finalizing the review set.'} The estimate is <strong>12% over budget</strong>; design fees project a <strong>29% margin.</strong></p></section><section class="slide"><div class="slide-title"><b>Where the budget stands</b><small>12% over</small></div><svg class="diagram" viewBox="0 0 380 110" role="img" aria-label="Budget 450 thousand dollars. Current estimate 504 thousand dollars, 54 thousand above budget."><text x="0" y="15">Landscape budget</text><rect x="0" y="25" width="286" height="17" rx="4" fill="#b8c9af"/><text x="302" y="38">$450k</text><text x="0" y="66">Current estimate</text><rect x="0" y="76" width="320" height="17" rx="4" fill="#d9b6c0"/><text x="335" y="89">$504k</text></svg><p>Review specification options before increasing the budget.</p></section><section class="slide"><div class="slide-title"><b>Work before delivery</b><small>Example allocation</small></div><svg class="diagram" viewBox="0 0 380 110" role="img" aria-label="15 hours of planned work and 12 hours available, a three hour gap"><text x="0" y="15">Planned effort · 15 hours</text><rect x="0" y="28" width="360" height="20" rx="4" fill="#b9cedc"/><text x="0" y="72">Available across projects · 12 hours</text><rect x="0" y="83" width="288" height="20" rx="4" fill="#b8c9af"/><rect x="294" y="83" width="66" height="20" rx="4" fill="#dec2c9"/></svg><p>Three hours need reassignment or a change to the plan.</p></section></div>${pager('brief',3)}</article>`}
const tasks=[['palette','Confirm material palette','Alex · client decision','0.5 h'],['plant','Finish planting plan','Maya · design development','4 h'],['light','Coordinate lighting','Maya · design development','3 h']];
const taskRows=()=>tasks.map(([id,t,sub,h])=>`<label class="task"><input type="checkbox" data-task="${id}" ${state.done.has(id)?'checked':''} aria-label="Complete ${t}"><span>${t}<small>${sub}</small></span><small>${h}</small></label>`).join('');
function milestone(){return `<article class="card milestone ${state.layout==='g'?'pink':'blue'}" data-card="milestone">${head('Next milestone','Milestone settings','Edit')}<div class="slides" id="milestone" tabindex="0" aria-label="Milestone slides"><section class="slide"><div class="countdown ${state.days<=2?'urgent':state.days<=7?'soon':'calm'}"><b class="big">${state.days}</b><span>${state.days===1?'day':'days'} to go</span></div><h3>Design development delivery</h3><small class="date">${new Date(Date.UTC(2026,8,28+state.days)).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'})} · Fixed deadline · Alex</small><div class="small-line"><span>${3-state.done.size} priority tasks remaining</span><button class="plain" data-slide="milestone" data-index="1">View tasks →</button></div><div class="track"><span style="width:${state.done.size/3*100}%"></span></div></section><section class="slide">${taskRows()}</section></div>${pager('milestone',2)}</article>`}
function budget(){return `<article class="card" data-card="budget">${head('Landscape budget','Estimate','Open estimate')}<small>Current estimate</small><div class="metric-top"><strong>$504,000</strong><span class="delta">12% over budget</span></div><svg class="budget-svg" viewBox="0 0 400 79" role="img" aria-label="504 thousand dollar estimate exceeds the 450 thousand dollar budget by 54 thousand dollars"><rect x="0" y="25" width="398" height="19" rx="5" fill="#edf1e9"/><rect x="0" y="25" width="354" height="19" rx="5" fill="#b6c6ad"/><path d="M354 25h39q5 0 5 5v9q0 5-5 5h-39z" fill="#dbb8c2"/><path d="M354 15v39" stroke="#6b7866"/><text x="0" y="70">$0</text><text x="310" y="9">Budget $450k</text><text x="350" y="70">$504k</text></svg><div class="budget-caption"><span>Above budget</span><b>$54,000</b></div>${bottom('View potential savings')}</article>`}
function fee(){return `<article class="card" data-card="fee">${head('Design fee','Financials','Financials')}<small>Projected profit</small><div class="fee-total"><b>$10,400</b><span class="phase">28.9% margin</span></div><div class="budget-caption"><span>Agreed fee</span><b>$36,000</b></div><div class="fee-bar" role="img" aria-label="36 thousand dollar fee: 18,400 costs to date, 7,200 forecast remaining costs, 10,400 projected profit"><span></span><span></span><span></span></div><div class="fee-legend"><div><small>Cost to date</small><b>$18,400</b></div><div><small>To complete</small><b>$7,200</b></div><div><small>Projected profit</small><b>$10,400</b></div></div></article>`}
function actions(){return `<article class="card tasks" data-card="actions">${head('Next actions','Task roadmap','Task roadmap')}${taskRows()}${bottom('View all tasks','Task roadmap')}</article>`}
function approvals(){return `<article class="card" data-card="approvals">${head('Pending approvals','Approval record','View record')}${[['material','Material palette','Needed before final specifications'],['coping','Pool coping selection','Client review · requested Sep 26']].map(([id,t,sub])=>`<label class="approval"><input type="checkbox" data-approval="${id}" ${state.approved.has(id)?'checked':''} aria-label="Record approval for ${t}"><span>${t}<small>${state.approved.has(id)?'Approval recorded by you · Undo by unchecking':sub}</small></span></label>`).join('')}<p>Already received a decision? Check it here.</p></article>`}
function journey(){return `<article class="card journey" data-card="journey">${head('Project journey','Task roadmap','View roadmap')}${[['✓','Discovery',9,9,'completed'],['!','Concept',11,13,'open'],['3','Design development',8,14,'current'],['4','Documentation',0,11,''],['5','Bidding',0,6,'']].map(([n,t,a,b,c])=>`<div class="journey-item ${c}"><span>${n}</span><span>${t}</span><i><b style="width:${a/b*100}%"></b></i><small>${a}/${b}</small></div>`).join('')}</article>`}
function week(){let work=state.fast?['Confirm palette; planting plan','Lighting & estimate','Assemble review set','Internal review','Client delivery']:['Confirm material palette','Planting & lighting','Update the estimate','Assemble review set','Client delivery'];return `<article class="card week-card" data-card="week"><div class="week-head"><h2>This week</h2><div class="segment"><button data-mode="spread" aria-pressed="${!state.fast}">Spread out</button><button data-mode="fast" aria-pressed="${state.fast}">Finish ASAP</button></div></div><div class="week">${['Mon','Tue','Wed','Thu','Fri'].map((d,i)=>`<div class="day ${i===0?'today':''}"><div><b>${d}</b><small>${[28,29,30,1,2][i]}</small></div><p>${work[i]}</p><small>${i===4?'Fixed date · Oct 2':['Alex','Maya','Alex','Maya'][i]}</small></div>`).join('')}</div></article>`}
function activity(){return `<article class="card" data-card="activity">${head('Latest activity','Activity history','View history')}<div class="activity-line"><span class="initial">M</span><div>Maya updated the planting plan.<small>Today · 10:42 am</small></div></div><div class="activity-line"><span class="initial">A</span><div>Alex revised the estimate.<small>Today · 9:15 am</small></div></div><div class="activity-line"><span class="initial">C</span><div>Last client email received.<small>Sep 25 · example connection</small></div></div></article>`}
function savings(){return `<article class="card" data-card="savings">${head('Closing the budget gap','View potential savings','Explore')}${[['Specification swaps','$9,400'],['Adjust selected finishes','$6,300'],['Consider a later phase','$6,400']].map(([t,n])=>`<div class="list-row"><span>${t}</span><b>${n}</b></div>`).join('')}<small>Example opportunities · not verified or additive.</small></article>`}
function bids(){return `<article class="card" data-card="bids">${head('Contractor bids','Bid comparison','Compare')}<p>Three bids ready to review.</p>${[['Contractor A','$498,000'],['Contractor B','$476,000'],['Contractor C','$521,000']].map(([t,n])=>`<div class="list-row"><span>${t}</span><b>${n}</b></div>`).join('')}</article>`}
const cards={brief,milestone,actions,budget,fee,journey,approvals,week,activity,savings,bids};
function render(){const s=state;document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.layout===s.layout));let list=s.selected[s.layout];const draw=ids=>ids.map(id=>cards[id]()).join('')||'<div class="empty">Choose a card in Customize home.</div>';if(s.layout==='g')$('#canvas').innerHTML=scene(true)+`<div class="board">${draw(list)}</div>`;if(s.layout==='h')$('#canvas').innerHTML=`<div class="journal-top">${brief(true)}${scene()}</div><div class="board journal-grid">${draw(list.filter(id=>id!=='brief'))}</div>`;if(s.layout==='i'){let active=s.tab==='today'?list:s.tab==='numbers'?['budget','fee']:['journey','activity'];$('#canvas').innerHTML=`<div class="quiet-top">${scene()}${milestone()}</div><div class="quiet-brief"><div><span class="eyebrow">AI PROJECT BRIEF</span><p>Keep the design moving. ${s.approved.size===2?'The material decisions are recorded.':'Two material decisions need a response.'} The estimate is 12% above budget, while the design fee remains profitable.</p></div><button data-info="Visual project brief">Explore the brief</button></div><div class="tabs" role="tablist" aria-label="Project focus">${[['today','Today'],['numbers','The numbers'],['progress','Progress']].map(([id,t])=>`<button role="tab" data-tab="${id}" aria-selected="${s.tab===id}">${t}</button>`).join('')}</div><div class="board quiet-grid" role="tabpanel">${draw(active.filter(id=>id!=='milestone'))}</div>`}$('#caption').textContent={g:'G · A visual welcome, then four useful cards.',h:'H · A project story, a working week, room to breathe.',i:'I · One focus at a time. Details when you need them.'}[s.layout];renderAlert();wireSlides();}
function renderAlert(){const visible=state.alerts&&state.timing==='now'&&!state.dismissed;$('#alert').innerHTML=visible?`<div class="notice" role="status"><p><b>Delivery needs a little attention.</b><small>Example forecast: 15 hours of work, 12 hours available.</small></p><button data-action="alerts">Preferences</button><button class="x" data-action="dismiss" aria-label="Dismiss delivery alert">×</button></div>`:''}
function wireSlides(){document.querySelectorAll('.slides').forEach(el=>{el.addEventListener('scroll',()=>{const i=Math.round(el.scrollLeft/el.clientWidth);document.querySelectorAll(`[data-slide="${el.id}"]`).forEach(b=>b.setAttribute('aria-current',+b.dataset.index===i))},{passive:true});el.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();el.scrollBy({left:el.clientWidth*(e.key==='ArrowRight'?1:-1),behavior:'smooth'})}})})}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').hidden=true,2300)}
function modal(title,content){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=content;if(!$('dialog').open)$('dialog').showModal()}
function preferences(){modal('Your alerts, your timing',`<p>Choose whether Home shows delivery-risk alerts and when you want to review them.</p><label><input id="alerts-enabled" type="checkbox" ${state.alerts?'checked':''}>Show delivery-risk alerts on Home</label><label class="field">When to show alerts<select id="alert-timing"><option value="now">When a new risk is detected</option><option value="daily">Daily summary · 9 am</option><option value="weekly">Weekly planning · Monday 9 am</option></select></label><label><input type="checkbox" checked disabled>Keep milestone dates visible</label><small>Preview only. Daily and weekly notifications need the future scheduler. “When a new risk is detected” shows an example you can dismiss.</small><br><button class="primary" data-action="save-alerts">Save preferences</button>`);$('#alert-timing').value=state.timing}
function customization(){const fixed=state.layout==='h'?['brief']:state.layout==='i'?['milestone']:[];modal('Make this home yours',`<p>${state.layout==='i'?'Choose cards for the Today tab. The numbers and Progress stay one click away.':'Choose a few useful cards. They stay aligned in rows.'}</p>${Object.entries(titles).filter(([id])=>!fixed.includes(id)).map(([id,t])=>`<label><input type="checkbox" data-card-toggle="${id}" ${state.selected[state.layout].includes(id)?'checked':''}>${t}</label>`).join('')}<button class="primary" data-action="close">Done</button><button data-action="reset-cards">Restore this layout</button>`)}
const info={
'About this study':'Three standalone Project Home directions. The project name, address and $450,000 budget follow the built-in sample. Images are design references. Other figures, tasks, staff, dates, activity and AI wording are illustrative. Nothing here changes your project or sends notifications. Preferences reset when you reload.',
'Brief sources':'In the finished app, the brief would link to the latest estimate, agreed fee, remaining effort, approval records and committed milestones. These slides use example figures. The diagrams show the underlying amounts, rather than an unexplained AI score.',
'Task roadmap':'This will open the project’s phase-by-phase tasks, owners, dependencies and completion evidence. Checking a priority task here updates this preview only; it does not stand in for a recorded client approval.',
'Approval record':'A check records that the designer received approval. The finished app should store who recorded it, when, the exact selection or revision, and optional email or document evidence. It is not an automatic client signature. You can uncheck an item in this study to undo it.',
'Financials':'The example agreed design fee is $36,000. Costs to date are $18,400, with $7,200 forecast to finish. Projected profit is $10,400, or 28.9%. This is an example forecast, not invoiced or collected cash.',
'Estimate':'Example estimate: $504,000 against a $450,000 landscape budget. The difference is $54,000, or 12%. The approved Home card will use the project’s calculated estimate.',
'View potential savings':'This opens cost-saving options tied to real quantities and specifications. This preview’s opportunities are illustrative and must not be added together as guaranteed savings.',
'Bid comparison':'This would open the three bids with scope, quantities, allowances and exclusions compared. The preview figures are examples.',
'Plans & files':'Open the existing project file library: current plans, prior revisions, photos and issued deliverables. This is a shortcut, not a second file store.',
'Ask Studio H':'The project assistant will answer in a lightbox using authorized project information. No AI service is connected to this standalone study.',
'Switch project':'In the app, this switches the entire Home page to the selected project. This design study has one sample project.'};
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.layout){state.layout=b.dataset.layout;location.hash=state.layout;render();return}if(b.dataset.tab){state.tab=b.dataset.tab;render();return}if(b.dataset.slide){let el=document.getElementById(b.dataset.slide);el.scrollTo({left:el.clientWidth*Number(b.dataset.index),behavior:'smooth'});return}if(b.dataset.carousel){const el=document.getElementById(b.dataset.carousel),n=el.children.length,i=Math.round(el.scrollLeft/el.clientWidth);el.scrollTo({left:el.clientWidth*((i+Number(b.dataset.step)+n)%n),behavior:'smooth'});return}if(b.dataset.mode){state.fast=b.dataset.mode==='fast';render();return}const action=b.dataset.action;if(action==='close')$('dialog').close();if(action==='cards')customization();if(action==='alerts')preferences();if(action==='dismiss'){state.dismissed=true;renderAlert()}if(action==='save-alerts'){state.alerts=$('#alerts-enabled').checked;state.timing=$('#alert-timing').value;state.dismissed=false;$('dialog').close();renderAlert();toast('Alert preference saved for this preview.')}if(action==='reset-cards'){state.selected[state.layout]=[...defaults[state.layout]];render();customization()}if(action==='save-milestone'){const d=Number($('#remaining-days').value);if(!Number.isInteger(d)||d<1||d>90){toast('Choose 1–90 days.');return}state.days=d;$('dialog').close();render()}if(b.dataset.info){const key=b.dataset.info;if(key==='Milestone settings'){modal('Milestone timing',`<p>Try the countdown colors: 1–2 days is muted rose, 3–7 powder blue, and more than a week soft green. The words and number stay visible.</p><label class="field">Days until delivery<input id="remaining-days" type="number" min="1" max="90" value="${state.days}"></label><button class="primary" data-action="save-milestone">Update preview</button>`)}else if(key==='Visual project brief'){modal('A visual project brief',brief(true).replaceAll('id="brief"','id="brief-modal"').replaceAll('data-slide="brief"','data-slide="brief-modal"').replaceAll('data-carousel="brief"','data-carousel="brief-modal"'));wireSlides()}else modal(key,`<p>${info[key]||`This would open ${key.toLowerCase()} for the current project. This standalone mockup keeps you on the preview.`}</p><button class="primary" data-action="close">Done</button>`)}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.task){t.checked?state.done.add(t.dataset.task):state.done.delete(t.dataset.task);const indexes={};document.querySelectorAll('.slides').forEach(s=>indexes[s.id]=Math.round(s.scrollLeft/s.clientWidth));render();Object.entries(indexes).forEach(([id,n])=>{const el=document.getElementById(id);if(el)el.scrollLeft=el.clientWidth*n});toast('Task updated in this preview.')}if(t.dataset.approval){t.checked?state.approved.add(t.dataset.approval):state.approved.delete(t.dataset.approval);render();toast(t.checked?'Approval recorded in preview. Uncheck to undo.':'Preview approval removed.')}if(t.dataset.cardToggle){let a=state.selected[state.layout];state.selected[state.layout]=t.checked?[...a,t.dataset.cardToggle]:a.filter(id=>id!==t.dataset.cardToggle);render()}});
window.addEventListener('hashchange',()=>{if(names[location.hash.slice(1)]){state.layout=location.hash.slice(1);render()}});render();
