/* Server-authoritative storage. Browser persistence is read only for one-time recovery. */
(()=>{'use strict';
// This experimental build cannot start on the live application origin.
if(!['localhost','127.0.0.1'].includes(location.hostname)){document.body.textContent='This isolated test build is not enabled on this host.';return;}
const endpoint='http://127.0.0.1:8788',nativeStorage=window.localStorage;
const memory=new Map();let token='',user=null,projectId='',etag='',prefsTag='',current=null,engineStore={},pending=false,dirty=false,saving=null,prefsDirty=false,timer,started=false,loading=false,conflict=false,lastBid=null,bidSignature='',engineSignature='',recoveryWarning='';
const shellKey='studioh_v2_workspace_v2',assetCache=new Map(),uploaded=new Set();
const prefsObject=()=>Object.fromEntries([...memory].filter(([k])=>k!==shellKey&&!/admin_key|token|password/i.test(k)));
const storage={getItem:k=>memory.get(String(k))??null,setItem(k,v){memory.set(String(k),String(v));if(k===shellKey){dirty=true;schedule()}else{prefsDirty=true;schedule()}},removeItem(k){memory.delete(String(k));prefsDirty=true;schedule()},clear(){memory.clear();prefsDirty=true;schedule()},key:i=>[...memory.keys()][i]??null,get length(){return memory.size}};
Object.defineProperty(window,'localStorage',{value:storage});
function status(text,error=false){const el=document.getElementById('v2-state');if(el){el.textContent=text;el.dataset.error=String(error)}document.getElementById('v2-cloud-retry')?.toggleAttribute('hidden',!error)}
async function api(path,options={}){const r=await fetch(endpoint+path,{...options,headers:{Authorization:'Bearer '+token,...options.headers},signal:AbortSignal.timeout(90000),cache:'no-store'});if(!r.ok&&r.status!==404){let d={};try{d=await r.json()}catch{}const e=Error(d.error||'Cloudflare could not save. Please retry.');e.status=r.status;throw e}return r}
const jsonPut=(path,data,tag)=>api(path,{method:'PUT',headers:{'Content-Type':'application/json',...(tag?{'If-Match':tag}:{'If-None-Match':'*'})},body:JSON.stringify(data)});
async function sha(b){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function decode64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function encode64(buf){const a=new Uint8Array(buf);let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s)}
async function media(value,raw=false){const marker=raw?'data:application/pdf;base64,'+value:value;if(assetCache.has(marker))return assetCache.get(marker);const m=marker.match(/^data:([^;,]*)(;base64)?,([\s\S]*)$/);if(!m)return value;const bytes=m[2]?decode64(m[3]):new TextEncoder().encode(decodeURIComponent(m[3]));if(bytes.byteLength>50*1024*1024)throw Error('Files must be under 50 MB.');const hash=await sha(bytes),key=projectId+'/'+hash;if(!uploaded.has(key)){await api('/projects/'+key.replace('/','/assets/'),{method:'PUT',headers:{'Content-Type':m[1]||'application/octet-stream'},body:bytes});uploaded.add(key)}const ref={__v2asset:hash,project:projectId,mime:m[1]||'application/octet-stream',raw};assetCache.set(marker,ref);return ref}
async function pack(value,key=''){if(typeof value==='string'){if(value.startsWith('data:'))return media(value);if(key==='pdf'&&value.length>100&&/^[a-zA-Z0-9+/=\s]+$/.test(value))return media(value,true);return value}if(Array.isArray(value))return Promise.all(value.map(v=>pack(v)));if(value&&typeof value==='object'){const out={};for(const [k,v]of Object.entries(value))out[k]=await pack(v,k);return out}return value}
async function unpack(value){if(value?.__v2asset){const r=await api(`/projects/${value.project||projectId}/assets/${value.__v2asset}`);if(!r.ok)throw Error('A saved project file could not be loaded.');const s=encode64(await r.arrayBuffer()),out=value.raw?s:`data:${value.mime};base64,${s}`;assetCache.set(value.raw?'data:application/pdf;base64,'+s:out,value);uploaded.add(projectId+'/'+value.__v2asset);return out}if(Array.isArray(value))return Promise.all(value.map(unpack));if(value&&typeof value==='object'){const out={};for(const [k,v]of Object.entries(value))out[k]=await unpack(v);return out}return value}
function parseValues(obj){return Object.fromEntries(Object.entries(obj||{}).filter(([k])=>!/(admin_key|password|token)/i.test(k)).map(([k,v])=>{try{return [k,{json:JSON.parse(v)}]}catch{return [k,{text:v}]}}))}
function stringifyValues(obj){return Object.fromEntries(Object.entries(obj||{}).map(([k,v])=>[k,'json'in v?JSON.stringify(v.json):v.text]))}
function schedule(){if(!started||loading||!token||conflict)return;clearTimeout(timer);status('Changes waiting to save…');timer=setTimeout(()=>flush().catch(()=>{}),1000)}
async function flush(){clearTimeout(timer);if(saving){await saving;if(dirty||prefsDirty)return flush();return}if(loading||!token||(!dirty&&!prefsDirty))return;if(conflict)throw Error('Resolve the server conflict before saving.');const task=(async()=>{await Promise.resolve();try{
 while(dirty||prefsDirty){status('Saving to Cloudflare…');if(dirty&&lastBid){dirty=false;const capture=structuredClone(lastBid),store={...engineStore};delete store.v2_project;delete store.studioh_bid_last;
 const data=await pack({schema:1,projectId,name:capture.S?.pi?.project||capture.S?.pi?.client||'Untitled project',bid:capture,engine:parseValues(store),workspace:memory.get(shellKey)||'',updated:new Date().toISOString()});
 try{const r=await jsonPut('/projects/'+projectId,data,etag);etag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''));current=data;memory.set('studioh_v2_last_project',projectId);prefsDirty=true}catch(e){dirty=true;throw e}}
 else if(dirty&&!lastBid){dirty=false}
 if(prefsDirty){prefsDirty=false;try{const data=await pack(parseValues(prefsObject()));const r=await jsonPut('/preferences',data,prefsTag);prefsTag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''))}catch(e){prefsDirty=true;throw e}}
 }status('Saved to Cloudflare');window.dispatchEvent(new Event('v2-cloud-saved'));
 }catch(e){if(e.status===409)conflict=true;status(e.status===409?'Save conflict · your edits are still open':'Not saved · '+e.message,true);if(e.status===401)showGate('Your sign-in expired. Reconnect to save the edits still open in this tab.');window.v2Preview?.notice(e.message);throw e}finally{saving=null}})();saving=task;return task}
async function readProject(id){const old=projectId;projectId=id;engineSignature='';assetCache.clear();uploaded.clear();const r=await api('/projects/'+id);if(r.status===404){projectId=old;return false}const packed=await r.json();const data=await unpack(packed);etag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''));current=packed;engineStore=stringifyValues(data.engine);lastBid=data.bid;bidSignature=signature(lastBid);memory.set(shellKey,data.workspace||'{}');memory.set('studioh_v2_last_project',id);prefsDirty=true;return true}
async function openProject(id){await flush();loading=true;try{if(!await readProject(id))throw Error('Project not found.');window.v2Workspace?.restoreCloud();await v2Preview.reload();document.getElementById('v2-projects').close();v2Preview.show('projectinfo','Project info');status('Opened from Cloudflare')}finally{loading=false;schedule()}}
async function createFromBid(bid,name,options={}){await flush();projectId=crypto.randomUUID();etag='';assetCache.clear();uploaded.clear();engineStore=options.engine||{};engineSignature='';lastBid=structuredClone(bid);bidSignature=signature(lastBid);if(name)lastBid.S.pi.project=name;memory.set(shellKey,options.workspace||'{}');window.v2Workspace?.restoreCloud();dirty=true;await flush();loading=true;try{await v2Preview.reload()}finally{loading=false}return projectId}
async function list(){const r=await api('/projects');return (await r.json()).projects}
async function showProjects(){const box=document.getElementById('v2-cloud-projects');box.textContent='Loading server projects…';try{box.replaceChildren(...(await list()).sort((a,b)=>String(b.updated).localeCompare(String(a.updated))).map(p=>{const b=document.createElement('button');b.textContent=p.name;b.onclick=()=>openProject(p.id).catch(e=>v2Preview.notice(e.message));return b}));if(!box.children.length)box.textContent='Your first project will appear after it saves.'}catch(e){box.textContent=e.message}}
function signature(bid){return JSON.stringify(bid,(k,v)=>['savedAt','view'].includes(k)?undefined:v)}
function saveBid(bid){const sig=signature(bid);lastBid=bid;if(sig===bidSignature)return;bidSignature=sig;dirty=true;schedule()}
function storeEngine(data){const copy={...data};delete copy.v2_project;delete copy.studioh_bid_last;const sig=JSON.stringify(copy);const changed=engineSignature&&sig!==engineSignature;engineSignature=sig;engineStore=data;if(changed){dirty=true;schedule()}}
async function migrateLegacy(){
 const copies=[];const databases=typeof indexedDB.databases==='function'?await indexedDB.databases():[];
 if(databases.some(d=>d.name==='studioh-v2-projects')){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('studioh-v2-projects');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{if(db.objectStoreNames.contains('projects')){const tx=db.transaction('projects'),os=tx.objectStore('projects');const entries=await Promise.all([new Promise((resolve,reject)=>{const r=os.getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),new Promise((resolve,reject)=>{const r=os.getAllKeys();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})]);entries[0].forEach((store,i)=>copies.push({store,key:entries[1][i]}))}}finally{db.close()}}
 try{const store=JSON.parse(nativeStorage.getItem('studioh_v2_preview_store_v1')||'null');if(store)copies.push({store,key:'older preview'})}catch{}
 const localPrefs={};for(let i=0;i<nativeStorage.length;i++){const k=nativeStorage.key(i);if(k.startsWith('studioh_v2_')&&!/preview_store|last_project/.test(k))localPrefs[k]=nativeStorage.getItem(k)}
 if(!copies.length&&!Object.keys(localPrefs).length)return false;
 for(const [k,v]of Object.entries(localPrefs))if(k!==shellKey&&!memory.has(k))memory.set(k,v);
 prefsDirty=true;let recovered='',incomplete=false;const seen=new Set();
 for(const {store,key} of copies.sort((a,b)=>(a.key==='current')-(b.key==='current'))){let bid;try{bid=JSON.parse(store?.v2_project||store?.studioh_bid_last||'null')}catch{}if(!bid?.S){if(store&&Object.keys(store).length)incomplete=true;continue;}
  const digest=await sha(new TextEncoder().encode(JSON.stringify(store))),id='recovered-'+digest.slice(0,24);if(seen.has(id))continue;seen.add(id);
  const found=await api('/projects/'+id);if(found.status===404){projectId=id;etag='';assetCache.clear();uploaded.clear();engineStore=store;lastBid=bid;lastBid.S.pi.project=(lastBid.S.pi?.project||'Project')+' · recovered '+key;bidSignature=signature(lastBid);memory.set(shellKey,key==='current'?(localPrefs[shellKey]||'{}'):'{}');dirty=true;await flush()}
  const check=await api('/projects/'+id);if(!check.ok||(await check.json()).projectId!==id)throw Error('Recovery could not be verified. Browser copies have been retained.');recovered=id;
 }
 if(recovered)await readProject(recovered);await flush();
 if(incomplete){recoveryWarning='An older browser backup needs recovery. It is preserved on this device; your server workspace is available.';return true;}
 // Migration is copy-only in this test version. Never delete legacy or V1 stores.
 // Keep source copies throughout the test phase, even after server read-back.
 return true;
}
async function recover(){await flush();const found=await migrateLegacy();if(!found)throw Error('No browser-only V2 work remains to recover.');window.v2Workspace?.restoreCloud();loading=true;try{await v2Preview.reload()}finally{loading=false}status('Recovered project saved to Cloudflare')}
async function start(sessionToken){token=sessionToken;user=await (await api('/session')).json();document.getElementById('v2-cloud-gate')?.remove();if(started){await flush();return}loading=true;
 const prefs=await api('/preferences');if(prefs.ok){prefsTag=(prefs.headers.get('X-StudioH-Revision')||prefs.headers.get('ETag')?.replace(/^W\//,''));const data=await unpack(await prefs.json()); // Preferences may contain image framing, not project media.
 for(const [k,v]of Object.entries(stringifyValues(data)))memory.set(k,v)}
 const last=memory.get('studioh_v2_last_project');if(!last||!await readProject(last)){const projects=await list();if(projects.length)await readProject(projects.sort((a,b)=>String(b.updated).localeCompare(String(a.updated)))[0].id);else{projectId=crypto.randomUUID();etag=''}}
 loading=false;started=true;try{await migrateLegacy()}catch(e){recoveryWarning='Browser recovery is unfinished: '+e.message}await boot();status(etag?'Opened from Cloudflare':'New project · server saving enabled');if(recoveryWarning){const note=document.createElement('p');note.id='v2-recovery-warning';note.setAttribute('role','status');note.textContent=recoveryWarning;document.getElementById('v2-global').append(note);}
}
async function boot(){const old=document.getElementById('v2-app-bootstrap'),script=document.createElement('script');script.textContent=old.textContent;document.body.append(script);const version=document.querySelector('meta[name=studioh-version]').content;for(const name of ['shell','icons','libraries','workspace','experience'])await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='src/'+name+'.js?v='+version;s.onload=resolve;s.onerror=reject;document.body.append(s)});document.getElementById('sh-v2').inert=false;
 const controls=document.getElementById('v2-global');const retry=document.createElement('button');retry.id='v2-cloud-retry';retry.hidden=true;retry.textContent='Resolve save';retry.onclick=()=>{if(conflict){const d=document.createElement('dialog');d.innerHTML='<h2>Another device saved changes</h2><p>Your edits are still open. Save them as a separate project to keep both versions.</p><button data-copy>Save my edits as a new project</button><button data-close>Keep reviewing</button>';d.querySelector('[data-copy]').onclick=async()=>{conflict=false;etag='';projectId=crypto.randomUUID();uploaded.clear();assetCache.clear();dirty=true;prefsTag=(await api('/preferences')).headers.get('X-StudioH-Revision')||'';try{await flush();d.close()}catch{}};d.querySelector('[data-close]').onclick=()=>d.close();document.body.append(d);d.showModal()}else flush().catch(()=>{})};controls.append(retry);
 const signout=document.createElement('button');signout.textContent='Sign out';signout.onclick=async()=>{try{await flush();await api('/logout',{method:'POST'});const url=new URL(location.href);url.searchParams.set('signedOut','1');location.href=url.href}catch{}};controls.append(signout);
 document.getElementById('v2-restore-previous').textContent='Recover previous browser-only work';document.getElementById('v2-restore-previous').onclick=()=>recover().catch(e=>v2Preview.notice(e.message));
 const legacyList=document.getElementById('v2-cloud-list').onclick;const legacyButton=document.createElement('button');legacyButton.textContent='Import an existing V1 project';legacyButton.onclick=legacyList;document.getElementById('v2-cloud-list').after(legacyButton);document.getElementById('v2-cloud-list').textContent='Browse server projects';document.getElementById('v2-cloud-list').onclick=showProjects;
}
let authWindow,authState;
function showGate(message=''){let gate=document.getElementById('v2-cloud-gate');if(!gate){gate=document.createElement('section');gate.id='v2-cloud-gate';gate.innerHTML='<div><span>STUDIO H · SERVER WORKSPACE</span><h1>Your work belongs with your project.</h1><p>Connect your studio to open and save projects, photos, files and preferences on Cloudflare.</p><button>Connect Studio H</button><p role="status"></p><small>Isolated storage test. Existing browser copies are preserved; this does not connect to live projects.</small></div>';document.body.append(gate);gate.querySelector('button').onclick=()=>{authState=crypto.randomUUID();authWindow=window.open(endpoint+'/authorize?state='+authState,'studioh-cloud-signin','popup,width=520,height=680');if(!authWindow)gate.querySelector('[role=status]').textContent='Allow the sign-in popup, then choose Connect again.'}}gate.querySelector('[role=status]').textContent=message}
window.addEventListener('message',e=>{if(e.origin!==endpoint||e.source!==authWindow||e.data?.state!==authState||!e.data.studiohCloudSession)return;start(e.data.studiohCloudSession).catch(e=>showGate(e.message))});
window.addEventListener('beforeunload',e=>{if(dirty||prefsDirty||saving){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>{if(dirty||prefsDirty)flush().catch(()=>{})});
window.v2Cloud={start,flush,saveBid,storeEngine,openProject,createFromBid,list,recover,get seed(){return {...engineStore,...(lastBid?{v2_project:JSON.stringify(lastBid)}:{})}},get projectId(){return projectId},get authenticated(){return !!user},get dirty(){return dirty||prefsDirty},status};
document.getElementById('sh-v2').inert=true;showGate();
// No automatic V1 credential reuse in the isolated test build.
})();
