/* Server-authoritative storage. Browser persistence is read only for one-time recovery. */
(()=>{'use strict';
const endpoint='https://studioh-v2-storage.warwick-cca.workers.dev',nativeStorage=window.localStorage;
const memory=new Map();let token='',user=null,projectId='',etag='',prefsTag='',current=null,engineStore={},pending=false,dirty=false,saving=null,prefsDirty=false,timer,started=false,loading=false,conflict=false,lastBid=null,bidSignature='',engineSignature='',recoveryWarning='';
const demoMode=new URLSearchParams(location.search).get('demo')==='1';
const sessionKey='studioh_v2_session_tab',rememberKey='studioh_v2_login_session';
function rememberSession(value){sessionStorage.setItem(sessionKey,value);nativeStorage.setItem(rememberKey,value)}
function forgetSession(){sessionStorage.removeItem(sessionKey);nativeStorage.removeItem(rememberKey)}
// A recovery session travels in the URL fragment, never in a request or referrer.
const recoverySession=new URLSearchParams(location.hash.slice(1)).get('session');
if(new URLSearchParams(location.search).has('owner-access')&&/^[a-f0-9]{64}$/.test(recoverySession||'')){sessionStorage.setItem(sessionKey,recoverySession);const clean=new URL(location.href);clean.hash='';clean.searchParams.delete('owner-access');history.replaceState(null,'',clean.href)}
let projectAccess='owner',capabilities={emailEnabled:false};
let seedReady=Promise.resolve();
const assetReads=new Map();let assetActive=0;const assetQueue=[];
async function readAsset(path){if(assetActive>=8)await new Promise(resolve=>assetQueue.push(resolve));assetActive++;try{const r=await api(path);if(!r.ok)throw Error('A saved project file could not be loaded.');return await r.arrayBuffer()}finally{assetActive--;assetQueue.shift()?.()}}
const release=document.querySelector('meta[name=studioh-version]').content;
const engineHTML=fetch('engine.html?v='+encodeURIComponent(release)).then(r=>{if(!r.ok)throw Error('Project tools could not load');return r.text()});engineHTML.catch(()=>{});
const shellKey='studioh_v2_workspace_v2',assetCache=new Map(),uploaded=new Set();
const prefsObject=()=>Object.fromEntries([...memory].filter(([k])=>k!==shellKey&&!/admin_key|token|password|login_session|session_tab/i.test(k)));
const storage={getItem:k=>memory.get(String(k))??null,setItem(k,v){if(memory.get(String(k))===String(v))return;memory.set(String(k),String(v));if(k===shellKey){dirty=true;schedule()}else{prefsDirty=true;schedule()}},removeItem(k){memory.delete(String(k));prefsDirty=true;schedule()},clear(){memory.clear();prefsDirty=true;schedule()},key:i=>[...memory.keys()][i]??null,get length(){return memory.size}};
Object.defineProperty(window,'localStorage',{value:storage});
function status(text,error=false){const el=document.getElementById('v2-state');if(el){el.textContent=text;el.dataset.error=String(error)}document.getElementById('v2-cloud-retry')?.toggleAttribute('hidden',!error)}
async function api(path,options={}){if(demoMode)throw Error('The demo does not access private cloud projects.');const r=await fetch(endpoint+path,{...options,headers:{Authorization:'Bearer '+token,...options.headers},signal:AbortSignal.timeout(90000),cache:'no-store'});if(!r.ok&&r.status!==404){let d={};try{d=await r.json()}catch{}const e=Error(d.error||'Cloudflare could not save. Please retry.');e.status=r.status;throw e}return r}
const jsonPut=(path,data,tag)=>api(path,{method:'PUT',headers:{'Content-Type':'application/json',...(tag?{'If-Match':tag}:{'If-None-Match':'*'})},body:JSON.stringify(data)});
async function sha(b){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function decode64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function encode64(buf){const a=new Uint8Array(buf);let s='';for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s)}
async function media(value,raw=false){const marker=raw?'data:application/pdf;base64,'+value:value;if(assetCache.has(marker))return assetCache.get(marker);const m=marker.match(/^data:([^;,]*)(;base64)?,([\s\S]*)$/);if(!m)return value;const bytes=m[2]?decode64(m[3]):new TextEncoder().encode(decodeURIComponent(m[3]));if(bytes.byteLength>50*1024*1024)throw Error('Files must be under 50 MB.');const hash=await sha(bytes),key=projectId+'/'+hash;if(!uploaded.has(key)){await api('/projects/'+key.replace('/','/assets/'),{method:'PUT',headers:{'Content-Type':m[1]||'application/octet-stream'},body:bytes});uploaded.add(key)}const ref={__v2asset:hash,project:projectId,mime:m[1]||'application/octet-stream',raw};assetCache.set(marker,ref);return ref}
async function compact(value,key){if(!key||['S','bid','project','workspace'].includes(key))return value;const text=JSON.stringify(value);if(text.length<128000)return value;const bytes=new TextEncoder().encode(text);const compressed=await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();const ref=await media('data:application/gzip;base64,'+encode64(compressed));return {...ref,json:true,encoding:'gzip'}}
async function pack(value,key=''){if(typeof value==='string'){if(value.startsWith('data:'))return media(value);if(key==='pdf'&&value.length>100&&/^[a-zA-Z0-9+/=\s]+$/.test(value))return media(value,true);return value}if(Array.isArray(value))return compact(await Promise.all(value.map(v=>pack(v))),key);if(value&&typeof value==='object'){const out={};for(const [k,v]of Object.entries(value))out[k]=await pack(v,k);return compact(out,key)}return value}
async function unpack(value){if(value?.__v2asset){const key=(value.project||projectId)+'/'+value.__v2asset+'/'+!!value.json+'/'+!!value.raw;if(!assetReads.has(key)){const task=unpackAsset(value);assetReads.set(key,task);task.catch(()=>assetReads.delete(key))}return structuredClone(await assetReads.get(key))}if(Array.isArray(value))return Promise.all(value.map(unpack));if(value&&typeof value==='object')return Object.fromEntries(await Promise.all(Object.entries(value).map(async([k,v])=>[k,await unpack(v)])));return value}
async function unpackAsset(value){const bytes=await readAsset(`/projects/${value.project||projectId}/assets/${value.__v2asset}`);if(value.json){const plain=value.encoding==='gzip'?await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text():new TextDecoder().decode(bytes);assetCache.set('data:application/gzip;base64,'+encode64(bytes),value);uploaded.add((value.project||projectId)+'/'+value.__v2asset);return plain.includes('"__v2asset"')?unpack(JSON.parse(plain)):JSON.parse(plain)}const s=encode64(bytes),out=value.raw?s:`data:${value.mime};base64,${s}`;assetCache.set(value.raw?'data:application/pdf;base64,'+s:out,value);uploaded.add(projectId+'/'+value.__v2asset);return out}
function parseValues(obj){return Object.fromEntries(Object.entries(obj||{}).filter(([k])=>!/(admin_key|password|token)/i.test(k)).map(([k,v])=>{try{return [k,{json:JSON.parse(v)}]}catch{return [k,{text:v}]}}))}
function stringifyValues(obj){return Object.fromEntries(Object.entries(obj||{}).map(([k,v])=>[k,'json'in v?JSON.stringify(v.json):v.text]))}
function schedule(){if(demoMode){dirty=false;prefsDirty=false;status('Demo · changes last until you leave this page');return}if(projectAccess==='viewer'){dirty=false;prefsDirty=false;status('View only');return}if(!started||loading||!token||conflict||(!dirty&&!prefsDirty))return;clearTimeout(timer);status('Changes waiting to save…');timer=setTimeout(()=>flush().catch(()=>{}),1000)}
async function flush(){if(demoMode){dirty=false;prefsDirty=false;status('Demo · changes last until you leave this page');return}if(projectAccess==='viewer'){dirty=false;prefsDirty=false;status('View only');return}clearTimeout(timer);if(saving){await saving;if(dirty||prefsDirty)return flush();return}if(loading||!token||(!dirty&&!prefsDirty))return;if(conflict)throw Error('Resolve the server conflict before saving.');const task=(async()=>{await Promise.resolve();try{
 while(dirty||prefsDirty){status('Saving to Cloudflare…');if(dirty&&lastBid){dirty=false;const capture=structuredClone(lastBid),store={...engineStore};delete store.v2_project;delete store.studioh_bid_last;
 const data=await pack({schema:1,projectId,name:capture.S?.pi?.project||capture.S?.pi?.client||'Untitled project',bid:capture,engine:parseValues(store),workspace:JSON.parse(memory.get(shellKey)||'{}'),updated:new Date().toISOString()});
 try{const r=await jsonPut('/projects/'+projectId,data,etag);etag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''));current=data;memory.set('studioh_v2_last_project',projectId);prefsDirty=true}catch(e){dirty=true;throw e}}
 else if(dirty&&!lastBid){dirty=false}
 if(prefsDirty){prefsDirty=false;try{const data=await pack(parseValues(prefsObject()));const r=await jsonPut('/preferences',data,prefsTag);prefsTag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''))}catch(e){prefsDirty=true;throw e}}
 }status('Saved to Cloudflare');window.dispatchEvent(new Event('v2-cloud-saved'));
 }catch(e){if(e.status===409)conflict=true;status(e.status===409?'Save conflict · your edits are still open':'Not saved · '+e.message,true);if(e.status===401)showGate('Your sign-in expired. Reconnect to save the edits still open in this tab.');window.v2Preview?.notice(e.message);throw e}finally{saving=null}})();saving=task;return task}
async function readProject(id,progressive=false){const old=projectId,prior={access:projectAccess,etag,current,workspace:memory.get(shellKey),last:memory.get('studioh_v2_last_project'),prefsDirty};projectId=id;engineSignature='';assetCache.clear();uploaded.clear();let r;try{r=await api('/projects/'+id)}catch(e){projectId=old;throw e}if(r.status===404){projectId=old;return false}const packed=await r.json();projectAccess=r.headers.get('X-StudioH-Access')||'owner';document.body.dataset.projectAccess=projectAccess;
 const workspace=await unpack(packed.workspace||{});memory.set(shellKey,typeof workspace==='string'?workspace:JSON.stringify(workspace));
 etag=(r.headers.get('X-StudioH-Revision')||r.headers.get('ETag')?.replace(/^W\//,''));current=packed;
 if(memory.get('studioh_v2_last_project')!==id){memory.set('studioh_v2_last_project',id);prefsDirty=true}
 const hydrate=(async()=>{const [bid,engine]=await Promise.all([unpack(packed.bid),unpack(packed.engine)]);engineStore=stringifyValues(engine);lastBid=bid;bidSignature=signature(lastBid);performance.mark('studioh-project-ready')})();
 if(progressive){seedReady=hydrate;seedReady.catch(e=>{status('Project could not finish loading. Please retry.',true);showGate(e.message)});return true}
 try{await hydrate}catch(e){projectId=old;projectAccess=prior.access;document.body.dataset.projectAccess=projectAccess;etag=prior.etag;current=prior.current;prefsDirty=prior.prefsDirty;prior.workspace===undefined?memory.delete(shellKey):memory.set(shellKey,prior.workspace);prior.last===undefined?memory.delete('studioh_v2_last_project'):memory.set('studioh_v2_last_project',prior.last);throw e}return true}

async function openProject(id){await v2Preview.capture();await flush();loading=true;try{if(!await readProject(id))throw Error('Project not found.');window.v2Workspace?.restoreCloud();await v2Preview.reload();document.getElementById('v2-projects').close();v2Preview.show('projectinfo','Project info');status('Opened from Cloudflare')}finally{loading=false;schedule()}}
async function createFromBid(bid,name,options={}){if(user&&user.role!=='admin')throw Error('Only the workspace owner can create projects.');await v2Preview.capture();await flush();projectId=crypto.randomUUID();etag='';assetCache.clear();uploaded.clear();engineStore=options.engine||{};engineSignature='';lastBid=structuredClone(bid);bidSignature=signature(lastBid);if(name)lastBid.S.pi.project=name;memory.set(shellKey,options.workspace||'{}');window.v2Workspace?.restoreCloud();dirty=true;await flush();loading=true;try{await v2Preview.reload()}finally{loading=false}return projectId}
async function list(){if(demoMode)return [];const r=await api('/projects');return (await r.json()).projects}
async function showProjects(){const box=document.getElementById('v2-cloud-projects');box.textContent='Loading server projects…';try{box.replaceChildren(...(await list()).sort((a,b)=>String(b.updated).localeCompare(String(a.updated))).map(p=>{const b=document.createElement('button');b.textContent=p.name;b.onclick=()=>openProject(p.id).catch(e=>v2Preview.notice(e.message));return b}));if(!box.children.length)box.textContent='Your first project will appear after it saves.'}catch(e){box.textContent=e.message}}
function signature(bid){return JSON.stringify(bid,(k,v)=>['savedAt','view'].includes(k)?undefined:v)}
function saveBid(bid){const sig=signature(bid);lastBid=bid;if(sig===bidSignature)return;bidSignature=sig;dirty=true;schedule()}
function storeEngine(data){const copy={...data};delete copy.v2_project;delete copy.studioh_bid_last;const sig=JSON.stringify(copy);const changed=engineSignature&&sig!==engineSignature;engineSignature=sig;engineStore=data;if(changed){dirty=true;schedule()}}
async function migrateLegacy(){
 const copies=[];const databases=typeof indexedDB.databases==='function'?await indexedDB.databases():[];
 if(databases.some(d=>d.name==='studioh-v2-projects')){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('studioh-v2-projects');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{if(db.objectStoreNames.contains('projects')){const tx=db.transaction('projects'),os=tx.objectStore('projects');const entries=await Promise.all([new Promise((resolve,reject)=>{const r=os.getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}),new Promise((resolve,reject)=>{const r=os.getAllKeys();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})]);entries[0].forEach((store,i)=>copies.push({store,key:entries[1][i]}))}}finally{db.close()}}
 try{const store=JSON.parse(nativeStorage.getItem('studioh_v2_preview_store_v1')||'null');if(store)copies.push({store,key:'older preview'})}catch{}
 const localPrefs={};for(let i=0;i<nativeStorage.length;i++){const k=nativeStorage.key(i);if(k.startsWith('studioh_v2_')&&!/preview_store|last_project|login_session|session_tab/.test(k))localPrefs[k]=nativeStorage.getItem(k)}
 if(!copies.length&&!Object.keys(localPrefs).length)return false;
 for(const [k,v]of Object.entries(localPrefs))if(k!==shellKey&&!memory.has(k))memory.set(k,v);
 prefsDirty=true;let recovered='',incomplete=false;const seen=new Set();const previouslyRecovered=new Set(JSON.parse(memory.get('studioh_v2_recovered')||'[]'));
 for(const {store,key} of copies.sort((a,b)=>(a.key==='current')-(b.key==='current'))){let bid;try{bid=JSON.parse(store?.v2_project||store?.studioh_bid_last||'null')}catch{}if(!bid?.S){if(store&&Object.keys(store).length)incomplete=true;continue;}
  const digest=await sha(new TextEncoder().encode(JSON.stringify(store))),id='recovered-'+digest.slice(0,24);if(seen.has(id)||previouslyRecovered.has(id))continue;seen.add(id);
  const found=await api('/projects/'+id);if(found.status===404){projectId=id;etag='';assetCache.clear();uploaded.clear();engineStore=store;lastBid=bid;lastBid.S.pi.project=(lastBid.S.pi?.project||'Project')+' · recovered '+key;bidSignature=signature(lastBid);memory.set(shellKey,key==='current'?(localPrefs[shellKey]||'{}'):'{}');dirty=true;await flush()}
  const check=await api('/projects/'+id);if(!check.ok||(await unpack(await check.json())).projectId!==id)throw Error('Recovery could not be verified. Browser copies have been retained.');recovered=id;previouslyRecovered.add(id);memory.set('studioh_v2_recovered',JSON.stringify([...previouslyRecovered]));prefsDirty=true;
 }
 if(recovered)await readProject(recovered);await flush();
 if(incomplete){recoveryWarning='An older browser backup needs recovery. It is preserved on this device; your server workspace is available.';return true;}
 // Keep pre-migration browser copies as recovery backups; no new device writes.
 return true;
}
async function recover(){await flush();const found=await migrateLegacy();if(!found)throw Error('No browser-only V2 work remains to recover.');window.v2Workspace?.restoreCloud();loading=true;try{await v2Preview.reload()}finally{loading=false}status('Recovered project saved to Cloudflare')}
async function start(sessionToken){performance.mark('studioh-start');showOpening();token=sessionToken;let prefs;try{const results=await Promise.all([api('/session'),api('/preferences')]);user=await results[0].json();prefs=results[1];try{const c=await api('/auth/config');if(c.ok)capabilities=await c.json()}catch{}rememberSession(token)}catch(e){forgetSession();showGate(e.status===401?'Please sign in to continue.':e.message);throw e}if(started){await flush();document.getElementById('v2-cloud-gate')?.remove();return}loading=true;
 if(prefs.ok){prefsTag=(prefs.headers.get('X-StudioH-Revision')||prefs.headers.get('ETag')?.replace(/^W\//,''));const data=await unpack(await prefs.json()); // Preferences may contain image framing, not project media.
 for(const [k,v]of Object.entries(stringifyValues(data)))memory.set(k,v)}
 const last=memory.get('studioh_v2_last_project');if(!last||!await readProject(last,true)){const projects=await list();if(projects.length)await readProject(projects.sort((a,b)=>String(b.updated).localeCompare(String(a.updated)))[0].id,true);else{if(user.role!=='admin'){showGate('No shared projects are available for this email. Ask the owner for an invitation.');return}projectId=crypto.randomUUID();etag=''}}
 started=true;if(!current){loading=false;try{await migrateLegacy()}catch(e){recoveryWarning='Browser recovery is unfinished: '+e.message}}performance.mark('studioh-data-ready');await boot();performance.mark('studioh-workspace-ready');document.documentElement.removeAttribute('data-cloud-opening');document.getElementById('v2-cloud-gate')?.remove();status(etag?'Opening project…':'New project · server saving enabled');seedReady.then(()=>{loading=false;status(etag?'Opened from Cloudflare':'Server saving enabled');schedule()}).catch(()=>{});
}
async function boot(){const old=document.getElementById('v2-app-bootstrap'),script=document.createElement('script');script.textContent=old.textContent;document.body.append(script);const version=document.querySelector('meta[name=studioh-version]').content;for(const name of ['shell','icons','libraries','project-home','workspace','experience','top-controls','button-cleanup'])await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='src/'+name+'.js?v='+version;s.onload=resolve;s.onerror=reject;document.body.append(s)});document.getElementById('sh-v2').inert=false;
 const controls=document.getElementById('v2-global');const retry=document.createElement('button');retry.id='v2-cloud-retry';retry.hidden=true;retry.textContent='Resolve save';retry.onclick=()=>{if(conflict){const d=document.createElement('dialog');d.innerHTML='<h2>Another device saved changes</h2><p>Your edits are still open. Save them as a separate project to keep both versions.</p><button data-copy>Save my edits as a new project</button><button data-close>Keep reviewing</button>';d.querySelector('[data-copy]').onclick=async()=>{conflict=false;etag='';projectId=crypto.randomUUID();uploaded.clear();assetCache.clear();dirty=true;prefsTag=(await api('/preferences')).headers.get('X-StudioH-Revision')||'';try{await flush();d.close()}catch{}};d.querySelector('[data-close]').onclick=()=>d.close();document.body.append(d);d.showModal()}else flush().catch(()=>{})};document.getElementById('v2-state').after(retry);
 const signout=document.createElement('button');signout.id='v2-cloud-signout';signout.textContent=demoMode?'Sign in':'Sign out';signout.onclick=async()=>{if(demoMode){const url=new URL(location.href);url.searchParams.delete('demo');location.href=url.href;return}try{await v2Preview.capture();await flush();await api('/logout',{method:'POST'});forgetSession();const url=new URL(location.href);url.searchParams.set('signedOut','1');location.href=url.href}catch{}};controls.append(signout);
 document.getElementById('v2-restore-previous').textContent='Recover previous browser-only work';document.getElementById('v2-restore-previous').onclick=()=>recover().catch(e=>v2Preview.notice(e.message));
 const legacyList=document.getElementById('v2-cloud-list').onclick;const legacyButton=document.createElement('button');legacyButton.textContent='Import an existing V1 project';legacyButton.onclick=legacyList;document.getElementById('v2-cloud-list').after(legacyButton);document.getElementById('v2-cloud-list').textContent='Browse server projects';document.getElementById('v2-cloud-list').onclick=showProjects;const share=document.createElement('button');share.textContent='Share this project';share.hidden=demoMode||user?.role!=='admin'||!capabilities.emailEnabled;share.onclick=showSharing;document.getElementById('v2-cloud-list').after(share);if(demoMode){legacyButton.hidden=true;document.getElementById('v2-restore-previous').hidden=true;document.getElementById('v2-cloud-list').hidden=true;}
}

async function showSharing(){await v2Preview.capture();await flush();const id=projectId;let box=document.getElementById('v2-share-dialog');if(!box){box=document.createElement('dialog');box.id='v2-share-dialog';document.body.append(box)}box.innerHTML='<h2>Share this project</h2><p>Invite someone by email. They will verify their email to open this project.</p><form><label>Email<input type="email" name="email" required autocomplete="email"></label><label>Access<select name="role"><option value="viewer">View only</option><option value="editor">Can edit</option></select></label><button>Send invitation</button></form><p role="status"></p><div data-invitations></div><button data-close>Close</button>';box.querySelector('[data-close]').onclick=()=>box.close();box.showModal();const message=t=>box.querySelector('[role=status]').textContent=t;async function update(){const r=await api('/projects/'+id+'/sharing');const d=await r.json();const list=box.querySelector('[data-invitations]');list.replaceChildren();for(const row of d.invitations){const p=document.createElement('p');p.textContent=row.email+' · '+(row.role==='editor'?'Can edit':'View only')+' ';const revoke=document.createElement('button');revoke.textContent='Remove access';revoke.onclick=async()=>{try{await api('/projects/'+id+'/sharing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:row.email,role:'revoke'})});await update();message('Access removed.')}catch(e){message(e.message)}};p.append(revoke);list.append(p)}}box.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;message('Sending invitation…');try{const f=new FormData(e.target);await api('/projects/'+id+'/sharing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),role:f.get('role')})});message('Invitation sent.');e.target.reset();await update()}catch(e){message(e.message)}finally{b.disabled=false}};try{await update()}catch(e){message(e.message)}}

async function beginSignIn(){
 const r=await fetch(endpoint+'/auth/config',{cache:'no-store'}),cfg=await r.json();
 if(!cfg.managedLogin){if(cfg.emailEnabled){authState=crypto.randomUUID();authWindow=window.open(endpoint+'/authorize?state='+authState,'studioh-cloud-signin','popup,width=520,height=680');if(!authWindow)throw Error('Allow the sign-in window and try again.');return}throw Error('Email login is not ready yet. Please try again shortly.');}
 const bytes=()=>[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');
 const verifier=bytes(),state=bytes(),challenge=await sha(new TextEncoder().encode(verifier));
 sessionStorage.setItem('studioh_login_attempt',JSON.stringify({verifier,state}));
 location.assign(endpoint+'/login?state='+state+'&challenge='+challenge);
}
async function finishSignIn(code,state){
 const clean=new URL(location.href);clean.searchParams.delete('login-code');clean.searchParams.delete('state');history.replaceState(null,'',clean.href);
 let attempt;try{attempt=JSON.parse(sessionStorage.getItem('studioh_login_attempt')||'null')}catch{}
 if(!attempt||attempt.state!==state)throw Error('Please sign in again in this tab.');
 const r=await fetch(endpoint+'/auth/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,state,verifier:attempt.verifier})});
 const d=await r.json();if(!r.ok)throw Error(d.error||'Sign-in could not finish. Please try again.');
 sessionStorage.removeItem('studioh_login_attempt');rememberSession(d.token);await start(d.token);
}
let authWindow,authState;
function showOpening(){let gate=document.getElementById('v2-cloud-gate');if(!gate){gate=document.createElement('section');gate.id='v2-cloud-gate';document.body.append(gate)}gate.innerHTML='<div><span>STUDIO H</span><h1>Opening your workspace</h1><p role="status">Loading your project…</p></div>'}

function showGate(message=''){let gate=document.getElementById('v2-cloud-gate');if(!gate||!gate.querySelector('button')){if(!gate){gate=document.createElement('section');gate.id='v2-cloud-gate'}gate.innerHTML='<div><span>STUDIO H</span><h1>Welcome back.</h1><p>Sign in to open your projects.</p><button>Connect Studio H</button><button data-demo>Try the demo</button><p role="status"></p></div>';document.body.append(gate);gate.querySelector('button').textContent='Sign in with email';gate.querySelector('button').onclick=()=>beginSignIn().catch(e=>gate.querySelector('[role=status]').textContent=e.message)}gate.querySelector('[data-demo]').onclick=()=>{const u=new URL(location.href);u.searchParams.set('demo','1');location.href=u.href};gate.querySelector('[role=status]').textContent=message}
window.addEventListener('message',e=>{if(e.origin!==endpoint||e.source!==authWindow||e.data?.state!==authState||!e.data.studiohCloudSession)return;start(e.data.studiohCloudSession).catch(e=>showGate(e.message))});
window.addEventListener('beforeunload',e=>{if(dirty||prefsDirty||saving){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>{if(dirty||prefsDirty)flush().catch(()=>{})});
window.v2Cloud={get readOnly(){return projectAccess==='viewer'},get demo(){return demoMode},engineHTML,get seedReady(){return seedReady},get projectName(){return current?.name||lastBid?.S?.pi?.project||'Project'},start,flush,saveBid,storeEngine,openProject,createFromBid,list,recover,get seed(){return {...engineStore,...(lastBid?{v2_project:JSON.stringify(lastBid)}:{})}},get projectId(){return projectId},get authenticated(){return !!user},get dirty(){return dirty||prefsDirty||!!saving},status};
document.getElementById('sh-v2').inert=true;showOpening();
// Reuse an already-authorized V1 publishing credential if present; never copy it into V2 storage.
const params=new URLSearchParams(location.search),savedSession=sessionStorage.getItem(sessionKey)||nativeStorage.getItem(rememberKey),legacyKey=!demoMode&&nativeStorage.getItem('studioh_admin_key');
if(demoMode){started=true;projectId='public-demo';boot().then(()=>{document.documentElement.removeAttribute('data-cloud-opening');document.getElementById('v2-cloud-gate')?.remove();status('Demo · changes last until you leave this page')}).catch(e=>showGate(e.message))}
else if(params.has('login-code'))finishSignIn(params.get('login-code'),params.get('state')).catch(e=>showGate(e.message));
else if(params.has('signin')){const clean=new URL(location.href);clean.searchParams.delete('signin');history.replaceState(null,'',clean.href);beginSignIn().catch(e=>showGate(e.message))}
else if(params.has('signedOut')){forgetSession();showGate()}
else if(savedSession)start(savedSession).catch(e=>showGate(e.message));
else if(legacyKey)fetch(endpoint+'/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:legacyKey}),signal:AbortSignal.timeout(15000)}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Please sign in to continue.');await start(d.token)}).catch(e=>showGate(e.message));
else showGate();
})();
