// Role-specific V2 dashboards. Uses the existing insight calculations and details.
let v2InsightRole=localStorage.getItem('v2_insight_role')==='customer'?'customer':'designer',v2InsightPage='insights',v2InsightCategory='dashboard',v2InsightQuery='';
function v2InsightCatalog(){return INS_CARDS.filter(c=>v2InsightRole==='designer'?c.id!=='fire':c.client===1)}
function v2InsightConfig(){S.v2Dashboards??={};const defaults=v2InsightRole==='customer'?['total','dist','lot','water','palette','bloomcal']:['total','dist','lot','water','palette','ready'];const cfg=S.v2Dashboards[v2InsightRole]??={home:[...defaults],insights:[...defaults]};for(const k of ['home','insights'])if(!Array.isArray(cfg[k]))cfg[k]=[...defaults];return cfg}
function v2InsightSelection(){const allowed=new Set(v2InsightCatalog().map(c=>c.id));return [...new Set(v2InsightConfig()[v2InsightPage])].filter(id=>allowed.has(id))}
function v2InsightSave(ids){v2InsightConfig()[v2InsightPage]=ids;_bidSchedule()}
function v2Insights(home=false){v2InsightPage=home?'home':'insights';v2InsightCategory='dashboard';v2InsightQuery='';v2InsightRender()}
function v2InsightRender(){
 document.getElementById('v2-insights')?.remove();const host=document.createElement('section');host.id='v2-insights';const esc=v2PhotoEscape,home=v2InsightPage==='home',who=v2InsightRole==='customer'?'Customer':'Designer';
 host.innerHTML=`<div class="vi-heading"><div><small>${home?'YOUR PROJECT':'BRIEF & SITE · 04'}</small><h1>${home?'Your project at a glance.':'Project Insights'}</h1><p>${esc(S.pi?.project||S.pi?.client||'Your project')} · ${esc(phaseNow().nm)}${S._sample?' · Sample project':''}</p></div><div class="vi-roles" aria-label="Dashboard role">${['designer','customer'].map(r=>`<button data-role="${r}" aria-pressed="${r===v2InsightRole}">${r==='designer'?'Designer':'Customer'}</button>`).join('')}</div></div><div class="vi-banner"><div><strong>${who}’s ${home?'home dashboard':'insights dashboard'}</strong><p>Choose and arrange your cards. Home and Insights selections are saved separately for each role.</p></div><button data-customize>Customize dashboard</button></div><p class="vi-preview-note">Role preview · Saved with this V2 project on this device. Separate customer sign-in and account syncing are not connected yet.</p>${home?'<div class="vi-actions"><button data-nav="brief">Brief & site →</button><button data-nav="design">Review design →</button><button data-open-insights>Explore all insights →</button></div>':'<nav class="vi-categories" aria-label="Insight categories"></nav><div class="vi-search"><input type="search" aria-label="Find an insight" placeholder="Find an insight" value="'+esc(v2InsightQuery)+'"><span class="vi-count"></span></div>'}<div class="vi-grid"></div>`;
 document.body.append(host);host.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{v2InsightRole=b.dataset.role;localStorage.setItem('v2_insight_role',v2InsightRole);v2InsightCategory='dashboard';v2InsightRender()});host.querySelector('[data-customize]').onclick=v2InsightCustomize;host.querySelector('[data-open-insights]')?.addEventListener('click',()=>parent.postMessage({v2:'insights-open'},'*'));host.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>parent.postMessage({v2:'workspace-page',page:b.dataset.nav},'*'));host.querySelector('input[type=search]')?.addEventListener('input',e=>{v2InsightQuery=e.target.value;v2InsightDraw()});v2InsightDraw();
}
function v2InsightDraw(){
 const host=document.getElementById('v2-insights');if(!host)return;const catalog=v2InsightCatalog(),selected=v2InsightSelection(),groups=[{id:'dashboard',nm:'My dashboard'},{id:'all',nm:'All insights'},...INS_GROUPS],home=v2InsightPage==='home';
 const count=g=>g==='dashboard'?selected.length:catalog.filter(c=>g==='all'||c.g===g).length;
 const nav=host.querySelector('.vi-categories');if(nav){nav.innerHTML=groups.map(g=>`<button data-category="${g.id}" aria-pressed="${v2InsightCategory===g.id}">${g.nm} <span>${count(g.id)}</span></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{v2InsightCategory=b.dataset.category;v2InsightDraw()})}
 const subset=home||v2InsightCategory==='dashboard'?selected.map(id=>catalog.find(c=>c.id===id)):catalog.filter(c=>v2InsightCategory==='all'||c.g===v2InsightCategory);
 const shown=subset.filter(c=>[c.nm,c.desc].join(' ').toLowerCase().includes(v2InsightQuery.toLowerCase()));let data,tally,error='';try{data=_proCardData();tally=_plantTally()}catch{error='Project calculations are unavailable. Please reopen the project.'}
 const grid=host.querySelector('.vi-grid');grid.innerHTML=shown.map(c=>{let reason=error,body='';try{reason=reason||c.need(data,tally);if(!reason)body=(c.drawFull||c.draw)(data,tally)}catch{reason='This insight needs additional project data.'}return `<article class="vi-card ic" data-id="${c.id}"><div class="vi-card-heading"><small>${INS_GROUPS.find(g=>g.id===c.g)?.nm||''}</small><button data-star="${c.id}" aria-label="${selected.includes(c.id)?'Remove':'Add'} ${v2PhotoEscape(c.nm)} ${selected.includes(c.id)?'from':'to'} this dashboard" aria-pressed="${selected.includes(c.id)}">${selected.includes(c.id)?'★':'☆'}</button></div><h2>${v2PhotoEscape(c.nm)}</h2><div class="vi-card-data">${reason?'<p class="vi-empty-reason">'+v2PhotoEscape(reason)+'</p>':body}</div><div class="vi-card-footer"><span>${S._sample?'Sample project':'Project calculations'}</span><button data-detail="${c.id}" ${reason?'disabled':''}>View detail →</button></div></article>`}).join('')||'<div class="vi-empty"><h2>No cards here yet</h2><p>Choose cards using Customize dashboard, or try another category.</p></div>';
 if(host.querySelector('.vi-count'))host.querySelector('.vi-count').textContent=shown.length+' cards';grid.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{const ids=v2InsightSelection(),id=b.dataset.star;v2InsightSave(ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);v2InsightDraw()});grid.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{if(v2InsightCatalog().some(c=>c.id===b.dataset.detail))insOpen(b.dataset.detail)});
}
function v2InsightCustomize(){
 document.getElementById('vi-customize')?.remove();const dialog=document.createElement('dialog');dialog.id='vi-customize';dialog.innerHTML='<div class="vi-modal-heading"><h2>Customize '+(v2InsightRole==='customer'?'customer':'designer')+' '+(v2InsightPage==='home'?'home':'insights')+'</h2><button data-done>Done</button></div><p>Check cards to add them. Move selected cards up or down to arrange your dashboard.</p><div class="vi-picker"></div>';document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-done]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());
 function draw(){const selected=v2InsightSelection(),catalog=v2InsightCatalog(),ordered=[...selected.map(id=>catalog.find(c=>c.id===id)),...catalog.filter(c=>!selected.includes(c.id))];dialog.querySelector('.vi-picker').innerHTML=ordered.map(c=>{const n=selected.indexOf(c.id);return `<div><label><input type="checkbox" data-select="${c.id}" ${n>=0?'checked':''}>${v2PhotoEscape(c.nm)}</label>${n>=0?`<button data-move="${c.id}" data-dir="-1" aria-label="Move ${v2PhotoEscape(c.nm)} up" ${n===0?'disabled':''}>↑</button><button data-move="${c.id}" data-dir="1" aria-label="Move ${v2PhotoEscape(c.nm)} down" ${n===selected.length-1?'disabled':''}>↓</button>`:''}</div>`}).join('');dialog.querySelectorAll('[data-select]').forEach(input=>input.onchange=()=>{const ids=v2InsightSelection();v2InsightSave(input.checked?[...ids,input.dataset.select]:ids.filter(id=>id!==input.dataset.select));draw();v2InsightDraw()});dialog.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const ids=v2InsightSelection(),i=ids.indexOf(b.dataset.move),j=i+Number(b.dataset.dir);if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];v2InsightSave(ids);draw();v2InsightDraw()})}draw();
}
