/* Read-only shared catalogs. No production save API or V1 storage is used here. */
(()=>{
'use strict';
const AI='https://studioh-ai.warwick-cca.workers.dev',GOODS='https://studioh-goods.warwick-cca.workers.dev';
const specs={plantbook:{title:'Plant Book',payload:{type:'loadbook'},url:AI},materials:{title:'Materials',payload:{type:'loadgoods',book:'materials'},url:GOODS},furnishings:{title:'Furnishings',payload:{type:'loadgoods',book:'furnishings'},url:GOODS},colorlibrary:{title:'Color Library',payload:{type:'loadgoods',book:'colorpalettes'},url:GOODS}};
const kinds={tree:'Trees',shrub:'Shrubs',gc:'Groundcovers',palm:'Palms'};
const cache=new Map(),inflight=new Map();let active='',host=null,query='',category='All',onlyFavorites=false,onlyPhotos=false,limit=48,cols=4,loading=false,warning='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
let overrides={};try{overrides=JSON.parse(localStorage.getItem('studioh_v2_library_favorites_v1')||'{}')}catch{}
let favorites=[];
let framing={},adjusting=false,developerTools=localStorage.getItem('studioh_v2_image_tools')==='on';
try{framing=JSON.parse(localStorage.getItem('studioh_v2_image_framing_v1')||'{}')}catch{}
const frameKey=(key,src)=>key+'|'+src;
function frameValue(key,src){const v=framing[frameKey(key,src)]||{};return {z:Math.max(1,Math.min(4,Number(v.z)||1)),x:Math.max(0,Math.min(100,v.x??50)),y:Math.max(0,Math.min(100,v.y??50))}}
function applyFrame(img){if(!img?.naturalWidth||!img.closest('.catalog-photo')||!img.dataset.frameKey)return;const v=frameValue(img.dataset.frameKey,img.getAttribute('src')),r=img.naturalWidth/img.naturalHeight;Object.assign(img.style,{width:Math.max(1,r)*v.z*100+'%',height:Math.max(1,1/r)*v.z*100+'%',left:v.x+'%',top:v.y+'%',transform:`translate(${-v.x}%,${-v.y}%)`})}
function saveFrame(key,src,v){framing[frameKey(key,src)]=v;try{localStorage.setItem('studioh_v2_image_framing_v1',JSON.stringify(framing))}catch{warning='Image framing could not be saved on this device.'}host?.querySelectorAll('.catalog-photo img').forEach(img=>{if(img.dataset.frameKey===key)applyFrame(img)})}
function frameControls(p){return adjusting&&active==='plantbook'&&p._image?`<div class="catalog-frame-controls"><label>Zoom<input type="range" min="1" max="4" step="0.05" value="${frameValue(p._key,p._image).z}" data-frame-zoom="${esc(p._key)}" aria-label="Zoom ${esc(p._name)}"></label><button data-frame-reset="${esc(p._key)}">Reset</button></div>`:''}

const db=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('studioh_v2_catalogs',1);r.onupgradeneeded=()=>r.result.createObjectStore('catalogs');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function saved(id,value){let d;try{d=await db();return await new Promise((resolve,reject)=>{const t=d.transaction('catalogs',value?'readwrite':'readonly'),s=t.objectStore('catalogs'),r=value?s.put(value,id):s.get(id);t.oncomplete=()=>resolve(r.result);t.onerror=()=>reject(t.error)})}finally{d?.close()}}
async function read(spec){const r=await fetch(spec.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(spec.payload),credentials:'omit',signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Library service is unavailable');const d=await r.json();if(d.error||d.err)throw Error('Library service is unavailable');return d}
function normalize(id,d){if(id==='plantbook'){if(!d.found||!d.book||!Object.keys(kinds).every(k=>Array.isArray(d.book[k])))throw Error('Plant library could not be loaded');return {data:d.book,at:d.meta?.savedAt||'',fetched:new Date().toISOString()}}if(!d.ok||!Array.isArray(d.data))throw Error('Library could not be loaded');return {data:d.data,at:d.savedAt||'',fetched:new Date().toISOString()}}
function sync(id){const selected=new Set(favorites);for(const [key,value] of Object.entries(overrides))if(/^(tree|shrub|gc|palm):/.test(key)){if(value)selected.add(key);else selected.delete(key)}if(window.v2Preview?.ready&&cache.has(id))v2Preview.command({v2cmd:'catalog',id,data:cache.get(id).data,favorites:[...selected]})}
async function load(id,refresh=false){if(!refresh&&cache.has(id))return cache.get(id);if(inflight.has(id))return inflight.get(id);const task=(async()=>{let prior=cache.get(id);if(!prior){try{prior=await saved(id);if(prior)cache.set(id,prior)}catch{}}try{const value=normalize(id,await read(specs[id]));cache.set(id,value);try{await saved(id,value)}catch{}sync(id);return value}catch(e){if(prior){prior.offline=true;sync(id);return prior}throw e}})();inflight.set(id,task);try{return await task}finally{inflight.delete(id)}}
async function loadFavorites(){try{const d=await read({url:AI,payload:{type:'loadconfig'}});const f=JSON.parse(d.config?.data?.studioh_favs_v1||'[]');if(Array.isArray(f))favorites=f;try{await saved('favorites',{data:favorites})}catch{}}catch{try{favorites=(await saved('favorites'))?.data||[]}catch{}}sync('plantbook')}
function rows(){const value=cache.get(active);if(!value)return [];if(active==='plantbook')return Object.entries(kinds).flatMap(([kind,label])=>(value.data[kind]||[]).map(p=>({...p,_key:kind+':'+p.id,_cat:label,_name:p.c||p.b||'Unnamed plant',_sub:[p.b,p.cv?"'"+p.cv+"'":''].filter(Boolean).join(' '),_image:url(p.img||p.imgs?.[0]),_favorite:favorites.includes(kind+':'+p.id)})));return value.data.filter(p=>!p.archived).map(p=>({...p,_key:active+':'+p.id,_name:p.nm||p.name||'Untitled',_sub:p.brand||p.sup||(p.tags||[]).slice(0,3).join(' · '),_cat:active==='colorlibrary'?(p.source==='theme'?'Style palettes':'Saved palettes'):(p.cat||'Other'),_image:url(p.shvizCard||p.img||p.imgs?.[0]),_favorite:!!p.favorite}))}
const favorite=p=>overrides[p._key]??p._favorite;
const swatches=p=>Object.entries(p.sw||{}).filter(([,v])=>Array.isArray(v)&&/^#[\da-f]{6}$/i.test(v[1]));
function picture(p){return active==='colorlibrary'?`<div class="catalog-palette">${swatches(p).slice(0,14).map(([k,v])=>`<span style="background:${v[1]}" title="${esc(v[0])}"></span>`).join('')}</div>`:p._image?`<img ${active==='plantbook'?`data-frame-key="${esc(p._key)}"`: ''} draggable="false" src="${esc(p._image)}" alt="${esc(p._name)}" loading="lazy" referrerpolicy="no-referrer"><span class="catalog-noimage" hidden>Photo unavailable</span>`:'<span class="catalog-noimage">No photo yet</span>'}
function cards(){if(!host?.querySelector('#catalog-results'))return;const all=rows(),q=query.toLowerCase(),filtered=all.filter(p=>(category==='All'||p._cat===category)&&(!onlyFavorites||favorite(p))&&(!onlyPhotos||p._image)&&(p._name+' '+p._sub+' '+(p.tags||[]).join(' ')).toLowerCase().includes(q));host.querySelector('#catalog-count').textContent=filtered.length.toLocaleString()+' '+(active==='plantbook'?'plants':active==='colorlibrary'?'palettes':'items');host.querySelector('#catalog-results').innerHTML=filtered.slice(0,limit).map(p=>`<article class="catalog-card"><button class="catalog-photo ${active==='plantbook'?'plant-photo':''} ${adjusting?'is-adjusting':''}" data-catalog-detail="${esc(p._key)}" aria-label="View ${esc(p._name)}">${picture(p)}</button>${frameControls(p)}<div class="catalog-caption"><button data-catalog-detail="${esc(p._key)}"><strong>${esc(p._name)}</strong><span>${esc(p._sub)}</span></button><button class="catalog-heart" data-catalog-favorite="${esc(p._key)}" aria-label="${favorite(p)?'Unsave':'Save'} ${esc(p._name)}" aria-pressed="${!!favorite(p)}">${favorite(p)?'♥':'♡'}</button></div><small>${esc(p._cat)}${p.imgAI?' · AI image':''}</small></article>`).join('')||`<div class="catalog-empty"><h3>${loading?'Loading your library…':'No matches'}</h3><p>${loading?'Bringing in the saved records and photos.':'Try a different search or clear the filters.'}</p></div>`;host.querySelector('#catalog-more').hidden=filtered.length<=limit;host.querySelector('#catalog-results').style.setProperty('--catalog-cols',cols);host.querySelectorAll('.catalog-photo img').forEach(applyFrame);}
function render(){if(!host||!specs[active])return;const value=cache.get(active),all=rows(),cats=['All',...new Set(all.map(p=>p._cat))];host.innerHTML=`<div class="heading"><div class="sectionhead"><span class="tag">Studio libraries</span><button class="quiet" data-page="libraries">← All libraries</button></div><h1>${specs[active].title}</h1><p>Your shared library, with changes in V2 kept separate.</p></div><div class="catalog-toolbar"><label class="catalog-search">Search ${specs[active].title.toLowerCase()}<input type="search" id="catalog-search" value="${esc(query)}" placeholder="${active==='plantbook'?'Common or botanical name…':'Name, brand or material…'}"></label><button data-catalog-filter="favorites" aria-pressed="${onlyFavorites}">♥ Favorites</button>${active!=='colorlibrary'?`<button data-catalog-filter="photos" aria-pressed="${onlyPhotos}">With photos</button>`:''}<label class="catalog-density">Card size<input id="catalog-density" aria-label="Cards per row" type="range" min="1" max="6" value="${cols}"></label>${developerTools&&active==='plantbook'?`<button data-frame-toggle aria-pressed="${adjusting}">${adjusting?'Done adjusting':'Adjust images'}</button>`:''}<button data-catalog-tools>Project tools →</button><button data-catalog-refresh ${loading?'disabled':''}>${loading?'Loading…':'Refresh library'}</button></div><div class="catalog-categories">${cats.map(c=>`<button data-catalog-category="${esc(c)}" aria-pressed="${category===c}">${esc(c)} <span>${c==='All'?all.length:all.filter(p=>p._cat===c).length}</span></button>`).join('')}</div><div class="catalog-status"><strong id="catalog-count" aria-live="polite"></strong><span>${esc(warning||(value?.offline?'Saved copy · unable to refresh':value?'Shared library · updated '+new Date(value.fetched).toLocaleDateString():'Connecting to your shared library…'))}</span></div>${adjusting?'<p class="w-note">Drag a photo to position it. Use Zoom to crop closer. Changes save on this device.</p>':''}<div id="catalog-results" class="catalog-grid"></div><button id="catalog-more" class="quiet" data-catalog-more hidden>Show more</button><p class="w-note">Favorites you change here are saved in V2 on this device.</p>`;cards()}
async function open(id,target){active=id;host=target;query='';category='All';onlyFavorites=false;onlyPhotos=false;limit=48;loading=true;warning='';render();try{await Promise.all([load(id),id==='plantbook'?loadFavorites():Promise.resolve()])}catch{if(active===id)warning='Could not load this library. Check your connection and try Refresh library.'}finally{if(active===id){loading=false;render()}}}
function detail(key){const p=rows().find(x=>x._key===key);if(!p)return;let d=document.getElementById('v2-catalog-detail');if(!d){d=document.createElement('dialog');d.id='v2-catalog-detail';document.getElementById('sh-v2').append(d)}const props=active==='plantbook'?[['Plant type',p._cat],['Mature height',p.h?p.h+' ft':''],['Mature width',p.w?p.w+' ft':''],['Water use',({VL:'Very low',L:'Low',M:'Moderate',H:'High'})[p.wu]||p.wu],['Light',p.light],['Bloom',p.bloomSeason||p.bloom],['Growth',p.growthRate],['Source',p.imgSrc],['Photo credit',p.imgAttr],['License',p.imgLic]]:[['Category',p.cat],['Brand',p.brand||p.sup],['Dimensions',p.dims||p.sizes],['Finish',p.fin||p.frame],['SKU',p.sku],['Price source',p.msrpSrc||p.priced]];d.innerHTML=`<div class="sectionhead"><div><h2>${esc(p._name)}</h2><p>${esc(p._sub)}</p></div><button data-catalog-close aria-label="Close details">✕</button></div><div class="catalog-detail-grid"><div class="catalog-detail-image">${picture(p)}</div><div>${active==='colorlibrary'?`<div class="catalog-swatches">${swatches(p).map(([k,v])=>`<div><i style="background:${v[1]}"></i><span>${esc(v[0])}<small>${esc(k.replaceAll('_',' '))} · ${v[1]}</small></span></div>`).join('')}</div>`:`<dl>${props.filter(([,v])=>v&&v!=='—').map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`}${p.msrp>0?`<p>Recorded list price: <strong>$${Number(p.msrp).toLocaleString()}</strong>${p.msrpAI?' · AI estimate':''}</p><small>From the saved library record; confirm current pricing with the supplier.</small>`:''}${url(p.srcUrl)?`<p><a href="${esc(url(p.srcUrl))}" target="_blank" rel="noopener noreferrer">View supplier source ↗</a></p>`:''}${p.imgAI?'<p class="w-note">AI-generated library image.</p>':''}</div></div>`;d.showModal()}
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'&&e.target.closest('.catalog-photo,.catalog-detail-image')){e.target.hidden=true;const fallback=e.target.nextElementSibling;if(fallback)fallback.hidden=false}},true);
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-catalog-close')){b.closest('dialog').close();return}if(!host||!b.closest('#sh-content'))return;if(b.hasAttribute('data-catalog-tools')){const id=active;v2Preview.show(id,specs[id].title+' · project tools',true);return}if(b.hasAttribute('data-frame-toggle')){adjusting=!adjusting;render();return}if(b.dataset.frameReset){const p=rows().find(x=>x._key===b.dataset.frameReset);if(p){saveFrame(p._key,p._image,{z:1,x:50,y:50});cards()}return}if(b.dataset.catalogDetail){if(adjusting&&b.classList.contains('catalog-photo'))return;detail(b.dataset.catalogDetail);return}if(b.dataset.catalogFavorite){const p=rows().find(x=>x._key===b.dataset.catalogFavorite);if(p){overrides[p._key]=!favorite(p);try{localStorage.setItem('studioh_v2_library_favorites_v1',JSON.stringify(overrides))}catch{}if(active==='plantbook')sync(active);cards()}return}if(b.dataset.catalogCategory){category=b.dataset.catalogCategory;limit=48;render()}if(b.dataset.catalogFilter){if(b.dataset.catalogFilter==='favorites')onlyFavorites=!onlyFavorites;else onlyPhotos=!onlyPhotos;limit=48;render()}if(b.hasAttribute('data-catalog-more')){limit+=48;cards()}if(b.hasAttribute('data-catalog-refresh')){const id=active;loading=true;warning='';render();try{await Promise.all([load(id,true),id==='plantbook'?loadFavorites():Promise.resolve()])}catch{warning='Could not refresh. Please try again.'}finally{if(active===id){loading=false;render()}}}});
document.addEventListener('input',e=>{if(e.target.dataset.frameZoom){const p=rows().find(x=>x._key===e.target.dataset.frameZoom);if(p)saveFrame(p._key,p._image,{...frameValue(p._key,p._image),z:Number(e.target.value)});}if(e.target.id==='catalog-search'){query=e.target.value;limit=48;cards()}if(e.target.id==='catalog-density'){cols=Number(e.target.value);cards()}});
document.addEventListener('load',e=>{if(e.target.tagName==='IMG')applyFrame(e.target)},true);
let drag=null;
document.addEventListener('pointerdown',e=>{const box=e.target.closest('.plant-photo.is-adjusting');if(!box||!adjusting)return;const img=box.querySelector('img');if(!img?.naturalWidth)return;e.preventDefault();const v=frameValue(img.dataset.frameKey,img.getAttribute('src'));drag={box,img,v,startX:e.clientX,startY:e.clientY,w:img.getBoundingClientRect().width-box.clientWidth,h:img.getBoundingClientRect().height-box.clientHeight};box.setPointerCapture(e.pointerId)});
document.addEventListener('pointermove',e=>{if(!drag)return;const {img,v,startX,startY,w,h}=drag;saveFrame(img.dataset.frameKey,img.getAttribute('src'),{z:v.z,x:w>0?Math.max(0,Math.min(100,v.x-(e.clientX-startX)/w*100)):50,y:h>0?Math.max(0,Math.min(100,v.y-(e.clientY-startY)/h*100)):50})});
for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,()=>{drag=null});
document.addEventListener('keydown',e=>{if(!adjusting||!e.target.matches('.plant-photo')||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const img=e.target.querySelector('img');if(!img)return;const v=frameValue(img.dataset.frameKey,img.getAttribute('src'));if(e.key==='ArrowLeft')v.x=Math.max(0,v.x-5);if(e.key==='ArrowRight')v.x=Math.min(100,v.x+5);if(e.key==='ArrowUp')v.y=Math.max(0,v.y-5);if(e.key==='ArrowDown')v.y=Math.min(100,v.y+5);saveFrame(img.dataset.frameKey,img.getAttribute('src'),v)});
window.v2Libraries={supports:id=>!!specs[id],open,get developerTools(){return developerTools},toggleDeveloperTools(){developerTools=!developerTools;localStorage.setItem('studioh_v2_image_tools',developerTools?'on':'off');adjusting=false},close(){adjusting=false;active='';host=null},sync(){for(const id of cache.keys())sync(id)}};
})();
