/* Appearance controls use the existing account preference store and save flow. */
(()=>{
const key='studioh_ui_palette_v1',defaults={forest:'#193F35',green:'#55764C',sage:'#DDE7D5',soft:'#EDF2E7',lime:'#DCF3A6',purple:'#AA94CF',lavender:'#EEE8F6',canvas:'#F3F5EF',white:'#FFFFFF',ink:'#293B33',muted:'#617066'};
const labels={forest:'Forest · primary',green:'Leaf green · secondary',sage:'Sage · supporting cards',soft:'Pale sage · quiet controls',lime:'Lime · highlight',purple:'Purple · chart accent',lavender:'Lavender · accent surface',canvas:'Page background',white:'Default card',ink:'Main text',muted:'Secondary text'};
const valid=p=>p&&Object.keys(defaults).every(k=>/^#[0-9a-f]{6}$/i.test(p[k]));
let stored;try{stored=JSON.parse(localStorage.getItem(key)||'null')}catch{}let saved=valid(stored)?stored:null;
const css=p=>p?`:root,body,#sh-v2,#sh-v2[data-theme],#firm-app{--card-forest:${p.forest}!important;--card-lime:${p.lime}!important;--card-purple:${p.lavender}!important;--card-purple-strong:${p.purple}!important;--card-canvas:${p.canvas}!important;--card-white:${p.white}!important;--card-ink:${p.ink}!important;--card-muted:${p.muted}!important;--green:${p.forest}!important;--sage:${p.sage}!important;--soft:${p.soft}!important;--paper:${p.canvas}!important;--ground:${p.canvas}!important;--white:${p.white}!important;--ink:${p.ink}!important;--muted:${p.muted}!important;--sub:${p.muted}!important;--theme-hero:${p.sage}!important;--theme-railwell:${p.sage}!important}#sh-v2 .rail-item.active{background:${p.sage}!important}#sh-v2 #v2-project-home .stat-track i,#firm-app .dc-track i{background:${p.green}!important}body :is(.cost-net,.cost-total-strip,.cost-group-total){background:${p.sage}!important}#firm-app .dc-card.lime .dc-track i{background:${p.forest}!important}`:'';
function apply(doc=document){try{let style=doc.getElementById('studio-palette-override');if(!style){style=doc.createElement('style');style.id='studio-palette-override';(doc.head||doc.documentElement).append(style)}style.textContent=css(saved);doc.querySelectorAll('iframe').forEach(f=>{if(f.contentDocument)apply(f.contentDocument)})}catch{}}
// Each newly loaded same-origin document receives the saved palette, without a reload.
document.addEventListener('load',e=>{if(e.target.tagName==='IFRAME')try{const d=e.target.contentDocument;if(d){apply(d);d.addEventListener('load',ev=>{if(ev.target.tagName==='IFRAME')try{apply(ev.target.contentDocument)}catch{}},true)}}catch{}},true);
apply();

window.v2Palette={defaults:{...defaults},get(){return {...(saved||defaults)}},apply(p){if(!valid(p))throw Error('Choose valid hex colors.');saved={...p};localStorage.setItem(key,JSON.stringify(saved));apply()},reset(){saved=null;localStorage.removeItem(key);apply()}};
})();
/* Usage targets affect only flexible financial card surfaces, never explicit heroes or charts. */
(()=>{const watched=new WeakSet();let queued=false;
const contrast=hex=>{const v=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2]>.35?'#193F35':'#FFFFFF'};
function apply(doc){try{let balance;try{balance=JSON.parse(localStorage.getItem('studioh_ui_palette_balance_v2')||'null')}catch{}const w=balance?.weights,c=v2Palette.get(),valid=w&&['neutral','green','lime','purple'].every(k=>Number.isFinite(w[k])&&w[k]>=0)&&Object.values(w).reduce((a,b)=>a+b,0)===100;const colors={neutral:c.white,green:c.sage,lime:c.lime,purple:c.lavender};
 const all=[...doc.querySelectorAll('.pf-approved .grid>.card:not(.forest):not(.lime):not(.lavender):not(.sage)')];all.forEach((el,i)=>{if(!valid){el.removeAttribute('data-palette-flex');return}let position=(i+.5)/all.length*100,role='neutral';for(const k of ['neutral','green','lime','purple']){position-=w[k];role=k;if(position<=0)break}el.dataset.paletteFlex=role;el.style.setProperty('--flex-bg',colors[role]);el.style.setProperty('--flex-ink',contrast(colors[role]));});
 let style=doc.getElementById('palette-flex-style');if(!style){style=doc.createElement('style');style.id='palette-flex-style';doc.head.append(style)}const css='.pf-approved .card[data-palette-flex]{background:var(--flex-bg)!important;color:var(--flex-ink)!important}.pf-approved .card[data-palette-flex]>.num,.pf-approved .card[data-palette-flex]>.head,.pf-approved .card[data-palette-flex]>.muted,.pf-approved .card[data-palette-flex]>.foot{color:var(--flex-ink)!important}';if(style.textContent!==css)style.textContent=css;
 if(!watched.has(doc)){watched.add(doc);new MutationObserver(records=>{if(records.some(r=>[...r.addedNodes].some(n=>n.nodeType===1))&&!queued){queued=true;requestAnimationFrame(()=>{queued=false;apply(document)})}}).observe(doc.body,{childList:true,subtree:true});doc.addEventListener('load',e=>{if(e.target.tagName==='IFRAME')apply(document)},true)}doc.querySelectorAll('iframe').forEach(f=>{if(f.contentDocument?.body)apply(f.contentDocument)})}catch{}}
window.v2PaletteBalance={refresh:()=>apply(document)};apply(document);
})();
