// Standalone gallery, sharing the questionnaire's project collection.
const v2PhotoCategories=['All','Site photos','Inspiration','Materials','Products'];
let v2PhotoFilter='All',v2PhotoSearch='',v2PhotoColumns=4;
const v2PhotoEscape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function v2PhotoURL(s,image=false){try{if(image&&/^data:image\/(jpeg|png|webp);base64,/.test(s))return s;const u=new URL(s);return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}}
function v2PhotoItems(){S.designBrief??={fields:{},elements:[],styles:[],completed:[]};return S.designBrief.photos??=[]}
function v2PhotoCategory(p){return p.v2Category||(p.kind==='Inspiration'?'Inspiration':p.kind==='Furniture references'?'Products':'Site photos')}
function v2PrimaryPhoto(){return v2PhotoItems().find(p=>p.id===S.v2PrimaryPhotoId&&v2PhotoURL(p.url,true))}
function v2PublishIdentity(){const p=v2PrimaryPhoto();parent.postMessage({v2:'identity',photo:p?{url:p.url,name:p.name}:null},'*');v2ProjectIdentity()}
function v2ProjectIdentity(){const card=document.querySelector('#view-projectinfo .pinfo-card');if(!card)return;let banner=document.getElementById('v2-project-identity');if(!banner){banner=document.createElement('section');banner.id='v2-project-identity';card.prepend(banner)}const p=v2PrimaryPhoto();banner.innerHTML=`<div><small>YOUR PROJECT</small><h1>${v2PhotoEscape(S.pi?.project||'Your project')}</h1><p>${v2PhotoEscape(S.pi?.address||'Add your project address below.')}</p><button class="btn" id="v2-manage-primary">Manage project photos →</button></div>${p?`<img src="${v2PhotoEscape(p.url)}" alt="${v2PhotoEscape(p.name)}">`:'<div class="v2-primary-empty">Choose a primary project photo<br><small>One photo for Project info and Home</small></div>'}`;banner.querySelector('button').onclick=()=>parent.postMessage({v2:'open-photos'},'*')}
function v2PhotoChanged(){v2PublishIdentity();const d=S.designBrief;d.confirmed=false;d.completed=(d.completed||[]).filter(x=>x!==7);d.updatedAt=new Date().toISOString();_bidSchedule()}
function v2Photos(){
 v2PhotoColumns=Math.max(1,Math.min(6,S.v2PhotoColumns||4));
 // Drop a hidden questionnaire frame so an old draft cannot overwrite gallery edits.
 _qFrame?.remove();_qFrame=null;_qToken='';_qSession=-1;document.getElementById('view-questionnaire')?.classList.remove('active');
 document.getElementById('v2-photos')?.remove();v2PhotoItems();
 const host=document.createElement('section');host.id='v2-photos';host.innerHTML=`<h1>Your project, collected.</h1><p>Site photos, inspiration, materials and product links together. Photos added in the questionnaire appear here too.</p><div class="v2-photo-drop"><div><strong>Drop photos into this project</strong><p>Add photos or a website link, then label it so it’s easy to find.</p></div><div class="v2-photo-actions"><button class="primary" data-add="photo">Add photos</button><button data-add="camera">Take a photo</button><button data-add="link">Add a link</button></div></div><input hidden id="v2-photo-files" type="file" accept="image/jpeg,image/png,image/webp" multiple><input hidden id="v2-photo-camera" type="file" accept="image/*" capture="environment"><nav class="v2-photo-filters">${v2PhotoCategories.map(c=>`<button data-filter="${c}" aria-pressed="${c===v2PhotoFilter}">${c}</button>`).join('')}</nav><div class="v2-photo-toolbar"><input id="v2-photo-search" type="search" aria-label="Search photos and references" placeholder="Search photos & references" value="${v2PhotoEscape(v2PhotoSearch)}"><label>Card size <input id="v2-photo-size" aria-label="Card size" type="range" min="1" max="6" value="${7-v2PhotoColumns}"></label><span id="v2-photo-count"></span></div><div id="v2-photo-status" role="status"></div><div class="v2-photo-grid"></div><p class="v2-photo-note">Photos, tags and links save privately with your project on Cloudflare. Online image and price lookup is not connected yet.</p>`;
 document.body.append(host);v2PhotoDraw();
 host.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{v2PhotoFilter=b.dataset.filter;host.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));v2PhotoDraw()});
 host.querySelector('#v2-photo-search').oninput=e=>{v2PhotoSearch=e.target.value;v2PhotoDraw()};
 host.querySelector('#v2-photo-size').oninput=e=>{v2PhotoColumns=7-Number(e.target.value);S.v2PhotoColumns=v2PhotoColumns;_bidSchedule();v2PhotoDraw()};
 host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{if(b.dataset.add==='link')v2PhotoEdit(-1);else host.querySelector(b.dataset.add==='camera'?'#v2-photo-camera':'#v2-photo-files').click()});
 host.querySelectorAll('input[type=file]').forEach(input=>input.onchange=async()=>{await v2PhotoUpload([...input.files]);input.value=''});
 const drop=host.querySelector('.v2-photo-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');v2PhotoUpload([...e.dataTransfer.files])};
}
function v2PhotoDraw(){const grid=document.querySelector('.v2-photo-grid');if(!grid)return;const rows=v2PhotoItems().map((p,i)=>({p,i})).filter(({p})=>(v2PhotoFilter==='All'||v2PhotoCategory(p)===v2PhotoFilter)&&[p.name,p.caption,p.comments,p.sourceUrl,...(p.tags||[])].join(' ').toLowerCase().includes(v2PhotoSearch.toLowerCase()));grid.style.setProperty('--photo-columns',Math.min(v2PhotoColumns,Math.max(1,Math.floor(grid.clientWidth/190))));document.querySelector('#v2-photo-count').textContent=rows.length+' references';grid.innerHTML=rows.map(({p,i})=>{const url=v2PhotoURL(p.url,true);return `<article class="v2-photo-card"><button class="v2-photo-open" data-photo="${i}">${url?`<img src="${v2PhotoEscape(url)}" alt="${v2PhotoEscape(p.caption||p.name)}" loading="lazy">`:'<div class="v2-link-preview">↗<span>Website reference</span></div>'}<strong>${v2PhotoEscape(p.name||'Untitled reference')}</strong><span>${v2PhotoEscape(v2PhotoCategory(p))}</span></button><button class="v2-photo-favorite" data-favorite="${i}" aria-label="Favorite ${v2PhotoEscape(p.name)}" aria-pressed="${!!p.favorite}">${p.favorite?'★':'☆'}</button></article>`}).join('')||'<div class="v2-photo-empty"><h2>No references here yet</h2><p>Add a photo or link, or choose another category.</p></div>';grid.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const p=v2PhotoItems()[Number(b.dataset.favorite)];p.favorite=!p.favorite;v2PhotoChanged();v2PhotoDraw()});grid.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>v2PhotoEdit(Number(b.dataset.photo)))}
async function v2PhotoUpload(files){const status=document.querySelector('#v2-photo-status');const project=S;let added=0;for(const file of files){try{if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Use JPG, PNG or WebP.');if(file.size>15*1024*1024)throw Error('Use an image under 15 MB.');status.textContent='Adding '+file.name+'…';const url=await v2PhotoResize(file);if(S!==project)throw Error('Project changed. Please add the photo again.');const c=v2PhotoFilter==='All'?'Site photos':v2PhotoFilter;v2PhotoItems().push({id:crypto.randomUUID(),name:file.name,url,original:await v2FileData(file),kind:c==='Products'?'Furniture references':c==='Site photos'?'Site overview':'Inspiration',v2Category:c,caption:'',addedBy:'Designer'});v2PhotoChanged();added++}catch(e){status.textContent=file.name+': '+e.message;v2PhotoDraw();return}}status.textContent=added+' photos added to this project.';v2PhotoDraw()}
async function v2PhotoResize(file){const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();return c.toDataURL('image/jpeg',.78)}
function v2PhotoEdit(index){
 document.getElementById('v2-photo-editor')?.remove();
 const p=v2PhotoItems()[index],category=p?v2PhotoCategory(p):(v2PhotoFilter==='All'?'Inspiration':v2PhotoFilter),d=document.createElement('dialog'),esc=v2PhotoEscape;
 const imageURL=p&&v2PhotoURL(p.url,true);let tags=[...(Array.isArray(p?.tags)?p.tags:[])],favorite=!!p?.favorite;
 d.id='v2-photo-editor';d.classList.toggle('has-photo',!!imageURL);d.setAttribute('aria-labelledby','v2-reference-title');
 d.innerHTML=`<header class="v2-reference-header"><h2 id="v2-reference-title">${p?'Reference details':'Add a reference link'}</h2><button type="button" data-favorite-toggle aria-pressed="${favorite}">${favorite?'★ Favorited':'☆ Favorite'}</button><button type="button" data-close aria-label="Close reference details">×</button></header><div class="v2-reference-body">${imageURL?`<div class="v2-reference-image"><img src="${esc(imageURL)}" alt="${esc(p.name||'Project reference')}"></div>`:''}<form id="v2-reference-form">${imageURL?`<label class="v2-primary-choice"><input type="checkbox" name="primaryPhoto" ${p.id&&p.id===S.v2PrimaryPhotoId?'checked':''}> Use as primary project photo<small>Shown on Project info and Home.</small></label>`:''}<label>Title<input name="name" required value="${esc(p?.name)}"></label><label>Category<select name="category">${v2PhotoCategories.slice(1).map(c=>`<option ${c===category?'selected':''}>${c}</option>`).join('')}</select></label><label>Website or product link<input name="sourceUrl" type="url" ${!p?'required':''} placeholder="https://" value="${esc(p?.sourceUrl)}"></label><div class="v2-reference-tags"><label for="v2-tag-entry">Tags</label><div class="v2-tag-chips" aria-label="Reference tags"></div><div class="v2-tag-entry"><input id="v2-tag-entry" name="tags" placeholder="Add a tag…" aria-label="Add tags"><button type="button" data-add-tag>Add</button></div><small>Press Enter or add several tags with commas.</small></div><label>Notes<textarea name="caption" rows="3">${esc(p?.caption)}</textarea></label>${p?.kind==='Furniture references'?`<label>Ownership<select name="ownership"><option ${p.ownership==='Would like'?'selected':''}>Would like</option><option ${p.ownership==='Already own'?'selected':''}>Already own</option></select></label>`:''}</form></div><footer class="v2-reference-footer">${p?'<button type="button" data-delete>Delete reference</button>':'<button type="button" data-cancel>Cancel</button>'}<button class="primary" type="button" data-save>Save reference</button></footer>`;
 document.body.append(d);d.showModal();d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-cancel]')?.addEventListener('click',()=>d.close());d.addEventListener('close',()=>d.remove());
 const drawTags=()=>{const box=d.querySelector('.v2-tag-chips');box.innerHTML=tags.map((t,i)=>`<button type="button" data-remove-tag="${i}" aria-label="Remove tag ${esc(t)}">${esc(t)} <span aria-hidden="true">×</span></button>`).join('');box.querySelectorAll('[data-remove-tag]').forEach(b=>b.onclick=()=>{tags.splice(Number(b.dataset.removeTag),1);drawTags()})};
 const addTags=()=>{const input=d.querySelector('[name=tags]');for(const tag of input.value.split(',').map(t=>t.trim()).filter(Boolean))if(!tags.some(t=>t.toLowerCase()===tag.toLowerCase()))tags.push(tag);input.value='';drawTags()};drawTags();d.querySelector('[data-add-tag]').onclick=addTags;
 d.querySelector('[data-favorite-toggle]').onclick=e=>{favorite=!favorite;e.currentTarget.setAttribute('aria-pressed',favorite);e.currentTarget.textContent=favorite?'★ Favorited':'☆ Favorite'};
 const saveReference=()=>{const form=d.querySelector('form');if(!form.reportValidity())return;const data=new FormData(form),source=data.get('sourceUrl').trim();if(source&&!v2PhotoURL(source)){form.elements.sourceUrl.setCustomValidity('Use an http or https link.');form.elements.sourceUrl.reportValidity();return}addTags();const c=data.get('category'),target=p||{id:crypto.randomUUID(),url:'',addedBy:window.v2ExperienceRole==='customer'?'Customer':'Designer'};Object.assign(target,{name:data.get('name').trim(),sourceUrl:source,caption:data.get('caption'),tags:[...tags],favorite,v2Category:c});if(c!==category||!p)target.kind=c==='Products'?'Furniture references':c==='Site photos'?'Site overview':'Inspiration';if(data.has('ownership'))target.ownership=data.get('ownership');if(!p)v2PhotoItems().push(target);if(imageURL){target.id||=crypto.randomUUID();if(data.has('primaryPhoto'))S.v2PrimaryPhotoId=target.id;else if(S.v2PrimaryPhotoId===target.id)delete S.v2PrimaryPhotoId}v2PhotoChanged();d.close();v2PhotoDraw()};
 d.querySelector('[data-save]').onclick=saveReference;d.querySelector('form').onsubmit=e=>{e.preventDefault();saveReference()};d.querySelector('form').onkeydown=e=>{if(e.key==='Enter'&&e.target.name==='tags'){e.preventDefault();addTags()}else if(e.key==='Enter'&&e.target.tagName==='INPUT'){e.preventDefault();saveReference()}};d.querySelector('[name=sourceUrl]').oninput=e=>e.target.setCustomValidity('');
 d.querySelector('[data-delete]')?.addEventListener('click',()=>{if(confirm('Delete this reference from the project?')){v2PhotoItems().splice(index,1);v2PhotoChanged();d.close();v2PhotoDraw()}});
}

window.addEventListener('resize',()=>{if(document.querySelector('.v2-photo-grid'))v2PhotoDraw()});

function v2FileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error("Could not read file"));r.readAsDataURL(file)})}
