/* Schedule shares the Project Home records; no separate demo store. */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={overview:'Overview',tasks:'Tasks',milestones:'Milestones',deliverables:'Deliverables',approvals:'Pending approvals',timeline:'Timeline',cards:'Cards'};
let host,c,view='overview',query='',filter='open';
const editable=()=>c.canEdit();
const ms=()=>Array.isArray(c.data.milestones)?c.data.milestones:c.data.milestone?.title?[{...c.data.milestone,id:'legacy-milestone',state:'Active'}]:[];
const rows=()=>view==='milestones'?ms():(c.data[view]||[]);
const done=x=>view==='milestones'?x.state==='Complete':!!(x.done||x.ready);
const date=x=>view==='milestones'?x.date:x.dueDate;
function save(){const next=[...ms()].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).find(m=>m.state!=='Complete');c.data.milestone=next?{...next}:null;c.save()}
function shell(){host.innerHTML=`<style>
.plan-hub{padding:12px;min-width:0}.plan-hub h1{font-size:28px;margin:6px 0}.plan-hub p{color:#737d72}.plan-tabs{display:flex;gap:8px;overflow:auto;border-bottom:1px solid #dfe5da;padding:16px 0;margin-bottom:20px;overscroll-behavior:none}.plan-tabs button{white-space:nowrap;border:0;border-radius:12px;padding:12px 16px;background:transparent;font:inherit;color:inherit}.plan-tabs button[aria-selected=true]{background:#537642;color:white}.plan-controls{display:flex;gap:10px;margin-bottom:20px}.plan-controls input{flex:1;min-width:0}.plan-hub input,.plan-hub select{font:inherit;padding:12px;border:1px solid #dce3d6;border-radius:10px;background:white}.plan-list{background:white;border-radius:20px;padding:18px}.plan-row{display:flex;gap:14px;align-items:center;padding:20px 8px;border-bottom:1px solid #edf0e8}.plan-row:last-child{border:0}.plan-row .copy{flex:1;min-width:0}.plan-row small{display:block;color:#778170;margin-top:7px}.plan-row input[type=checkbox]{width:22px;height:22px;accent-color:#537642}.plan-row.completed .copy b{text-decoration:line-through;color:#71816d}.plan-hub button{cursor:pointer}.plan-hub .soft{border:0;border-radius:10px;padding:10px 14px;background:#eef3e8;color:#34432f;font:inherit}.plan-hub .primary{background:#537642;color:white}.plan-hub dialog{border:0;border-radius:20px;padding:26px;max-width:520px;width:calc(100% - 32px)}.plan-hub dialog::backdrop{background:#25352255}.plan-hub form{display:grid;gap:16px}.plan-hub label{display:grid;gap:6px}.plan-hub footer{display:flex;justify-content:flex-end;gap:10px;margin-top:14px}.plan-hub .status{font-size:12px;border-radius:10px;background:#edf3e7;padding:7px 10px}
.plan-row .quick-date{display:grid;gap:4px;flex-shrink:0;font-size:11px;color:var(--muted)}.plan-row .quick-date input{width:160px;background:var(--paper);color:var(--ink);border-color:var(--sage);font-size:13px;padding:10px}.plan-list{background:var(--white)}.plan-row{border-color:var(--sage)}@media(max-width:650px){.plan-row{flex-wrap:wrap}.plan-row .copy{flex-basis:65%}.plan-row .quick-date{margin-left:auto}}
</style><section class="plan-hub"><h1>Schedule</h1><p>Your tasks, milestones, deliverables and dates. One place to keep things moving.</p><nav class="plan-tabs" role="tablist" aria-label="Schedule pages">${Object.entries(titles).map(([id,t])=>`<button role="tab" data-plan-tab="${id}" aria-selected="${view===id}">${t}</button>`).join('')}</nav><div id="plan-body"></div><dialog id="plan-editor"></dialog></section>`;
host.querySelectorAll('[data-plan-tab]').forEach(b=>b.onclick=()=>{view=b.dataset.planTab;query='';filter='open';shell()});draw();}
function draw(){const body=host.querySelector('#plan-body');const context={...c,back:()=>{view='overview';shell()}};if(view==='overview'){window.v2Milestones.mount(body,{...context,initialView:'overview'});return}if(view==='timeline'||view==='cards'){window.v2PlanViews.mount(body,context,view==='timeline'?'a':'b');return}
body.innerHTML=`<div class="plan-controls"><input aria-label="Search ${titles[view]}" placeholder="Search ${titles[view].toLowerCase()} or owners…" value="${esc(query)}"><select aria-label="Status filter"><option value="open">Open items</option><option value="all">All items</option><option value="complete">Completed</option></select>${editable()?`<button class="soft primary" data-add>+ Add ${view==='milestones'?'milestone':view==='tasks'?'task':view==='approvals'?'approval':'deliverable'}</button>`:''}</div><div class="plan-list"></div><p style="font-size:12px">Changes here also update the calendar, Timeline, Cards and linked project records.</p>`;
body.querySelector('select').value=filter;body.querySelector('input').oninput=e=>{query=e.target.value;list()};body.querySelector('select').onchange=e=>{filter=e.target.value;list()};body.querySelector('[data-add]')?.addEventListener('click',()=>edit(-1));list();}
function list(){const records=rows();host.querySelector('.plan-list').innerHTML=records.map((x,i)=>({x,i})).sort((a,b)=>(date(a.x)||'9999').localeCompare(date(b.x)||'9999')).filter(({x})=>(filter==='all'||done(x)===(filter==='complete'))&&`${x.title} ${x.owner||''}`.toLowerCase().includes(query.toLowerCase())).map(({x,i})=>{const m=ms().find(m=>m.id===x.milestoneId);return `<div class="plan-row ${done(x)?'completed':''}">${view==='milestones'?`<span class="status">${done(x)?'✓ Completed':esc(x.state||'Planned')}</span>`:`<input type="checkbox" aria-label="Complete ${esc(x.title)}" data-check="${i}" ${done(x)?'checked':''} ${editable()?'':'disabled'}>`}<div class="copy"><b>${esc(x.title)}</b><small>${esc(x.owner||'Unassigned')}${m?' · '+esc(m.title):''}</small>${view==='milestones'?`<small>${['tasks','deliverables'].map(k=>{const r=(c.data[k]||[]).filter(t=>t.milestoneId===x.id||(!t.milestoneId&&x.id==='legacy-milestone'));return `${r.filter(t=>t.done||t.ready).length}/${r.length} ${k}`}).join(' · ')}</small>`:''}</div>${view!=='approvals'?`<label class="quick-date"><span>Due date</span><input type="date" aria-label="Due date for ${esc(x.title)}" data-quick-date="${i}" value="${esc(date(x)||'')}" ${editable()?'':'disabled'}></label>`:''}${view!=='approvals'?`<button class="soft" data-start-time="${i}">Start timer</button><button class="soft" data-enter-time="${i}">Enter time</button>`:''}<button class="soft" data-edit="${i}">${editable()?'Edit':'View'}</button></div>`}).join('')||'<p>No matching items. Choose “All items” to include completed work.</p>';
host.querySelectorAll('[data-start-time]').forEach(b=>b.onclick=()=>{const x=records[+b.dataset.startTime];window.v2Time?.timer({type:view.slice(0,-1),id:x.id})});host.querySelectorAll('[data-enter-time]').forEach(b=>b.onclick=()=>{const x=records[+b.dataset.enterTime];window.v2Time?.enter({type:view.slice(0,-1),id:x.id||view+'-'+b.dataset.enterTime})});host.querySelectorAll('[data-quick-date]').forEach(input=>input.onchange=()=>{if(!editable()||!input.validity.valid)return;records[+input.dataset.quickDate][view==='milestones'?'date':'dueDate']=input.value;save();list()});host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(+b.dataset.edit));host.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{const x=records[+b.dataset.check];x.done=b.checked;if(view==='deliverables')x.ready=b.checked;if(!b.checked){const milestone=ms().find(m=>m.id===x.milestoneId);if(milestone?.state==='Complete')milestone.state='Planned'}save();list()});}
function edit(index){if(index>=0&&view!=='approvals')window.v2Time?.focus({type:view.slice(0,-1),id:rows()[index]?.id});const x=rows()[index]||{},milestone=view==='milestones',dialog=host.querySelector('#plan-editor');dialog.innerHTML=`<h2>${index<0?'Add':'Edit'} ${milestone?'milestone':view==='tasks'?'task':view==='deliverables'?'deliverable':'approval'}</h2><form><label>Name<input name="title" required maxlength="200" value="${esc(x.title)}"></label><label>Assigned to<input name="owner" value="${esc(x.owner||'')}"></label><label>${milestone?'Deadline':'Due date (optional)'}<input type="date" name="date" value="${esc(date(x)||'')}"></label>${milestone?'<p>Complete required tasks and deliverables in Timeline or Cards before completing this milestone.</p>':`<label>Linked milestone<select name="milestoneId"><option value="">Not linked</option>${ms().map(m=>`<option value="${esc(m.id)}" ${x.milestoneId===m.id?'selected':''}>${esc(m.title)}</option>`).join('')}</select></label>`}<footer><button type="button" class="soft" data-cancel>Cancel</button>${editable()?'<button class="soft primary" type="submit">Save changes</button>':''}</footer></form>`;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(!editable())return;const f=new FormData(e.target),record={...x,id:x.id||crypto.randomUUID(),title:f.get('title').trim(),owner:f.get('owner'),[milestone?'date':'dueDate']:f.get('date'),...(milestone?{state:x.state||'Planned'}:{milestoneId:f.get('milestoneId')})};if(milestone){const all=ms();if(index<0)all.push(record);else all[index]=record;c.data.milestones=all;const next=all.find(m=>m.state!=='Complete');c.data.milestone=next?{...next}:null}else{c.data[view]??=[];if(index<0)c.data[view].push(record);else c.data[view][index]=record}save();dialog.close();draw()};dialog.showModal();}
window.v2ProjectPlan={mount(el,context){window.v2Workspace?.timeWork();host=el;c=context;view='overview';query='';filter='open';shell()}};
})();
