/* Project Home: project-derived summaries; no sample deadlines, fees or activity. */
(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'Not set':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
let layout=sessionStorage.getItem('studioh_home_layout')||'r';if(!['p','q','r'].includes(layout))layout='r';let host,ctx,data=null,tab='today',seq=0,loadedId=null;
const displayName=()=>data.name.replace(/ · recovered current$/,'');
const defaultCards=()=>[storage().milestone?'milestone':'budget',storage().tasks.length?'tasks':'scope',storage().approvals.length?'approvals':'history'];
const names={p:'Working studio',q:'Project collection',r:'Daily briefing'};
const button=(label,route)=>`<button data-home-route="${route}">${esc(label)}</button>`;
const img=p=>p.sampleScene?'<span class="home-sample-scene" role="img" aria-label="Sample garden inspiration"></span>':`<img src="${esc(p.url)}" alt="${esc(p.name)}" loading="lazy">`;
const empty=(text,label,route)=>`<div class="home-empty"><p>${esc(text)}</p>${button(label,route)}</div>`;
const card=(title,body)=>`<article class="card"><div class="card-head"><h2>${title}</h2></div>${body}</article>`;
function storage(){ctx.data.tasks??=[];ctx.data.approvals??=[];ctx.data.events??=[];return ctx.data}
function save(event){const s=storage();s.events.unshift({text:event,time:new Date().toISOString()});s.events=s.events.slice(0,30);ctx.save();draw()}
const canEdit=()=>window.v2Experience?.role!=='customer';
const remaining=()=>storage().tasks.filter(t=>!t.done).length;
function days(){const date=storage().milestone?.date;if(!date)return null;const now=new Date();return Math.round((new Date(date+'T00:00:00')-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)}
function pager(id,count){return `<div class="pager"><div class="dots">${Array.from({length:count},(_,i)=>`<button data-home-slide="${id}" data-n="${i}" aria-label="View ${i+1}" aria-current="${!i}"></button>`).join('')}</div><div class="arrows"><button data-home-step="-1" data-target="${id}" aria-label="Previous view">‹</button><button data-home-step="1" data-target="${id}" aria-label="Next view">›</button></div></div>`}
function recap(){const d=data,over=d.budget&&d.estimate!=null?d.estimate-d.budget:null,images=d.images.slice(0,2);return `<article class="visual-recap"><div class="recap-heading"><span class="eyebrow">PROJECT RECAP</span><button data-home-info="recap" class="plain">Sources</button></div><div class="slides" id="home-recap" tabindex="0" aria-label="Project recap"><section class="slide"><h2>${d.images.length?'Your project,<br>coming together.':'A clear place<br>to begin.'}</h2><p>${d.images.length?`${d.images.length} project images are available to explore. `:'Add photos or moodboard selections to bring the project into view. '}${over==null?'Set the budget and estimate to see their comparison here.':`The estimate is ${money(Math.abs(over))} ${over>0?'above':over<0?'below':'from'} the landscape budget.`}</p><div class="recap-evidence">${images.map(x=>`<button data-home-route="mood">${img(x)}</button>`).join('')}${images.length?'<div><b>From your project</b><small>Photos & moodboard selections</small></div>':''}</div></section><section class="slide"><h2>The budget,<br>in perspective.</h2><p>Landscape budget: ${money(d.budget)}<br>Current estimate: ${money(d.estimate)}</p><div class="stat-track"><i style="width:${d.budget&&d.estimate!=null?Math.min(100,d.estimate/d.budget*100):0}%"></i></div>${button('Open estimate','estimate')}</section><section class="slide"><h2>What needs<br>your attention.</h2><p>${remaining()} open Home tasks. ${storage().approvals.filter(a=>!a.done).length} approvals awaiting a recorded decision.</p>${button('Review the project','brief')}</section></div>${pager('home-recap',3)}</article>`}
function cover(){let images=data.images;return `<div class="cover-options"><div class="cover-frame" tabindex="0" aria-label="Project images; swipe or use arrow keys">${images.length?`<div class="cover-slide"><div class="mood-collage">${images.slice(0,3).map((x,i)=>`<div class="${i===0?'collage-main':''}">${img(x)}</div>`).join('')}</div></div>`+images.map(x=>`<div class="cover-slide">${img(x)}</div>`).join(''):`<div class="cover-slide no-cover"><span class="eyebrow">YOUR PROJECT</span><h2>Every garden starts<br>with a conversation.</h2><p>Add your first project image.</p>${button('Add photos','photos')}</div>`}</div></div>`}
function tasks(){const s=storage();return card('Next actions',`<div class="task-scroll" tabindex="0">${s.tasks.length?s.tasks.map((t,i)=>`<label class="task"><input type="checkbox" data-home-task="${i}" ${t.done?'checked':''} ${canEdit()?'':'disabled'}><span>${esc(t.title)}</span></label>`).join(''):empty('Create the next actions for this project.','Review questionnaire','clientbrief')}</div>${canEdit()?'<div class="bottom"><button data-home-edit="task">Add task</button></div>':''}`)}
function approvals(){return card('Pending approvals',storage().approvals.length?storage().approvals.map((a,i)=>`<label class="approval"><input type="checkbox" data-home-approval="${i}" ${a.done?'checked':''} ${canEdit()?'':'disabled'}><span>${esc(a.title)}<small>${a.done?'Recorded '+esc(new Date(a.recorded).toLocaleDateString()):'Awaiting a recorded decision'}</small></span></label>`).join('')+(canEdit()?'<button data-home-edit="approval">Add approval</button>':''):empty('No approval requests have been recorded for this project.','Open client workspace','client')+(canEdit()?'<button data-home-edit="approval">Add approval</button>':''))}
function milestone(){const m=storage().milestone,n=days();return card('Next milestone',m?`<div class="countdown ${n<=2?'urgent':'soon'}"><b class="big">${Math.abs(n)}</b><span>${n<0?'days past due':n===0?'due today':'days to go'}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.date)} · ${m.fixed?'Fixed date':'Target date'}</p><div class="bottom"><button data-home-edit="milestone">Edit milestone</button></div>`:empty('Give the next delivery a date.','Review project information','projectinfo')+'<div class="bottom"><button data-home-edit="milestone">Set milestone</button></div>')}
function budget(){const d=data,v=d.budget&&d.estimate!=null?d.estimate-d.budget:null;return card('Landscape budget',`<small>Current estimate</small><div class="stat-number">${money(d.estimate)}</div><p>Budget ${money(d.budget)}</p><div class="stat-track"><i style="width:${v==null?0:Math.min(100,d.estimate/d.budget*100)}%"></i></div><p>${v==null?'Set a budget to compare.':`${money(Math.abs(v))} ${v>0?'over':v<0?'under':'from'} budget`}</p><div class="bottom">${button('Review estimate','estimate')}</div>`)}
function metric(title,value,desc,route){return card(title,`<div class="stat-number">${esc(value)}</div><p>${esc(desc)}</p><div class="bottom">${button('View details',route)}</div>`)}
function updates(){return card('Latest updates',storage().events.length?storage().events.slice(0,5).map(e=>`<div class="completion-row"><span>${esc(e.text)}</span><small>${esc(new Date(e.time).toLocaleDateString())}</small></div>`).join(''):empty('New Home tasks, milestone changes and recorded approvals will appear here.','Open project files','projectfiles'))}
function renderCard(id){if(id==='history')return card('Project journey',`<p>Current phase · ${esc(data.phase||'Not set')}</p>${(data.history||[]).map(h=>`<div class="completion-row"><span><b>${esc(h.name)}</b><small>${h.date?esc(new Date(h.date).toLocaleDateString()):''}</small></span><strong>${money(h.total)}</strong></div>`).join('')||'<p>No saved phase estimates yet.</p>'}<div class="bottom">${button('Review estimate','estimate')}</div>`);if(id==='tasks')return tasks();if(id==='approvals')return approvals();if(id==='milestone')return milestone();if(id==='budget')return budget();if(id==='updates')return updates();if(id==='fee')return card('Design fee',empty('Project fee reporting is not connected to Home yet.','Open Financials','financials'));if(id==='scope')return metric('Estimate scope',data.active??'—',`${data.empty.length} active sections have no priced amount.`,'estimate');if(id==='area')return metric('Landscape area',data.area?data.area.toLocaleString()+' sf':'Not set','From the project area calculation.','trace');if(id==='files')return metric('Project files',data.files.length,'Documents saved with this project.','projectfiles');if(id==='images')return metric('Project images',data.photoCount,'Photos and references saved in the project.','photos');if(id==='questionnaire')return card('Questionnaire',`<div class="stat-number">${data.briefStarted?'In progress':'Not started'}</div><p>${data.briefCompleted} sections marked complete.</p><div class="bottom">${button('Continue questionnaire','clientbrief')}</div>`);if(id==='tasksProgress')return metric('Completed tasks',storage().tasks.filter(t=>t.done).length+' / '+storage().tasks.length,'Completion is based on your recorded Home tasks.','brief');return ''}
function middle(){const d=data,s=storage();if(layout==='p'){const items=[['Project images',d.images[0],d.photoCount+' references','photos'],['Landscape estimate',null,money(d.estimate),'estimate'],['Project files',null,d.files.length+' saved documents','projectfiles'],['Recorded activity',d.images[1],s.events[0]?.text||'No Home activity yet','brief']];return `<div class="change-bridge"><span class="eyebrow">PROJECT AT A GLANCE</span><div class="bridge-items">${items.map(([title,image,sub,route])=>`<button data-home-route="${route}">${image?img(image):'<span class="initial">'+(title==='Landscape estimate'?'$':'≡')+'</span>'}<span><b>${title}</b><small>${esc(sub)}</small></span></button>`).join('')}</div></div>`}if(layout==='q')return `<div class="section-brief"><span class="eyebrow">TODAY’S FOCUS</span><h3>${remaining()?'<mark>'+esc(s.tasks.find(t=>!t.done).title)+'</mark>':'<mark>Review the brief.</mark> Choose the next action for this project.'}</h3><span>${remaining()} open tasks · ${s.approvals.filter(a=>!a.done).length} pending approvals</span></div>`;let n=days();return `<div class="strong-deadline"><div><b>${n==null?'—':Math.abs(n)}</b><span>${n==null?'Set your next delivery':n<0?'days past due':'days until delivery'}<small>${esc(s.milestone?.title||'Choose a milestone and date')}</small></span></div><div class="deadline-note"><strong>${remaining()} open tasks</strong><small>Project Home actions</small></div><div class="extra-metric"><strong>${s.approvals.filter(a=>!a.done).length} pending approvals</strong><small>Awaiting a recorded decision</small></div><button data-home-edit="milestone">${n==null?'Set':'Review'} milestone ↗</button></div>`}
function draw(){if(!host?.isConnected)return;if(!data){host.innerHTML='<div class="home-empty"><h2>Opening your project</h2><p>Loading the project summary…</p></div>';return}const list=tab==='today'?(storage().cards||defaultCards()):tab==='numbers'?['budget','fee','scope','area','files','images']:['history','tasksProgress','questionnaire','scope','files'];const top=layout==='p'?`<div class="top-p">${recap()}${cover()}</div>`:`<div class="${layout==='q'?'top-q':'top-r'}">${cover()}${recap()}</div>`;host.innerHTML=`<div class="home-heading"><div><span class="eyebrow">${esc(data.address||'YOUR PROJECT')}</span><h1>${esc(displayName())}</h1>${data.sample?'<small>Sample project</small>':''}</div><button data-home-edit="cards">Customize home</button></div>${top}${middle()}<div class="tabs" role="tablist" aria-label="Project focus">${['today','numbers','progress'].map(t=>`<button data-home-tab="${t}" role="tab" aria-selected="${tab===t}">${{today:'Today',numbers:'The numbers',progress:'Progress'}[t]}</button>`).join('')}</div><div class="shelf-heading"><small>${list.length} cards</small><div><button data-home-shelf="-1" aria-label="Previous cards">‹</button><button data-home-shelf="1" aria-label="Next cards">›</button></div></div><div class="card-shelf" role="tabpanel">${list.map(renderCard).join('')}</div><div class="shortcuts"><span>Project shortcuts</span>${['estimate','clientbrief','mood','projectfiles','reports'].map(r=>button({estimate:'Estimate',clientbrief:'Questionnaire',mood:'Moodboard',projectfiles:'Files',reports:'Reports'}[r],r)).join('')}</div>`;if(!canEdit())host.querySelectorAll('[data-home-edit]').forEach(b=>b.hidden=true);host.querySelectorAll('.slides').forEach(el=>el.onscroll=()=>{const i=Math.round(el.scrollLeft/el.clientWidth);host.querySelectorAll(`[data-home-slide="${el.id}"]`).forEach(b=>b.setAttribute('aria-current',+b.dataset.n===i))});host.querySelectorAll('.slides,.cover-frame').forEach(el=>el.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();el.scrollBy({left:el.clientWidth*(e.key==='ArrowRight'?1:-1),behavior:'smooth'})}})}
function dialog(title,body){host.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.className='home-detail';el.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button data-home-close aria-label="Close dialog">×</button></div>${body}`;host.append(el);el.showModal()}
function edit(kind){if(!canEdit())return;const s=storage();if(kind==='cards'){dialog('Customize Project Home',`<form class="home-form" data-home-form="cards">${['milestone','tasks','approvals','updates','budget','scope','history','files'].map(id=>`<label><input type="checkbox" name="card" value="${id}" ${(s.cards||defaultCards()).includes(id)?'checked':''}>${{history:'Project journey',scope:'Estimate scope',milestone:'Next milestone',tasks:'Next actions',approvals:'Pending approvals',updates:'Latest updates',budget:'Landscape budget',files:'Project files'}[id]}</label>`).join('')}<button>Save</button></form>`);return}dialog(kind==='milestone'?'Next milestone':kind==='task'?'Add next action':'Record an approval request',`<form class="home-form" data-home-form="${kind}"><label>Title<input name="title" maxlength="200" required value="${esc(kind==='milestone'?s.milestone?.title||'':'')}"></label>${kind==='milestone'?`<label>Delivery date<input name="date" type="date" required value="${esc(s.milestone?.date||'')}"></label><label><input name="fixed" type="checkbox" ${s.milestone?.fixed!==false?'checked':''}>Fixed date</label><p>Dates are saved as entered. Automatic scheduling is not connected.</p>`:''}<button>Save</button></form>`)}
function bind(){host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.homeTab){tab=b.dataset.homeTab;draw()}if(b.dataset.homeRoute){const r=b.dataset.homeRoute;if(['estimate','mood','brief','client','financials'].includes(r))ctx.open(r);else ctx.tool(r)}if(b.dataset.homeEdit)edit(b.dataset.homeEdit);if(b.hasAttribute('data-home-close'))b.closest('dialog').close();if(b.dataset.homeInfo)dialog('Project recap sources','<p>This summary uses the current project’s budget, calculated estimate, images, files and Home records. It is a deterministic summary; AI writing and cross-project scheduling are not connected.</p>');if(b.dataset.homeShelf)host.querySelector('.card-shelf').scrollBy({left:host.querySelector('.card-shelf').clientWidth*+b.dataset.homeShelf,behavior:'smooth'});if(b.dataset.homeSlide){const el=host.querySelector('#'+b.dataset.homeSlide);el.scrollTo({left:el.clientWidth*+b.dataset.n,behavior:'smooth'})}if(b.dataset.homeStep){const el=host.querySelector('#'+b.dataset.target);const next=(Math.round(el.scrollLeft/el.clientWidth)+ +b.dataset.homeStep+el.children.length)%el.children.length;el.scrollTo({left:el.clientWidth*next,behavior:'smooth'})}};
host.onchange=e=>{if(!canEdit())return;const t=e.target;if(t.dataset.homeTask!==undefined){storage().tasks[+t.dataset.homeTask].done=t.checked;save('Task '+(t.checked?'completed':'reopened'))}if(t.dataset.homeApproval!==undefined){Object.assign(storage().approvals[+t.dataset.homeApproval],{done:t.checked,recorded:new Date().toISOString()});save('Designer '+(t.checked?'recorded':'reopened')+' an approval')}};
host.onsubmit=e=>{const kind=e.target.dataset.homeForm;if(!kind)return;e.preventDefault();if(!canEdit())return;const f=new FormData(e.target),s=storage();if(kind==='cards')s.cards=f.getAll('card');else if(kind==='milestone')s.milestone={title:f.get('title').trim(),date:f.get('date'),fixed:f.has('fixed')};else s[kind==='task'?'tasks':'approvals'].push({title:f.get('title').trim(),done:false});save(kind==='cards'?'Home cards updated':kind==='milestone'?'Milestone updated':kind==='task'?'Task added':'Approval request added')};}
async function refresh(){const token=++seq,id=ctx.projectId;try{const result=await v2Preview.plantRequest('home-summary');if(token!==seq||id!==ctx.projectId)return;data=result;loadedId=id;draw()}catch(e){if(token===seq&&host?.isConnected){host.innerHTML='<div class="home-empty"><h2>Project summary is not available yet</h2><button data-home-retry>Try again</button></div>';host.querySelector('button').onclick=refresh}}}
window.addEventListener('message',e=>{if(e.source===document.getElementById('v2-engine')?.contentWindow&&e.data?.v2==='ready'&&window.v2Workspace?.active==='home'&&host?.isConnected)refresh()});
window.v2Home={get layout(){return layout},setLayout(value){if(window.v2Experience?.role!=='developer'||!['p','q','r'].includes(value))return;layout=value;sessionStorage.setItem('studioh_home_layout',value)},mount(el,context){host=el;ctx=context;if(loadedId!==ctx.projectId)data=null;storage();draw();bind();if(window.v2Preview?.ready)refresh();else{const token=++seq;let attempts=0;const timer=setInterval(()=>{if(token!==seq||!host?.isConnected||attempts++>60){clearInterval(timer);return}if(window.v2Preview?.ready){clearInterval(timer);refresh()}},250)}}};
})();
