// Project document register. Originals travel with project exports in the isolated preview.
function v2ProjectFiles(){
 if(window.v2ExperienceRole==='customer')return;
 document.getElementById('v2-project-files')?.remove();
 const host=document.createElement('section');host.id='v2-project-files';const esc=v2PhotoEscape;
 const files=S.v2ProjectFiles??=[];
 host.innerHTML=`<h1>Your project files.</h1><p>Plans, photos and source documents, together with the project they belong to.</p><section class="v2-files-connect"><div><small>PROJECT SOURCES</small><h2>Bring the project together.</h2><p>Upload a plan to trace, collect site photos, or keep the documents behind your project decisions.</p><button class="btn primary" data-upload>Add files →</button> <button class="btn" data-dropbox>Connect Dropbox</button></div><div><h3>Project folder</h3><p>Dropbox is not connected.</p><p>Website account sign-in and Dropbox app authorization are needed before a folder can sync.</p></div></section><input type="file" hidden multiple accept=".pdf,.dxf,.dwg,.txt,.jpg,.jpeg,.png,.webp"><p id="v2-files-status" role="status">Files are saved with this project on this device. Export the project for a backup. Cloud sync and AI extraction are not connected.</p><section class="v2-files-list"><header><h2>Project documents</h2><span>${files.length} files</span></header>${files.length?files.map((f,i)=>`<article><div><strong>${esc(f.name)}</strong><small>${esc(f.category)} · ${Math.round(f.size/1024)} KB · Uploaded ${esc(f.date)}</small></div><label>Category<select data-category="${i}">${['Plans','HOA & guidelines','Address & contacts','Proposals & fees','Other'].map(c=>`<option ${c===f.category?'selected':''}>${c}</option>`).join('')}</select></label><div class="v2-file-actions">${/\.(pdf|dxf)$/i.test(f.name)?`<button class="btn" data-trace="${i}">Open in tracer</button>`:''}<button class="btn" data-download="${i}">Download</button><button class="btn" data-remove="${i}">Remove</button></div></article>`).join(''):'<div class="v2-files-empty"><h3>No documents yet</h3><p>Add a PDF, DXF, text document or photo. Photos go into Photos & references.</p></div>'}</section><section class="v2-files-review"><h2>Review before applying</h2><p>Source documents stay here. Open them to review their contents, then update the relevant project fields.</p><div><button class="btn" data-info>Open Project info →</button><button class="btn" data-photos>Open Photos & references →</button></div><p>Automatic address, HOA and proposal extraction will require the connected account service. No project values are changed by uploading a document.</p></section>`;
 document.body.append(host);const status=host.querySelector('#v2-files-status'),input=host.querySelector('input[type=file]');
 host.querySelector('[data-upload]').onclick=()=>input.click();
 host.querySelector('[data-dropbox]').onclick=()=>{status.textContent='Dropbox setup needed: Studio H needs its own registered Dropbox app and account sign-in. Your Dropbox connection in Codex does not connect this website. Local uploads work now.';status.scrollIntoView({block:'nearest'})};
 host.querySelector('[data-info]').onclick=()=>parent.postMessage({v2:'open-project-info'},'*');
 host.querySelector('[data-photos]').onclick=()=>parent.postMessage({v2:'open-photos'},'*');
 input.onchange=async()=>{const project=S;let error='';for(const file of input.files){try{
 if(!/\.(pdf|dxf|dwg|txt|jpe?g|png|webp)$/i.test(file.name))throw Error('Use PDF, DXF, DWG, TXT, JPG, PNG or WebP.');
 if(/\.(jpe?g|png|webp)$/i.test(file.name)){if(file.size>15*1024*1024)throw Error('Photos must be under 15 MB.');const url=await v2PhotoResize(file);if(S!==project)return;v2PhotoItems().push({id:crypto.randomUUID(),name:file.name,url,kind:'Site overview',v2Category:'Site photos',addedBy:'Designer'});v2PhotoChanged();continue}
 if(file.size+files.reduce((n,f)=>n+f.size,0)>1500000)throw Error('This device preview allows 1.5 MB of source documents per project. Larger plans can be opened directly in Programming. Cloud file storage needs account setup.');
 const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read file'));r.readAsDataURL(file)});if(S!==project)return;
 files.push({id:crypto.randomUUID(),name:file.name,size:file.size,data,date:new Date().toLocaleDateString(),category:/\.(dxf|dwg)$/i.test(file.name)?'Plans':/hoa|guideline/i.test(file.name)?'HOA & guidelines':/proposal|fee/i.test(file.name)?'Proposals & fees':'Other'});_bidSchedule();
 }catch(e){error=file.name+': '+e.message;break}}v2ProjectFiles();document.querySelector('#v2-files-status').textContent=error||'Files added. Photos are available in Photos & references. Export your project for a backup.'};
 host.querySelectorAll('[data-category]').forEach(b=>b.onchange=()=>{files[+b.dataset.category].category=b.value;_bidSchedule()});
 host.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>{const f=files[+b.dataset.download],a=document.createElement('a');a.href=f.data;a.download=f.name;a.click()});
 host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Remove this source document from the project?')){files.splice(+b.dataset.remove,1);_bidSchedule();v2ProjectFiles()}});
 host.querySelectorAll('[data-trace]').forEach(b=>b.onclick=async()=>{const f=files[+b.dataset.trace];if((PT.pdfData||PT.satBase)&&!confirm('Replace the current plan and tracing? Export your project first to keep a backup.'))return;try{const bytes=Uint8Array.from(atob(f.data.split(',')[1]),c=>c.charCodeAt(0));const data=/\.dxf$/i.test(f.name)?await v2DxfPdf(new TextDecoder().decode(bytes)):bytes.buffer;if(await _ptOpenDocBuf(data,false)){S.v2Programming={name:f.name};_bidSchedule()}}catch(e){status.textContent=e.message}});
}
