/* Approved J layout. Read-only progress from the current project engine. */
(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=['Project info','Questionnaire','Photos & references','Programming'],routes=['projectinfo','clientbrief','photos','trace'];
let seq=0,scopeSaving=false;
function sitePlan(){return '<img src="assets/programming-plan-v2.png" alt="Illustrative watercolor garden plan with a residence, pool, paving and planting">'}
function sun(){return `<svg viewBox="0 0 120 85" role="img" aria-label="Sun path illustration"><path d="M10 68Q60 -20 110 68" fill="none" stroke="#b8c9a9" stroke-width="1.5" stroke-dasharray="3 4"/><path d="M9 72H111M43 72V55l17-12 17 12v17" fill="none" stroke="#9bad8e" stroke-width="1.5"/><circle cx="66" cy="23" r="10" fill="#d2deb9"/><g stroke="#b5c49d"><path d="M66 8V3M66 43V38M81 23H86M46 23H51M77 12l4-4M55 34l-4 4M55 12l-4-4M77 34l4 4"/></g></svg>`}
function image(x){if(x.sampleScene)return '<svg class="scene" viewBox="386 514 380 507" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Sample garden inspiration"><image href="assets/asian-scenes.png" width="1536" height="1024"/></svg>';const url=String(x.url||'');return /^(https?:|data:image\/|blob:)/.test(url)?`<img src="${esc(url)}" alt="${esc(x.name||'Project reference')}" loading="lazy">`:''}
function render(d){
 const sets=d.setup||[[],[],[],[]],counts=sets.map(a=>[a.filter(x=>x[1]).length,a.length]),pct=i=>counts[i][1]?Math.round(counts[i][0]/counts[i][1]*100):0,complete=i=>counts[i][1]>0&&counts[i][0]===counts[i][1];
 const images=d.images||[],refs=images.slice(0,3).map(image).join(''),remaining=i=>counts[i][1]-counts[i][0];
 const badge=i=>complete(i)?'<span class="badge done"><span class="check">✓</span>Complete</span>':`<span class="badge">${counts[i][0]} / ${counts[i][1]}</span>`;
 const art=i=>i===0?`<div class="card-art garden">${images[0]?image(images[0]):'<div class="setup-placeholder">Your project image</div>'}<small>${esc(d.address||'Add the site address')}</small></div>`:i===1?`<div class="card-art q-art"><div><b>${pct(1)}%</b><small style="display:block">of the brief reviewed</small></div><span class="mini-ring" style="background:conic-gradient(#bf9ba7 ${pct(1)}%,#eadbe0 0)"></span></div>`:i===2?`<div class="card-art ${images.length?'photo-art':'empty-art'}">${refs||'A site photo.<br>A favorite material.<br>A place to begin.'}</div>`:`<div class="card-art plan-art" title="Programming illustration · ${Number(d.traceCount)||0} traced items">${sitePlan()}</div>`;
 let next=counts.findIndex((_,i)=>!complete(i));if(next<0)next=1;
 const nextItem=sets[next].find(x=>!x[1])?.[0];
 const bars=(d.groups||[]).filter(g=>g.amount>0).slice(0,5),max=Math.max(1,...bars.map(g=>g.amount));
 const chart=`<svg viewBox="0 0 120 85" role="img" aria-label="Estimate group costs">${bars.map((g,i)=>`<rect x="${i*24}" y="${80-g.amount/max*70}" width="17" height="${g.amount/max*70}" rx="4" fill="#c3d5de"><title>${esc(g.name)}: ${esc(g.amount)}</title></rect>`).join('')}</svg>`;
 return `<div class="identity"><div><span class="eyebrow">${esc(d.name)}</span><h1>Setup</h1><p>The starting points for a thoughtful design.</p></div><span class="overall"><i></i>${counts.filter((_,i)=>complete(i)).length} of 4 steps complete</span></div>
 <section class="lead"><article class="focus"><div class="focus-content"><div class="ring" style="--progress:${pct(next)}%"><div><b>${pct(next)}%</b><small>${next===1?'Brief reviewed':'Complete'}</small></div></div><div><span class="eyebrow">UP NEXT · ${names[next]}</span><h3>${esc(nextItem||'Your setup is ready to review.')}</h3><p>${['Confirm the people, property and budget for this project.','Review client priorities, preferences and site requirements.','Collect references and review them in the questionnaire.','Choose a source, confirm scale and define the design areas.'][next]}</p></div></div><div class="focus-actions"><button class="primary" data-setup-tool="${next}">${complete(next)?'Review':'Continue'} ${names[next].toLowerCase()} →</button><small>${remaining(next)} ${next===1?'sections':'items'} remaining</small></div></article>
 <article class="references"><div class="reference-head"><h2>Starting references</h2></div>${refs?`<div class="reference-strip">${refs}</div>`:'<div class="reference-empty"><b>Start with what you have.</b><small>A site photo or one idea. No moodboard required.</small></div>'}<small>Collect here. Build your moodboard in Design.</small></article></section>
 <div class="section-title"><h2>Your setup steps</h2><small>A guide, not a fixed order.</small></div><section class="step-grid">${names.map((name,i)=>`<button class="step-card" data-setup-tool="${i}" aria-label="Open ${name}" title="${esc(sets[i].map(x=>(x[1]?'✓ ':'○ ')+x[0]).join(' · '))}"><div class="card-top"><span class="step-number">0${i+1}</span>${badge(i)}</div><h2>${name}</h2>${art(i)}<p>${['People, property and the project essentials.','Understand how the client wants to live outside.','Capture the site and gather early inspiration.','Define the work area and the spaces to include.'][i]}</p><div class="progress-line" role="progressbar" aria-label="${name} completion" aria-valuemin="0" aria-valuemax="${counts[i][1]}" aria-valuenow="${counts[i][0]}"><i style="width:${pct(i)}%"></i></div><div class="card-footer"><span>${complete(i)?'Ready to review':remaining(i)+' '+(i===1?'sections':'items')+' remaining'}</span><span class="go">↗</span></div></button>`).join('')}</section>
 <div class="section-title"><div><h2>Reference throughout the project</h2><small>Useful during setup. Richer as your design develops.</small></div></div><section class="reference-grid"><button class="resource" data-setup-tool="insights"><div><h2>Project Insights</h2><p>Property, planting, water and cost in context.</p><span class="open">Explore insights ↗</span></div>${chart}</button><button class="resource" data-setup-tool="knowledge"><div><h2>Site Knowledge</h2><p>Sun, access, drainage and site requirements.</p><span class="open">Explore site knowledge ↗</span></div>${sun()}</button></section><div class="design-link"><div><b>Ready to develop the design?</b><small>Your setup information stays available as the project evolves.</small></div><button data-setup-tool="design">Open Design →</button></div>`;
}
function scopePanel(host,model){
 const agreed=model.scopeAgreement,selectedPhases=new Set(agreed?.phaseIds||model.phases.filter(p=>p.applicable!==false).map(p=>p.id)),selectedDeliverables=new Set(model.steps.filter(n=>n.kind==='deliverable'&&!(agreed?.excludedDeliverableIds||[]).includes(n.id)).map(n=>n.id));let busy=false;
 const section=document.createElement('section');section.className='setup-scope';host.querySelector('.step-grid').after(section);
 function paint(){section.innerHTML=`<div class="section-title"><div><span class="eyebrow">PROJECT SCOPE · ${agreed?'CONFIRMED':'DRAFT'}</span><h2>Confirm the work before you begin.</h2><p>Choose the phases and deliverables agreed for this project. Their tasks form your working Process.</p></div></div>${agreed?'<p class="scope-note">Changing this selection revises the confirmed scope. Check it against your agreement before confirming.</p>':'<p class="scope-note">This is a proposed starting checklist. Consultation can proceed while the project scope is being agreed.</p>'}<div class="scope-phases">${model.phases.map((p,i)=>`<details ${p.id==='consult'?'':'open'}><summary><span>${i+1}. ${esc(p.t)}</span><label><input type="checkbox" data-scope-phase="${p.id}" ${selectedPhases.has(p.id)?'checked':''} ${p.id==='consult'?'disabled':''}> ${p.id==='consult'?'Always available':'In scope'}</label></summary><div class="scope-deliverables">${model.steps.filter(n=>n.ph===p.id&&n.kind==='deliverable'&&!n.track).map(n=>`<label><input type="checkbox" data-scope-deliverable="${esc(n.id)}" ${selectedDeliverables.has(n.id)?'checked':''} ${p.id==='consult'||n.hard||n.rule==='above-contracted-maximum'||!selectedPhases.has(p.id)?'disabled':''}> <span>${esc(n.t)}${n.rule==='above-contracted-maximum'?' · only when required by the budget comparison':''}</span></label>`).join('')||'<p>Standalone tasks are included with this phase.</p>'}</div></details>`).join('')}</div><p>Excluding work keeps its saved tasks, notes and time intact. It removes that work from the applicable Process.</p><div class="scope-actions"><button class="primary" data-confirm-scope ${v2Cloud.readOnly?'disabled':''}>${agreed?'Confirm revised scope':'Confirm scope & open Process'} →</button><button data-preview-process>View ${agreed?'Process':'draft Process'} →</button></div><p role="status" data-scope-status></p>`;}
 section.addEventListener('change',e=>{const d=e.target.dataset;if(d.scopePhase){e.target.checked?selectedPhases.add(d.scopePhase):selectedPhases.delete(d.scopePhase);paint()}if(d.scopeDeliverable)e.target.checked?selectedDeliverables.add(d.scopeDeliverable):selectedDeliverables.delete(d.scopeDeliverable)});
 section.addEventListener('click',async e=>{if(e.target.closest('[data-preview-process]')){v2Workspace.open('process');return}if(!e.target.closest('[data-confirm-scope]')||busy||v2Cloud.readOnly)return;busy=true;scopeSaving=true;const button=section.querySelector('[data-confirm-scope]'),status=section.querySelector('[data-scope-status]');button.disabled=true;status.textContent='Saving confirmed scope…';try{const project=v2Cloud.projectId;if(!host.isConnected)throw Error('Reopen Setup before confirming.');await v2Preview.plantRequest('process-v2-save',{revision:model.revision,process:{...model,scopeConfirm:true,scopeSelection:{phaseIds:[...selectedPhases],deliverableIds:[...selectedDeliverables]}}});if(project!==v2Cloud.projectId)throw Error('Project changed. Reopen Setup.');await v2Preview.capture();await v2Cloud.flush();status.textContent='Scope confirmed and saved.';scopeSaving=false;v2Workspace.open('process')}catch(error){status.textContent='Scope not confirmed on the server. '+error.message+' Reopen Setup to review and retry.'}finally{busy=false;scopeSaving=false;button.disabled=!!v2Cloud.readOnly}});paint();
}

window.v2Setup={render,hasPending:()=>scopeSaving,mount(host){const token=++seq,id=window.v2Cloud?.projectId;host.innerHTML='<p role="status">Loading your project setup…</p>';host.onclick=e=>{const b=e.target.closest('[data-setup-tool]');if(!b)return;const key=b.dataset.setupTool;if(key==='knowledge'){v2Workspace.open('studies');return}if(key==='design'){v2Workspace.open('design');return}const i=Number(key);v2Preview.show(key==='insights'?'insights':routes[i],key==='insights'?'Project Insights':names[i]);document.getElementById('v2-back').textContent='← Setup'};
 async function load(){try{let attempts=0;while(!v2Preview.ready&&attempts++<60){await new Promise(r=>setTimeout(r,250));if(token!==seq||!host.isConnected)return}const d=await v2Preview.plantRequest('setup-summary');if(token!==seq||!host.isConnected||id!==window.v2Cloud?.projectId)return;host.innerHTML=render(d);const process=await v2Preview.plantRequest('process-v2-read');if(token!==seq||!host.isConnected||id!==window.v2Cloud?.projectId)return;scopePanel(host,process)}catch(e){if(token!==seq||!host.isConnected)return;host.innerHTML='<h2>Project setup could not load</h2><p>Please try again.</p><button data-setup-retry>Try again</button>';host.querySelector('button').onclick=load}}load();}};
})();
