/* Project Home: project-derived summaries; no sample deadlines, fees or activity. */
(()=>{'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null?'Not set':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
let layout=sessionStorage.getItem('studioh_home_layout')||'r';if(!['p','q','r'].includes(layout))layout='r';let host,ctx,data=null,tab='today',seq=0,loadedId=null;
const displayName=()=>data.name.replace(/ · recovered current$/,'');
const defaultCards=()=>layout==='r'?['tasks','approvals','updates']:['milestone','tasks','approvals'];
const names={p:'Working studio',q:'Project collection',r:'Daily briefing'};
const button=(label,route)=>`<button data-home-route="${route}">${esc(label)}</button>`;
const img=p=>p.sampleScene?'<svg class="home-sample-scene" viewBox="386 514 380 507" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Sample garden inspiration"><image href="assets/asian-scenes.png" width="1536" height="1024"/></svg>':`<img src="${esc(p.url)}" alt="${esc(p.name)}" loading="lazy">`;
const empty=(text,label,route)=>`<div class="home-empty"><p>${esc(text)}</p>${button(label,route)}</div>`;
const card=(title,body)=>`<article class="card"><div class="card-head"><h2>${title}</h2></div>${body}</article>`;
function storage(){ctx.data.tasks??=[];ctx.data.approvals??=[];ctx.data.events??=[];return ctx.data}
function save(event){const s=storage();s.events.unshift({text:event,time:new Date().toISOString()});s.events=s.events.slice(0,30);ctx.save();draw()}
const canEdit=()=>!window.v2Cloud?.readOnly&&window.v2Experience?.role!=='customer';
const remaining=()=>storage().tasks.filter(t=>!t.done).length;
function days(){const date=storage().milestone?.date;if(!date)return null;const now=new Date();return Math.round((new Date(date+'T00:00:00')-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000)}
function pager(id,count){return `<div class="pager"><div class="dots">${Array.from({length:count},(_,i)=>`<button data-home-slide="${id}" data-n="${i}" aria-label="View ${i+1}" aria-current="${!i}"></button>`).join('')}</div><div class="arrows"><button data-home-step="-1" data-target="${id}" aria-label="Previous view">‹</button><button data-home-step="1" data-target="${id}" aria-label="Next view">›</button></div></div>`}

function seedSample(){
 const s=storage();if(!data.sample||s.sampleVersion)return false;
 const date=new Date();date.setDate(date.getDate()+4);const due=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');
 s.references??=[{url:'sample-garden',name:'Garden concept',sampleScene:true},{url:new URL('assets/med-materials.png',location.href).href,name:'Material palette'},{url:new URL('assets/lounge-chair.png',location.href).href,name:'Outdoor lounge selection'}];
 if(!s.tasks.length)s.tasks=[{title:'Confirm material palette',owner:'Alex',detail:'client decision',hours:.5,done:false},{title:'Finish planting plan',owner:'Maya',detail:'design development',hours:4,done:false},{title:'Coordinate lighting',owner:'Maya',detail:'design development',hours:3,done:false},{title:'Update the estimate',owner:'Alex',detail:'after palette review',hours:2,done:false},{title:'Assemble the review set',owner:'Maya',detail:'internal review',hours:4,done:false}];
 if(!s.approvals.length)s.approvals=[{title:'Material palette',detail:'Needed before final specifications',done:false},{title:'Pool coping selection',detail:'Client review · awaiting response',done:false}];
 s.milestone??={title:'Design development delivery',date:due,fixed:true,owner:'Alex'};
 s.fee??={agreed:36000,cost:18400,remaining:7200,invoiced:24000,collected:18000};
 s.hours??=[{phase:'Discovery',logged:18,planned:20},{phase:'Concept',logged:40,planned:48},{phase:'Development',logged:34,planned:60}];
 s.capacity??=12;
 s.journey??=[{name:'Discovery',done:9,total:9,status:'completed'},{name:'Concept',done:11,total:13,status:'open'},{name:'Design development',done:8,total:14,status:'current'},{name:'Documentation',done:0,total:11,status:''},{name:'Bidding',done:0,total:6,status:''}];
 s.updates??=[{title:'Material palette refined',by:'Maya',date:new Date().toISOString(),description:'Review the palette before finalizing specifications.',image:s.references[1]},{title:'Outdoor lounge selection added',by:'Alex',date:new Date().toISOString(),description:'A furniture reference is ready for review.',image:s.references[2]},{title:'Concept reference updated',by:'Maya',date:new Date().toISOString(),description:'Review the outdoor living direction alongside the latest work.',image:s.references[0]},{title:'Estimate ready for review',by:'Alex',date:new Date().toISOString(),description:'Review the current project estimate and budget.',image:s.references[0]}];
 s.savings??=[{title:'Specification swaps',amount:9400},{title:'Adjust selected finishes',amount:6300},{title:'Consider a later phase',amount:6400}];s.deliverables??=[{title:'Concept direction',ready:true},{title:'Planting plan',ready:true},{title:'Material palette',ready:true},{title:'Lighting plan',ready:false},{title:'Review set',ready:false}];s.sampleVersion=1;s.sampleRecordNote='Demonstration workflow records added for the sample project; estimate remains calculated from project selections.';ctx.save();return true;
}
const projectImages=()=>storage().references?.length?[...storage().references,...data.images]:data.images;
const hhead=(title,action,label)=>`<div class="card-head"><h2>${title}</h2>${action?`<button data-home-edit="${action}">${label||'Edit'}</button>`:''}</div>`;
const hoursLeft=()=>storage().tasks.filter(t=>!t.done).reduce((n,t)=>n+(Number(t.hours)||0),0);
const taskRows=()=>storage().tasks.map((t,i)=>`<label class="task"><input type="checkbox" data-home-task="${i}" ${t.done?'checked':''} ${canEdit()?'':'disabled'}><span>${esc(t.title)}<small>${esc([t.owner,t.detail].filter(Boolean).join(' · '))}</small></span><small>${t.hours==null?'':esc(t.hours)+' h'}</small></label>`).join('');
function album(){const all=projectImages(),images=all.length>1?all.slice(1):all;return `<div class="q-album"><div class="album-top"><div class="album-detail"><div class="slides" id="home-album" tabindex="0">${images.map(p=>`<section class="slide"><button data-home-route="mood">${img(p)}</button><div><span class="eyebrow">PROJECT DIRECTION</span><h3>${esc(p.name)}</h3><p>${data.sample?'Sample project reference':'From your project'}</p></div></section>`).join('')||'<section class="slide"><h3>Add your first reference</h3></section>'}</div>${pager('home-album',images.length||1)}</div></div><button class="gallery-toggle" data-home-gallery>Play images</button></div>`}

function recap(){const d=data,s=storage(),over=d.budget&&d.estimate!=null?d.estimate-d.budget:null,images=projectImages().slice(1,3),pending=s.approvals.filter(a=>!a.done).length;return `<article class="visual-recap"><div class="recap-heading"><span class="eyebrow">PROJECT RECAP${d.sample?' · SAMPLE':''}</span><button data-home-info="recap" class="plain">Sources</button></div><div class="slides" id="home-recap" tabindex="0"><section class="slide"><h2>The details are<br>coming together.</h2><p>The palette and outdoor living selections are taking shape. ${pending} decisions need a response before the next issue.</p><div class="recap-evidence">${images.map(x=>`<button data-home-route="mood">${img(x)}</button>`).join('')}<div><b>Follow the changes.</b><small>Palette & furniture<br>${d.sample?'Sample project references':'Project references'}</small></div></div></section><section class="slide"><h2>A little room<br>to rebalance.</h2><p>${over==null?'Set the landscape budget to compare.':`The estimate is ${Math.abs(over/d.budget*100).toFixed(1)}% ${over>0?'above':'below'} budget. Review the selections while keeping the design intent.`}</p><svg class="diagram" viewBox="0 0 380 110"><text x="0" y="15">Budget · ${money(d.budget)}</text><rect x="0" y="26" width="${Math.max(d.budget||0,0)/Math.max(d.budget||0,d.estimate||0,1)*360}" height="18" rx="4" fill="#b8c9af"/><text x="0" y="72">Estimate · ${money(d.estimate)}</text><rect x="0" y="84" width="${Math.max(d.estimate||0,0)/Math.max(d.budget||0,d.estimate||0,1)*360}" height="18" rx="4" fill="#dbb7c2"/></svg></section><section class="slide"><h2>Protect the time<br>for the final details.</h2><p>${hoursLeft()} hours of recorded work remain before delivery.</p><div class="recap-stat"><strong>${s.capacity==null?'—':Math.max(0,hoursLeft()-s.capacity)+' h'}</strong><span>capacity gap<small>Based on recorded work and availability</small></span></div><button data-home-edit="task">Review the plan</button></section><section class="slide"><h2>One decision can<br>unlock the next step.</h2><p>${s.approvals.filter(a=>a.done).length} of ${s.approvals.length} approvals are recorded. Review the remaining decisions before the final specification review.</p><div class="recap-evidence">${images[0]?`<button data-home-route="mood">${img(images[0])}</button>`:''}<div><b>${esc(s.approvals.find(a=>!a.done)?.title||'Review the next step')}</b><small>Project decision record</small></div></div></section><section class="slide"><h2>The week,<br>made manageable.</h2><p>Start with decisions, then focus on the design. Protect time for a final review before delivery.</p><div class="mini-week">${s.tasks.slice(0,5).map((t,i)=>`<span><b>${['M','T','W','T','F'][i]}</b>${esc(t.title)}</span>`).join('')}</div></section></div>${pager('home-recap',5)}</article>`}
function cover(){let images=projectImages();return `<div class="cover-options"><div class="cover-frame" tabindex="0" aria-label="Project images; swipe or use arrow keys">${images.length?`<div class="cover-slide"><div class="mood-collage">${images.slice(0,3).map((x,i)=>`<div class="${i===0?'collage-main':''}">${img(x)}</div>`).join('')}</div></div>`+images.map(x=>`<div class="cover-slide">${img(x)}</div>`).join(''):`<div class="cover-slide no-cover"><span class="eyebrow">YOUR PROJECT</span><h2>Every garden starts<br>with a conversation.</h2><p>Add your first project image.</p>${button('Add photos','photos')}</div>`}</div></div>`}
function tasks(){return `<article class="card tasks">${hhead('Next actions','task','Task roadmap')}<div class="task-scroll" tabindex="0">${taskRows()||'<p>Add the next actions for this project.</p>'}</div><div class="bottom"><button data-home-edit="task">View all tasks</button></div></article>`}
function approvals(){return `<article class="card">${hhead('Pending approvals','approval','View record')}${storage().approvals.map((a,i)=>`<label class="approval"><input type="checkbox" data-home-approval="${i}" ${a.done?'checked':''} ${canEdit()?'':'disabled'}><span>${esc(a.title)}<small>${a.done?'Approval recorded · uncheck to undo':esc(a.detail||'Awaiting a recorded decision')}</small></span></label>`).join('')||'<p>No approvals recorded yet.</p>'}<p>Already received a decision? Check it here.</p></article>`}
function milestone(){const m=storage().milestone,n=days();return `<article class="card milestone blue">${hhead('Next milestone','milestone','Edit')}<div class="slides" id="home-milestone" tabindex="0"><section class="slide"><div class="countdown ${n<=2?'urgent':n<=7?'soon':'calm'}"><b class="big">${n==null?'—':Math.abs(n)}</b><span>${n<0?'days past due':'days to go'}</span></div><h3>${esc(m?.title||'Choose your next milestone')}</h3><small class="date">${esc(m?.date||'No date set')} · ${m?.fixed?'Fixed deadline':'Target date'}${m?.owner?' · '+esc(m.owner):''}</small><div class="small-line"><span>${remaining()} tasks remaining</span><button class="plain" data-home-slide="home-milestone" data-n="1">View tasks →</button></div><div class="track"><span style="width:${storage().tasks.length?(1-remaining()/storage().tasks.length)*100:0}%"></span></div></section><section class="slide">${taskRows()}</section></div>${pager('home-milestone',2)}</article>`}
function budget(){const d=data,delta=d.budget&&d.estimate!=null?d.estimate-d.budget:null,max=Math.max(d.budget||0,d.estimate||0,1),bw=(d.budget||0)/max*398,ew=(d.estimate||0)/max*398;return `<article class="card"><div class="card-head"><h2>Landscape budget</h2><button data-home-route="estimate">Open estimate</button></div><small>Current estimate</small><div class="metric-top"><strong>${money(d.estimate)}</strong><span class="delta">${delta==null?'Budget not set':Math.abs(delta/d.budget*100).toFixed(1)+'% '+(delta>0?'over':'under')+' budget'}</span></div><svg class="budget-svg" viewBox="0 0 400 79" role="img" aria-label="Estimate compared with budget"><rect x="0" y="25" width="398" height="19" rx="5" fill="#edf1e9"/><rect x="0" y="25" width="${ew}" height="19" rx="5" fill="#b6c6ad"/>${ew>bw?`<rect x="${bw}" y="25" width="${ew-bw}" height="19" fill="#dbb8c2"/>`:''}<path d="M${bw} 15v39" stroke="#6b7866"/><text x="0" y="70">$0</text><text x="230" y="9">Budget ${money(d.budget)}</text></svg><div class="budget-caption"><span>${delta>0?'Above':'Below'} budget</span><b>${delta==null?'—':money(Math.abs(delta))}</b></div><div class="bottom">${button(delta>0?'View potential savings':'Review upgrade options','estimate')}</div></article>`}
function metric(title,value,desc,route){return card(title,`<div class="stat-number">${esc(value)}</div><p>${esc(desc)}</p><div class="bottom">${button('View details',route)}</div>`)}
function updates(){const updates=storage().updates||[];return `<article class="card update-card">${hhead('Latest updates','updates','View all')}<div class="slides" id="home-updates" tabindex="0">${updates.map((u,i)=>`<section class="slide"><button class="update-photo" data-home-update="${i}">${u.image?img(u.image):'<span class="update-graphic">Project update</span>'}</button><div class="update-copy"><span class="eyebrow">${data.sample?'SAMPLE PROJECT ACTIVITY':'PROJECT ACTIVITY'}</span><h3>${esc(u.title)}</h3><small>${esc(u.by||'Project team')} · ${esc(new Date(u.date).toLocaleDateString())}</small><p>${esc(u.description)}</p><button class="plain" data-home-update="${i}">View update ↗</button></div></section>`).join('')||'<section class="slide"><h3>No updates yet</h3><p>Recorded project changes will appear here.</p></section>'}</div>${pager('home-updates',updates.length||1)}</article>`}

function financeCard(kind){const f=storage().fee;if(!f)return card(kind==='fee'?'Design fee':kind==='cash'?'Invoicing':'Design hours','<p>Add the project financial records to see this card.</p><button data-home-edit="finance">Set up records</button>');const profit=f.agreed-f.cost-f.remaining;
 if(kind==='fee')return `<article class="card">${hhead('Design fee','finance','Financials')}<small>Projected profit</small><div class="fee-total"><b>${money(profit)}</b><span class="phase">${f.agreed?(profit/f.agreed*100).toFixed(1):0}% margin</span></div><div class="budget-caption"><span>Agreed fee</span><b>${money(f.agreed)}</b></div><div class="fee-bar">${[f.cost,f.remaining,Math.max(0,profit)].map(v=>`<span style="width:${f.agreed?v/f.agreed*100:0}%"></span>`).join('')}</div><div class="fee-legend">${[['Cost to date',f.cost],['To complete',f.remaining],['Projected profit',profit]].map(([t,v])=>`<div><small>${t}</small><b>${money(v)}</b></div>`).join('')}</div></article>`;
 if(kind==='cash')return `<article class="card">${hhead('Invoicing','finance','Details')}<div class="stat-number">${money(f.collected)}</div><p>Collected of ${money(f.invoiced)} invoiced</p><div class="stat-track"><i style="width:${f.invoiced?f.collected/f.invoiced*100:0}%"></i></div><div class="stat-pair"><span>Outstanding<b>${money(f.invoiced-f.collected)}</b></span><span>Agreed fee<b>${money(f.agreed)}</b></span></div></article>`;
 const hours=storage().hours||[];return `<article class="card">${hhead('Design hours','finance','Details')}<div class="stat-number">${hours.reduce((n,h)=>n+h.logged,0)} h</div><p>Logged against ${hours.reduce((n,h)=>n+h.planned,0)} planned hours</p><div class="hour-chart">${hours.map(h=>`<span style="height:${h.logged/Math.max(...hours.map(x=>x.logged),1)*100}%"></span>`).join('')}</div><div class="chart-label">${hours.map(h=>`<span>${esc(h.phase)}</span>`).join('')}</div></article>`;
}
function journey(){return `<article class="card journey">${hhead('Project journey','task','View roadmap')}${(storage().journey||[]).map((j,i)=>`<div class="journey-item ${esc(j.status)}"><span>${j.status==='completed'?'✓':j.status==='open'?'!':i+1}</span><span>${esc(j.name)}</span><i><b style="width:${j.total?j.done/j.total*100:0}%"></b></i><small>${j.done}/${j.total}</small></div>`).join('')||'<p>Add the project roadmap to track progress.</p>'}</article>`}
function readiness(){const j=storage().journey||[],total=j.reduce((n,x)=>n+x.total,0),done=j.reduce((n,x)=>n+x.done,0);return `<article class="card">${hhead('Design readiness','task','Details')}<div class="stat-number">${done} / ${total}</div><p>Required steps completed</p><div class="steps-grid">${Array.from({length:total},(_,i)=>`<i class="${i<done?'complete':''}"></i>`).join('')}</div><small>Recorded project roadmap</small></article>`}


function waterCard(){const w=data.water;return `<article class="card"><div class="card-head"><h2>Water use</h2><button data-home-route="insights">Details</button></div><div class="stat-number">${w?Math.round(w.gal).toLocaleString():'—'}</div><p>Estimated gallons per year</p><svg class="water-wave" viewBox="0 0 300 70"><path d="M0 30Q40 5 80 30T160 30T240 30T320 30V70H0Z" fill="#d8e8f2"/><path d="M0 45Q40 20 80 45T160 45T240 45T320 45V70H0Z" fill="#b3cfdf"/></svg><div class="stat-pair"><span>Annual cost<b>${w?money(w.cost):'—'}</b></span><span>Coverage<b>${w?w.wuKnown+' / '+w.qty:'—'} plants</b></span></div></article>`}
function savingsCard(){return `<article class="card"><div class="card-head"><h2>Closing the budget gap</h2><button data-home-route="savings">Explore</button></div>${(storage().savings||[]).map(r=>`<div class="list-row"><span>${esc(r.title)}</span><b>${money(r.amount)}</b></div>`).join('')||'<p>No savings scenarios recorded.</p>'}<small>${data.sample?'Sample scenarios · not verified or additive':'Review scenarios before applying changes.'}</small></article>`}
function documentsCard(){const files=storage().deliverables||[],ready=files.filter(f=>f.ready).length;return `<article class="card"><div class="card-head"><h2>Deliverables</h2><button data-home-route="projectfiles">Open files</button></div><div class="doc-preview">${projectImages()[0]?img(projectImages()[0]):''}<span>Concept direction · preview</span></div><h3>Design review package</h3><div class="completion-row"><span>Ready for review</span><b>${ready} / ${files.length} files</b></div><small>${files.length-ready} drawings still need internal review.</small></article>`}

function questionnaireCard(){const steps=data.briefSteps||[],done=steps.filter(s=>s.done).length;return `<article class="card"><div class="card-head"><h2>Questionnaire</h2><button data-home-route="clientbrief">Details</button></div><div class="stat-number">${done} / ${steps.length}</div><p>Sections reviewed</p><div class="stat-track"><i style="width:${steps.length?done/steps.length*100:0}%"></i></div>${steps.slice(0,3).map(x=>`<div class="completion-row"><span>${esc(x.name)}</span><b>${x.done?'Complete':'To review'}</b></div>`).join('')}<div class="bottom">${button('Review questionnaire','clientbrief')}</div></article>`}
function renderCard(id){if(id==='questionnaire')return questionnaireCard();if(id==='water')return waterCard();if(id==='savings')return savingsCard();if(id==='documents')return documentsCard();if(['fee','cash','effort'].includes(id))return financeCard(id);if(id==='journey')return journey();if(id==='readiness')return readiness();if(id==='history')return card('Project journey',`<p>Current phase · ${esc(data.phase||'Not set')}</p>${(data.history||[]).map(h=>`<div class="completion-row"><span><b>${esc(h.name)}</b><small>${h.date?esc(new Date(h.date).toLocaleDateString()):''}</small></span><strong>${money(h.total)}</strong></div>`).join('')||'<p>No saved phase estimates yet.</p>'}<div class="bottom">${button('Review estimate','estimate')}</div>`);if(id==='tasks')return tasks();if(id==='approvals')return approvals();if(id==='milestone')return milestone();if(id==='budget')return budget();if(id==='updates')return updates();if(id==='fee')return card('Design fee',empty('Project fee reporting is not connected to Home yet.','Open Financials','financials'));if(id==='scope')return metric('Estimate scope',data.active??'—',`${data.empty.length} active sections have no priced amount.`,'estimate');if(id==='area')return metric('Landscape area',data.area?data.area.toLocaleString()+' sf':'Not set','From the project area calculation.','trace');if(id==='files')return metric('Project files',data.files.length,'Documents saved with this project.','projectfiles');if(id==='images')return metric('Project images',data.photoCount,'Photos and references saved in the project.','photos');if(id==='questionnaire')return card('Questionnaire',`<div class="stat-number">${data.briefStarted?'In progress':'Not started'}</div><p>${data.briefCompleted} sections marked complete.</p><div class="bottom">${button('Continue questionnaire','clientbrief')}</div>`);if(id==='tasksProgress')return metric('Completed tasks',storage().tasks.filter(t=>t.done).length+' / '+storage().tasks.length,'Completion is based on your recorded Home tasks.','brief');return ''}
function middle(){const d=data,s=storage();if(layout==='p')return `<div class="change-bridge"><span class="eyebrow">SINCE YOUR LAST VISIT</span><div class="bridge-items">${(s.updates||[]).slice(0,4).map((u,i)=>`<button data-home-update="${i}"><span class="mini-photo">${u.image?img(u.image):''}</span><span><b>${esc(u.title)}</b><small>${esc(u.by)} · ${esc(new Date(u.date).toLocaleDateString())}</small></span></button>`).join('')||'<p>No recorded updates yet.</p>'}</div></div>`;if(layout==='q')return `<div class="section-brief"><span class="eyebrow">TODAY’S FOCUS</span><h3>${esc(s.tasks.find(t=>!t.done)?.title||'Choose your next action')}. <mark>${esc(s.tasks.filter(t=>!t.done).slice(1,3).map(t=>t.title+'.').join(' '))}</mark></h3><span>${remaining()} priorities, one clear next step.</span></div>`;const n=days();return `<div class="strong-deadline"><div><b>${n==null?'—':Math.abs(n)}</b><span>${n<0?'days past due':'days until delivery'}<small>${esc(s.milestone?.title||'Choose a milestone')} · ${s.milestone?.fixed?'fixed deadline':'target date'}</small></span></div><div class="deadline-note"><strong>${remaining()} priority tasks</strong><small>Finish the work, then review the issue set.</small></div><div class="extra-metric"><strong>${s.approvals.filter(a=>!a.done).length} pending approvals</strong><small>Decisions before the next issue.</small></div><button data-home-edit="milestone">Review milestone ↗</button></div>`}

function draw(){if(!host?.isConnected)return;if(!data){host.innerHTML='<div class="home-empty"><h2>Opening your project</h2><p>Loading the project summary…</p></div>';return}const list=tab==='today'?(storage().layoutCards?.[layout]||defaultCards()):tab==='numbers'?['budget','fee','cash','effort','savings','water']:['journey','questionnaire','readiness','documents'];const top=layout==='p'?`<div class="top-p">${recap()}${cover()}</div>`:`<div class="${layout==='q'?'top-q':'top-r'}">${layout==='q'?album():cover()}${recap()}</div>`;host.innerHTML=`<div class="home-heading"><div><span class="eyebrow">${esc(data.address||'YOUR PROJECT')}</span><h1>${esc(displayName())}</h1>${data.sample?'<small>Sample project</small>':''}</div><button data-home-edit="cards">Customize home</button></div>${top}${middle()}<div class="focus-nav"><div class="tabs" role="tablist" aria-label="Project focus">${['today','numbers','progress'].map(t=>`<button data-home-tab="${t}" role="tab" aria-selected="${tab===t}">${{today:'Today',numbers:'The numbers',progress:'Progress'}[t]}</button>`).join('')}</div><span>${tab==='today'?'A few things to move forward.':tab==='numbers'?'Budget & design-fee health.':'The journey and what changed.'}</span></div><div class="shelf-heading"><small>${list.length} cards · swipe or use the arrows</small><div><button data-home-shelf="-1" aria-label="Previous cards">‹</button><button data-home-shelf="1" aria-label="Next cards">›</button></div></div><div class="card-shelf" role="tabpanel">${list.map(renderCard).join('')}</div><div class="shortcuts"><span>Project shortcuts</span>${['estimate','clientbrief','mood','projectfiles','reports'].map(r=>button({estimate:'Estimate',clientbrief:'Questionnaire',mood:'Moodboard',projectfiles:'Files',reports:'Reports'}[r],r)).join('')}</div>`;if(!canEdit())host.querySelectorAll('[data-home-edit]').forEach(b=>b.hidden=true);host.querySelectorAll('.slides').forEach(el=>el.onscroll=()=>{const i=Math.round(el.scrollLeft/el.clientWidth);host.querySelectorAll(`[data-home-slide="${el.id}"]`).forEach(b=>b.setAttribute('aria-current',+b.dataset.n===i))});host.querySelectorAll('.slides,.cover-frame').forEach(el=>el.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();el.scrollBy({left:el.clientWidth*(e.key==='ArrowRight'?1:-1),behavior:'smooth'})}})}
function dialog(title,body){host.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.className='home-detail';el.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button data-home-close aria-label="Close dialog">×</button></div>${body}`;host.append(el);el.showModal()}
function edit(kind){if(!canEdit())return;const s=storage();if(kind==='updates'){dialog('Latest updates',(s.updates||[]).map(u=>`<h3>${esc(u.title)}</h3><p>${esc(u.description)}</p>`).join('')||'<p>No updates yet.</p>');return}if(kind==='finance'){dialog('Project financial records',`<form class="home-form" data-home-form="finance">${['agreed','cost','remaining','invoiced','collected'].map(k=>`<label>${{agreed:'Agreed fee',cost:'Cost to date',remaining:'Forecast cost to complete',invoiced:'Invoiced',collected:'Collected'}[k]}<input name="${k}" type="number" min="0" step="0.01" required value="${s.fee?.[k]||0}"></label>`).join('')}<button>Save</button></form>`);return}if(kind==='cards'){dialog('Customize Project Home',`<form class="home-form" data-home-form="cards">${['milestone','tasks','approvals','updates','budget','fee','cash','effort','savings','water','journey','questionnaire','readiness','documents'].map(id=>`<label><input type="checkbox" name="card" value="${id}" ${(s.layoutCards?.[layout]||defaultCards()).includes(id)?'checked':''}>${{fee:'Design fee',cash:'Invoicing',effort:'Design hours',savings:'Closing the budget gap',water:'Water use',journey:'Project journey',questionnaire:'Questionnaire',readiness:'Design readiness',documents:'Deliverables',history:'Project journey',scope:'Estimate scope',milestone:'Next milestone',tasks:'Next actions',approvals:'Pending approvals',updates:'Latest updates',budget:'Landscape budget',files:'Project files'}[id]}</label>`).join('')}<button>Save</button></form>`);return}dialog(kind==='milestone'?'Next milestone':kind==='task'?'Add next action':'Record an approval request',`${kind==='task'?'<div class="task-scroll">'+taskRows()+'</div>':kind==='approval'?s.approvals.map(a=>'<p>'+esc(a.title)+' · '+(a.done?'Recorded':'Awaiting decision')+'</p>').join(''):''}<form class="home-form" data-home-form="${kind}"><label>Title<input name="title" maxlength="200" required value="${esc(kind==='milestone'?s.milestone?.title||'':'')}"></label>${kind==='milestone'?`<label>Delivery date<input name="date" type="date" required value="${esc(s.milestone?.date||'')}"></label><label><input name="fixed" type="checkbox" ${s.milestone?.fixed!==false?'checked':''}>Fixed date</label><p>Dates are saved as entered. Automatic scheduling is not connected.</p>`:''}${kind==='task'?'<label>Assigned to<input name="owner"></label><label>Estimated hours<input name="hours" type="number" min="0" step="0.5"></label>':''}${kind==='approval'?'<label>Context<input name="detail"></label>':''}<button>Save</button></form>`)}
let galleryTimer;function bind(){clearInterval(galleryTimer);host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-home-gallery')){if(galleryTimer){clearInterval(galleryTimer);galleryTimer=null;b.textContent='Play images'}else{b.textContent='Pause images';galleryTimer=setInterval(()=>{const el=host.querySelector('#home-album');if(!el||!host.isConnected){clearInterval(galleryTimer);galleryTimer=null;return}if(!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches)el.scrollTo({left:el.clientWidth*((Math.round(el.scrollLeft/el.clientWidth)+1)%el.children.length),behavior:'smooth'})},6000)}}if(b.dataset.homeTab){tab=b.dataset.homeTab;draw()}if(b.dataset.homeRoute){const r=b.dataset.homeRoute;if(['estimate','mood','brief','client','financials','savings','insights'].includes(r))ctx.open(r);else ctx.tool(r)}if(b.dataset.homeEdit)edit(b.dataset.homeEdit);if(b.dataset.homeUpdate!==undefined){const u=storage().updates[+b.dataset.homeUpdate];dialog(esc(u.title),`<div class="home-update-detail">${u.image?img(u.image):''}</div><p>${esc(u.description)}</p><small>${esc(u.by)} · ${esc(new Date(u.date).toLocaleDateString())}</small>`);}if(b.hasAttribute('data-home-close'))b.closest('dialog').close();if(b.dataset.homeInfo)dialog('Project recap sources','<p>This summary uses the current project’s budget, calculated estimate, images, files and Home records. It is a deterministic summary; AI writing and cross-project scheduling are not connected.</p>');if(b.dataset.homeShelf)host.querySelector('.card-shelf').scrollBy({left:host.querySelector('.card-shelf').clientWidth*+b.dataset.homeShelf,behavior:'smooth'});if(b.dataset.homeSlide){const el=host.querySelector('#'+b.dataset.homeSlide);el.scrollTo({left:el.clientWidth*+b.dataset.n,behavior:'smooth'})}if(b.dataset.homeStep){const el=host.querySelector('#'+b.dataset.target);const next=(Math.round(el.scrollLeft/el.clientWidth)+ +b.dataset.homeStep+el.children.length)%el.children.length;el.scrollTo({left:el.clientWidth*next,behavior:'smooth'})}};
host.onchange=e=>{if(!canEdit())return;const t=e.target;if(t.dataset.homeTask!==undefined){storage().tasks[+t.dataset.homeTask].done=t.checked;save('Task '+(t.checked?'completed':'reopened'))}if(t.dataset.homeApproval!==undefined){Object.assign(storage().approvals[+t.dataset.homeApproval],{done:t.checked,recorded:new Date().toISOString()});save('Designer '+(t.checked?'recorded':'reopened')+' an approval')}};
host.onsubmit=e=>{const kind=e.target.dataset.homeForm;if(!kind)return;e.preventDefault();if(!canEdit())return;const f=new FormData(e.target),s=storage();if(kind==='finance'){s.fee=Object.fromEntries(['agreed','cost','remaining','invoiced','collected'].map(k=>[k,Number(f.get(k))]));save('Financial records updated');return}if(kind==='cards'){s.layoutCards??={};s.layoutCards[layout]=f.getAll('card');}else if(kind==='milestone')s.milestone={title:f.get('title').trim(),date:f.get('date'),fixed:f.has('fixed')};else s[kind==='task'?'tasks':'approvals'].push({title:f.get('title').trim(),done:false,owner:f.get('owner')||'',hours:f.get('hours')?Number(f.get('hours')):null,detail:f.get('detail')||''});save(kind==='cards'?'Home cards updated':kind==='milestone'?'Milestone updated':kind==='task'?'Task added':'Approval request added')};}
async function refresh(){const token=++seq,id=ctx.projectId;try{const result=await v2Preview.plantRequest('home-summary');if(token!==seq||id!==ctx.projectId)return;data=result;loadedId=id;seedSample();draw()}catch(e){if(token===seq&&host?.isConnected){host.innerHTML='<div class="home-empty"><h2>Project summary is not available yet</h2><button data-home-retry>Try again</button></div>';host.querySelector('button').onclick=refresh}}}
window.addEventListener('message',e=>{if(e.source===document.getElementById('v2-engine')?.contentWindow&&e.data?.v2==='ready'&&window.v2Workspace?.active==='home'&&host?.isConnected)refresh()});
window.v2Home={get layout(){return layout},setLayout(value){if(window.v2Experience?.role!=='developer'||!['p','q','r'].includes(value))return;layout=value;sessionStorage.setItem('studioh_home_layout',value)},mount(el,context){host=el;ctx=context;if(loadedId!==ctx.projectId)data=null;storage();draw();bind();if(window.v2Preview?.ready)refresh();else{const token=++seq;let attempts=0;const timer=setInterval(()=>{if(token!==seq||!host?.isConnected||attempts++>60){clearInterval(timer);return}if(window.v2Preview?.ready){clearInterval(timer);refresh()}},250)}}};
})();
