import {labor} from './time-finance.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(Number(n||0).toFixed(2)).toLocaleString(),sum=a=>a.reduce((n,e)=>n+e.hours,0),cash=n=>n==null?'Not set':Number(n).toLocaleString(undefined,{maximumFractionDigits:0});
const money=cash;
const icon=kind=>`<svg class="a1-line-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${({play:'<path d="m9 5 10 7-10 7z"/>',edit:'<path d="m4 16 12-12 4 4L8 20H4zM13 7l4 4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<path d="m5 12 4 4L19 6"/>',cost:'<rect x="3" y="5" width="18" height="14" rx="3"/><circle cx="12" cy="12" r="3"/>'})[kind]}</svg>`;

const card=(title,body,cls='',sub='')=>`<section class="card ${cls}"><div class="cardhead"><h3>${title}</h3><span>${sub}</span></div>${body}</section>`;
const row=(title,meta,right)=>`<div class="row"><div><b>${title}</b><span>${meta}</span></div>${right}</div>`;
const progress=pct=>`<div class="progress"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div>`;
let projectFilter='all',personFilter='all';
export async function renderA1(c){const {panel,me,tab,api,week,shift,fmt:date,projectId,work,allowance,used,refresh,render,notify,isCurrent}=c;panel.closest('.tm').classList.add('tm-a1-exact');
 const days=Array.from({length:7},(_,i)=>shift(week,i)),inWeek=e=>!e.voided&&e.date>=week&&e.date<=days[6],own=me.entries.filter(inWeek),daily=a=>days.map(d=>sum(a.filter(e=>e.date===d))),total=sum(own),bill=sum(own.filter(e=>e.billable)),sheetState=me.weeks[week]?.state||'draft';
 const toolbar=(title,desc)=>`<div class="toolbar"><div><h2>${title}</h2><p>${desc}</p></div><div class="actions"><span class="range-label">${date(week)} — ${date(days[6])}</span><button data-date-range>Change dates ⌄</button></div></div>`;
 const graphics=[];
 const graphic=(a,title)=>{const id=graphics.length;graphics.push({rows:a,title});return `data-graphic="${id}" tabindex="0" role="button" aria-label="${esc(title)}"`};
 const summaryGraphic=(title,summary)=>{const id=graphics.length;graphics.push({rows:[],title,summary});return `data-graphic="${id}" tabindex="0" role="button" aria-label="${esc(title)}"`};
 const mini=(a,type)=>type==='status'?`<div class="micro-status"><span>✓ Entries recorded</span><span>Review before approval</span></div>`:type==='cost'?'<div class="micro-status"><span>Internal cost</span><span>Studio currency</span></div>':`<div class="microbars">${daily(a).map((n,i)=>`<button type="button" ${graphic(a.filter(e=>e.date===days[i]),date(days[i])+" · "+fmt(n)+" hours")} style="height:${Math.max(8,n/Math.max(1,...daily(a))*100)}%;opacity:${n?1:.2}"></button>`).join('')}</div><span class="microlabel">Recorded hours · Mon–Sun</span>`;
 const metric=(label,value,note,a=own,type='trend',cls='')=>`<section class="card metric ${cls}"><div class="metric-top"><small>${label}</small><span class="metric-icon">${icon(type==='cost'?'cost':type==='status'?'check':'clock')}</span></div><div class="number">${value}</div><p>${note}</p>${mini(a,type)}</section>`;
 const plot=a=>`<div class="bars" role="group" aria-label="Recorded daily hours">${daily(a).map((n,i)=>{const b=sum(a.filter(e=>e.date===days[i]&&e.billable));return `<div class="barcol"><b>${n?fmt(n):'—'}</b><button class="stack" ${graphic(a.filter(e=>e.date===days[i]),date(days[i])+" · "+fmt(n)+" hours")} aria-label="${date(days[i])}: ${fmt(n)} hours" style="height:${n/Math.max(8,...daily(a))*140}px;min-height:${n?10:3}px;padding:0"><i style="height:${n?b/n*100:0}%"></i></button><label>${new Date(days[i]+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</label></div>`}).join('')}</div><div class="legend"><span><i class="dot"></i>Billable</span><span><i class="dot light"></i>Non-billable</span></div>`;
 const activeWork=()=>work().filter(w=>{const data=window.v2Workspace?.timeWork()||{},r=(data[w.type+'s']||[]).find(x=>x.id===w.id);return !r?.done&&!r?.ready&&r?.state!=='Complete'});
 const allowances=()=>activeWork().filter(w=>allowance(w)).slice(0,3).map(w=>`<div class="budget"><div class="row"><b>${esc(w.title)}</b><b>${fmt(Math.max(0,allowance(w)-used(w)))}h left</b></div><div ${graphic(me.entries.filter(e=>!e.voided&&e.workType===w.type&&e.workId===w.id),w.title+" · "+fmt(used(w))+" of "+fmt(allowance(w))+" hours used")}>${progress(used(w)/allowance(w)*100)}</div><p>${fmt(used(w))} / ${fmt(allowance(w))}h used</p></div>`).join('')||'<p>No allowances set.</p>';
 const allowanceCard=()=>card('Work allowances',allowances()+'<div class="foot"><button data-tab-time="Time budgets">All allowances →</button></div>');
 let chartRows=own;
 const detail=(title,body)=>{const d=document.createElement('dialog');d.className='tm-dialog tm-a1-exact-dialog';d.innerHTML=`<div class="tm tm-a1-exact"><div class="modalhead"><h2>${title}</h2><button data-close>×</button></div><div class="modalbody">${body}</div></div>`;document.getElementById('sh-v2').append(d);d.showModal();d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();return d};
 if(tab==='My time'){
 const focus=work().find(w=>w.type===me.timer?.workType&&w.id===me.timer?.workId)||activeWork().find(w=>allowance(w)&&used(w)<allowance(w))||work().find(w=>!['project','studio'].includes(w.type)),cap=focus?allowance(focus):null,remaining=cap?Math.max(0,cap-used(focus)):0,mins=Math.floor(remaining*60),dayRows=me.entries.filter(e=>!e.voided&&e.date===c.day);
 panel.innerHTML=toolbar('A good day, accounted for.',`${esc(me.name)} · ${new Date(c.day+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}`)+`<div class="grid">${card('This week',`<div class="number">${fmt(total)}<em>hours</em></div><div class="weekdots">${days.map((d,i)=>`<div><small>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'narrow'})}</small><button class="datepill" data-time-day="${d}" aria-label="View ${date(d)} entries">${fmt(daily(own)[i])}</button></div>`).join('')}</div><div class="foot"><span>${fmt(bill)}h billable</span><button data-sheet>Review sheet →</button></div>`,'blue')}${card('Continue your focus',`<small>${esc(focus?.title||'Choose your work')}</small><div class="number focus-number">${me.timer?c.clock(c.seconds(me.timer)):cap?Math.floor(mins/60)+':'+String(mins%60).padStart(2,'0'):'0:00'}<em>${me.timer?(me.timer.paused?'paused':'elapsed'):cap?'remaining':'ready'}</em></div><div ${graphic(focus?me.entries.filter(e=>!e.voided&&e.workType===focus.type&&e.workId===focus.id):[],"Focus time recorded")}>${progress(cap?used(focus)/cap*100:0)}</div><div class="foot"><span>${cap?fmt(used(focus))+' of '+fmt(cap)+'h used':'Stopwatch ready'}</span><button class="primary" data-focus-timer>${me.timer?'Open timer':icon('play')+' Start timer'}</button></div>`)}${card('Quick entry',`<h2>Say it your way.</h2><p>“I spent 30 minutes on studio admin.”</p><button class="primary a1-quick-entry" type="button" data-speak>Type or dictate →</button><div class="foot">Confirm the category before saving.</div>`,'soft')}${card(c.day===c.today()?'Today’s entries':date(c.day)+' entries','<div class="a1-entry-scroll" tabindex="0" aria-label="Entries for this day">'+dayRows.map(e=>row(esc(e.workTitle),`${esc(e.projectName)} · ${e.billable?'Billable':'Non-billable'}`,`<div class="a1-entry-actions"><span class="timepill">${fmt(e.hours)}h</span><button class="a1-edit-entry" data-entry="${esc(e.id)}" aria-label="Edit ${esc(e.workTitle)}">${icon("edit")}</button></div>`)).join('')+(!dayRows.length?'<p>No entries for this day.</p>':'')+'</div><div class="foot"> <button data-enter>＋ Enter time</button><button data-today>Today</button></div>','wide')}${allowanceCard()}</div>`;
 panel.querySelector('[data-focus-timer]').onclick=()=>me.timer?c.timerStatus():c.timerDialog(focus?{type:focus.type,id:focus.id}:null);
 }
 if(tab==='My timesheet'){
 const groups=[...new Map(own.map(e=>[e.projectId+'|'+e.workType+'|'+e.workId,e])).values()];
 panel.innerHTML=toolbar('Your week, ready to review.',`${esc(me.name)} · Click a value to enter or adjust time`)+`<div class="metrics">${metric('THIS WEEK',fmt(total)+'<em>h</em>','Project + studio work',own,'trend','blue')}${metric('BILLABLE',fmt(bill)+'<em>h</em>','Client work',own.filter(e=>e.billable))}${metric('NON-BILLABLE',fmt(total-bill)+'<em>h</em>','Studio contribution',own.filter(e=>!e.billable),'trend','soft')}${metric('STATUS',esc(sheetState),'Ready for your review',own,'status')}</div><section class="card"><div class="cardhead"><h3>Weekly timesheet</h3><span class="pill">${esc(sheetState)}</span></div><div class="tablewrap"><table class="sheet"><thead><tr><th>Project / work</th>${days.map(d=>`<th><span class="datepill ${d===c.today()?'current':''}">${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}<br>${date(d)}</span></th>`).join('')}<th>Total</th></tr></thead><tbody>${groups.map((e,i)=>{const rows=own.filter(x=>x.projectId===e.projectId&&x.workType===e.workType&&x.workId===e.workId);return `<tr><td><b>${esc(e.workTitle)}</b><small>${esc(e.projectName)}${e.workType==='studio'?' · Non-billable':''}</small></td>${days.map(d=>{const n=sum(rows.filter(e=>e.date===d));return `<td><button class="timepill ${d===c.today()?'current':''}" data-cell="${i}" data-cell-date="${d}" aria-label="${esc(e.workTitle)} · ${date(d)} · ${fmt(n)} hours">${n?fmt(n):'＋'}</button></td>`}).join('')}<td><b>${fmt(sum(rows))}</b></td></tr>`}).join('')}</tbody><tfoot><tr><td>Total hours</td>${daily(own).map(n=>`<td>${n?fmt(n):'—'}</td>`).join('')}<td>${fmt(total)}</td></tr></tfoot></table></div><div class="foot"><button data-enter>＋ Add work</button><span>Submitted weeks lock for review.</span>${['draft','returned'].includes(sheetState)?'<button class="primary" data-submit>Review & submit →</button>':sheetState==='submitted'?'<button data-withdraw>Withdraw submission</button>':'<span>✓ Approved</span>'}</div></section>`;
 panel.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>c.openCell(groups[+b.dataset.cell],b.dataset.cellDate));
 }
 if(tab==='Reports'){
 const csv=panel.querySelector('[data-csv]');
 panel.innerHTML=toolbar(`${esc(me.name)}’s week in focus.`,'Project and studio work · Week to date')+`<div class="metrics">${metric('RECORDED TIME',fmt(total)+'<em>h</em>','Billable and non-billable',own,'trend','blue')}${metric('BILLABLE HOURS',fmt(bill)+'<em>h</em>','Client work',own.filter(e=>e.billable))}${metric('STUDIO HOURS',fmt(sum(own.filter(e=>e.projectId==='studio')))+'<em>h</em>','Administration and internal work',own.filter(e=>e.projectId==='studio'))}${metric('SHEET STATUS',esc(sheetState),'Review before submission',own,'status','soft')}</div><div class="grid">${card('Recorded hours',plot(own),'wide','THIS WEEK')}${allowanceCard()}${card('Time by work',[...new Set(own.map(e=>e.workTitle))].map(w=>{const a=own.filter(e=>e.workTitle===w);return row(esc(w),esc(a[0].projectName),`<b>${fmt(sum(a))}h</b>`)}).join(''))}${card('Where the hours went',`<div class="a1-mix-summary"><div><small>THIS WEEK</small><b class="a1-week-dominant">${fmt(total)}<em>h</em></b></div><div><small>BILLABLE</small><b>${fmt(total?bill/total*100:0)}%</b><span>${fmt(bill)}h</span></div><div><small>NON-BILLABLE</small><b>${fmt(total?(total-bill)/total*100:0)}%</b><span>${fmt(total-bill)}h</span></div></div><div ${graphic(own,'Billable and non-billable time')} class="a1-mix-track"><i style="width:${total?bill/total*100:0}%"></i></div><div class="a1-work-breakdown">${[...new Set(own.map(e=>e.workTitle))].map(title=>({title,rows:own.filter(e=>e.workTitle===title)})).sort((a,b)=>sum(b.rows)-sum(a.rows)).map(g=>`<button class="a1-work-bar" ${graphic(g.rows,g.title)}><span class="a1-bar-label"><b>${esc(g.title)}</b><span>${fmt(sum(g.rows))}h · ${fmt(total?sum(g.rows)/total*100:0)}%</span></span>${progress(total?sum(g.rows)/total*100:0)}</button>`).join('')}</div><p>Hover or select a work item to see its entries. Hours show recorded effort, not completion.</p><div class="foot" data-export></div>`,'wide')}</div>`;if(csv)panel.querySelector('[data-export]').append(csv);
 }
 if(['Team review','Project hours'].includes(tab)&&me.admin){
 const [team,cfg,d]=await Promise.all([api('team'),api('settings'),api('project?id='+encodeURIComponent(projectId()))]);if(!isCurrent())return;
 const all=team.people.flatMap(p=>p.entries.filter(e=>!e.voided).map(e=>({...e,user:p.user,person:p.name}))),a=all.filter(e=>inWeek(e)&&(tab==='Project hours'?e.projectId===projectId():(projectFilter==='all'||e.projectId===projectFilter)&&(personFilter==='all'||e.user===personFilter))),hours=sum(a),billable=sum(a.filter(e=>e.billable)),cost=labor(a,cfg.rates),f=d.finance,pending=team.people.filter(p=>p.weeks[week]?.state==='submitted');chartRows=a;
 const tasks=(window.v2Workspace?.timeWork()?.tasks||[]).filter(t=>!t.done&&t.dueDate&&t.dueDate>=c.today()&&t.dueDate<=shift(c.today(),7));
 const insight=()=>card(tab==='Team review'?'Studio overview & AI briefing':'Project overview & AI briefing',`<span class="pill">Project overview</span><h2 class="insight-title">${!f.complete?'The cost forecast needs more information.':f.costBudget==null?'Set a cost budget to see the outlook.':f.forecast<=f.costBudget?'Budget has room.':'The cost forecast needs review.'} ${tasks.length?'The next handoff needs attention.':''}</h2><p>${f.complete&&f.costBudget!=null?'The forecast is '+cash(Math.abs(f.costBudget-f.forecast))+' '+(f.forecast<=f.costBudget?'below':'over')+' the cost budget. ':'Missing rates or estimates keep the forecast incomplete. '}${tasks.length} open tasks have due dates within the next seven days.</p><div class="evidence"><span>${tasks.length} open tasks</span><span>Forecast ${f.complete?cash(f.forecast):'incomplete'}</span></div><p class="muted">Open tasks do not establish that someone is behind. Confirm their status and remaining effort before changing the plan.</p><section data-ai-summary aria-live="polite"><p>Generate an AI review of the current hours, costs and upcoming work.</p><button class="primary" data-ai-report>Generate AI summary</button></section><div class="foot"><button data-evidence>Review tasks →</button><button data-evidence>Why this suggestion?</button></div>`,'insight wide','PROJECT HEALTH');
 const costCard=()=>card('Cost summary & forecast',row('Recorded labor','Tracked and period summaries · This project',`<b>${cash(f.laborCost)}</b>`)+row('Remaining labor','Estimate · Editable',`<b>${cash(f.remainingLabor)}</b>`)+row('Consultant fees','Total expected fees',`<b>${cash(f.consultantFees)}</b>`)+row('Expenses','Total expected expenses',`<b>${cash(f.expenses)}</b>`)+`<div class="cost-stack"><i ${summaryGraphic("Recorded labor",cash(f.laborCost)+" · Tracked time and period summaries")} style="flex:${f.laborCost||1}"></i><i ${summaryGraphic("Remaining labor",cash(f.remainingLabor)+" · Estimated cost to finish")} style="flex:${f.remainingLabor||0}"></i><i ${summaryGraphic("Fees and expenses",cash(f.consultantFees)+" consultant fees + "+cash(f.expenses)+" expenses")} style="flex:${(f.consultantFees||0)+(f.expenses||0)}"></i></div><div class="row"><b>Forecast total</b><b>${f.complete?cash(f.forecast):'Incomplete'}</b></div><div class="foot"><button data-forecast>Edit forecast →</button><span>Fee: ${cash(f.fee)}</span></div>`,'blue');
 if(tab==='Team review'){
 const reviewPanel=panel.firstElementChild;panel.innerHTML=toolbar('Your studio, in perspective.','Administrator · All people · Project and studio hours')+`<div class="metrics">${metric('RECORDED HOURS',fmt(hours)+'<em>h</em>',team.people.length+' people · Week to date',a,'trend','blue')}${metric('INTERNAL LABOR',cash(cost.cost),cost.unratedHours?fmt(cost.unratedHours)+'h missing rates':'Recorded hours × cost rates',a,'cost')}${metric('BILLABLE SHARE',fmt(hours?billable/hours*100:0)+'<em>%</em>',fmt(hours-billable)+'h non-billable',a)}${metric('TEAM REVIEW',pending.length+'<em>ready</em>','Submitted weeks to review',a,'status','soft')}</div><div class="grid">${card('The week in hours',plot(a),'wide','HOURS / DAY')}${card('People & internal cost',team.people.filter(p=>personFilter==='all'||p.user===personFilter).map(p=>{const r=a.filter(e=>e.user===p.user);return row(`<span class="personline"><i class="avatar">${esc(p.name[0])}</i>${esc(p.name)}</span>`,'Internal labor',`<div class="right"><b>${fmt(sum(r))}h</b><span>${cash(labor(r,cfg.rates).cost)}</span></div>`)}).join('')+'<div class="foot"><button data-review-scroll>Review timesheets →</button></div>')}${insight()}${card('Studio work',(cfg.categories||[]).slice(0,3).map(cat=>row(esc(cat),'Non-billable · Internal',`<b>${fmt(sum(a.filter(e=>e.projectId==='studio'&&e.workId===cat)))}h</b>`)).join('')+'<div class="foot"><button data-categories>Manage categories →</button></div>')}</div><details class="a1-filters"><summary>Filter project or person</summary><div class="split"><label>Project<select data-project-filter><option value="all">All projects + studio</option>${[...new Map(all.map(e=>[e.projectId,e.projectName])).entries()].map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('')}</select></label><label>Person<select data-person-filter><option value="all">Everyone</option>${team.people.map(p=>`<option value="${esc(p.user)}">${esc(p.name)}</option>`).join('')}</select></label></div></details>`;
 const pf=panel.querySelector('[data-project-filter]'),uf=panel.querySelector('[data-person-filter]');pf.value=projectFilter;uf.value=personFilter;pf.onchange=()=>{projectFilter=pf.value;render()};uf.onchange=()=>{personFilter=uf.value;render()};
 if(reviewPanel){const wrapper=document.createElement('details');wrapper.className='a1-review';wrapper.innerHTML='<summary>Staff timesheets & approvals</summary>';wrapper.append(reviewPanel);panel.append(wrapper);panel.querySelector('[data-review-scroll]').onclick=()=>{wrapper.open=true;wrapper.scrollIntoView({behavior:'smooth',block:'start'})}}
 }else{
 panel.innerHTML=toolbar(`${esc(me.demo?'San Marino':window.v2Cloud.projectName)}, from hours to outcomes.`,'Project performance · Studio currency · Current forecast')+`<div class="metrics">${metric('RECORDED TIME',fmt(d.total)+'<em>h</em>','All project time',a,'trend','blue')}${metric('RECORDED LABOR',cash(f.laborCost),'Actual time and period summaries',a,'cost')}${metric('FORECAST COST',f.complete?cash(f.forecast):'Incomplete','Recorded + remaining + fees + expenses',a,'cost')}${metric('COST BUDGET',cash(f.costBudget),f.complete&&f.costBudget!=null?cash(Math.abs(f.costBudget-f.forecast))+(f.forecast<=f.costBudget?' headroom':' over budget'):'Review forecast inputs',a,'cost','soft')}</div><div class="grid">${card('Recorded hours',plot(a),'wide','THIS WEEK')}${allowanceCard()}${costCard()}${insight()}</div><details class="a1-review"><summary>Cost coverage & work detail</summary><p>${fmt(f.unratedHours)} hours need rates. ${fmt(f.estimatedRateHours)} legacy hours use current rates. Period summaries replace recorded costs for their dates.</p>${(d.work||[]).map(w=>row(esc(w.title),esc(w.type),`<b>${fmt(w.hours)}h</b>`)).join('')}</details>`;
 }
 panel.querySelector('[data-ai-report]')?.addEventListener('click',async e=>{const b=e.currentTarget,target=panel.querySelector('[data-ai-summary]');b.disabled=true;b.textContent='Reviewing project data…';try{const context={scope:tab==='Team review'?'Studio and staff':'Project',period:{from:week,to:days[6]},demo:!!me.demo,hours, billableHours:billable,nonBillableHours:hours-billable,recordedLabor:cost,projectForecast:f,people:team.people.map(p=>({name:p.name,hours:sum(a.filter(e=>e.user===p.user)),billableHours:sum(a.filter(e=>e.user===p.user&&e.billable))})),upcomingWork:tasks.slice(0,30).map(t=>({title:t.title,dueDate:t.dueDate,owner:t.owner||t.assignee||'',done:!!t.done})),limitations:['Hours are recorded time, not capacity or performance. Open tasks alone do not establish lateness. Missing timesheets may understate costs.']};const result=await window.v2Cloud.time('report',{projectId:projectId(),context});target.innerHTML=`<span class="pill">AI-generated · ${new Date(result.generatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><div class="a1-ai-copy">${esc(result.summary)}</div><small>Based on the displayed snapshot. Review recommendations against project records.</small>`}catch(err){b.disabled=false;b.textContent='Retry AI summary';let note=target.querySelector('[data-ai-error]');if(!note){note=document.createElement('p');note.dataset.aiError='';target.append(note)}note.textContent=err.message}});
 panel.querySelectorAll('[data-forecast]').forEach(b=>b.onclick=()=>forecastEditor(c));panel.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>detail('The records behind this insight',tasks.map(t=>row(esc(t.title),esc(t.dueDate),'<span class="pill">Open</span>')).join('')+`<p>Current forecast: ${f.complete?cash(f.forecast):'Incomplete'}. Cost budget: ${cash(f.costBudget)}. These are calculated facts; AI is not connected.</p>`));
 }
 if(tab==='Settings'&&me.admin){
 const [cfg,team]=await Promise.all([api('settings'),api('team')]);if(!isCurrent())return;const people=team.people.length?team.people:[me],budget=cfg.projects[projectId()]||{};
 panel.innerHTML=`<form data-a1-settings><div class="toolbar"><div><h2>Clear settings. Carefully aligned.</h2><p>Administrator settings · Saved to your studio</p></div><button class="primary">Save settings</button></div><div class="settings">${card('Tracking & visibility',`<div class="settingrow"><div><b>Time tracking</b><p>Allow entries and timers · <strong data-tracking-state>${cfg.enabled?"On":"Off"}</strong></p></div><label class="toggle"><input name="enabled" type="checkbox" ${cfg.enabled?'checked':''} aria-label="Time tracking"><span></span></label></div><label>Staff visibility<select name="visibility"><option value="total">Own entries + project totals</option><option value="work">Own entries + project totals by work</option><option value="own">Own entries only</option></select></label><div class="notice">Detailed staff costs remain admin-only.</div><div class="foot"><button type="button" data-tab-time="Tracking settings">My tracking preferences →</button></div>`)}${card('People & internal cost',people.map((p,i)=>`<div class="rate-row"><div class="personline"><i class="avatar">${esc(p.name[0])}</i><div><b>${esc(p.name)}</b><span>Internal cost</span></div></div><label class="unitfield"><input name="rate${i}" aria-label="${esc(p.name)} hourly cost" type="number" min="0" step="0.01" value="${cfg.rates[p.user]??''}" placeholder="Not set"><span>/hr</span></label></div>`).join('')+'<p class="muted">New entries retain their cost rate. Legacy hours use the current rate.</p>')}${card((me.demo?'San Marino':esc(window.v2Cloud.projectName))+' budget',`<div class="rate-row"><div><b>Agreed fee</b><span>Fixed project fee</span></div><label class="unitfield"><input name="fee" aria-label="Agreed fee" type="number" min="0" step="0.01" value="${budget.fee??''}"><span></span></label></div><div class="rate-row"><div><b>Cost budget</b><span>Internal project costs</span></div><label class="unitfield"><input name="costBudget" aria-label="Cost budget" type="number" min="0" step="0.01" value="${budget.costBudget??''}"><span></span></label></div><div class="foot"><button type="button" data-forecast>Edit remaining costs →</button></div>`,'blue')}${card('Studio & non-billable work',`<p>Record time spent running the studio, such as administration, training and marketing. These entries appear in your timesheet and staff reports, but are not charged to a project.</p><div class="evidence">${(cfg.categories||[]).map(n=>`<button type="button" data-studio-entry="${esc(n)}">${esc(n)} +</button>`).join('')}</div><div class="foot"><button type="button" data-categories>Manage categories →</button><button type="button" data-tab-time="Time budgets">Time allowances →</button></div>`,'soft')}</div></form>`;
 const form=panel.querySelector('form');form.elements.enabled.onchange=()=>{panel.querySelector('[data-tracking-state]').textContent=form.elements.enabled.checked?'On · save to apply':'Off · save to apply'};form.elements.visibility.value=cfg.visibility;form.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=new FormData(form),rates={...cfg.rates},projects={...cfg.projects,[projectId()]:{...budget}};people.forEach((p,i)=>{if(f.get('rate'+i)==='')delete rates[p.user];else rates[p.user]=+f.get('rate'+i)});for(const k of ['fee','costBudget'])if(f.get(k)==='')delete projects[projectId()][k];else projects[projectId()][k]=+f.get(k);await api('settings',{revision:cfg.revision,enabled:f.has('enabled'),visibility:f.get('visibility'),rates,projects,categories:cfg.categories});await refresh();await render();notify('Settings saved.')}catch(err){notify(err.message);e.submitter.disabled=false}};
 panel.querySelector('[data-forecast]').onclick=()=>forecastEditor(c);
 }
 if(tab==='Connections')panel.innerHTML=toolbar('Harvest first. Enter time once.','Planned integration · No live API connection')+`<div class="grid">${card('Harvest',`<h2>Keep the tool your team already uses.</h2><p>Import approved time, connect projects and map work once.</p>${row('01 · Connect an account','Explicit account authorization','')}${row('02 · Match projects and people','Remember matches across syncs','')}${row('03 · Review imported time','Use source IDs to prevent duplicates','')}<div class="foot"><button data-connection>View connection flow →</button></div>`,'wide')}${card('What comes first','<p>Admin reports</p><p>Studio / non-billable categories</p><p>Cost summaries and forecasts</p><span class="pill">Then Harvest integration</span>','blue')}</div>`;
 panel.querySelectorAll('[data-studio-entry]').forEach(b=>b.onclick=()=>c.enter({type:'studio',id:b.dataset.studioEntry}));
 panel.querySelector('[data-connection]')?.addEventListener('click',()=>detail('Harvest connection plan','<p>Harvest integration has not been built yet. Time currently stays in Studio H.</p><p>The planned flow will authorize an account, match projects and work, then review imports without duplicates.</p>'));
 panel.querySelectorAll('[data-categories]').forEach(b=>b.onclick=async()=>{const cfg=await api('settings'),d=detail('Studio categories',`<form><p>Non-billable by default. One category per line.</p><label>Categories<textarea name="categories" rows="7">${esc((cfg.categories||[]).join('\n'))}</textarea></label><p role="status"></p><div class="foot"><button class="primary">Save categories</button></div></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('settings',{...cfg,categories:new FormData(e.target).get('categories').split('\n').map(x=>x.trim()).filter(Boolean)});d.close();await refresh();await render()}catch(err){d.querySelector('[role=status]').textContent=err.message;e.submitter.disabled=false}}});
 panel.querySelector('[data-date-range]')?.addEventListener('click',()=>{const d=detail('Choose your week',`<div class="actions a1-week-actions"><button data-back>‹ Previous week</button><button data-now>Current week</button><button data-forward>Next week ›</button></div><label>Week containing<input type="date" data-week-pick value="${week}"></label>`);d.querySelector('[data-back]').onclick=()=>{d.close();c.setWeek(shift(week,-7))};d.querySelector('[data-forward]').onclick=()=>{d.close();c.setWeek(shift(week,7))};d.querySelector('[data-now]').onclick=()=>{d.close();c.setWeek(c.today())};d.querySelector('[data-week-pick]').onchange=e=>{if(e.target.value){d.close();c.setWeek(e.target.value)}}});

 const popup=document.createElement('div');popup.className='a1-chart-popup';popup.setAttribute('role','tooltip');popup.hidden=true;panel.append(popup);
 const graphicBody=g=>g.summary?`<b>${esc(g.title)}</b><p>${esc(g.summary)}</p>`:`<b>${esc(g.title)}</b><p>${fmt(sum(g.rows))}h total · ${fmt(sum(g.rows.filter(e=>e.billable)))}h billable</p>${g.rows.slice(0,6).map(e=>row(esc(e.workTitle),esc(e.person||me.name),`<b>${fmt(e.hours)}h</b>`)).join('')}${g.rows.length>6?'<p>Click to see all '+g.rows.length+' entries.</p>':''}${!g.rows.length?'<p>No recorded entries.</p>':''}`;
 panel.querySelectorAll('[data-graphic]').forEach(b=>{const g=graphics[+b.dataset.graphic];const show=()=>{popup.innerHTML=graphicBody(g);popup.hidden=false;const r=b.getBoundingClientRect(),p=popup.getBoundingClientRect();popup.style.left=Math.max(12,Math.min(innerWidth-p.width-12,r.left+r.width/2-p.width/2))+'px';popup.style.top=Math.max(12,r.top-p.height-12)+'px'};b.onpointerenter=show;b.onfocus=show;b.onpointerleave=()=>popup.hidden=true;b.onblur=()=>popup.hidden=true;b.onclick=()=>{popup.hidden=true;detail(esc(g.title),g.summary?`<p>${esc(g.summary)}</p>`:g.rows.map(e=>row(esc(e.workTitle),esc(e.person||me.name)+' · '+esc(e.projectName),`<b>${fmt(e.hours)}h</b>`)).join('')||'<p>No recorded entries.</p>')};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click()}if(e.key==='Escape')popup.hidden=true}});
 panel.querySelectorAll('[data-report-day]').forEach(b=>b.onclick=()=>{const rows=chartRows.filter(e=>e.date===b.dataset.reportDay);detail(date(b.dataset.reportDay)+' · Recorded time',rows.map(e=>row(esc(e.workTitle),esc(e.person||me.name)+' · '+esc(e.projectName),`<b>${fmt(e.hours)}h</b>`)).join('')||'<p>No recorded time for this day.</p>')});
}

async function forecastEditor(c){const {api,projectId,render}=c,cfg=await api('settings'),f=cfg.projects[projectId()]||{},dialog=document.createElement('dialog');dialog.className='tm-dialog';dialog.setAttribute('aria-label','Project forecast');dialog.innerHTML=`<form class="tm"><header class="tm-head"><h2>Project forecast</h2><button type="button" data-close>Close</button></header><p>Studio currency. Enter zero when no cost is expected. Empty estimates keep the forecast incomplete.</p><div class="tm-grid">${[['costBudget','Cost budget'],['remainingLabor','Remaining labor'],['consultantFees','Total consultant fees'],['expenses','Total other expenses']].map(([k,label])=>`<label>${label}<input name="${k}" type="number" min="0" step="0.01" value="${f[k]??''}"></label>`).join('')}</div><details><summary>Labor cost from an external timesheet report</summary><p>A summary replaces recorded labor costs for its date range. Hours remain visible and costs are counted once.</p>${(f.laborSummaries||[]).map((s,i)=>`<label class="tm-check"><input type="checkbox" name="keep${i}" checked>Keep ${esc(s.from)} – ${esc(s.to)} · ${money(s.amount)}</label>`).join('')}<div class="tm-grid"><label>From<input name="from" type="date"></label><label>Through<input name="to" type="date"></label></div><label>Labor cost for this period<input name="amount" type="number" min="0" step="0.01" placeholder="Optional"></label></details><p role="status" data-error></p><footer><button class="tm-primary">Save forecast</button></footer></form>`;document.getElementById('sh-v2').append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target),values={...f};for(const k of ['costBudget','remainingLabor','consultantFees','expenses']){if(data.get(k)==='')delete values[k];else values[k]=+data.get(k)}values.laborSummaries=(f.laborSummaries||[]).filter((_,i)=>data.has('keep'+i));if(data.get('amount')!==''||data.get('from')||data.get('to'))values.laborSummaries.push({from:data.get('from'),to:data.get('to'),amount:data.get('amount')===''?NaN:+data.get('amount')});e.submitter.disabled=true;try{await api('forecast',{revision:cfg.revision,projectId:projectId(),values,replace:true});dialog.close();await render()}catch(err){dialog.querySelector('[data-error]').textContent=err.message;e.submitter.disabled=false}}}
