(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const shift=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const monday=date=>shift(date,-(new Date(date+'T12:00:00').getDay()+6)%7);
const fmt=date=>new Date(date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}),hrs=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
let sample,host,me,tab='My time',week=monday(today()),generation=0;
let demoModule,loadedProject;
const api=async(path,data)=>{const project=window.v2Workspace?.timeWork();if(project?.sampleVersion&&project.sampleTime){demoModule||=import(new URL('src/demo-time-api.js',location.href).href);return (await demoModule).demoTime(path,data,project,projectId(),()=>window.v2Workspace.saveDemoTime())}return window.v2Cloud.time(path,data)};
const projectId=()=>window.v2Cloud.projectId;
function work(){const d=window.v2Workspace?.timeWork()||{};return [{key:'project:',type:'project',id:'',title:'General project work'},...(me?.settings?.categories||[]).map(title=>({key:'studio:'+title,type:'studio',id:title,title})),...['tasks','deliverables','milestones'].flatMap(k=>(d[k]||[]).map((x,i)=>({key:k+':'+(x.id||i),type:k.slice(0,-1),id:x.id||k+'-'+i,title:x.title,milestoneId:k==='milestones'?x.id:x.milestoneId||''})))]}
const buttons=names=>names.map(n=>`<button data-tab-time="${n}" aria-selected="${tab===n}">${({'My timesheet':'Timesheet','Reports':'My reports','Project hours':'Project reports','Team review':'Team reports'})[n]||n}</button>`).join('');
let day=today(),returnTab='Settings';
const entries=()=>me.entries.filter(e=>!e.voided),mineWeek=()=>entries().filter(e=>e.date>=week&&e.date<=shift(week,6));
const notify=message=>{const el=host?.querySelector('[data-time-status]');if(el)el.textContent=message};
async function refresh(){me=await api('me');loadedProject=projectId();return me}
async function act(path,data){await api(path,{revision:me.revision,...data});await refresh();await render()}
function row(e){return `<div class="tm-row"><div><b>${esc(e.workTitle)}</b><small>${esc(e.projectName)} · ${esc(e.workType)} · ${fmt(e.date)}</small>${e.note?`<small>${esc(e.note)}</small>`:''}</div><strong>${hrs(e.hours)} h</strong>${e.projectId===projectId()?`<button data-resume-work="${esc(e.id)}">Start timer</button>`:''}<button data-entry="${esc(e.id)}">Edit</button></div>`}
async function render(){if(!host?.isConnected)return;const version=++generation;const total=mineWeek().reduce((n,e)=>n+e.hours,0);host.innerHTML=`<section class="tm tm-a1-exact"><header class="tm-head"><div><span class="tm-eyebrow">YOUR STUDIO · YOUR TIME</span><h1>Time well spent.</h1></div><button class="tm-primary" data-enter ${me.settings.enabled?'':'disabled'}>+ Enter time</button></header>${me.demo?`<section class="demo"><div><small>SAMPLE WORKSPACE</small><b>Sample — San Marino</b><span>Fictional hours, people and costs. Your real work stays separate.</span></div><div class="employee"><span class="avatar">${esc(me.name[0])}</span><label>View demo as<select data-demo-person aria-label="View demo as">${['Alex','Maya','Studio principal'].map(n=>`<option ${me.name===n?'selected':''}>${n}</option>`).join('')}</select></label><span class="chevron">⌄</span></div></section>`:''}<nav class="tm-tabs a1-pages">${buttons(['My time','My timesheet','Reports','Project hours',...(me.admin?['Team review','Settings','Connections']:['Tracking settings'])])}</nav>${!me.settings.enabled?'<p class="tm-banner">Time tracking is off. Your saved history is still available.</p>':''}<p role="status" data-time-status></p><div data-panel></div></section>`;
 const panel=host.querySelector('[data-panel]');
 if(tab==='My time')panel.innerHTML=`<div class="tm-grid"><article class="tm-card tm-blue"><span class="tm-eyebrow">THIS WEEK · ${fmt(week)} – ${fmt(shift(week,6))}</span><h2><span class="tm-number">${hrs(total)}</span> hours</h2><p>${esc(me.name)} · across your projects</p><button data-sheet>Review my timesheet →</button></article><article class="tm-card"><span class="tm-eyebrow">QUICK ENTRY</span><h2>Say it in your own words.</h2><p>“I spent 2.5 hours on the proposal today.”</p><button data-speak>Type or dictate time →</button><small>Keyboard dictation supported. Suggestions are reviewed before saving.</small></article></div><article class="tm-card tm-timer"><div><b>${me.timer?esc(me.timer.workTitle):'Make time for the work.'}</b><small>${me.timer?(me.timer.paused?'Paused':'Timer running'):'Start a stopwatch or count down your work allowance.'}</small></div><div class="tm-tools"><button data-start-clock ${me.settings.enabled?'':'disabled'}>${me.timer?'Choose work':'Start timer'}</button>${me.timer||me.drafts?.length?'<button data-session-review>Review tracked time</button>':''}</div></article><article class="tm-card"><header class="tm-head"><h2>${fmt(day)}${day===today()?' · Today':''}</h2><div class="tm-tools"><button data-day-step="-7">‹ Week</button><button data-day-step="7">Week ›</button><button data-today>Today</button></div></header><div class="tm-day-strip">${Array.from({length:7},(_,i)=>shift(monday(day),i)).map(d=>`<button data-time-day="${d}" aria-pressed="${day===d}"><small>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</small><b>${fmt(d)}</b><small>${hrs(entries().filter(e=>e.date===d).reduce((n,e)=>n+e.hours,0))} h</small></button>`).join('')}</div>${entries().filter(e=>e.date===day).map(row).join('')||'<p>No entries for this day. Enter hours or start a timer.</p>'}</article>`;
 if(tab==='My timesheet'){
 const days=Array.from({length:7},(_,i)=>shift(week,i)),state=me.weeks[week]?.state||'draft',items=mineWeek(),groups=[...new Map(items.map(e=>[e.projectId+'|'+e.workType+'|'+e.workId,e])).values()];
 panel.innerHTML=`<div class="tm-head"><div class="tm-tools"><button data-week="-7">‹ Week</button><b>${fmt(week)} – ${fmt(shift(week,6))}</b><button data-week="7">Week ›</button><button data-current>Current week</button></div><span class="tm-badge">${esc(state)}</span></div><article class="tm-card"><div class="tm-table-wrap"><table><thead><tr><th>Project / work</th>${days.map(d=>`<th>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}<small>${fmt(d)}</small></th>`).join('')}<th>Total</th></tr></thead><tbody>${groups.map(e=>{const matching=items.filter(x=>x.projectId===e.projectId&&x.workType===e.workType&&x.workId===e.workId);return `<tr><th>${esc(e.workTitle)}<small>${esc(e.projectName)}</small></th>${days.map(d=>`<td>${hrs(matching.filter(x=>x.date===d).reduce((n,x)=>n+x.hours,0))}</td>`).join('')}<td><b>${hrs(matching.reduce((n,x)=>n+x.hours,0))}</b></td></tr>`}).join('')}</tbody><tfoot><tr><th>Total hours</th>${days.map(d=>`<td>${hrs(items.filter(x=>x.date===d).reduce((n,x)=>n+x.hours,0))}</td>`).join('')}<td><b>${hrs(total)}</b></td></tr></tfoot></table></div><footer><small>Submitted weeks are locked until withdrawn or returned.</small>${['draft','returned'].includes(state)?'<button class="tm-primary" data-submit>Submit week</button>':state==='submitted'?'<button data-withdraw>Withdraw submission</button>':'<b>✓ Approved</b>'}</footer></article><article class="tm-card"><h2>Entries this week</h2>${items.map(row).join('')||'<p>No entries for this week.</p>'}</article>`;
 }
 if(tab==='Project hours'){
 panel.innerHTML='<p>Loading project hours…</p>';const d=await api('project?id='+encodeURIComponent(projectId()));if(version!==generation)return;
 panel.innerHTML=`<article class="tm-card tm-blue"><span class="tm-eyebrow">${esc(window.v2Cloud.projectName)}</span><h2><span class="tm-number">${hrs(d.restricted?entries().filter(e=>e.projectId===projectId()).reduce((n,e)=>n+e.hours,0):d.total)}</span> hours</h2><p>${d.restricted?'Your hours · team totals hidden by studio settings':'Total team hours · every entry counted once'}</p></article>${d.work?.length?`<article class="tm-card"><h2>Hours by work</h2>${d.work.map(x=>`<div class="tm-row"><div><b>${esc(x.title)}</b><small>${esc(x.type)}</small></div><strong>${hrs(x.hours)} h</strong></div>`).join('')}</article>`:''}${Object.keys(d.milestones||{}).length?`<article class="tm-card"><h2>Milestone roll-up</h2><p>Includes linked tasks and deliverables. These hours are already in the project total.</p>${Object.entries(d.milestones).map(([id,h])=>`<div class="tm-row"><b>${esc(work().find(w=>w.type==='milestone'&&w.id===id)?.title||'Linked milestone')}</b><strong>${hrs(h)} h</strong></div>`).join('')}</article>`:''}${me.admin?`<article class="tm-card"><span class="tm-eyebrow">ADMINISTRATORS ONLY</span><h2>Project cost & budget</h2><div class="tm-metrics"><div><b>${hrs(d.finance.laborCost)}</b><small>Recorded labor cost · studio currency</small></div><div><b>${d.finance.budgetHours===undefined?'Not set':hrs(d.finance.budgetHours)}</b><small>Budget hours</small></div><div><b>${d.finance.fee===undefined?'Not set':hrs(d.finance.fee)}</b><small>Agreed fee · studio currency</small></div></div><p>${d.finance.unratedHours?hrs(d.finance.unratedHours)+' hours need an hourly cost rate. Cost is incomplete.':'Rates use the current studio settings.'} Labor cost alone is not project profit; expenses and remaining work also matter.</p><button data-settings>Set rates & budget →</button></article>`:''}`;
 }
 if(tab==='Team review'){
 const team=await api('team');if(version!==generation)return;panel.innerHTML=`<article class="tm-card"><span class="tm-eyebrow">ADMINISTRATORS ONLY</span><h2>Staff timesheets</h2>${team.people.map(p=>`<details><summary>${esc(p.name)} · ${hrs(p.entries.filter(e=>!e.voided).reduce((n,e)=>n+e.hours,0))} hours</summary>${Object.entries(p.weeks).map(([w,s])=>`<div class="tm-row"><div><b>${fmt(w)} – ${fmt(shift(w,6))}</b><small>${esc(s.state)}</small></div>${s.state==='submitted'?`<button data-review="approved" data-user="${esc(p.user)}" data-rev="${p.revision}" data-week-id="${w}">Approve</button>`:''}${['submitted','approved'].includes(s.state)?`<button data-review="returned" data-user="${esc(p.user)}" data-rev="${p.revision}" data-week-id="${w}">Return</button>`:''}</div>`).join('')}${p.entries.filter(e=>!e.voided).map(e=>`<div class="tm-row"><div><b>${esc(e.workTitle)}</b><small>${esc(e.projectName)} · ${fmt(e.date)}${e.note?' · '+esc(e.note):''}</small></div><strong>${hrs(e.hours)} h</strong></div>`).join('')}</details>`).join('')||'<p>No staff time submitted yet.</p>'}</article>`;
 }
 if(tab==='Settings'){
 const [cfg,team]=await Promise.all([api('settings'),api('team')]);if(version!==generation)return;const people=team.people.length?team.people:[me];panel.innerHTML=`<form class="tm-card" data-settings-form><h2>Time tracking settings</h2><label class="tm-check"><input type="checkbox" name="enabled" ${cfg.enabled?'checked':''}>Enable time tracking</label><label>Staff visibility<select name="visibility"><option value="total">Own entries + total project hours</option><option value="work">Own entries + project totals by work</option><option value="own">Own entries only</option></select></label><p>Only administrators can see other staff entries and cost rates. These permissions are enforced on the server.</p><h3>Hourly cost rates · studio currency</h3><p>Internal labor cost per hour, not the client billing rate.</p>${people.map((p,i)=>`<label>${esc(p.name)}<input type="number" step="0.01" min="0" name="rate${i}" placeholder="Not set" value="${cfg.rates[p.user]??''}"></label>`).join('')}<h3>${esc(window.v2Cloud.projectName)}</h3><div class="tm-grid"><label>Agreed fee<input name="fee" type="number" min="0" step="0.01" value="${cfg.projects[projectId()]?.fee??''}"></label><label>Budget hours<input name="budgetHours" type="number" min="0" step="0.25" value="${cfg.projects[projectId()]?.budgetHours??''}"></label></div><button class="tm-primary">Save settings</button></form>`;panel.querySelector('select').value=cfg.visibility;
 panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),rates={...cfg.rates},projects={...cfg.projects};people.forEach((p,i)=>{const v=f.get('rate'+i);if(v==='')delete rates[p.user];else rates[p.user]=Number(v)});projects[projectId()]={...projects[projectId()]};for(const k of ['fee','budgetHours'])if(f.get(k)!=='')projects[projectId()][k]=Number(f.get(k));await run(e.submitter,async()=>{await api('settings',{revision:cfg.revision,enabled:f.has('enabled'),visibility:f.get('visibility'),rates,projects});await refresh();await render();notify('Settings saved.')})};
 }
 if(tab==='Sample walkthrough'){
 const total=sample.entries.reduce((n,e)=>n+e.hours,0),cost=sample.entries.reduce((n,e)=>n+e.hours*(sample.rates[e.owner]||0),0),people=[...new Set(sample.entries.map(e=>e.owner))],milestones=window.v2Workspace.timeWork().milestones||[];
 panel.innerHTML=`<p class="tm-banner">Sample — San Marino · Fictional demo data. These hours are separate from actual staff timesheets.</p><div class="tm-grid"><article class="tm-card tm-blue"><span class="tm-eyebrow">SAMPLE TEAM HOURS</span><h2><span class="tm-number">${hrs(total)}</span> hours</h2><p>${hrs(sample.budgetHours-total)} hours remaining from a ${sample.budgetHours}-hour example budget.</p></article><article class="tm-card"><span class="tm-eyebrow">SAMPLE PROJECT FINANCIALS</span><h2>${hrs(cost)} labor cost</h2><p>Example design fee: ${hrs(sample.fee)} · studio currency. Labor-to-date is not final project profit.</p></article></div><article class="tm-card"><h2>Demo time allowances</h2><p>Example countdowns for the sample project. Demo hours stay separate from staff records.</p>${(sample.allowances||[]).map(a=>`<div class="tm-budget-row"><div><b>${esc(a.title)}</b><small>${hrs(a.used)} / ${hrs(a.hours)} hours used</small></div><strong>${clock(Math.max(0,a.hours-a.used)*3600)} remaining</strong></div>`).join('')}<h2>Milestones & linked work</h2>${milestones.map(m=>{const h=sample.entries.filter(e=>e.milestoneId===m.id).reduce((n,e)=>n+e.hours,0);return `<div class="tm-row"><div><b>${esc(m.title)}</b><small>${esc(m.state||'Planned')} · ${m.date?fmt(m.date):'No date'}</small></div><strong>${hrs(h)} h</strong></div>`}).join('')}</article><article class="tm-card"><h2>Example staff timesheets</h2>${people.map(person=>`<details open><summary>${esc(person)} · ${hrs(sample.entries.filter(e=>e.owner===person).reduce((n,e)=>n+e.hours,0))} hours</summary>${sample.entries.filter(e=>e.owner===person).map(e=>`<div class="tm-row"><div><b>${esc(e.title)}</b><small>${fmt(e.date)} · ${esc(e.type)} · ${esc(e.note)}</small></div><strong>${hrs(e.hours)} h</strong></div>`).join('')}</details>`).join('')}</article>`;
 }
 if(tab==='Connections')panel.innerHTML=`<div class="tm-grid">${['Harvest','Toggl Track'].map(name=>`<article class="tm-card"><span class="tm-eyebrow">NOT CONNECTED</span><h2>${name}</h2><p>Time is currently saved in Studio H. External syncing is not enabled.</p><p>Planned connection: match a project, map external tasks to Studio H work, and import entries once using their source ID.</p><a href="${name==='Harvest'?'https://help.getharvest.com/api-v2/':'https://engineering.toggl.com/docs/'}" target="_blank" rel="noopener">View API documentation ↗</a></article>`).join('')}</div><article class="tm-card"><h2>Native first. Connect when you need it.</h2><p>Harvest is the recommended first integration. Either service needs account authorization and explicit work mapping. Milestones and deliverables remain Studio H relationships.</p></article>`;
 if(version!==generation)return;await studioPanel(panel);if(version!==generation)return;const a1=await import(new URL('src/time-a1.js',location.href).href);if(version!==generation)return;await a1.renderA1({panel,me,tab,api,week,day,today,shift,fmt,projectId,work,allowance,used,refresh,render,notify,setWeek:d=>{week=monday(d);render()},openCell,enter,timerDialog,timerStatus,clock,seconds,isCurrent:()=>version===generation});if(version!==generation)return;
 if(['Tracking settings','Time budgets'].includes(tab)){const back=`<div class="a1-subpage-nav"><button type="button" data-time-back>← Back to ${returnTab==='My time'?'My time':returnTab==='Reports'?'My reports':returnTab==='Project hours'?'Project reports':returnTab==='Team review'?'Team reports':'Settings'}</button></div>`;panel.insertAdjacentHTML('afterbegin',back);panel.insertAdjacentHTML('beforeend',back)}
 bind();dock();
}
async function run(button,fn){if(button)button.disabled=true;try{await fn()}catch(e){notify(e.message);if(button)button.disabled=false}}
function bind(){host.querySelectorAll('[data-time-back]').forEach(b=>b.onclick=()=>{tab=returnTab;render().then(()=>host.querySelector('[data-panel]')?.scrollIntoView({block:'start'}))});host.querySelector('[data-demo-person]')?.addEventListener('change',async e=>{if(me.timer){notify('Finish the demo timer before switching staff.');e.target.value=me.name;return}window.v2Workspace.timeWork().sampleTime.activePerson=e.target.value;window.v2Workspace.saveDemoTime();await refresh();await render()});host.querySelectorAll('[data-resume-work]').forEach(b=>b.onclick=()=>{const e=entries().find(x=>x.id===b.dataset.resumeWork);timerDialog({type:e.workType,id:e.workId})});host.querySelector('[data-start-clock]')?.addEventListener('click',()=>timerDialog());host.querySelector('[data-session-review]')?.addEventListener('click',reviewSession);host.querySelectorAll('[data-time-day]').forEach(b=>b.onclick=()=>{day=b.dataset.timeDay;render()});host.querySelectorAll('[data-day-step]').forEach(b=>b.onclick=()=>{day=shift(day,+b.dataset.dayStep);render()});host.querySelector('[data-today]')?.addEventListener('click',()=>{day=today();render()});host.querySelectorAll('[data-tab-time]').forEach(b=>b.onclick=()=>{if(['Tracking settings','Time budgets'].includes(b.dataset.tabTime)&&!['Tracking settings','Time budgets'].includes(tab))returnTab=tab;tab=b.dataset.tabTime;const nested=['Tracking settings','Time budgets'].includes(tab);render().then(()=>{if(nested)host.querySelector('[data-panel]')?.scrollIntoView({block:'start'})}).catch(e=>notify(e.message))});host.querySelectorAll('[data-enter],[data-speak]').forEach(b=>b.onclick=()=>enter(null,{natural:b.hasAttribute('data-speak')}));host.querySelector('[data-sheet]')?.addEventListener('click',()=>{tab='My timesheet';render()});host.querySelector('[data-settings]')?.addEventListener('click',()=>{tab='Settings';render()});host.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>enter(null,{entry:entries().find(e=>e.id===b.dataset.entry)}));host.querySelector('[data-timer]')?.addEventListener('click',()=>enter(null,me.timer?{timer:me.timer}:{startTimer:true}));host.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{week=shift(week,+b.dataset.week);render()});host.querySelector('[data-current]')?.addEventListener('click',()=>{week=monday(today());render()});for(const [sel,state]of [['[data-submit]','submitted'],['[data-withdraw]','draft']])host.querySelector(sel)?.addEventListener('click',e=>run(e.currentTarget,()=>act('week',{week,state})));host.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>run(b,async()=>{await api('review',{user:b.dataset.user,revision:b.dataset.rev,week:b.dataset.weekId,state:b.dataset.review});await render()}));}

function openCell(group,date){const matches=entries().filter(e=>e.projectId===group.projectId&&e.workType===group.workType&&e.workId===group.workId&&e.date===date);if(matches.length===1)return enter(null,{entry:matches[0]});if(!matches.length)return enter(null,{date,workContext:group});const el=modal('Time for '+esc(fmt(date)));el.querySelector('[data-modal-body]').innerHTML=matches.map(e=>`<div class="tm-row"><div><b>${esc(e.workTitle)}</b><small>${esc(e.note||e.projectName)}</small></div><button data-cell-edit="${esc(e.id)}">${hrs(e.hours)} h · Edit</button></div>`).join('')+'<footer><button data-cell-add>＋ Add time</button></footer>';el.querySelectorAll('[data-cell-edit]').forEach(b=>b.onclick=()=>{el.close();enter(null,{entry:matches.find(e=>e.id===b.dataset.cellEdit)})});el.querySelector('[data-cell-add]').onclick=()=>{el.close();enter(null,{date,workContext:group})};}

async function enter(link,options={}){
 if(options.startTimer)return timerDialog(link);if(options.timer)return reviewSession();
 const root=document.getElementById('sh-v2'),dialog=document.createElement('dialog');dialog.className='tm-dialog';dialog.setAttribute('aria-label','Enter time');dialog.innerHTML='<p>Loading your time entry…</p><button data-close>Close</button>';root.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());
 try{await refresh();if(!me.settings.enabled)throw Error('Time tracking is turned off. An administrator can enable it in Time & timesheets.');const entry=options.entry||options.timer||(options.workContext?{...options.workContext,date:options.date,hours:'',note:''}: {}),list=work(),linkWork=link?list.find(w=>w.type===link.type&&w.id===link.id):null;let selected=linkWork||list.find(w=>w.type===entry.workType&&w.id===entry.workId)||list[0];if(entry.projectId&&entry.projectId!==projectId()){selected={key:'existing',type:entry.workType,id:entry.workId,title:entry.workTitle,milestoneId:entry.milestoneId};list.push(selected)}
 const locked=options.entry&&['submitted','approved'].includes(me.weeks[monday(entry.date)]?.state),id=options.entry?.id||crypto.randomUUID();
 dialog.innerHTML=`<div class="tm tm-a1-exact tm-a1-entry"><header class="tm-head"><div><span class="tm-eyebrow">${esc(entry.projectName||window.v2Cloud.projectName)}</span><h2>Record a little progress.</h2></div><button type="button" data-close aria-label="Close time entry">×</button></header><div class="entrytabs"><button type="button" data-manual class="${options.natural?'':'tm-primary'}">Manual</button><button type="button" data-linked-timer ${options.entry?'disabled':''}>Timer</button><button type="button" data-natural class="${options.natural?'tm-primary':''}">Type or dictate</button></div><section data-natural-panel ${options.natural?'':'hidden'}><label>Describe your work<textarea data-phrase rows="2" placeholder="I spent 2.5hrs working on the proposal today"></textarea></label><button type="button" data-parse>Suggest entry</button><small>Use your keyboard microphone to dictate. Review the suggested work, date and duration before saving.</small><p role="status" data-parse-note></p></section><form><div class="duration"><div><small>DURATION</small><label><input name="hours" aria-label="Hours" type="number" min="0.0001" max="24" step="any" required value="${entry.hours||''}" placeholder="0.0"><span>hours</span></label></div><div class="quick-duration"><b data-duration-copy>Quick amounts</b><div class="tm-tools">${[.25,.5,1,2].map(n=>`<button type="button" data-hours="${n}">${n<1?n*60+'m':n+'h'}</button>`).join('')}</div></div></div><label>Work<select name="work">${list.map(w=>`<option value="${esc(w.key)}">${esc(w.title)} · ${w.type}</option>`).join('')}</select></label><div class="tm-grid a1-date-person"><label>Date<input name="date" type="date" value="${options.date||entry.date||today()}" required></label><label>Person<input value="${esc(me.name)}" readonly></label></div><label>Note · optional<input name="note" maxlength="2000" value="${esc(entry.note||'')}" placeholder="What moved forward?"></label><p role="status" data-error>${locked?'This week is locked. Withdraw its submission or ask an administrator to return it.':''}</p><footer><label class="tm-check"><input name="billable" type="checkbox" ${entry.billable!==false?'checked':''}><span>Billable work<small>Client work</small></span></label><div class="tm-tools">${options.entry&&!locked?'<button type="button" data-void>Remove</button>':''}<button class="tm-primary" data-save-time ${locked?'disabled':''}>Save time →</button></div></footer></form></div>`;
 const setMode=natural=>{dialog.querySelector('[data-natural-panel]').hidden=!natural;dialog.querySelector('[data-natural]').classList.toggle('tm-primary',natural);dialog.querySelector('[data-manual]').classList.toggle('tm-primary',!natural)};dialog.querySelector('[data-natural]').onclick=()=>setMode(true);dialog.querySelector('[data-manual]').onclick=()=>setMode(false);
 const updateDuration=()=>{const n=Number(dialog.querySelector('[name=hours]').value),m=Math.round(n*60),label=n>0?`${Math.floor(m/60)?Math.floor(m/60)+'h ':''}${m%60?m%60+'m':''}`.trim():'';dialog.querySelector('[data-duration-copy]').textContent=label||'Quick amounts';dialog.querySelector('[data-save-time]').textContent=label?'Save '+label+' →':'Save time →'};dialog.querySelector('[name=hours]').oninput=updateDuration;updateDuration();
 dialog.querySelector('[data-linked-timer]')?.addEventListener('click',()=>{dialog.close();timerDialog(link||{type:selected.type,id:selected.id})});
 const form=dialog.querySelector('form');form.elements.work.value=selected.key;const updateBillable=()=>{const studio=list.find(w=>w.key===form.elements.work.value)?.type==='studio';form.elements.billable.disabled=studio;if(studio)form.elements.billable.checked=false;const label=form.elements.billable.nextElementSibling;if(label)label.innerHTML=studio?'Non-billable<small>Studio work</small>':'Billable work<small>Client work</small>'};form.elements.work.onchange=updateBillable;updateBillable();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelectorAll('[data-hours]').forEach(b=>b.onclick=()=>{form.elements.hours.value=b.dataset.hours;updateDuration()});
 dialog.querySelector('[data-parse]').onclick=async e=>{const button=e.currentTarget,text=dialog.querySelector('[data-phrase]').value,note=dialog.querySelector('[data-parse-note]');button.disabled=true;note.textContent='Suggesting your time entry…';let p=window.v2TimeParse(text,list,today()),ai=false;try{const result=await api('suggest',{projectId:entry.projectId||projectId(),text,today:today(),work:list.map(w=>({key:w.key,title:w.title}))});if(result.ai){p={...p,...result,dateCertain:!!result.date};ai=true}}catch{}if(!dialog.isConnected)return;if(p.hours&&form.elements.hours)form.elements.hours.value=p.hours;if(p.date)form.elements.date.value=p.date;if(p.matches.length===1)form.elements.work.value=p.matches[0];updateBillable();updateDuration();form.elements.note.value=text;note.textContent=(ai?'AI draft. ':me.demo?'Demo draft · word matching. ':'AI unavailable; basic word matching used. ')+(p.hours?'Duration suggested. ':'Add a duration, such as 2.5 hours. ')+(p.matches.length===1?'Work suggested. ':p.matches.length>1?'Several items match; choose the correct work. ':'No clear work match; choose the correct work. ')+(p.dateCertain?'':'Check the date. ')+'Review before saving.';button.disabled=false};

 const save=async(button,path,payload)=>{button.disabled=true;try{await api(path,{revision:me.revision,...payload});dialog.close();await refresh();if(host?.isConnected)await render();updateQuick();}catch(e){dialog.querySelector('[data-error]').textContent=e.message;button.disabled=false}};
 form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),w=list.find(w=>w.key===f.get('work'));save(e.submitter,options.startTimer?'timer/start':'entry',{id,projectId:w.type==='studio'?'studio':entry.projectId&&entry.projectId!=='studio'?entry.projectId:projectId(),workType:w.type,workId:w.id,workTitle:w.title,milestoneId:w.milestoneId||'',date:f.get('date'),hours:Number(f.get('hours')),note:f.get('note'),billable:w.type!=='studio'&&f.has('billable'),...(options.timer?{timerId:entry.id}:{})})};dialog.querySelector('[data-void]')?.addEventListener('click',e=>save(e.currentTarget,'void',{id}));
 }catch(e){dialog.innerHTML=`<div class="tm"><h2>Time entry</h2><p>${esc(e.message)}</p><button data-close>Close</button></div>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close()}
}
function updateQuick(){const b=document.getElementById('tm-quick');if(b)b.textContent=me?.timer?'Timer · '+(me.timer.paused?'Paused':'Running'):'Enter time'}
// Live timer UI. Only deliberate work selections can change the assignment.
const timerController=crypto.randomUUID();
let dockSignature='',pendingFocus=null;
let sessionBusy=false,sessionError='',lastActivity=Date.now(),lastPulse=0,installed=false,trackingConsent=false;
const clock=n=>{n=Math.max(0,Math.floor(n||0));return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(x=>String(x).padStart(2,'0')).join(':')};
const seconds=t=>Math.min(t?.limitSeconds??Infinity,(t?.elapsedSeconds||0)+(t&&!t.paused?Math.max(0,(Math.min(Date.now(),Date.parse(t.leaseUntil)||Date.now())-Date.parse(t.runningSince||t.startedAt))/1000):0));
const allowance=w=>me?.budgets?.[projectId()]?.[w.type+':'+w.id];
const used=w=>(me?.entries||[]).concat(me?.drafts||[]).filter(e=>!e.voided&&e.projectId===projectId()&&e.workType===w.type&&e.workId===w.id).reduce((n,e)=>n+e.hours,0);
function modal(title){const el=document.createElement('dialog');el.className='tm-dialog';el.innerHTML=`<div class="tm tm-a1-exact"><header class="tm-head"><div><span class="tm-eyebrow">${esc(window.v2Cloud.projectName)}</span><h2>${title}</h2></div><button data-close>Close</button></header><div data-modal-body></div><p role="status" data-session-error></p></div>`;document.getElementById('sh-v2').append(el);el.querySelector('[data-close]').onclick=()=>el.close();el.onclose=()=>el.remove();el.showModal();return el}
async function session(path,data={},redraw=true){if(sessionBusy)return false;sessionBusy=true;try{const result=await api('session/'+path,{revision:me.revision,controller:timerController,...data});await refresh();sessionError=result.warning||'';if(['start','resume','switch'].includes(path)){trackingConsent=true;lastActivity=Date.now()}if(path==='finish')trackingConsent=false;if(redraw&&host?.isConnected)await render();return true}catch(e){sessionError=e.message;try{await refresh()}catch{}document.querySelectorAll('[data-session-error]').forEach(el=>el.textContent=e.message);return false}finally{sessionBusy=false;dock();if(pendingFocus){const next=pendingFocus;pendingFocus=null;queueMicrotask(()=>focusWork(next))}}}
async function timerDialog(link){try{await refresh()}catch(e){sessionError=e.message;dock();return}const list=work(),selected=link?list.find(w=>w.type===link.type&&w.id===link.id):list.find(w=>!['project','studio'].includes(w.type))||list[0];const el=modal('Make time for the work.');el.querySelector('[data-modal-body]').innerHTML=`<div class="entrytabs"><button data-timer-manual>Manual</button><button class="tm-primary" type="button">Timer</button><button data-timer-natural>Type or dictate</button></div><form data-start><label>What are you working on?<select name="work">${list.map(w=>`<option value="${esc(w.key)}">${esc(w.title)} · ${w.type}</option>`).join('')}</select></label><div class="tm-grid"><label>Timer style<select name="mode"><option value="stopwatch">Stopwatch · elapsed time</option><option value="countdown">Countdown · remaining allowance</option></select></label><div class="tm-budget-copy"></div></div><div class="tm-focus"><div class="tm-ring"><small data-clock-label>READY TO START</small><strong data-clock>00:00:00</strong></div><p>One active clock.<br>Pause for calls or breaks.<br>Review your time before saving.</p></div><details><summary>Notes · optional</summary><textarea name="note" rows="2" maxlength="2000"></textarea></details><label class="tm-check"><input type="checkbox" name="billable" checked>Billable time</label><footer><button class="tm-primary">${me.timer?'Switch work':'Start timer'}</button></footer></form>`;
 el.querySelector('[data-timer-manual]').onclick=()=>{el.close();enter(link)};el.querySelector('[data-timer-natural]').onclick=()=>{el.close();enter(link,{natural:true})};
 const f=el.querySelector('form');f.elements.work.value=selected.key;const update=()=>{const w=list.find(w=>w.key===f.elements.work.value),cap=allowance(w),left=Math.max(0,(cap||0)-used(w));f.elements.billable.disabled=w.type==='studio';if(w.type==='studio')f.elements.billable.checked=false;el.querySelector('.tm-budget-copy').innerHTML=`<small>YOUR WORK ALLOWANCE</small><b>${cap?hrs(left)+' of '+hrs(cap)+' h remaining':'No allowance set'}</b><small>${cap?'Your recorded and draft hours count toward this allowance.':'Use a stopwatch, or set an allowance in Time budgets.'}</small>`;el.querySelector('.tm-ring').style.setProperty('--arc',((cap?left/cap:1)*360)+'deg');el.querySelector('[data-clock]').textContent=clock(f.elements.mode.value==='countdown'?left*3600:0);el.querySelector('[data-clock-label]').textContent=f.elements.mode.value==='countdown'?'TIME REMAINING':'ELAPSED TIME'};f.elements.mode.value=allowance(selected)?'countdown':'stopwatch';update();f.onchange=e=>{if(e.target===f.elements.work){const w=list.find(w=>w.key===f.elements.work.value);f.elements.mode.value=allowance(w)?'countdown':'stopwatch'}update()};
 f.onsubmit=async e=>{e.preventDefault();const w=list.find(w=>w.key===f.elements.work.value);e.submitter.disabled=true;if(me.timer&&!me.preferences?.smart){el.querySelector('[data-session-error]').textContent='Finish the current timer before starting another, or enable smart switching in Tracking settings.';e.submitter.disabled=false;return}const ok=await session(me.timer?'switch':'start',{projectId:w.type==='studio'?'studio':projectId(),date:today(),offsetMinutes:new Date().getTimezoneOffset(),workType:w.type,workId:w.id,workTitle:w.title,milestoneId:w.milestoneId||'',mode:f.elements.mode.value,note:f.elements.note.value,billable:w.type!=='studio'&&f.elements.billable.checked});if(ok){trackingConsent=true;el.close()}else e.submitter.disabled=false};
}
async function reviewSession(){await refresh();if(me.timer){if(!await session('finish',{timerId:me.timer.id}))return}const el=modal('Review your tracked time'),drafts=me.drafts||[];el.querySelector('[data-modal-body]').innerHTML=drafts.length?`<p>Adjust the work, date and hours. Unchecked rows will be discarded when you save this review.</p><form data-review-drafts>${drafts.map((d,i)=>{const list=d.projectId===projectId()?work():[{key:d.workType+':'+d.workId,type:d.workType,id:d.workId,title:d.workTitle}];return `<section class="tm-draft"><label class="tm-check"><input name="include${i}" type="checkbox" checked>Include · ${esc(d.projectName)}</label><label>Work<select name="work${i}">${list.map(w=>`<option value="${esc(w.type+':'+w.id)}" ${w.type===d.workType&&w.id===d.workId?'selected':''}>${esc(w.title)} · ${w.type}</option>`).join('')}</select></label><div class="tm-grid a1-date-person"><label>Date<input name="date${i}" type="date" required value="${d.date}"></label><label>Hours<input name="hours${i}" type="number" min="0.0001" max="24" step="any" required value="${Math.max(.0001,d.hours).toFixed(4)}"></label></div><label>Notes<input name="note${i}" value="${esc(d.note)}" maxlength="2000"></label><label class="tm-check"><input name="billable${i}" type="checkbox" ${d.billable?'checked':''}>Billable</label></section>`}).join('')}<footer><button class="tm-primary">Save reviewed time</button></footer></form>`:'<p>No tracked time to review yet.</p>';
 const f=el.querySelector('form');if(f)f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const items=drafts.map((d,i)=>{const v=f.elements['work'+i].value,type=v.split(':')[0],id=v.slice(type.length+1),w=work().find(w=>w.type===type&&w.id===id);return {id:d.id,discard:!f.elements['include'+i].checked,workType:type,workId:id,workTitle:d.projectId===projectId()?w?.title||d.workTitle:d.workTitle,milestoneId:d.projectId===projectId()?w?.milestoneId||'':d.milestoneId,date:f.elements['date'+i].value,hours:+f.elements['hours'+i].value,note:f.elements['note'+i].value,billable:f.elements['billable'+i].checked}});if(await session('review',{items})){el.close()}else e.submitter.disabled=false};
}
function dock(){let el=document.getElementById('tm-dock');if(!el){el=document.createElement('div');el.id='tm-dock';el.className='tm';document.getElementById('sh-v2')?.append(el)}if(!me||!el)return;const t=me.timer,n=me.drafts?.length||0;if(!t&&!n&&!sessionError){el.hidden=true;dockSignature='';return}el.hidden=false;const s=seconds(t),left=t?.limitSeconds==null?s:Math.max(0,t.limitSeconds-s);document.querySelectorAll('.tm-focus-live .tm-ring').forEach(x=>x.style.setProperty('--arc',((t?.capSeconds?left/t.capSeconds:1)*360)+'deg'));document.querySelectorAll('[data-live-clock]').forEach(x=>x.textContent=clock(left));document.querySelectorAll('[data-live-state]').forEach(x=>x.textContent=t?.paused?(t.reason||'Paused'):'Clock running');document.querySelectorAll('[data-live-pause]').forEach(x=>x.textContent=t?.paused||t?.controller!==timerController?'Resume here':'Pause');const sig=JSON.stringify([t?.id,t?.paused,t?.reason,t?.workTitle,t?.controller,n,sessionError,me.preferences?.smart]);if(sig===dockSignature){const c=el.querySelector('.tm-clock');if(c)c.textContent=clock(left);return}dockSignature=sig;el.innerHTML=`${sessionError?`<p role="status">${esc(sessionError)}</p>`:''}${t?`<div><small>${t.paused?esc(t.reason||'Paused'):t.mode==='countdown'?'COUNTDOWN RUNNING':'TIMER RUNNING'}${me.preferences?.smart?' · SMART SWITCHING':''}</small><b>${esc(t.workTitle)}</b><small>${esc(t.projectName)}</small></div><button class="tm-clock" data-clock-open aria-label="Open active timer">${clock(left)}</button><button data-pause>${t.paused||t.controller!==timerController?'Resume here':'Pause'}</button><button data-finish>Finish & review</button>`:`<b>${n} time ${n===1?'entry':'entries'} to review</b><button data-finish>Review time</button>`}`;el.querySelector('[data-clock-open]')?.addEventListener('click',timerStatus);el.querySelector('[data-pause]')?.addEventListener('click',()=>session(t.paused||t.controller!==timerController?'resume':'pause',{timerId:t.id}));el.querySelector('[data-finish]')?.addEventListener('click',reviewSession);updateQuick()}
async function focusWork(link){lastActivity=Date.now();if(sessionBusy){pendingFocus=link;return}if(me?.timer?.controller!==timerController||!trackingConsent||!me?.preferences?.smart||!me?.timer||me.timer.paused||sessionBusy)return;const w=work().find(w=>w.type===link.type&&w.id===link.id);if(!w)return;await session('switch',{projectId:w.type==='studio'?'studio':projectId(),date:today(),offsetMinutes:new Date().getTimezoneOffset(),workType:w.type,workId:w.id,workTitle:w.title,milestoneId:w.milestoneId||'',mode:allowance(w)?'countdown':'stopwatch',billable:me.timer.billable,note:''},false)}
async function studioPanel(panel){
 if(tab==='Tracking settings'){const p=me.preferences||{smart:false,idleMinutes:5,pauseHidden:true};panel.innerHTML=`<form class="tm-card" data-preferences><h2>A timer that follows your work.</h2><p>Start one timer. With smart switching on, opening another task, deliverable or milestone in Schedule moves the clock to that item. General pages keep the current assignment. Pausing stays paused until you resume.</p><label class="tm-check"><input name="smart" type="checkbox" ${p.smart?'checked':''}>Automatically switch when I open specific work</label><label>Pause after inactivity<select name="idle"><option>2</option><option>5</option><option>10</option><option>15</option></select> minutes</label><label class="tm-check"><input name="hidden" type="checkbox" ${p.pauseHidden?'checked':''}>Pause when I leave this browser tab</label><p>Only activity inside Studio H is used. Calls and work in other apps are not detected. Review and adjust tracked entries before saving. An interrupted connection pauses tracking after at most 90 seconds.</p><button class="tm-primary">Save my preferences</button></form>`;const f=panel.querySelector('form');f.elements.idle.value=p.idleMinutes;f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const saved=await session('preferences',{smart:f.elements.smart.checked,idleMinutes:+f.elements.idle.value,pauseHidden:f.elements.hidden.checked});if(saved){trackingConsent=true;notify('Tracking preferences saved.')}else{notify(sessionError||'Preferences could not be saved. Please try again.');e.submitter.disabled=false}};}
 if(tab==='Time budgets'){const cfg=me.admin?await api('settings'):null;const list=work().filter(w=>!['project','studio'].includes(w.type));panel.innerHTML=`<form class="tm-card" data-work-budgets><h2>Time allowances</h2><p>Optional maximum hours per person for each work item. Countdowns subtract that person's saved and draft time. Milestone tracking is direct review work; linked task time is reported separately to avoid counting it twice.</p>${list.map((w,i)=>`<label class="tm-budget-row"><span><b>${esc(w.title)}</b><small>${w.type}</small></span><input type="number" name="cap${i}" min="0.01" step="any" placeholder="No limit" value="${allowance(w)??''}" ${me.admin?'':'disabled'} aria-label="Hours for ${esc(w.title)}"></label>`).join('')}${me.admin?'<button class="tm-primary">Save allowances</button>':'<p>An administrator sets these allowances.</p>'}</form>`;panel.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const budgets={};list.forEach((w,i)=>{const v=e.target.elements['cap'+i].value;if(v!=='')budgets[w.type+':'+w.id]=+v});try{await api('budgets',{revision:cfg.revision,projectId:projectId(),budgets});await refresh();await render();notify('Time allowances saved. Active sessions keep the allowance they started with.')}catch(err){notify(err.message);e.submitter.disabled=false}};}
 if(tab==='Reports'){const items=mineWeek(),days=Array.from({length:7},(_,i)=>shift(week,i)),total=items.reduce((n,e)=>n+e.hours,0),bill=items.filter(e=>e.billable).reduce((n,e)=>n+e.hours,0),max=Math.max(8,...days.map(d=>items.filter(e=>e.date===d).reduce((n,e)=>n+e.hours,0)));panel.innerHTML=`<div class="tm-head"><h2>Your week in view</h2><div class="tm-tools"><button data-week="-7">‹ Week</button><b>${fmt(week)} – ${fmt(shift(week,6))}</b><button data-week="7">Week ›</button></div></div><div class="tm-grid"><article class="tm-card tm-blue"><small>HOURS RECORDED</small><strong class="tm-number">${hrs(total)}</strong></article><article class="tm-card"><small>BILLABLE HOURS</small><strong class="tm-number">${hrs(bill)}</strong></article></div><article class="tm-card"><h2>Daily hours</h2><div class="tm-chart">${days.map(d=>{const n=items.filter(e=>e.date===d).reduce((n,e)=>n+e.hours,0);return `<div><b>${hrs(n)}</b><div class="tm-chart-bar" style="height:${Math.max(3,n/max*140)}px"></div><small>${new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</small></div>`}).join('')}</div><button data-csv>Download my week · CSV</button></article><article class="tm-card"><h2>Work allowances · this project</h2>${work().filter(w=>allowance(w)).map(w=>`<div class="tm-budget-row"><div><b>${esc(w.title)}</b><small>${hrs(used(w))} / ${hrs(allowance(w))} h · your saved + draft time</small><progress max="${allowance(w)}" value="${Math.min(allowance(w),used(w))}"></progress></div><b>${used(w)>allowance(w)?'Over allowance':hrs(allowance(w)-used(w))+' h left'}</b></div>`).join('')||'<p>No allowances set yet.</p>'}<p>Team totals and project labor costs are available under Project hours.</p></article>`;panel.querySelector('[data-csv]').onclick=()=>{const safe=s=>'"'+String(s??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"',csv=[['Date','Project','Work','Hours','Billable','Notes'],...items.map(e=>[e.date,e.projectName,e.workTitle,e.hours,e.billable?'Yes':'No',e.note])].map(r=>r.map(safe).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='my-time-'+week+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};}
}
async function timerStatus(){await refresh();if(!me.timer)return reviewSession();const t=me.timer,el=modal(esc(t.workTitle));el.querySelector('[data-modal-body]').innerHTML=`<div class="tm-focus tm-focus-live"><div class="tm-ring"><small>${t.mode==='countdown'?'TIME REMAINING':'ELAPSED TIME'}</small><strong data-live-clock></strong></div><div><b data-live-state></b><p>${esc(t.projectName)}</p><p>${me.preferences?.smart?'Smart switching is on. Open another item in Schedule to move the clock.':'This timer stays on this work until you finish.'}</p></div></div><footer><button data-live-pause>Pause</button><button data-switch>Choose work</button><button class="tm-primary" data-finish>Finish & review</button></footer>`;el.querySelector('[data-live-pause]').onclick=()=>session(me.timer.paused||me.timer.controller!==timerController?'resume':'pause',{timerId:me.timer.id});el.querySelector('[data-switch]').onclick=()=>{el.close();timerDialog()};el.querySelector('[data-finish]').onclick=()=>{el.close();reviewSession()};dock()}
function startMonitor(){if(installed)return;installed=true;['pointerdown','keydown','touchstart'].forEach(k=>document.addEventListener(k,()=>lastActivity=Date.now(),{passive:true}));document.addEventListener('visibilitychange',()=>{if(trackingConsent&&me?.timer?.controller===timerController&&document.hidden&&me?.timer&&!me.timer.paused&&me.preferences?.pauseHidden!==false)session('pause',{timerId:me.timer.id,reason:'Tab hidden'},false)});setInterval(async()=>{if(loadedProject&&loadedProject!==projectId()){trackingConsent=false;await refresh().catch(()=>{});dock();return}if(!me?.timer){dock();return}const t=me.timer;if(!t.paused&&t.leaseUntil&&Date.parse(t.leaseUntil)<=Date.now()){t.elapsedSeconds=seconds(t);t.paused=true;t.reason='Session inactive — resume to continue'}dock();if(sessionBusy||t.paused||!trackingConsent||t.controller!==timerController)return;const limit=t.limitSeconds!=null&&seconds(t)>=t.limitSeconds,idle=Date.now()-lastActivity>(me.preferences?.idleMinutes||5)*60000;if(limit||idle){await session('pause',{timerId:t.id,reason:limit?'Budget reached':'Idle — review before resuming'},false);return}if(Date.now()-lastPulse>30000){lastPulse=Date.now();await session('pulse',{timerId:t.id},false)}},1000)}

window.v2Time={enter,focus:focusWork,timer:timerDialog,mount:async el=>{host=el;sample=window.v2Workspace?.timeWork().sampleTime; if(tab==='Sample walkthrough')tab='My time';el.innerHTML='<p>Loading timesheets…</p>';try{await refresh();if(sample&&me.admin&&!me.budgets?.[projectId()]&&sample.allowances?.length){const cfg=await api('settings');await api('budgets',{revision:cfg.revision,projectId:projectId(),budgets:Object.fromEntries(sample.allowances.map(a=>[a.type+':'+a.workId,a.hours]))});await refresh()}await render()}catch(e){el.innerHTML=`<div class="tm"><h2>Time & timesheets</h2><p>${esc(e.message)}</p><button data-retry>Try again</button></div>`;el.querySelector('[data-retry]').onclick=()=>window.v2Time.mount(el)}},install(){startMonitor();const top=document.querySelector('#sh-v2 .topright');if(top&&!document.getElementById('tm-quick')){const b=document.createElement('button');b.id='tm-quick';b.textContent='Enter time';b.onclick=async()=>{try{await refresh()}catch{}me?.timer?timerStatus():enter(null,{})};top.append(b);refresh().then(()=>{trackingConsent=false;dock()}).catch(()=>{})}}};
})();
