/* V2 preview interactions. All writes are local and use V2-only keys. */
(()=>{'use strict';
const root=document.getElementById('sh-v2'),main=document.getElementById('sh-content'),oldAside=root.querySelector('aside');
root.classList.add('studio-v2');oldAside.hidden=true;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const appVersion=document.querySelector('meta[name="studioh-version"]')?.content||'V2 preview';
const key='studioh_v2_workspace_v2';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
const demo=Object.assign({links:[],phase:'Concept',tasks:[false,false,true,false],decisions:{},messages:{client:[],community:[],team:[]},savings:[],watch:{},time:[],favorites:[],notes:{},board:['Garden direction','Outdoor living','Materials & texture'],tab:{},pin:true},saved);
let active='home',tab='',search='',roadmap=[],clientView=false;
function persist(){localStorage.setItem(key,JSON.stringify(demo))}
const paths={home:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',brief:'M7 4H4v17h16V4h-3 M8 3h8v4H8Z M8 11h8 M8 15h6',design:'m4 20 4-1L20 7l-3-3L5 16Z M14 7l3 3',cost:'M5 3h14v18H5Z M8 6h8 M8 11h1m4 0h1m-6 4h1m4 0h1',chat:'M3 4h18v13H8l-5 4Z M7 8h10 M7 12h7',book:'M3 4h7l2 2 2-2h7v16h-7l-2 1-2-1H3Z M12 6v15',plant:'M12 21V10 M12 14C2 14 3 3 3 3s10 0 9 11 M12 17c10 0 9-11 9-11s-9 0-9 11',chart:'M4 20V10h4v10 M10 20V4h4v16 M16 20v-7h4v7',grid:'M3 3h7v7H3Z M14 3h7v7h-7Z M3 14h7v7H3Z M14 14h7v7h-7Z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',pin:'m9 3 6 0-1 6 4 4H6l4-4Z M12 13v8',folder:'M3 6h7l2 2h9v12H3Z',check:'m5 12 4 4L19 6',sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M12 1v3m0 16v3M1 12h3m16 0h3',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6'};
const icon=name=>window.V2_ICONS?.[name]||`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;
// Approved library previews; kept separate so individual images can be replaced.
const libraryPreviews={"plantbook":"<img src=\"assets/library-icons/plantbook.svg\" alt=\"\" aria-hidden=\"true\">","pricebook":"<img src=\"assets/library-icons/pricebook.svg\" alt=\"\" aria-hidden=\"true\">","hoa":"<img src=\"assets/library-icons/hoa.svg\" alt=\"\" aria-hidden=\"true\">","cities":"<img src=\"assets/library-icons/cities.svg\" alt=\"\" aria-hidden=\"true\">","watch":"<img src=\"assets/library-icons/watch.svg\" alt=\"\" aria-hidden=\"true\">","materials":"<img src=\"assets/library-icons/materials.svg\" alt=\"\" aria-hidden=\"true\">","products":"<img src=\"assets/library-icons/products.svg\" alt=\"\" aria-hidden=\"true\">","colorlibrary":"<img src=\"assets/library-icons/colorlibrary.svg\" alt=\"\" aria-hidden=\"true\">","nurseries":"<img src=\"assets/library-icons/nurseries.svg\" alt=\"\" aria-hidden=\"true\">","cad":"<img src=\"assets/library-icons/cad.svg\" alt=\"\" aria-hidden=\"true\">","furnishings":"<img src=\"assets/library-icons/furnishings.svg\" alt=\"\" aria-hidden=\"true\">"};
const libraries=[['plantbook','Plant Book','plant','plantbook'],['pricebook','Price Book','book','pricebook'],['materials','Materials','book','materials'],['furnishings','Furnishings','grid','furnishings'],['products','Products','grid','products'],['colorlibrary','Color Library','grid','colorlibrary'],['hoa','HOA & DRC','book','hoa'],['cities','City Library','home'],['nurseries','Nurseries','plant','nurseries'],['cad','CAD & specifications','design'],['watch','Product Watch','search']];
const groups=[['This project',[
['home','Project home','home'],['brief','Brief & site','brief'],['design','Design','design'],['costs','Costs & savings','cost'],['client','Client Center','chat'],['financials','Financials','chart'],['deliver','Deliver','brief']]],
['Across the studio',[['libraries','Libraries','book'],['resources','Resource Center','book'],['community','Community','chat'],['business','Studio business','chart']]]];
const all=[...groups.flatMap(g=>g[1]),...libraries,['mood','Mood board','grid'],['insights','Project insights','chart','insights'],['estimate','Estimate','cost','estimate'],['savings','Savings Center','chart'],['bidcompare','Bid Compare','cost','bidcompare'],['roadmap','What’s coming','grid']];
const parentPage=id=>libraries.some(x=>x[0]===id)?'libraries':['estimate','savings','bidcompare'].includes(id)?'costs':['mood','studies'].includes(id)?'design':id==='insights'?'brief':id==='roadmap'?'resources':id;
const rail=document.createElement('aside');rail.id='v2-rail';rail.innerHTML=`<div class="rail-brand"><button id="rail-logo" aria-label="Expand navigation">${icon('logo')}</button><div class="rail-copy"><strong>Studio H</strong><small>Design workspace <b>${esc(appVersion)}</b></small></div><button id="v2-pin" aria-label="Collapse sidebar" title="Pin or collapse sidebar">${icon('pin')}</button></div><button class="rail-project" id="rail-project">${icon('folder')}<span class="rail-copy" id="rail-project-name">Preview project</span><span class="rail-copy">⌄</span></button><div class="rail-scroll">${groups.map(([label,items])=>`<section><button class="rail-label" data-group="${label}" aria-expanded="true"><span>${label}</span><span>⌄</span></button><nav aria-label="${label}">${items.map(([id,label,i])=>`<button class="rail-item" data-page="${id}" title="${label}">${icon(window.V2_ICONS?.[id]?id:i)}<span class="rail-copy">${label}</span></button>`).join('')}</nav></section>`).join('')}</div><button class="rail-item rail-settings" data-page="settings">${icon('settings')}<span class="rail-copy">Settings</span></button>`;root.prepend(rail);
const mobile=document.createElement('button');mobile.id='v2-menu';mobile.innerHTML='☰';mobile.setAttribute('aria-label','Open navigation');root.querySelector('.top').prepend(mobile);
root.querySelector('.top .brand').innerHTML='<span id="workspace-label">Dashboard</span><small class="top-caption">Studio H · '+esc(appVersion)+'</small>';
root.querySelector('.top .quiet').removeAttribute('data-go');root.querySelector('.top .quiet').dataset.page='assistant';
root.querySelector('#v2-project-button').hidden=true;
function pinned(v){demo.pin=v;root.classList.toggle('rail-collapsed',!v);document.getElementById('v2-pin').setAttribute('aria-label',v?'Collapse sidebar':'Pin sidebar');document.getElementById('v2-pin').setAttribute('aria-pressed',v);persist()}
pinned(demo.pin);document.getElementById('v2-pin').onclick=()=>pinned(!demo.pin);document.getElementById('rail-logo').onclick=()=>{if(innerWidth<=760)root.classList.toggle('mobile-open');else pinned(!demo.pin)};mobile.onclick=()=>root.classList.toggle('mobile-open');
rail.onpointerenter=e=>{if(e.pointerType==='mouse'&&!demo.pin)root.classList.add('rail-hover')};rail.onpointerleave=()=>root.classList.remove('rail-hover');
rail.addEventListener('focusin',()=>{if(!demo.pin)root.classList.add('rail-hover')});rail.addEventListener('focusout',e=>{if(!rail.contains(e.relatedTarget))root.classList.remove('rail-hover')});
const resize=document.createElement('div');resize.id='v2-rail-resize';resize.tabIndex=0;resize.role='separator';resize.setAttribute('aria-label','Resize navigation');resize.setAttribute('aria-orientation','vertical');resize.title='Drag to resize navigation';rail.append(resize);
function railWidth(w){demo.railWidth=Math.max(200,Math.min(310,w));root.style.setProperty('--expanded-rail',demo.railWidth+'px');resize.setAttribute('aria-valuenow',demo.railWidth);persist()}
railWidth(demo.railWidth||236);resize.onpointerdown=e=>{if(!demo.pin)return;resize.setPointerCapture(e.pointerId);resize.dataset.drag='1';e.preventDefault()};resize.onpointermove=e=>{if(resize.dataset.drag)railWidth(e.clientX-root.getBoundingClientRect().left)};resize.onpointerup=()=>delete resize.dataset.drag;resize.onpointercancel=()=>delete resize.dataset.drag;resize.ondblclick=()=>railWidth(236);resize.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();railWidth(demo.railWidth+(e.key==='ArrowRight'?8:-8))}};

document.getElementById('rail-project').onclick=()=>document.getElementById('v2-projects').showModal();
const projectObserver=new MutationObserver(()=>{document.getElementById('rail-project-name').textContent=oldAside.querySelector('.project strong')?.textContent||'Preview project'});projectObserver.observe(oldAside,{subtree:true,childList:true,characterData:true});
const btn=(label,attrs='',primary=false)=>`<button class="${primary?'action':'quiet'}" ${attrs}>${label}</button>`;
const go=(label,page)=>btn(label,`data-page="${page}"`);
const tool=(label,route)=>btn(label,`data-tool="${route}"`);
const tag=(text)=>`<span class="pill">${text}</span>`;
const card=(title,body,foot='')=>`<article class="w-card"><h3>${title}</h3>${body}${foot?`<div class="card-bottom">${foot}</div>`:''}</article>`;
const heading=(title,desc,sample=true)=>`<div class="heading"><div class="sectionhead"><span class="tag">${clientView?'Client preview':'Your workspace'}</span>${sample?tag('Sample workspace'):tag('Project tools')}</div><h1>${title}</h1><p>${desc}</p></div>`;
const tabs=arr=>`<div class="tabs w-tabs">${arr.map(x=>btn(x,`data-tab="${esc(x)}" aria-pressed="${tab===x}"`)).join('')}</div>`;
const metrics=items=>`<div class="w-metrics">${items.map(([label,value,sub])=>`<div><span>${label}</span><strong>${value}</strong><small>${sub||''}</small></div>`).join('')}</div>`;
const progress=(value,label)=>`<div class="w-progress"><span>${label}</span><strong>${value}%</strong><div><i style="width:${value}%"></i></div></div>`;
const note=text=>`<p class="w-note">${text}</p>`;
const fields=(label,key,placeholder='')=>`<label class="w-field">${label}<textarea data-note="${key}" placeholder="${esc(placeholder)}">${esc(demo.notes[key]||'')}</textarea></label>`;
const image=(file,alt,cls='')=>file.endsWith('-scenes')?`<div class="w-image scene-sprite ${cls}" role="img" aria-label="${esc(alt)}" style="background-image:url('assets/${file}.png')"></div>`:`<img class="w-image ${cls}" src="assets/${file}.png" alt="${esc(alt)}" loading="lazy">`;
function open(id){if(window.v2Experience&&!v2Experience.allowsPage(id))return;search='';active=id;tab=demo.tab[id]||'';clientView=false;root.classList.remove('mobile-open');root.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===parentPage(id));if(b.dataset.page===parentPage(id))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.getElementById('workspace-label').textContent=all.find(x=>x[0]===id)?.[1]||({settings:'Settings',assistant:'Ask Studio H'}[id]||'Workspace');const item=all.find(x=>x[0]===id);if(item?.[3]){v2Preview.show(item[3],item[1]);return}v2Preview.workspace();if(id==='financials'){v2Layout.financial();return}render();main.scrollTop=0;}
function render(){if(active==='settings'&&window.v2Experience?.role!=='developer'&&['Calculation rules','Library admin'].includes(tab))tab='Appearance';let h='';
if(active==='home'){
h=heading('A clear view of your project.','Your brief, design, decisions and delivery — all in one place.')+`<div class="w-hero"><div><span class="tag">Up next · ${demo.phase}</span><h2>Bring the outdoor living concept together.</h2><p>Confirm the client’s priorities, refine the palette, and review the budget.</p><div class="w-actions">${go('Continue the brief →','brief')}${go('Review the design','design')}</div></div>${image('asian-scenes','Sample garden inspiration')}</div>`+metrics([['Design progress','42%','Illustrative project'],['Awaiting a decision',Object.values(demo.decisions).filter(x=>x==='Approved').length+' / 3','Selections approved'],['Next milestone','Concept review','Sample · October 2'],['Design fee','$24,000','Illustrative fee']])+`<div class="w-grid two">${card('Your project journey',`<div class="phase-path">${['Discovery','Concept','Design development','Documentation','Bidding'].map((x,i)=>`<button data-phase="${x}" class="${demo.phase===x?'chosen':''}"><span>${i+1}</span>${x}</button>`).join('')}</div>`,note('Changing this sample phase does not change the estimate.'))}${card('Next steps',todo(),go('All checklists & reports','deliver'))}${card('Project insights',`<div class="w-list"><div><b>Design area needs confirmation</b><p>Confirm the work boundary before committing quantities.</p></div><div><b>Keep the client’s priorities visible</b><p>Review must-haves before considering savings.</p></div></div>`,go('Open insights','insights'))}${card('Latest activity',`<div class="timeline"><p><b>Today</b> · Concept board ready for review</p><p><b>Yesterday</b> · Client priorities collected</p><p><b>Monday</b> · Site visit photos organized</p></div>`,go('Open Client Center','client'))}</div>`;
}
else if(active==='costs'){
h=heading('Costs & savings','Understand the estimate, compare options and close the budget gap.',false)+`<div class="w-grid two">${card('Estimate','<p>Scope, quantities, allowances and calculated pricing.</p>',go('Open estimate →','estimate'))}${card('Savings Center','<p>Compare material substitutions, priorities and phasing with clear trade-offs.</p>',go('Explore savings →','savings'))}${card('Bid comparison','<p>Compare contractor scope, allowances, omissions and like-for-like totals.</p>',go('Compare bids →','bidcompare'))}${card('Cost insights','<p>Understand cost drivers, assumptions and what needs confirmation.</p>',go('Review insights →','insights'))}</div>`;
}
else if(active==='libraries'){
h=heading('Libraries','Shared knowledge and products, available inside every project.',false)+`<div class="library-preview-grid">${libraries.map(([id,title])=>`<article class="library-preview-card"><div class="library-preview-copy"><h2>${esc(title)}</h2><p>${({plantbook:'Plants, favorites and growing requirements.',pricebook:'Rates, assemblies, labor and bid feedback.',materials:'Finishes, sizes, suppliers and sourced prices.',furnishings:'Furniture, dimensions and supplier links.',products:'Lighting, equipment and specified products.',colorlibrary:'Saved palettes and manufacturer colors.',hoa:'Association guidelines, sources and contacts.',cities:'City documents, setbacks and source history.',nurseries:'Suppliers, stock and availability.',cad:'Details and specification references.',watch:'Review proposed price and availability updates.'})[id]}</p></div><div class="library-preview-thumb">${libraryPreviews[id]||''}</div>${go('Open library →',id)}</article>`).join('')}</div>`;
}
else if(active==='brief'){
h=heading('Brief & site','Your project, priorities and site knowledge in one place.',false)+`<div class="library-preview-grid brief-preview-grid">${[
['01','Project info','Address, contacts, property facts, site requirements and sources.','projectinfo','projectinfo'],
['02','Questionnaire','Client priorities and the designer’s site assessment.','clientgoals','clientbrief'],
['03','Programming','Define the work area using your plan or a site trace.','programming','trace'],
['04','Project Insights','Explore project insights by cost, property, planting, water and progress.','intelligence','insights'],
['05','Photos & references','Site photos, inspiration and products in one collection.','photos','photos'],
['','Site Knowledge','Compare take-off sets, explore sun and shade, and review site observations.','knowledge','studies']
].map(([n,t,d,asset,r])=>`<article class="library-preview-card"><div class="library-preview-copy">${n?`<span class="step-number">${n}</span>`:''}<h2>${t}</h2><p>${d}</p></div><div class="library-preview-thumb"><img src="assets/brief-icons/${asset}.svg" alt="" aria-hidden="true"></div>${r==='studies'?go('Explore site knowledge →',r):tool('Open '+t.toLowerCase()+' →',r)}</article>`).join('')}</div>`;
}
else if(active==='design'){
h=heading('Shape the outdoor space.','Move between the plan, your palettes, and the details that make it work.')+tabs(['Overview','Builders','Render studio']);if(!tab||tab==='Overview')h+=`<div class="w-hero"><div><span class="tag">Concept direction</span><h2>Quiet geometry. Warm materials.</h2><p>A layered garden with generous space for gathering and everyday living.</p><div class="w-actions">${tool('Open plan & take-offs','trace')}${go('Explore the mood board','mood')}</div></div>${image('asian-scenes','Illustrative garden concept')}</div><div class="w-grid three">${card('Planting palette','<p>Species, quantities, mature size and water needs.</p>',tool('Open Plant Book','plantbook'))}${card('Materials & finishes','<p>Compare finishes, costs and specification details.</p>',tool('Browse materials','materials'))}${card('Furniture & products','<p>Plan the pieces, sizes and clearances.</p>',tool('Browse furnishings','furnishings'))}</div>`;
else if(tab==='Builders')h+=`<div class="w-grid three">${['Pool & spa','Paving & decking','Walls','Fences & gates','Shade structures','Outdoor kitchen','Courts & play','Lighting','Water features'].map(x=>card(x,`<p>Design quantities, materials and specifications in the existing project tools.</p>`,tool('Open design tools','trace'))).join('')}</div>`;
else h+=`<div class="w-grid two">${card('From site photo to design',image('asian-scenes','Existing generated concept example')+`<div class="w-actions">${['At installation','Grown in'].map(x=>btn(x,`data-demo-choice="renderAge" data-value="${x}" aria-pressed="${demo.notes.renderAge===x}"`)).join('')}</div>`,note('Sample image · generation is not connected'))}${card('Guide the rendering',`<div class="w-list"><div><b>1 · Choose a site photo</b><p>Retain the house, terrain and camera position.</p></div><div><b>2 · Set the planting</b><p>Species, quantities, coverage and massing.</p></div><div><b>3 · Mark what changes</b><p>Tree positions, planting regions and protected areas.</p></div></div>${fields('Refinement notes','render','What should change in the next view?')}`,tool('Open planting & rendering tools','plantbook'))}</div>`;
}
else if(active==='mood'){
h=heading('A direction you can see.','Collect the materials, furniture and spaces that tell the same story.')+`<div class="w-actions">${tool('Open project mood board','moodboard')}${btn('Presentation view','data-present')}${btn('Add a section','data-add-board')}</div><div class="w-grid three board-grid">${demo.board.map((x,i)=>card(esc(x),image(['asian-scenes','lounge-chair','med-materials'][i%3],x)+fields('What you like','board-'+i,'Add your notes…'),`<div class="w-actions">${btn('←','data-move="'+i+'" data-dir="-1" aria-label="Move section left"')}${btn('→','data-move="'+i+'" data-dir="1" aria-label="Move section right"')}</div>`)).join('')}</div>`+note('Sample board · reorder and notes are saved on this device. Your existing project board opens separately.');
}
else if(active==='insights'){
h=heading('Know what needs your attention.','Design, budget, confidence and site findings in one view.')+metrics([['Confirmed inputs','68%','Sample confidence'],['Budget gap','$18,500','Sample scenario'],['Open decisions','3','Sample decisions'],['Site checks','4','Need confirmation']])+`<div class="w-grid two">${card('Budget & priorities','<p>Protect the outdoor kitchen and gathering space. Review paving finishes before reducing the scope.</p>',go('Review savings options','savings'))}${card('Sources & assumptions',progress(68,'Inputs confirmed')+'<p>Keep entered, measured and assumed values distinguishable.</p>',tool('Open calculated insights','insights'))}${card('Site & compliance','<p>Verify the city’s source documents and attached association guidelines before design review.</p>',go('Open City Library','cities'))}${card('Decisions & design','<p>The material palette and shade structure need a client decision.</p>',go('Review decisions','client'))}</div>`;
}
else if(active==='savings'){
const options=[['Porcelain instead of stone',8200,'Similar clean geometry; a different edge detail and finish.'],['Phase the secondary terrace',6800,'Build the core gathering space first; allow for later access.'],['Simplify the shade structure',3500,'Retain shade with fewer custom details.']];const total=options.reduce((s,x,i)=>s+(demo.savings.includes(i)?x[1]:0),0);
h=heading('Make room in the budget.','See the saving and the trade-off together. Keep what matters most.')+metrics([['Sample estimate','$268,500'],['Client target','$250,000'],['Selected savings','$'+total.toLocaleString()],['Remaining gap','$'+Math.max(0,18500-total).toLocaleString()]])+`<div class="w-actions">${tool('Open project Savings calculator','ve')}${tool('Compare contractor bids','bidcompare')}</div><div class="w-grid three">${options.map(([t,v,d],i)=>card(t,`<strong class="big-number">$${v.toLocaleString()}</strong><p>${d}</p>`,btn(demo.savings.includes(i)?'✓ In this scenario':'Try this option',`data-saving="${i}" aria-pressed="${demo.savings.includes(i)}"`,demo.savings.includes(i)))).join('')}</div>`+note('Illustrative alternatives only. This scenario does not change your estimate. AI recommendations will explain suitability as well as arithmetic.');
}
else if(active==='client'){
tab=tab||'Overview';h=heading('Keep the client in the loop.','One place for updates, conversations and decisions.')+tabs(['Overview','Chat','Decisions','Shared files','Portal preview']);if(tab==='Chat')h+=chat('client');else if(tab==='Decisions')h+=decisions();else if(tab==='Shared files')h+=files();else if(tab==='Portal preview'){clientView=true;h=heading('Welcome to your garden project.','Review the direction, share your thoughts, and see what comes next.')+btn('← Designer workspace','data-tab="Overview"')+`<div class="w-hero"><div><span class="tag">Your next step</span><h2>Tell us what you think of the palette.</h2><p>Your feedback helps us refine the next design.</p></div>${image('asian-scenes','Sample concept shared with the client')}</div>`+`<div class="w-actions">${btn('View design proposal','data-client-proposal')}</div>`+decisions()+note('Portal layout demonstration. A production client portal needs separate authenticated, client-safe data; no link is issued here.');}else h+=metrics([['Next meeting','Concept review','Sample · October 2'],['Awaiting review','3 selections'],['Shared documents','3','Sample files']])+`<div class="w-grid two">${card('Recent conversation','<div class="chat-bubble"><b>Client · Sample</b><p>We love the warm materials. Can we see an option with more afternoon shade?</p></div>',btn('Open conversation','data-tab="Chat"'))}${card('Design proposal','<p>Review scope, fees, payment milestones and the signature workflow.</p>',btn('Open proposal','data-fin-open="Proposal"'))}${card('Decisions to make','<p>Material direction, shade structure and outdoor seating.</p>',btn('Review selections','data-tab="Decisions"'))}${card('Shared with the client','<p>Concept board, design brief and next meeting agenda.</p>',btn('View shared files','data-tab="Shared files"'))}</div>`;
}
else if(active==='deliver'){
tab=tab||'Checklist';h=heading('Ready to share.','Review the work, assemble the documents and hand over with confidence.')+tabs(['Checklist','Reports','Plan Check','Specifications']);if(tab==='Checklist')h+=`<div class="w-grid two">${card('Before the next review',todo(),tool('Open project checklist','checklist'))}${card('Project handover',`<div class="w-list"><div><b>Agreed design direction</b><p>Record the decisions and approval history.</p></div><div><b>Drawings & schedules</b><p>Plans, plant schedule, materials and product specifications.</p></div><div><b>Scope & cost</b><p>Accepted proposal and construction estimate.</p></div></div>`,tool('Open reports','reports'))}</div>`;else if(tab==='Plan Check')h+=`<div class="w-grid two">${card('Drawing review',`<div class="file-well">PDF / DXF plan set<br><small>Sample: Nest Pine · Concept Rev B</small></div><div class="w-actions">${btn('Review sample findings','data-check-plan',true)}</div>`,note('AI review and Dropbox import are not connected.'))}${card('Review findings',`<div id="plan-findings">${demo.notes.planCheck?findings():'Run the sample review to see how findings link back to a drawing.'}</div>`)}</div>`;else if(tab==='Reports')h+=`<div class="w-grid three">${['Client estimate','Plant report','Mood board','Bid comparison','Whole-job receipt','Design proposal'].map(x=>card(x,'<p>Choose the audience and assemble the project information.</p>',x==='Design proposal'?btn('View proposal','data-fin-open="Proposal"'):tool('Open report options','reports'))).join('')}</div>`;else h+=`<div class="w-grid three">${['Plant schedule','Material specifications','Furniture schedule','Lighting & equipment','CAD details','Project archive'].map(x=>card(x,'<p>Specifications, quantities and source references kept together.</p>',x==='CAD details'?go('Browse CAD library','cad'):tool('Open project reports','reports'))).join('')}</div>`;
}
else if(active==='cities'){
h=heading('City Library','Source documents, research status and project requirements.')+`<div class="w-search">${icon('search')}<input data-city-search placeholder="Find a city…" value="${esc(search)}" aria-label="Find a city"></div><div class="w-grid three">${['Irvine','Newport Beach','Laguna Beach','Los Angeles','Costa Mesa','San Clemente'].filter(x=>x.toLowerCase().includes(search.toLowerCase())).map(x=>card(x,'<p>Zoning • Landscape setbacks • Water standards • Permit resources</p>'+tag('Source review required'),tool('Open city requirements','cities'))).join('')}</div>`+note('City cards illustrate the directory. Confirm requirements against the cited authority in the existing library.');
}
else if(active==='cad'){
h=heading('CAD & specifications','Find the detail, attach the specification, keep the source.')+tabs(['All details','Hardscape','Planting','Structures'])+`<div class="w-grid three">${['Paving edge detail','Tree planting detail','Raised planter','Shade structure connection','Pool coping','Irrigation assembly'].filter((x,i)=>!tab||tab==='All details'||(tab==='Planting'?[1,5]:tab==='Hardscape'?[0,2,4]:[3]).includes(i)).map(x=>card(x,`<div class="detail-drawing">${icon('design')}</div><p>DWG · PDF · Product specification</p>`,btn('Preview detail',`data-detail-demo="${x}"`))).join('')}</div>`;
}
else if(active==='watch'){
h=heading('Product Watch','Review changes before they enter your shared library.')+metrics([['Findings','3','Illustrative queue'],['Reviewed',String(Object.keys(demo.watch).length)],['Auto-applied','0','You remain in control']])+`<div class="w-grid three">${[['Outdoor lounge chair','Price change','$840 → $795'],['Porcelain paving','Availability','Restock expected next month'],['Wall light','New product','Specification sheet available']].map(([t,k,v],i)=>card(t,tag(k)+`<p class="big-number">${v}</p><p>Sample supplier finding. Check the source before accepting a library update.</p>`,demo.watch[i]?tag(demo.watch[i]):`<div class="w-actions">${btn('Accept sample',`data-watch="${i}" data-value="Accepted"`)}${btn('Dismiss',`data-watch="${i}" data-value="Dismissed"`)}</div>`)).join('')}</div>`+note('No supplier monitoring or master-library changes run in this preview.');
}
else if(active==='resources'){
h=heading('Resource Center','The references and tools your studio reaches for.')+tabs(['All','Guides','Tools','Saved'])+`<div class="w-grid three">${[['Getting started','Guides','A five-step walkthrough of a landscape project.','brief'],['Reading an estimate','Guides','Quantities, costs, allowances and uncertainty.','estimate'],['Design review checklist','Guides','What to check before sharing drawings.','deliver'],['City & code research','Tools','Source documents and local requirements.','cities'],['Plant research','Tools','Growing conditions, quantities and water needs.','plantbook'],['Materials & specifications','Tools','Product details and supplier references.','materials']].filter((x,i)=>!tab||tab==='All'||(tab==='Saved'?demo.favorites.includes(x[0]):x[1]===tab)).map(([t,c,d,p])=>card(t,tag(c)+`<p>${d}</p>`,`<div class="w-actions">${go('Open',p)}${btn(demo.favorites.includes(t)?'★ Saved':'☆ Save',`data-favorite="${t}"`)}</div>`)).join('')}</div>`+`<div class="w-card" style="margin-top:16px"><h3>Your studio links</h3>${go('Explore the roadmap','roadmap')}<p>Add a useful website and keep it close to your project tools.</p><div class="w-grid three">${demo.links.map(x=>`<a class="resource-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer"><b>${esc(x.name)}</b><span>${esc(new URL(x.url).hostname)} ↗</span></a>`).join('')}</div><form id="resource-form" class="resource-form"><label class="w-field">Name<input name="name" required placeholder="Resource name"></label><label class="w-field">Website<input name="url" type="url" required placeholder="https://…"></label><button class="action">Save link</button></form>${note('Links are saved on this device.')}</div>`;
}
else if(active==='community'){
tab=tab||'Discussions';h=heading('A community of good ideas.','Discuss the work, share useful palettes, and contribute what you know.')+tabs(['Discussions','Shared palettes','Contributions','Guidelines']);if(tab==='Discussions')h+=chat('community');else if(tab==='Shared palettes')h+=`<div class="w-grid three">${['Warm courtyard','Shaded retreat','Coastal textures'].map((t,i)=>card(t,image(['med-scenes','asian-scenes','med-materials'][i],t)+'<p>Example community collection · plants, materials and colors.</p>',btn(demo.favorites.includes(t)?'✓ Saved':'Save collection',`data-favorite="${t}"`))).join('')}</div>`;else if(tab==='Contributions')h+=card('Contribute to the shared library',`<p>Suggest a plant, HOA document, product or correction. Contributions are reviewed before publication.</p>${fields('Your contribution','contribution','Include the source and what needs updating…')}`,btn('Save contribution draft','data-save-draft',true));else h+=card('Helpful, sourced, respectful.','<div class="w-list"><div><b>Share the source</b><p>Keep pricing, plant information and local rules traceable.</p></div><div><b>Protect client information</b><p>Only share material you have permission to publish.</p></div><div><b>Contribute constructively</b><p>Explain the context and keep discussion useful.</p></div></div>');
}
else if(active==='business'){
tab=tab||'Overview';h=heading('See how the studio is doing.','Project fees, time, scope changes and your team’s work.')+tabs(['Overview','Time entry','Change orders','Team chat']);if(tab==='Time entry')h+=timeEntry();else if(tab==='Team chat')h+=chat('team');else if(tab==='Change orders')h+=`<div class="w-grid two">${card('Additional outdoor kitchen study','<p>Scope: explore a second layout after concept approval.</p>'+tag(demo.notes.changeStatus||'Draft')+fields('Scope & fee notes','change','Describe the added deliverable and fee…'),btn('Mark sample approved','data-change-approve'))}${card('Connect to the agreed scope','<p>Accepted changes should update the proposal and fee forecast, with a clear approval history.</p>',btn('Review proposal','data-fin-open="Proposal"'))}</div>`;else h+=metrics([['Active projects','6','Sample studio'],['Contracted fees','$142,000','Illustrative'],['Forecast margin','34%','Illustrative'],['Time logged',demo.time.reduce((s,x)=>s+x.hours,0)+' h','Local sample entries']])+`<div class="w-grid three">${['Nest Pine','Coastal Courtyard','Hillside Retreat'].map((x,i)=>card(x,progress([42,68,25][i],'Project progress')+`<p>Design fee · ${['$24,000','$18,500','$32,000'][i]}</p>`,btn('Review financials','data-fin-open="Profitability"'))).join('')}</div>`;
}
else if(active==='studies'){
h=`<div class="workspace-inline-header">${go('← Workspace','brief')}<h1>Site Knowledge</h1></div><p class="workspace-inline-intro">Explore the planned site-analysis workflow with illustrative controls.</p>`+tabs(['Sun & shade','Take-off sets','Site scan']);if(tab==='Take-off sets')h+=`<div class="w-grid two">${['Satellite','PDF plan'].map(x=>card(x,'<div class="file-well">'+x+' · Sample set</div>',btn(demo.notes.takeoff===x?'✓ In use':'Use this sample set',`data-demo-choice="takeoff" data-value="${x}"`))).join('')}</div>`+tool('Open existing site trace','trace');else if(tab==='Site scan')h+=card('Existing features',`<div class="w-actions">${['Pool','Driveway','Patio','Trees'].map(x=>tag(x)).join('')}</div><p>A future scan will propose existing features for review before adding them to the project.</p>`,note('Sample detection labels. No image analysis has run.'));else h+=`<div class="w-grid two">${card('Sun & shade study',`<div class="sun-study"><span class="sun-house">House</span><span class="sun-tree"></span><span class="shadow" style="transform:rotate(${(Number(demo.notes.sunHour)||12)*12}deg)"></span><span class="sun-caption">Illustrative diagram · not a solar calculation</span></div><label class="w-field">Time of day <strong id="sun-time">${demo.notes.sunHour||12}:00</strong><input type="range" min="6" max="18" value="${demo.notes.sunHour||12}" data-sun aria-label="Sample study time"></label>`,note('A real study needs location, date, building heights, neighboring shade and terrain.'))}${card('Compare the seasons',`<div class="w-actions">${['Summer','Equinox','Winter'].map(x=>btn(x,`data-demo-choice="season" data-value="${x}" aria-pressed="${demo.notes.season===x}"`)).join('')}</div>${fields('Site observations','shade','Record heights, nearby trees and areas that need shade…')}`,tool('Open site information','projectinfo'))}</div>`;
}
else if(active==='settings'){
h=heading('Make Studio H your own.','Appearance, studio defaults, permissions and library administration.')+tabs(['Appearance','Accounts & roles','Calculation rules','Library admin']);if(tab==='Accounts & roles')h+=`<div class="w-grid three">${['Studio owner','Designer','Client'].map(x=>card(x,`<p>${x==='Client'?'Shared proposal, decisions, files and conversations only.':x==='Designer'?'Project tools and assigned libraries.':'Studio defaults, rates, accounts and contribution review.'}</p>`,tag('Role preview'))).join('')}</div>`+note('Permissions and subscriptions require the account backend. This is not an access-control system.');else if(tab==='Calculation rules')h+=`<div class="w-grid three">${['Assemblies & resources','Overhead & profit','Quantity drivers','Modifiers & productivity','Sources & assumptions','Regional rates'].map(x=>card(x,'<p>Review the rule, its source and the effect on the estimate.</p>',tool('Open algorithms','algos'))).join('')}</div>`;else if(tab==='Library admin')h+=`<div class="w-grid three">${card('Image framing tools','<p>Show image adjustment controls in the Plant Book on this device.</p>',btn(window.v2Libraries?.developerTools?'Disable developer tools':'Enable developer tools','data-image-tools'))}${card('Product findings','<p>Review price, stock and specification changes.</p>',go('Open Product Watch','watch'))}${card('Contributions','<p>Review community additions before publication.</p>',go('Open Community','community'))}${card('Imports & shared data','<p>Master records, studio overlays and personal favorites.</p>',tool('Open library tools','plantbook'))}</div>`;else h+=`<div class="w-grid two">${card('Five moods. One workspace.',`<div class="theme-options">${['Morning','Day','Afternoon','Dusk','Night'].map(x=>`<button data-theme="${x}" aria-pressed="${root.dataset.theme===x}"><span class="theme-swatch ${x.toLowerCase()}"></span>${x}</button>`).join('')}</div>`)}${card('Navigation','<p>Use the pin to keep the sidebar open. Unpin it for an icon rail; hover with a mouse or tap the logo to expand.</p>',btn(demo.pin?'Collapse sidebar':'Pin sidebar','data-pin-toggle'))}${card('Units & offline access','<p>Metric conversion, native iPad support and verified offline workflows remain roadmap work.</p>',tag('Planned'))}${card('Usage & subscriptions','<p>Usage by documents and searches, studio roles and shared-library overlays.</p>',tag('Account phase'))}</div>`;
}
else if(active==='assistant')h=heading('Ask about the work in front of you.','Project context, calculation explanations and useful resources.')+`<div class="w-grid two">${card('Start with a question',fields('Question','ask','Why is this estimate above budget?'),btn('Show sample response','data-ask'))}${card('Helpful context',`<div id="ask-response">${demo.notes.asked?'Start with the largest cost drivers, confirm assumed quantities, then compare finish alternatives while protecting the client’s highest priorities. This is a sample response.':'Your brief, site information, selections and estimate will provide context.'}</div>`,go('Review project insights','insights'))}</div>`+note('AI is not connected in this isolated preview.');
else if(active==='roadmap')h=heading('Room for everything ahead.','The roadmap, organized around the work it supports.')+`<div class="w-search">${icon('search')}<input data-roadmap-search value="${esc(search)}" placeholder="Find a feature, workflow or decision…" aria-label="Search roadmap"></div><div class="roadmap-list">${roadmap.filter(x=>(x.title+' '+x.body).toLowerCase().includes(search.toLowerCase())).map(x=>`<details><summary><span>${esc(x.title)}</span>${tag(x.source)}</summary><p>${esc(x.body)}</p>${go('Open '+x.workspaceLabel,x.workspace)}</details>`).join('')||'<p>Loading the roadmap…</p>'}</div>`;
else h=heading('Workspace','Choose a section from the sidebar.',false);
main.innerHTML=h;main.querySelectorAll('.w-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
function todo(){return `<div class="todo-list">${['Confirm the design area','Review client priorities','Collect site photos','Approve the concept palette'].map((x,i)=>`<button data-todo="${i}" aria-pressed="${demo.tasks[i]}"><span class="todo-check">${demo.tasks[i]?'✓':''}</span><span>${x}</span></button>`).join('')}</div>`}
function decisions(){return `<div class="w-grid three">${['Material palette','Shade structure','Outdoor seating'].map((x,i)=>card(x,image(['med-materials','asian-scenes','lounge-chair'][i],x)+`<p>${['Warm grey, timber and soft planting.','A clean-lined structure for afternoon shade.','Comfortable seating with a restrained profile.'][i]}</p>`+tag(demo.decisions[x]||'Awaiting review'),`<div class="w-actions">${btn('Approve',`data-decision="${x}" data-value="Approved"`,demo.decisions[x]==='Approved')}${btn('Request changes',`data-decision="${x}" data-value="Changes requested"`)}</div>`)).join('')}</div>`}
function files(){return `<div class="w-grid three">${['Concept board · Rev B','Project brief','Meeting agenda'].map(x=>card(x,'<div class="file-well">'+icon('brief')+'<span>Sample document</span></div>',btn('View sample',`data-detail-demo="${x}"`))).join('')}</div>`}
function chat(channel){const seeds={client:['Client','We love the warm materials. Can we see an option with more afternoon shade?'],community:['Design discussion','What are your favorite ways to create shade in a small courtyard?'],team:['Studio team','The concept is ready for an internal review. Please add your notes before the client meeting.']};return `<div class="chat-layout"><div class="w-card"><h3>${channel==='client'?'Nest Pine · Client conversation':channel==='community'?'Garden design · Discussion':'Nest Pine · Internal team'}</h3><div class="chat-log"><div class="chat-bubble"><small>${seeds[channel][0]} · Sample</small><p>${seeds[channel][1]}</p></div>${demo.messages[channel].map(x=>`<div class="chat-bubble mine"><small>You · Local draft</small><p>${esc(x)}</p></div>`).join('')}</div><form data-chat="${channel}" class="chat-compose"><label class="sr-only" for="chat-text">Message draft</label><textarea id="chat-text" required placeholder="Write a sample reply…"></textarea><button class="action">Add to preview</button></form>${note('Local conversation demo. Messages are not sent to anyone.')}</div><div class="w-card"><h3>Alongside the conversation</h3><p>Keep decisions and references close to the discussion.</p><div class="w-actions">${go('Mood board','mood')}${go('Project brief','brief')}</div>${fields('Conversation notes',channel+'Notes','Anything to follow up on?')}</div></div>`}
function timeEntry(){return `<div class="w-grid two">${card('Log time by phase',`<form id="time-form"><label class="w-field">Phase<select name="phase"><option>Discovery</option><option>Concept</option><option>Design development</option><option>Documentation</option></select></label><label class="w-field">Hours<input type="number" name="hours" min="0.25" step="0.25" max="24" required placeholder="2.5"></label><label class="w-field">Note<input name="note" placeholder="Optional description"></label><button class="action">Add time entry</button></form>`)}${card('Your sample entries',demo.time.length?demo.time.map(x=>`<div class="w-line"><div><b>${esc(x.phase)}</b><p>${esc(x.note)}</p></div><strong>${x.hours} h</strong></div>`).join(''):'<p>No time logged yet. Add an entry to try the workflow.</p>',note('Local demonstration; not connected to project financial calculations.'))}</div>`}
function findings(){return '<div class="w-list"><div><b>Drawing A-102 · Detail reference</b><p>Example: referenced coping detail is missing.</p></div><div><b>Plant schedule · Naming</b><p>Example: reconcile botanical spelling with Plant Book.</p></div><div><b>Site plan · Review needed</b><p>Example: confirm setback source and HOA restrictions.</p></div></div>'}
function modal(title,body){let d=document.getElementById('workspace-dialog');if(!d){d=document.createElement('dialog');d.id='workspace-dialog';root.append(d)}d.innerHTML=`<div class="sectionhead"><h2>${esc(title)}</h2><button class="quiet" data-close-dialog aria-label="Close dialog">✕</button></div>${body}`;d.showModal()}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.hasAttribute('data-image-tools')){window.v2Libraries.toggleDeveloperTools();render();return}if(b.dataset.page){e.stopImmediatePropagation();open(b.dataset.page);return}
if(b.dataset.group){let nav=b.nextElementSibling;nav.hidden=!nav.hidden;b.setAttribute('aria-expanded',!nav.hidden);return}
if(b.dataset.tool){if(window.v2Libraries?.supports(b.dataset.tool))open(b.dataset.tool);else v2Preview.show(b.dataset.tool,b.textContent.replace('Open ',''));return}
if(b.hasAttribute('data-client-proposal')){active='financials';v2Preview.workspace();v2Layout.financial('Proposal','Client');return}
if(b.dataset.finOpen){active='financials';v2Preview.workspace();v2Layout.financial(b.dataset.finOpen);return}
if(b.dataset.theme){e.stopImmediatePropagation();root.dataset.theme=b.dataset.theme;root.querySelectorAll('[data-theme]').forEach(x=>{x.classList.toggle('active',x.dataset.theme===b.dataset.theme);x.setAttribute('aria-pressed',x.dataset.theme===b.dataset.theme)});if(active==='settings')render();return}
if(b.hasAttribute('data-pin-toggle')){pinned(!demo.pin);render();return}
if(b.dataset.tab){tab=b.dataset.tab;demo.tab[active]=tab}
else if(b.dataset.phase)demo.phase=b.dataset.phase;
else if(b.dataset.todo!==undefined){let i=+b.dataset.todo;demo.tasks[i]=!demo.tasks[i]}
else if(b.dataset.saving!==undefined){let i=+b.dataset.saving;demo.savings=demo.savings.includes(i)?demo.savings.filter(x=>x!==i):[...demo.savings,i]}
else if(b.dataset.decision)demo.decisions[b.dataset.decision]=b.dataset.value;
else if(b.dataset.watch!==undefined)demo.watch[b.dataset.watch]=b.dataset.value;
else if(b.dataset.demoChoice)demo.notes[b.dataset.demoChoice]=b.dataset.value;
else if(b.dataset.favorite){let x=b.dataset.favorite;demo.favorites=demo.favorites.includes(x)?demo.favorites.filter(y=>y!==x):[...demo.favorites,x]}
else if(b.hasAttribute('data-check-plan'))demo.notes.planCheck=true;
else if(b.hasAttribute('data-change-approve'))demo.notes.changeStatus='Approved · Sample';
else if(b.hasAttribute('data-ask'))demo.notes.asked=true;
else if(b.hasAttribute('data-save-draft')){persist();modal('Draft saved','<p>Your contribution is saved locally. It has not been submitted.</p>');return}
else if(b.hasAttribute('data-present')){modal('Concept board · Sample',`<div class="w-grid three">${demo.board.map((x,i)=>card(esc(x),image(['asian-scenes','lounge-chair','med-materials'][i%3],x))).join('')}</div>`);return}
else if(b.hasAttribute('data-add-board')){demo.board.push('New inspiration '+(demo.board.length+1))}
else if(b.dataset.move!==undefined){let i=+b.dataset.move,j=i+Number(b.dataset.dir);if(j>=0&&j<demo.board.length)[demo.board[i],demo.board[j]]=[demo.board[j],demo.board[i]]}
else if(b.dataset.detailDemo){modal(b.dataset.detailDemo,`<div class="file-well">${icon('brief')}<strong>${esc(b.dataset.detailDemo)}</strong><p>Sample preview</p></div><p>In the completed workspace, the document, source, revision and download will be kept here.</p>`);return}
else if(b.hasAttribute('data-close-dialog')){b.closest('dialog').close();return}
else return;persist();render();
},true);
root.addEventListener('input',e=>{const t=e.target;if(t.dataset.note){demo.notes[t.dataset.note]=t.value;persist()}if(t.hasAttribute('data-sun')){demo.notes.sunHour=t.value;persist();document.getElementById('sun-time').textContent=t.value+':00';main.querySelector('.shadow').style.transform=`rotate(${t.value*12}deg)`}if(t.hasAttribute('data-city-search')||t.hasAttribute('data-roadmap-search')){const pos=t.selectionStart;search=t.value;const attr=t.hasAttribute('data-city-search')?'data-city-search':'data-roadmap-search';render();let n=main.querySelector('['+attr+']');n.focus();n.setSelectionRange(pos,pos)}});
root.addEventListener('submit',e=>{if(e.target.id==='resource-form'){e.preventDefault();const f=new FormData(e.target),url=new URL(f.get('url'));if(!['http:','https:'].includes(url.protocol))return;demo.links.push({name:f.get('name'),url:url.href});persist();render()}else if(e.target.dataset.chat){e.preventDefault();let text=e.target.querySelector('textarea').value.trim();if(text)demo.messages[e.target.dataset.chat].push(text);persist();render()}else if(e.target.id==='time-form'){e.preventDefault();let f=new FormData(e.target);demo.time.push({phase:f.get('phase'),hours:Number(f.get('hours')),note:f.get('note')});persist();render()}});
// Returning from a real tool returns to its V2 workspace, not the retired tile-only shell.
document.getElementById('v2-back').onclick=()=>{v2Preview.workspace();const item=all.find(x=>x[0]===active);if(item?.[3])open(parentPage(active));else if(active==='financials')v2Layout.financial();else render()};
fetch('src/roadmap.json').then(r=>r.json()).then(x=>{roadmap=x;if(active==='roadmap')render()});
window.v2Workspace={open,get active(){return active},get demo(){return demo}};const initialView=new URLSearchParams(location.search).get('view');open(['brief','libraries','plantbook','materials','furnishings','colorlibrary'].includes(initialView)?initialView:'home');
})();
